-- Generated by snipgen 1 from a4.cwl; do not edit, regenerate.
-- source: TeXstudio completion/a4.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 6edc1ca9aef35be97457069a8a753ceb79cf18fc72c578f5f81d1e770384bed9
-- cwl-header:
--   # a4 package
--   # Matthew Bertucci 3/29/2022 for v1.2g
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "a4",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\WideMargins", dscr = "" }, { t("\\WideMargins") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/a4#c",
      lines = {
        "widemargins",
      },
    },
  },
}
