-- Generated by snipgen 1 from abntcite.cwl; do not edit, regenerate.
-- source: TeXstudio completion/abntcite.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 50c3eb596df69b09db4455ecf3e9d5a4384106fdbf907e0065310d9390a238b9
-- cwl-header:
--   # abntcite.cwl
--   # Edson 20-10-2010
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "abntcite",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\cite", dscr = "{bibid}" }, { t("\\cite{"), i(1, "bibid"), t("}") }, "c"),
    S({ trig = "\\citeonline", dscr = "{bibid}" }, { t("\\citeonline{"), i(1, "bibid"), t("}") }, "c"),
    S({ trig = "\\citeyear", dscr = "{bibid}" }, { t("\\citeyear{"), i(1, "bibid"), t("}") }, "c"),
    S({ trig = "\\citeauthor", dscr = "{bibid}" }, { t("\\citeauthor{"), i(1, "bibid"), t("}") }, "c"),
    S({ trig = "\\citeauthoronline", dscr = "{bibid}" }, { t("\\citeauthoronline{"), i(1, "bibid"), t("}") }, "c"),
    S({ trig = "\\leftovercite", dscr = "" }, { t("\\leftovercite") }),
    S({ trig = "\\rightovercite", dscr = "" }, { t("\\rightovercite") }),
    S({ trig = "\\citeoptions", dscr = "{options}" }, { t("\\citeoptions{"), i(1, "options"), t("}") }),
    S({ trig = "\\bibtextitlecommand", dscr = "" }, { t("\\bibtextitlecommand") }),
    S({ trig = "\\bibtextitlecommand", dscr = "{entry}{text}" }, { t("\\bibtextitlecommand{"), i(1, "entry"), t("}{"), i(2, "text"), t("}") }),
  },
  keyvals = {},
}
