-- Generated by snipgen 1 from ae.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ae.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 759d3642c48774e3174a6bbb47427af99ac1e41e4969805a683ae62ff7e44ea4
-- cwl-header:
--   # ae package
--   # Matthew Bertucci 2/3/2022 for v1.3
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ae",
  includes = { "fontenc" },
  lists = {},
  snippets = {
    S({ trig = "\\DH", dscr = "∗", priority = 900 }, { t("\\DH") }, "*n"),
    S({ trig = "\\NG", dscr = "∗", priority = 900 }, { t("\\NG") }, "*n"),
    S({ trig = "\\dj", dscr = "" }, { t("\\dj") }, "n"),
    S({ trig = "\\ng", dscr = "∗", priority = 900 }, { t("\\ng") }, "*n"),
    S({ trig = "\\k", dscr = "{arg}" }, { t("\\k{"), i(1, "arg"), t("}") }, "n"),
    S({ trig = "\\guillemotleft", dscr = "∗", priority = 900 }, { t("\\guillemotleft") }, "*n"),
    S({ trig = "\\guillemotright", dscr = "∗", priority = 900 }, { t("\\guillemotright") }, "*n"),
    S({ trig = "\\guilsinglleft", dscr = "∗", priority = 900 }, { t("\\guilsinglleft") }, "*n"),
    S({ trig = "\\guilsinglright", dscr = "∗", priority = 900 }, { t("\\guilsinglright") }, "*n"),
    S({ trig = "\\quotedblbase", dscr = "" }, { t("\\quotedblbase") }, "n"),
    S({ trig = "\\quotesinglbase", dscr = "" }, { t("\\quotesinglbase") }, "n"),
    S({ trig = "\\textquotedbl", dscr = "" }, { t("\\textquotedbl") }, "n"),
    S({ trig = "\\DJ", dscr = "∗", priority = 900 }, { t("\\DJ") }, "*n"),
    S({ trig = "\\th", dscr = "∗", priority = 900 }, { t("\\th") }, "*n"),
    S({ trig = "\\TH", dscr = "∗", priority = 900 }, { t("\\TH") }, "*n"),
    S({ trig = "\\dh", dscr = "∗", priority = 900 }, { t("\\dh") }, "*n"),
    S({ trig = "\\Hwithstroke", dscr = "∗", priority = 900 }, { t("\\Hwithstroke") }, "*n"),
    S({ trig = "\\hwithstroke", dscr = "∗", priority = 900 }, { t("\\hwithstroke") }, "*n"),
    S({ trig = "\\textogonekcentered", dscr = "{arg} ∗", priority = 900 }, { t("\\textogonekcentered{"), i(1, "arg"), t("}") }, "*n"),
    S({ trig = "\\guillemetleft", dscr = "∗", priority = 900 }, { t("\\guillemetleft") }, "*n"),
    S({ trig = "\\guillemetright", dscr = "∗", priority = 900 }, { t("\\guillemetright") }, "*n"),
  },
  keyvals = {
    {
      targets = "\\usepackage/ae#c",
      lines = {
        "slides",
      },
    },
  },
}
