-- Generated by snipgen 1 from aeb_mobile.cwl; do not edit, regenerate.
-- source: TeXstudio completion/aeb_mobile.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 22550eaf55e9a8fe3b8b82cfd34691df603ba86ce2ea4229914f90f96ae0343a
-- cwl-header:
--   # aeb_mobile package
--   # Matthew Bertucci 2022/05/10 for v1.4
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "aeb_mobile",
  includes = { "web", "eforms" },
  lists = {},
  snippets = {
    S({ trig = "\\scalefiguresOn", dscr = "" }, { t("\\scalefiguresOn") }),
    S({ trig = "\\scalefiguresOff", dscr = "" }, { t("\\scalefiguresOff") }),
    S({ trig = "\\mobPrint", dscr = "{text}" }, { t("\\mobPrint{"), i(1, "text"), t("}") }),
    S({ trig = "\\mobPrintTip", dscr = "∗", priority = 900 }, { t("\\mobPrintTip") }, "*"),
    S({ trig = "\\mobToggleCols", dscr = "{text}" }, { t("\\mobToggleCols{"), i(1, "text"), t("}") }),
    S({ trig = "\\mobToggleColsTip", dscr = "∗", priority = 900 }, { t("\\mobToggleColsTip") }, "*"),
    S({ trig = "\\mobFormPresets", dscr = "{commands}" }, { t("\\mobFormPresets{"), i(1, "commands"), t("}") }),
    S({ trig = "\\ifsmartphone", dscr = "∗", priority = 900 }, { t("\\ifsmartphone") }, "*"),
    S({ trig = "\\smartphonetrue", dscr = "∗", priority = 900 }, { t("\\smartphonetrue") }, "*"),
    S({ trig = "\\smartphonefalse", dscr = "∗", priority = 900 }, { t("\\smartphonefalse") }, "*"),
    S({ trig = "\\generateEvenPage", dscr = "∗", priority = 900 }, { t("\\generateEvenPage") }, "*"),
    S({ trig = "\\mobPrintIt", dscr = "∗", priority = 900 }, { t("\\mobPrintIt") }, "*"),
    S({ trig = "\\mobPrintIt", dscr = "[opt] ∗", priority = 900 }, { t("\\mobPrintIt["), i(1, "opt"), t("]") }, "*"),
    S({ trig = "\\mobTwoCols", dscr = "∗", priority = 900 }, { t("\\mobTwoCols") }, "*"),
    S({ trig = "\\mobTwoCols", dscr = "[opt] ∗", priority = 900 }, { t("\\mobTwoCols["), i(1, "opt"), t("]") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/aeb_mobile#c",
      lines = {
        "smartphone",
        "nomaketitle",
        "useforms",
        "scalefigures",
        "!scalefigures",
      },
    },
  },
}
