-- Generated by snipgen 1 from aesupp.cwl; do not edit, regenerate.
-- source: TeXstudio completion/aesupp.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: a30c19a92e8c9faf757811d1cdddde2d74e6ab310faf56fd1727ac29ce21d565
-- cwl-header:
--   # aesupp package
--   # Matthew Bertucci 1/18/2021 for v1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "aesupp",
  includes = { "ifthen" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\usepackage/aesupp#c",
      lines = {
        "OT1",
        "T1",
        "bx",
      },
    },
  },
}
