-- Generated by snipgen 1 from affilauthor.cwl; do not edit, regenerate.
-- source: TeXstudio completion/affilauthor.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: ec6fe746ff72e5f125857c3aeac096ed0990ad286263628003b0d2d60f341e19
-- cwl-header:
--   # affilauthor package
--   # Matthew Bertucci 2023/11/29 for v1.0.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "affilauthor",
  includes = { "marvosym" },
  lists = {},
  snippets = {
    S({ trig = "\\author", dscr = "{keyvals}" }, { t("\\author{"), i(1, "keyvals"), t("}") }),
    S({ trig = "\\affil", dscr = "{keyvals}" }, { t("\\affil{"), i(1, "keyvals"), t("}") }),
    S({ trig = "\\affilstyle", dscr = "[keyvals]" }, { t("\\affilstyle["), i(1, "keyvals"), t("]") }),
  },
  keyvals = {
    {
      targets = "\\author#c",
      lines = {
        "name={%<name1,name2,...%>}",
        "mail={%<email1,email2,...%>}",
        "phone={%<num1,num2,...%>}",
        "url={%<URL1,URL2,...%>}",
        "affil={%<affil1,affil2,...%>}",
        "note={%<note1,note2,...%>",
      },
    },
    {
      targets = "\\affil#c",
      lines = {
        "id=%<id%>",
        "div=%<text%>",
        "org=%<text%>",
        "addr=%<text%>",
        "street=%<text%>",
        "landmark=%<text%>",
        "pincode=%<text%>",
        "postbox=%<text%>",
        "city=%<text%>",
        "state=%<text%>",
        "country=%<text%>",
      },
    },
    {
      targets = "\\affilstyle#c",
      lines = {
        "authfont=%<font commands%>",
        "affilfont=%<font commands%>",
        "mailfont=%<font commands%>",
        "urlfont=%<font commands%>",
        "phonefont=%<font commands%>",
        "notefont=%<font commands%>",
        "notenum=#alpha,fnsym,roman",
        "authspace=##L",
        "affilspace=##L",
        "affilnum=#alpha,Alpha,roman,Roman",
      },
    },
  },
}
