-- Generated by snipgen 1 from appendix.cwl; do not edit, regenerate.
-- source: TeXstudio completion/appendix.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: adaa3fd5e4695720248d251a65ece96674ed8811275ef92a9f0e84a53f1f80f4
-- cwl-header:
--   # appendix.cwl
--   # Edson 28-12-2010
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "appendix",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\appendixpage", dscr = "" }, { t("\\appendixpage") }),
    S({ trig = "\\addappheadtotoc", dscr = "" }, { t("\\addappheadtotoc") }),
    S({ trig = "\\noappendicestocpagenum", dscr = "" }, { t("\\noappendicestocpagenum") }),
    S({ trig = "\\appendicestocpagenum", dscr = "" }, { t("\\appendicestocpagenum") }),
    S({ trig = "\\appendixtocname", dscr = "" }, { t("\\appendixtocname") }),
    S({ trig = "\\appendixpagename", dscr = "" }, { t("\\appendixpagename") }),
    S({ trig = "\\appendices", dscr = "\\begin{appendices}" }, { t({ "\\begin{appendices}", "\t" }), i(1), t({ "", "\\end{appendices}" }) }),
    S({ trig = "\\subappendices", dscr = "\\begin{subappendices}" }, { t({ "\\begin{subappendices}", "\t" }), i(1), t({ "", "\\end{subappendices}" }) }),
    S({ trig = "\\appendixtocon", dscr = "" }, { t("\\appendixtocon") }),
    S({ trig = "\\appendixtocoff", dscr = "" }, { t("\\appendixtocoff") }),
    S({ trig = "\\appendixpageon", dscr = "" }, { t("\\appendixpageon") }),
    S({ trig = "\\appendixpageoff", dscr = "" }, { t("\\appendixpageoff") }),
    S({ trig = "\\appendixtitleon", dscr = "" }, { t("\\appendixtitleon") }),
    S({ trig = "\\appendixtitleoff", dscr = "" }, { t("\\appendixtitleoff") }),
    S({ trig = "\\appendixtitletocon", dscr = "" }, { t("\\appendixtitletocon") }),
    S({ trig = "\\appendixtitletocoff", dscr = "" }, { t("\\appendixtitletocoff") }),
    S({ trig = "\\appendixheaderon", dscr = "" }, { t("\\appendixheaderon") }),
    S({ trig = "\\appendixheaderoff", dscr = "" }, { t("\\appendixheaderoff") }),
    S({ trig = "\\restoreapp", dscr = "" }, { t("\\restoreapp") }),
    S({ trig = "\\setthesection", dscr = "" }, { t("\\setthesection") }),
    S({ trig = "\\setthesubsection", dscr = "" }, { t("\\setthesubsection") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/appendix#c",
      lines = {
        "toc",
        "title",
        "titletoc",
        "header",
        "page",
      },
    },
  },
}
