-- Generated by snipgen 1 from array.cwl; do not edit, regenerate.
-- source: TeXstudio completion/array.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 90be69b4dd7208d2e3be56059d1f4ef8aea9945270ad589a28a07f002f6cc9f7
-- cwl-header:
--   # mode: array.sty
--   # dani/2006-02-18
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "array",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\arraybackslash", dscr = "" }, { t("\\arraybackslash") }),
    S({ trig = "\\extrarowheight", dscr = "" }, { t("\\extrarowheight") }),
    S({ trig = "\\extratabsurround", dscr = "" }, { t("\\extratabsurround") }),
    S({ trig = "\\firsthline", dscr = "" }, { t("\\firsthline") }, "t"),
    S({ trig = "\\lasthline", dscr = "" }, { t("\\lasthline") }, "t"),
    S({ trig = "\\newcolumntype", dscr = "{name}{definition}" }, { t("\\newcolumntype{"), i(1, "name"), t("}{"), i(2, "definition"), t("}") }),
    S({ trig = "\\newcolumntype", dscr = "{name}[args]{definition}" }, { t("\\newcolumntype{"), i(1, "name"), t("}["), i(2, "args"), t("]{"), i(3, "definition"), t("}") }),
    S({ trig = "\\showcols", dscr = "" }, { t("\\showcols") }),
  },
  keyvals = {},
}
