-- Generated by snipgen 1 from auncial.cwl; do not edit, regenerate.
-- source: TeXstudio completion/auncial.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f09e6af6d30500a53ee1095bdb5b59b904e11259393424547c4c77c573d3f039
-- cwl-header:
--   # auncial package
--   # Matthew Bertucci 8/27/2021 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "auncial",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\aunclfamily", dscr = "" }, { t("\\aunclfamily") }, "n"),
    S({ trig = "\\textauncl", dscr = "{text}" }, { t("\\textauncl{"), i(1, "text"), t("}") }, "n"),
  },
  keyvals = {},
}
