-- Generated by snipgen 1 from basicarith.cwl; do not edit, regenerate.
-- source: TeXstudio completion/basicarith.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: a3b1cd64f1e08f7dbb80ccbd4e7f4668e66842301be1647997e7d0f6b979cb70
-- cwl-header:
--   # basicarith package
--   # Matthew Bertucci 10/5/2021 for v1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "basicarith",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\probline", dscr = "{width}{number}" }, { t("\\probline{"), i(1, "width"), t("}{"), i(2, "number"), t("}") }),
    S({ trig = "\\nextpline", dscr = "{number}" }, { t("\\nextpline{"), i(1, "number"), t("}") }),
    S({ trig = "\\opline", dscr = "{operator}{number}" }, { t("\\opline{"), i(1, "operator"), t("}{"), i(2, "number"), t("}") }),
    S({ trig = "\\soluline", dscr = "{number}" }, { t("\\soluline{"), i(1, "number"), t("}") }),
    S({ trig = "\\noopline", dscr = "{number}" }, { t("\\noopline{"), i(1, "number"), t("}") }),
    S({ trig = "\\longdiv", dscr = "{length}{dividend}{divisor}" }, { t("\\longdiv{"), i(1, "length"), t("}{"), i(2, "dividend"), t("}{"), i(3, "divisor"), t("}") }),
    S({ trig = "\\ldsoluline", dscr = "{solution}{remainder}" }, { t("\\ldsoluline{"), i(1, "solution"), t("}{"), i(2, "remainder"), t("}") }),
    S({ trig = "\\nextldline", dscr = "{cutoff}{number}" }, { t("\\nextldline{"), i(1, "cutoff"), t("}{"), i(2, "number"), t("}") }),
    S({ trig = "\\linestyle", dscr = "{line number}{style}" }, { t("\\linestyle{"), i(1, "line number"), t("}{"), i(2, "style"), t("}") }),
    S({ trig = "\\clearlinestyles", dscr = "" }, { t("\\clearlinestyles") }),
    S({ trig = "\\digstyle", dscr = "{column number}{style}" }, { t("\\digstyle{"), i(1, "column number"), t("}{"), i(2, "style"), t("}") }),
    S({ trig = "\\cleardigitstyles", dscr = "" }, { t("\\cleardigitstyles") }),
    S({ trig = "\\carryline", dscr = "{num of digits}{carries}" }, { t("\\carryline{"), i(1, "num of digits"), t("}{"), i(2, "carries"), t("}") }),
    S({ trig = "\\strike", dscr = "{text}" }, { t("\\strike{"), i(1, "text"), t("}") }),
    S({ trig = "\\problembox", dscr = "{contents}" }, { t("\\problembox{"), i(1, "contents"), t("}") }),
    S({ trig = "\\showdivwork", dscr = "" }, { t("\\showdivwork") }),
    S({ trig = "\\noshowdivwork", dscr = "" }, { t("\\noshowdivwork") }),
    S({ trig = "\\fractionsymbol", dscr = "∗", priority = 900 }, { t("\\fractionsymbol") }, "*"),
    S({ trig = "\\ifshowdivisionwork", dscr = "∗", priority = 900 }, { t("\\ifshowdivisionwork") }, "*"),
    S({ trig = "\\showdivisionworktrue", dscr = "∗", priority = 900 }, { t("\\showdivisionworktrue") }, "*"),
    S({ trig = "\\showdivisionworkfalse", dscr = "∗", priority = 900 }, { t("\\showdivisionworkfalse") }, "*"),
    S({ trig = "\\specialdigitstyle", dscr = "∗", priority = 900 }, { t("\\specialdigitstyle") }, "*"),
    S({ trig = "\\speciallinestyle", dscr = "∗", priority = 900 }, { t("\\speciallinestyle") }, "*"),
    S({ trig = "\\gobblechar", dscr = "∗", priority = 900 }, { t("\\gobblechar") }, "*"),
    S({ trig = "\\assignthencheck", dscr = "∗", priority = 900 }, { t("\\assignthencheck") }, "*"),
    S({ trig = "\\countunlessnil", dscr = "∗", priority = 900 }, { t("\\countunlessnil") }, "*"),
    S({ trig = "\\auxcountchar", dscr = "∗", priority = 900 }, { t("\\auxcountchar") }, "*"),
    S({ trig = "\\countchar", dscr = "{arg} ∗", priority = 900 }, { t("\\countchar{"), i(1, "arg"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/basicarith#c",
      lines = {
        "noshowdivwork",
        "showdivwork",
      },
    },
  },
}
