-- Generated by snipgen 1 from beamersubframe.cwl; do not edit, regenerate.
-- source: TeXstudio completion/beamersubframe.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 84691ee10dfff1587662aff3e353f5b5704666635aef937e339836a2554fdcda
-- cwl-header:
--   # beamersubframe package
--   # Matthew Bertucci 2/12/2022 for v0.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "beamersubframe",
  includes = { "verbatim" },
  lists = {},
  snippets = {
    S({ trig = "\\subframe", dscr = "\\begin{subframe}" }, { t({ "\\begin{subframe}", "\t" }), i(1), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}<overlay specification>" }, { t("\\begin{subframe}<"), i(1, "overlay specification"), t({ ">", "\t" }), i(2), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}<overlay specification>[<default overlay specification>]" }, { t("\\begin{subframe}<"), i(1, "overlay specification"), t(">[<"), i(2, "default overlay specification"), t({ ">]", "\t" }), i(3), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}<overlay specification>[<default overlay specification>][options]" }, { t("\\begin{subframe}<"), i(1, "overlay specification"), t(">[<"), i(2, "default overlay specification"), t(">]["), i(3, "options"), t({ "]", "\t" }), i(4), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}<overlay specification>[<default overlay specification>][options]{title}" }, { t("\\begin{subframe}<"), i(1, "overlay specification"), t(">[<"), i(2, "default overlay specification"), t(">]["), i(3, "options"), t("]{"), i(4, "title"), t({ "}", "\t" }), i(5), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}<overlay specification>[<default overlay specification>][options]{title}{subtitle}" }, { t("\\begin{subframe}<"), i(1, "overlay specification"), t(">[<"), i(2, "default overlay specification"), t(">]["), i(3, "options"), t("]{"), i(4, "title"), t("}{"), i(5, "subtitle"), t({ "}", "\t" }), i(6), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}[<default overlay specification>]" }, { t("\\begin{subframe}[<"), i(1, "default overlay specification"), t({ ">]", "\t" }), i(2), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}[<default overlay specification>][options]" }, { t("\\begin{subframe}[<"), i(1, "default overlay specification"), t(">]["), i(2, "options"), t({ "]", "\t" }), i(3), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}[<default overlay specification>][options]{title}" }, { t("\\begin{subframe}[<"), i(1, "default overlay specification"), t(">]["), i(2, "options"), t("]{"), i(3, "title"), t({ "}", "\t" }), i(4), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}[<default overlay specification>][options]{title}{subtitle}" }, { t("\\begin{subframe}[<"), i(1, "default overlay specification"), t(">]["), i(2, "options"), t("]{"), i(3, "title"), t("}{"), i(4, "subtitle"), t({ "}", "\t" }), i(5), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}[options]" }, { t("\\begin{subframe}["), i(1, "options"), t({ "]", "\t" }), i(2), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}[options]{title}" }, { t("\\begin{subframe}["), i(1, "options"), t("]{"), i(2, "title"), t({ "}", "\t" }), i(3), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}[options]{title}{subtitle}" }, { t("\\begin{subframe}["), i(1, "options"), t("]{"), i(2, "title"), t("}{"), i(3, "subtitle"), t({ "}", "\t" }), i(4), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\subframe", dscr = "\\begin{subframe}{title}" }, { t("\\begin{subframe}{"), i(1, "title"), t({ "}", "\t" }), i(2), t({ "", "\\end{subframe}" }) }),
    S({ trig = "\\appendsubframes", dscr = "" }, { t("\\appendsubframes") }),
    S({ trig = "\\ifappend", dscr = "{append-mode material}{embed-mode material}" }, { t("\\ifappend{"), i(1, "append-mode material"), t("}{"), i(2, "embed-mode material"), t("}") }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}" }, { t({ "\\begin{lastframe}", "\t" }), i(1), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}<overlay specification>" }, { t("\\begin{lastframe}<"), i(1, "overlay specification"), t({ ">", "\t" }), i(2), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}<overlay specification>[<default overlay specification>]" }, { t("\\begin{lastframe}<"), i(1, "overlay specification"), t(">[<"), i(2, "default overlay specification"), t({ ">]", "\t" }), i(3), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}<overlay specification>[<default overlay specification>][options]" }, { t("\\begin{lastframe}<"), i(1, "overlay specification"), t(">[<"), i(2, "default overlay specification"), t(">]["), i(3, "options"), t({ "]", "\t" }), i(4), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}<overlay specification>[<default overlay specification>][options]{title}" }, { t("\\begin{lastframe}<"), i(1, "overlay specification"), t(">[<"), i(2, "default overlay specification"), t(">]["), i(3, "options"), t("]{"), i(4, "title"), t({ "}", "\t" }), i(5), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}<overlay specification>[<default overlay specification>][options]{title}{subtitle}" }, { t("\\begin{lastframe}<"), i(1, "overlay specification"), t(">[<"), i(2, "default overlay specification"), t(">]["), i(3, "options"), t("]{"), i(4, "title"), t("}{"), i(5, "subtitle"), t({ "}", "\t" }), i(6), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}[<default overlay specification>]" }, { t("\\begin{lastframe}[<"), i(1, "default overlay specification"), t({ ">]", "\t" }), i(2), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}[<default overlay specification>][options]" }, { t("\\begin{lastframe}[<"), i(1, "default overlay specification"), t(">]["), i(2, "options"), t({ "]", "\t" }), i(3), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}[<default overlay specification>][options]{title}" }, { t("\\begin{lastframe}[<"), i(1, "default overlay specification"), t(">]["), i(2, "options"), t("]{"), i(3, "title"), t({ "}", "\t" }), i(4), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}[<default overlay specification>][options]{title}{subtitle}" }, { t("\\begin{lastframe}[<"), i(1, "default overlay specification"), t(">]["), i(2, "options"), t("]{"), i(3, "title"), t("}{"), i(4, "subtitle"), t({ "}", "\t" }), i(5), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}[options]" }, { t("\\begin{lastframe}["), i(1, "options"), t({ "]", "\t" }), i(2), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}[options]{title}" }, { t("\\begin{lastframe}["), i(1, "options"), t("]{"), i(2, "title"), t({ "}", "\t" }), i(3), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}[options]{title}{subtitle}" }, { t("\\begin{lastframe}["), i(1, "options"), t("]{"), i(2, "title"), t("}{"), i(3, "subtitle"), t({ "}", "\t" }), i(4), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\lastframe", dscr = "\\begin{lastframe}{title}" }, { t("\\begin{lastframe}{"), i(1, "title"), t({ "}", "\t" }), i(2), t({ "", "\\end{lastframe}" }) }),
    S({ trig = "\\inserttotalframenumberwithsub", dscr = "∗", priority = 900 }, { t("\\inserttotalframenumberwithsub") }, "*"),
    S({ trig = "\\ifsubframe", dscr = "{subframe material}{normal-frame material}" }, { t("\\ifsubframe{"), i(1, "subframe material"), t("}{"), i(2, "normal-frame material"), t("}") }),
    S({ trig = "\\subslideentry", dscr = "{arg1}{arg2}{arg3}{arg4}{arg5}{arg6} ∗", priority = 900 }, { t("\\subslideentry{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}{"), i(3, "arg3"), t("}{"), i(4, "arg4"), t("}{"), i(5, "arg5"), t("}{"), i(6, "arg6"), t("}") }, "*"),
    S({ trig = "\\bsfrestorepart", dscr = "{new part page}{prev part num} ∗", priority = 900 }, { t("\\bsfrestorepart{"), i(1, "new part page"), t("}{"), i(2, "prev part num"), t("}") }, "*"),
    S({ trig = "\\bsfrestoresection", dscr = "{new sec page}{prev sec num} ∗", priority = 900 }, { t("\\bsfrestoresection{"), i(1, "new sec page"), t("}{"), i(2, "prev sec num"), t("}") }, "*"),
    S({ trig = "\\bsfrestoresubsection", dscr = "{new subsec page}{prev subsec num} ∗", priority = 900 }, { t("\\bsfrestoresubsection{"), i(1, "new subsec page"), t("}{"), i(2, "prev subsec num"), t("}") }, "*"),
    S({ trig = "\\bsfrestore", dscr = "{part num}{sec num}{subsec num}{subsecslide num} ∗", priority = 900 }, { t("\\bsfrestore{"), i(1, "part num"), t("}{"), i(2, "sec num"), t("}{"), i(3, "subsec num"), t("}{"), i(4, "subsecslide num"), t("}") }, "*"),
    S({ trig = "\\bsfsubframepages", dscr = "{part num}{sec num}{subsec num}{subsecslide num}{first page}{last page} ∗", priority = 900 }, { t("\\bsfsubframepages{"), i(1, "part num"), t("}{"), i(2, "sec num"), t("}{"), i(3, "subsec num"), t("}{"), i(4, "subsecslide num"), t("}{"), i(5, "first page"), t("}{"), i(6, "last page"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/beamersubframe#c",
      lines = {
        "embed",
        "append",
        "nominiframes",
      },
    },
  },
}
