-- Generated by snipgen 1 from beamerthemeAmurmaple.cwl; do not edit, regenerate.
-- source: TeXstudio completion/beamerthemeAmurmaple.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 8824fc6ad02383b7e5c131145fbc13a0a02735284df0267cf59774848c1c9ebb
-- cwl-header:
--   # Amurmaple beamertheme
--   # Matthew Bertucci 2024/02/07 for v1.3
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "beamerthemeAmurmaple",
  includes = { "multicol", "iftex", "pgfpages", "fontawesome5", "luamesh", "tcolorbox", "tcolorboxlibraryskins", "tikzlibrarybackgrounds", "tikzlibraryquotes", "tikzlibraryangles", "tikzlibraryautomata", "tikzlibrarycalc" },
  lists = {},
  snippets = {
    S({ trig = "\\information", dscr = "\\begin{information}" }, { t({ "\\begin{information}", "\t" }), i(1), t({ "", "\\end{information}" }) }),
    S({ trig = "\\information", dscr = "\\begin{information}[title]" }, { t("\\begin{information}["), i(1, "title"), t({ "]", "\t" }), i(2), t({ "", "\\end{information}" }) }),
    S({ trig = "\\quotation", dscr = "\\begin{quotation}[author(s)]" }, { t("\\begin{quotation}["), i(1, "author(s)"), t({ "]", "\t" }), i(2), t({ "", "\\end{quotation}" }) }),
    S({ trig = "\\remark", dscr = "\\begin{remark}" }, { t({ "\\begin{remark}", "\t" }), i(1), t({ "", "\\end{remark}" }) }),
    S({ trig = "\\remark", dscr = "\\begin{remark}[title complement]" }, { t("\\begin{remark}["), i(1, "title complement"), t({ "]", "\t" }), i(2), t({ "", "\\end{remark}" }) }),
    S({ trig = "\\boxalert", dscr = "{text}" }, { t("\\boxalert{"), i(1, "text"), t("}") }),
    S({ trig = "\\boxalert", dscr = "<overlay specification>{text}" }, { t("\\boxalert<"), i(1, "overlay specification"), t(">{"), i(2, "text"), t("}") }),
    S({ trig = "\\collaboration", dscr = "{collaboration}" }, { t("\\collaboration{"), i(1, "collaboration"), t("}") }),
    S({ trig = "\\framesection", dscr = "{text}" }, { t("\\framesection{"), i(1, "text"), t("}") }),
    S({ trig = "\\mail", dscr = "{email}" }, { t("\\mail{"), i(1, "email"), t("}") }, "U"),
    S({ trig = "\\sepframe", dscr = "" }, { t("\\sepframe") }),
    S({ trig = "\\sepframe", dscr = "[options]" }, { t("\\sepframe["), i(1, "options"), t("]") }),
    S({ trig = "\\thanksframe", dscr = "[graphic]{title}" }, { t("\\thanksframe["), i(1, "graphic"), t("]{"), i(2, "title"), t("}") }),
    S({ trig = "\\thanksframe", dscr = "{title}" }, { t("\\thanksframe{"), i(1, "title"), t("}") }),
    S({ trig = "\\webpage", dscr = "{URL}" }, { t("\\webpage{"), i(1, "URL"), t("}") }, "U"),
    S({ trig = "\\boxalertenv", dscr = "\\begin{boxalertenv} ∗", priority = 900 }, { t({ "\\begin{boxalertenv}", "\t" }), i(1), t({ "", "\\end{boxalertenv}" }) }, "*"),
    S({ trig = "\\theamurmapletoc", dscr = "∗", priority = 900 }, { t("\\theamurmapletoc") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usetheme/Amurmaple#c",
      lines = {
        "nogauge",
        "nomail",
        "delaunay",
        "amurmapleblue",
        "amurmaplegreen",
        "amurmapleblack",
        "sidebarwidth=##L",
        "sidebar",
        "toplogo",
        "leftframetitle",
        "rule",
        "rulecolor=#%color",
      },
    },
    {
      targets = "\\sepframe",
      lines = {
        "title={%<text%>}",
        "image={%<graphics code%>}",
      },
    },
  },
}
