-- Generated by snipgen 1 from beamerthemeTianQing.cwl; do not edit, regenerate.
-- source: TeXstudio completion/beamerthemeTianQing.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9c1cc44d98fc1714bd27ad08f5e9c7887c3f3efd6d6c2c3da9645da789677e95
-- cwl-header:
--   # TianQing beamertheme
--   # Matthew Bertucci 2024/09/23 for v1.02
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "beamerthemeTianQing",
  includes = { "cncolours", "pgfornament-han", "xpatch", "calc", "relsize", "unicode-math", "tcolorbox", "tcolorboxlibraryskins", "textpos" },
  lists = {},
  snippets = {
    S({ trig = "\\TQTopDecoWidth", dscr = "∗", priority = 900 }, { t("\\TQTopDecoWidth") }, "*"),
    S({ trig = "\\TQBottomDecoWidth", dscr = "∗", priority = 900 }, { t("\\TQBottomDecoWidth") }, "*"),
    S({ trig = "\\TQTopDecoOpacity", dscr = "∗", priority = 900 }, { t("\\TQTopDecoOpacity") }, "*"),
    S({ trig = "\\TQBottomDecoOpacity", dscr = "∗", priority = 900 }, { t("\\TQBottomDecoOpacity") }, "*"),
  },
  keyvals = {},
}
