-- Generated by snipgen 1 from beamerbasethemes.cwl; do not edit, regenerate.
-- source: TeXstudio completion/beamerbasethemes.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 5ee1d67f8fb5522616ebb3ce8a4a09ddc97736c8f0f8360d6c81ac6644e86960
-- cwl-header:
--   # beamerbasethemes package
--   # Matthew Bertucci 1/30/2022 for v3.65
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "beamerbasethemes",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\usetheme", dscr = "{beamertheme}" }, { t("\\usetheme{"), i(1, "beamertheme"), t("}") }, "u"),
    S({ trig = "\\usetheme", dscr = "[options]{beamertheme}" }, { t("\\usetheme["), i(1, "options"), t("]{"), i(2, "beamertheme"), t("}") }),
    S({ trig = "\\usecolortheme", dscr = "{beamer color theme}" }, { t("\\usecolortheme{"), i(1, "beamer color theme"), t("}") }, "u"),
    S({ trig = "\\usecolortheme", dscr = "[options]{beamer color theme}" }, { t("\\usecolortheme["), i(1, "options"), t("]{"), i(2, "beamer color theme"), t("}") }),
    S({ trig = "\\usefonttheme", dscr = "{beamer font theme}" }, { t("\\usefonttheme{"), i(1, "beamer font theme"), t("}") }, "u"),
    S({ trig = "\\usefonttheme", dscr = "[options]{beamer font theme}" }, { t("\\usefonttheme["), i(1, "options"), t("]{"), i(2, "beamer font theme"), t("}") }),
    S({ trig = "\\useoutertheme", dscr = "{beamer outer theme}" }, { t("\\useoutertheme{"), i(1, "beamer outer theme"), t("}") }, "u"),
    S({ trig = "\\useoutertheme", dscr = "[options]{beamer outer theme}" }, { t("\\useoutertheme["), i(1, "options"), t("]{"), i(2, "beamer outer theme"), t("}") }),
    S({ trig = "\\useinnertheme", dscr = "{beamer inner theme}" }, { t("\\useinnertheme{"), i(1, "beamer inner theme"), t("}") }, "u"),
    S({ trig = "\\useinnertheme", dscr = "[options]{beamer inner theme}" }, { t("\\useinnertheme["), i(1, "options"), t("]{"), i(2, "beamer inner theme"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\useinnertheme/rounded",
      lines = {
        "shadow#true,false",
      },
    },
    {
      targets = "\\useoutertheme/miniframes",
      lines = {
        "footline=#empty,authorinstitute,authortitle,institutetitle,authorinstitutetitle",
        "subsection#true,false",
      },
    },
    {
      targets = "\\useoutertheme/smoothbars",
      lines = {
        "subsection#true,false",
      },
    },
    {
      targets = "\\useoutertheme/sidebar",
      lines = {
        "height=##L",
        "hideothersubsections",
        "hideallsubsections",
        "left",
        "right",
        "width=##L",
      },
    },
    {
      targets = "\\useoutertheme/tree",
      lines = {
        "hooks#true,false",
      },
    },
    {
      targets = "\\usecolortheme/structure",
      lines = {
        "rgb={%<r,g,b%>}",
        "RGB={%<r,g,b%>}",
        "cmyk={%<c,m,y,k%>}",
        "cmy={%<c,m,y%>}",
        "hsb={%<h,s,b%>}",
        "named=#%color",
      },
    },
    {
      targets = "\\usecolortheme/albatross,\\usecolortheme/monarca",
      lines = {
        "overlystylish",
      },
    },
    {
      targets = "\\usefonttheme/serif",
      lines = {
        "stillsansserifmath",
        "stillsansserifsmall",
        "stillsansseriflarge",
        "stillsansseriftext",
        "onlymath",
      },
    },
    {
      targets = "\\usefonttheme/structurebold,\\usefonttheme/structureitalicserif,\\usefonttheme/structuresmallcapsserif",
      lines = {
        "onlysmall",
        "onlylarge",
      },
    },
  },
}
