-- Generated by snipgen 1 from beamerthemefocus.cwl; do not edit, regenerate.
-- source: TeXstudio completion/beamerthemefocus.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: ca1c041c34fe9401af0771648796b323733fcc6e44eecb96742555623279c367
-- cwl-header:
--   # focus beamertheme
--   # Matthew Bertucci 3/12/2022 for v3.3.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "beamerthemefocus",
  includes = { "fontenc", "FiraSans", "FiraMono", "firamath-otf", "appendixnumberbeamer", "bookmark", "etoolbox", "tikz" },
  lists = {},
  snippets = {
    S({ trig = "\\bkmtranslateto", dscr = "∗", priority = 900 }, { t("\\bkmtranslateto") }, "*"),
    S({ trig = "\\bkmtranslate", dscr = "{arg} ∗", priority = 900 }, { t("\\bkmtranslate{"), i(1, "arg"), t("}") }, "*"),
    S({ trig = "\\therealframenumber", dscr = "∗", priority = 900 }, { t("\\therealframenumber") }, "*"),
    S({ trig = "\\no", dscr = "∗", priority = 900 }, { t("\\no") }, "*"),
    S({ trig = "\\footlineinfo", dscr = "{text}" }, { t("\\footlineinfo{"), i(1, "text"), t("}") }),
    S({ trig = "\\DH", dscr = "" }, { t("\\DH") }, "n"),
    S({ trig = "\\NG", dscr = "" }, { t("\\NG") }, "n"),
    S({ trig = "\\dj", dscr = "" }, { t("\\dj") }, "n"),
    S({ trig = "\\ng", dscr = "" }, { t("\\ng") }, "n"),
    S({ trig = "\\k", dscr = "{arg}" }, { t("\\k{"), i(1, "arg"), t("}") }, "n"),
    S({ trig = "\\guillemotleft", dscr = "∗", priority = 900 }, { t("\\guillemotleft") }, "*n"),
    S({ trig = "\\guillemotright", dscr = "∗", priority = 900 }, { t("\\guillemotright") }, "*n"),
    S({ trig = "\\guilsinglleft", dscr = "" }, { t("\\guilsinglleft") }, "n"),
    S({ trig = "\\guilsinglright", dscr = "" }, { t("\\guilsinglright") }, "n"),
    S({ trig = "\\quotedblbase", dscr = "" }, { t("\\quotedblbase") }, "n"),
    S({ trig = "\\quotesinglbase", dscr = "" }, { t("\\quotesinglbase") }, "n"),
    S({ trig = "\\textquotedbl", dscr = "" }, { t("\\textquotedbl") }, "n"),
    S({ trig = "\\DJ", dscr = "" }, { t("\\DJ") }, "n"),
    S({ trig = "\\th", dscr = "" }, { t("\\th") }, "n"),
    S({ trig = "\\TH", dscr = "" }, { t("\\TH") }, "n"),
    S({ trig = "\\dh", dscr = "" }, { t("\\dh") }, "n"),
    S({ trig = "\\Hwithstroke", dscr = "∗", priority = 900 }, { t("\\Hwithstroke") }, "*n"),
    S({ trig = "\\hwithstroke", dscr = "∗", priority = 900 }, { t("\\hwithstroke") }, "*n"),
    S({ trig = "\\textogonekcentered", dscr = "{arg} ∗", priority = 900 }, { t("\\textogonekcentered{"), i(1, "arg"), t("}") }, "*n"),
    S({ trig = "\\guillemetleft", dscr = "" }, { t("\\guillemetleft") }, "n"),
    S({ trig = "\\guillemetright", dscr = "" }, { t("\\guillemetright") }, "n"),
  },
  keyvals = {
    {
      targets = "\\usetheme/focus",
      lines = {
        "numbering=#progressbar,fullbar,minimal,none",
        "totalframenumbering=#yes,no",
        "nofirafonts",
      },
    },
  },
}
