-- Generated by snipgen 1 from beuron.cwl; do not edit, regenerate.
-- source: TeXstudio completion/beuron.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 255d34b1b06c3a9f18355171b0926528ad56cb9a8190f90c6b2bab3a059f3e4b
-- cwl-header:
--   # beuron package
--   # Matthew Bertucci 8/29/2021 for v1.3
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "beuron",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\textbeuron", dscr = "{text}" }, { t("\\textbeuron{"), i(1, "text"), t("}") }, "n"),
    S({ trig = "\\textbeuronc", dscr = "{text}" }, { t("\\textbeuronc{"), i(1, "text"), t("}") }, "n"),
    S({ trig = "\\textbeuronx", dscr = "{text}" }, { t("\\textbeuronx{"), i(1, "text"), t("}") }, "n"),
    S({ trig = "\\textbeuron*", dscr = "{text}" }, { t("\\textbeuron*{"), i(1, "text"), t("}") }, "n"),
    S({ trig = "\\textbeuronc*", dscr = "{text}" }, { t("\\textbeuronc*{"), i(1, "text"), t("}") }, "n"),
    S({ trig = "\\textbeuronx*", dscr = "{text}" }, { t("\\textbeuronx*{"), i(1, "text"), t("}") }, "n"),
    S({ trig = "\\beuronOmega", dscr = "" }, { t("\\beuronOmega") }, "n"),
  },
  keyvals = {},
}
