-- Generated by snipgen 1 from bguq.cwl; do not edit, regenerate.
-- source: TeXstudio completion/bguq.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 7566808cdb85858dc871b711751778fc50d58c4d642100e4a9d00c41ece56558
-- cwl-header:
--   # bguq package
--   # Matthew Bertucci 8/27/2021 for v0.4
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "bguq",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\bguq", dscr = "" }, h.mathwrap({ t("\\bguq") }), "m"),
    S({ trig = "\\bguqwidth", dscr = "∗", priority = 900 }, { t("\\bguqwidth") }, "*"),
  },
  keyvals = {},
}
