-- Generated by snipgen 1 from bibtopicprefix.cwl; do not edit, regenerate.
-- source: TeXstudio completion/bibtopicprefix.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 159d9536bec5583f84fc73ef7e11eb7eabd0b7e8f2227dc296e0d6057b9c966f
-- cwl-header:
--   # bibtopicprefix package
--   # Matthew Bertucci 3/21/2022 for v1.10
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "bibtopicprefix",
  includes = { "scrlfile", "bibtopic" },
  lists = {},
  snippets = {
    S({ trig = "\\bibprefix", dscr = "" }, { t("\\bibprefix") }),
  },
  keyvals = {},
}
