-- Generated by snipgen 1 from blkarray.cwl; do not edit, regenerate.
-- source: TeXstudio completion/blkarray.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c1780e0d5b241f46cdf87377a65459d00ab601897eae9541850452a533a09477
-- cwl-header:
--   # blkarray package
--   # Matthew Bertucci 10/20/2021 for v0.07
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "blkarray",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\BAnewcolumntype", dscr = "{name}{argument}" }, { t("\\BAnewcolumntype{"), i(1, "name"), t("}{"), i(2, "argument"), t("}") }, "d"),
    S({ trig = "\\BAnewcolumntype", dscr = "[args]{name}{argument}" }, { t("\\BAnewcolumntype["), i(1, "args"), t("]{"), i(2, "name"), t("}{"), i(3, "argument"), t("}") }, "d"),
    S({ trig = "\\blockarray", dscr = "\\begin{blockarray}{cols}" }, { t("\\begin{blockarray}{"), i(1, "cols"), t({ "}", "\t" }), i(2), t({ "", "\\end{blockarray}" }) }, "\\tabular"),
    S({ trig = "\\BAmulticolumn", dscr = "{cols}{pos}{text}" }, { t("\\BAmulticolumn{"), i(1, "cols"), t("}{"), i(2, "pos"), t("}{"), i(3, "text"), t("}") }),
    S({ trig = "\\block", dscr = "\\begin{block}{cols}" }, { t("\\begin{block}{"), i(1, "cols"), t({ "}", "\t" }), i(2), t({ "", "\\end{block}" }) }, "\\tabular"),
    S({ trig = "\\block*", dscr = "\\begin{block*}{cols}" }, { t("\\begin{block*}{"), i(1, "cols"), t({ "}", "\t" }), i(2), t({ "", "\\end{block*}" }) }, "\\tabular"),
    S({ trig = "\\Left", dscr = "{text}{delim}" }, { t("\\Left{"), i(1, "text"), t("}{"), i(2, "delim"), t("}") }),
    S({ trig = "\\Right", dscr = "{text}{delim}" }, { t("\\Right{"), i(1, "text"), t("}{"), i(2, "delim"), t("}") }),
    S({ trig = "\\BAenum", dscr = "" }, { t("\\BAenum") }),
    S({ trig = "\\theBAenumi", dscr = "" }, { t("\\theBAenumi") }),
    S({ trig = "\\testBAtablenotes", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\testBAtablenotes{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\BAtablenotestrue", dscr = "" }, { t("\\BAtablenotestrue") }),
    S({ trig = "\\BAtablenotesfalse", dscr = "" }, { t("\\BAtablenotesfalse") }),
    S({ trig = "\\BAparfootnotes", dscr = "" }, { t("\\BAparfootnotes") }),
    S({ trig = "\\BAnoalign", dscr = "{text}" }, { t("\\BAnoalign{"), i(1, "text"), t("}") }),
    S({ trig = "\\BAnoalign*", dscr = "{text}" }, { t("\\BAnoalign*{"), i(1, "text"), t("}") }),
    S({ trig = "\\BAmultirow", dscr = "{dimen}" }, { t("\\BAmultirow{"), i(1, "dimen"), t("}") }),
    S({ trig = "\\BAmultirow", dscr = "{dimen}{text}" }, { t("\\BAmultirow{"), i(1, "dimen"), t("}{"), i(2, "text"), t("}") }),
    S({ trig = "\\BAhline", dscr = "" }, { t("\\BAhline") }, "t"),
    S({ trig = "\\BAhhline", dscr = "{colspec}" }, { t("\\BAhhline{"), i(1, "colspec"), t("}") }, "t"),
    S({ trig = "\\BAextraheightafterhline", dscr = "∗", priority = 900 }, { t("\\BAextraheightafterhline") }, "*"),
    S({ trig = "\\BAextrarowheight", dscr = "∗", priority = 900 }, { t("\\BAextrarowheight") }, "*"),
    S({ trig = "\\BAtracing", dscr = "∗", priority = 900 }, { t("\\BAtracing") }, "*"),
    S({ trig = "\\BAarrayrulewidth", dscr = "∗", priority = 900 }, { t("\\BAarrayrulewidth") }, "*"),
    S({ trig = "\\BAdoublerulesep", dscr = "∗", priority = 900 }, { t("\\BAdoublerulesep") }, "*"),
  },
  keyvals = {},
}
