-- Generated by snipgen 1 from boustr.cwl; do not edit, regenerate.
-- source: TeXstudio completion/boustr.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f4e241d497cb355983308b009d0248e18aa6182aaea2af43935d6aa25d1514da
-- cwl-header:
--   # boustr package
--   # Matthew Bertucci 2022/07/06 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "boustr",
  includes = { "graphicx" },
  lists = {},
  snippets = {
    S({ trig = "\\boustrophedon", dscr = "\\begin{boustrophedon}" }, { t({ "\\begin{boustrophedon}", "\t" }), i(1), t({ "", "\\end{boustrophedon}" }) }),
    S({ trig = "\\rtl", dscr = "\\begin{rtl}" }, { t({ "\\begin{rtl}", "\t" }), i(1), t({ "", "\\end{rtl}" }) }),
    S({ trig = "\\sidewaysflip", dscr = "\\begin{sidewaysflip}{width}" }, { t("\\begin{sidewaysflip}{"), i(1, "width"), t({ "}", "\t" }), i(2), t({ "", "\\end{sidewaysflip}" }) }),
    S({ trig = "\\ifboustright", dscr = "∗", priority = 900 }, { t("\\ifboustright") }, "*"),
    S({ trig = "\\boustrighttrue", dscr = "" }, { t("\\boustrighttrue") }),
    S({ trig = "\\boustrightfalse", dscr = "" }, { t("\\boustrightfalse") }),
  },
  keyvals = {},
}
