-- Generated by snipgen 1 from bubblesort.cwl; do not edit, regenerate.
-- source: TeXstudio completion/bubblesort.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b5fd750bb16b61fec0c359e367dd463e5e66d8a53e3ca1b69b045817782337a6
-- cwl-header:
--   # bubblesort package
--   # Matthew Bertucci 11/13/2021 for v1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "bubblesort",
  includes = { "etoolbox" },
  lists = {},
  snippets = {
    S({ trig = "\\bubblesort", dscr = "{list}{macro}" }, { t("\\bubblesort{"), i(1, "list"), t("}{"), i(2, "macro"), t("}") }, "d"),
    S({ trig = "\\bubblesort", dscr = "[comparator cmd]{list}{macro}" }, { t("\\bubblesort["), i(1, "comparator cmd"), t("]{"), i(2, "list"), t("}{"), i(3, "macro"), t("}") }, "d"),
    S({ trig = "\\doublebubblesort", dscr = "{list1}{macro1}{list2}{macro2}" }, { t("\\doublebubblesort{"), i(1, "list1"), t("}{"), i(2, "macro1"), t("}{"), i(3, "list2"), t("}{"), i(4, "macro2"), t("}") }, "d"),
    S({ trig = "\\doublebubblesort", dscr = "[comparator cmd]{list1}{macro1}{list2}{macro2}" }, { t("\\doublebubblesort["), i(1, "comparator cmd"), t("]{"), i(2, "list1"), t("}{"), i(3, "macro1"), t("}{"), i(4, "list2"), t("}{"), i(5, "macro2"), t("}") }, "d"),
    S({ trig = "\\bubblesortflag", dscr = "" }, { t("\\bubblesortflag") }),
    S({ trig = "\\realSort", dscr = "{arg1}{arg2}" }, { t("\\realSort{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }),
    S({ trig = "\\alphSort", dscr = "{arg1}{arg2}" }, { t("\\alphSort{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }),
  },
  keyvals = {},
}
