-- Generated by snipgen 1 from bussproofs-colorful.cwl; do not edit, regenerate.
-- source: TeXstudio completion/bussproofs-colorful.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 3f3e6f06d936d433483e738a052356f038a580d1266fd27e0fe620dbce5f41fb
-- cwl-header:
--   # bussproofs-colorful package
--   # Matthew Bertucci 2026/02/02 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "bussproofs-colorful",
  includes = { "bussproofs", "xcolor", "kvoptions" },
  lists = {},
  snippets = {
    S({ trig = "\\ProofColors", dscr = "\\begin{ProofColors}" }, { t({ "\\begin{ProofColors}", "\t" }), i(1), t({ "", "\\end{ProofColors}" }) }),
    S({ trig = "\\ProofColors", dscr = "\\begin{ProofColors}[options]" }, { t("\\begin{ProofColors}["), i(1, "options"), t({ "]", "\t" }), i(2), t({ "", "\\end{ProofColors}" }) }),
    S({ trig = "\\SetNodeColor", dscr = "{color}" }, { t("\\SetNodeColor{"), i(1, "color"), t("}") }),
    S({ trig = "\\SetLineColor", dscr = "{color}" }, { t("\\SetLineColor{"), i(1, "color"), t("}") }),
    S({ trig = "\\SetLabelColor", dscr = "{color}" }, { t("\\SetLabelColor{"), i(1, "color"), t("}") }),
    S({ trig = "\\ResetProofColors", dscr = "" }, { t("\\ResetProofColors") }),
    S({ trig = "\\LoadProofTheme", dscr = "{theme}" }, { t("\\LoadProofTheme{"), i(1, "theme"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/bussproofs-colorful#c",
      lines = {
        "nodecolor=#%color",
        "linecolor=#%color",
        "labelcolor=#%color",
        "patchnodes#true,false",
        "patchlines#true,false",
        "patchlabels#true,false",
        "debug#true,false",
        "theme=#classic,dark,pastel,highcontrast",
      },
    },
    {
      targets = "\\begin{ProofColors}",
      lines = {
        "node=#%color",
        "line=#%color",
        "label=#%color",
        "theme=#classic,dark,pastel,highcontrast",
      },
    },
    {
      targets = "\\LoadProofTheme",
      lines = {
        "classic",
        "dark",
        "pastel",
        "highcontrast",
      },
    },
  },
}
