-- Generated by snipgen 1 from bxcoloremoji.cwl; do not edit, regenerate.
-- source: TeXstudio completion/bxcoloremoji.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 53bf6202a8204468cf9899c0decee36bb6c2ec8b7d3af5b352e9f0556064d403
-- cwl-header:
--   # bxcoloremoji package
--   # Matthew Bertucci 2026/06/24 for v1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "bxcoloremoji",
  includes = { "etoolbox", "keyval", "graphicx", "color", "twemojis" },
  lists = {},
  snippets = {
    S({ trig = "\\coloremojisetup", dscr = "{keyvals}" }, { t("\\coloremojisetup{"), i(1, "keyvals"), t("}") }),
    S({ trig = "\\coloremoji", dscr = "{emoji name}" }, { t("\\coloremoji{"), i(1, "emoji name"), t("}") }),
    S({ trig = "\\coloremoji", dscr = "[keyvals]{emoji name}" }, { t("\\coloremoji["), i(1, "keyvals"), t("]{"), i(2, "emoji name"), t("}") }),
    S({ trig = "\\coloremoji*", dscr = "{emoji name}" }, { t("\\coloremoji*{"), i(1, "emoji name"), t("}") }),
    S({ trig = "\\coloremoji*", dscr = "[keyvals]{emoji name}" }, { t("\\coloremoji*["), i(1, "keyvals"), t("]{"), i(2, "emoji name"), t("}") }),
    S({ trig = "\\coloremojicode", dscr = "{code value list}" }, { t("\\coloremojicode{"), i(1, "code value list"), t("}") }),
    S({ trig = "\\coloremojicode", dscr = "[keyvals]{code value list}" }, { t("\\coloremojicode["), i(1, "keyvals"), t("]{"), i(2, "code value list"), t("}") }),
    S({ trig = "\\coloremojicode*", dscr = "{code value list}" }, { t("\\coloremojicode*{"), i(1, "code value list"), t("}") }),
    S({ trig = "\\coloremojicode*", dscr = "[keyvals]{code value list}" }, { t("\\coloremojicode*["), i(1, "keyvals"), t("]{"), i(2, "code value list"), t("}") }),
    S({ trig = "\\coloremojikeycapof", dscr = "{number}" }, { t("\\coloremojikeycapof{"), i(1, "number"), t("}") }),
    S({ trig = "\\coloremojikeycapof", dscr = "[keyvals]{number}" }, { t("\\coloremojikeycapof["), i(1, "keyvals"), t("]{"), i(2, "number"), t("}") }),
    S({ trig = "\\coloremojikeycapof*", dscr = "{number}" }, { t("\\coloremojikeycapof*{"), i(1, "number"), t("}") }),
    S({ trig = "\\coloremojikeycapof*", dscr = "[keyvals]{number}" }, { t("\\coloremojikeycapof*["), i(1, "keyvals"), t("]{"), i(2, "number"), t("}") }),
    S({ trig = "\\coloremojikeycap", dscr = "{counter}" }, { t("\\coloremojikeycap{"), i(1, "counter"), t("}") }),
    S({ trig = "\\coloremojikeycap", dscr = "[keyvals]{counter}" }, { t("\\coloremojikeycap["), i(1, "keyvals"), t("]{"), i(2, "counter"), t("}") }),
    S({ trig = "\\coloremojikeycap*", dscr = "{counter}" }, { t("\\coloremojikeycap*{"), i(1, "counter"), t("}") }),
    S({ trig = "\\coloremojikeycap*", dscr = "[keyvals]{counter}" }, { t("\\coloremojikeycap*["), i(1, "keyvals"), t("]{"), i(2, "counter"), t("}") }),
    S({ trig = "\\coloremojifill", dscr = "{emoji name}" }, { t("\\coloremojifill{"), i(1, "emoji name"), t("}") }),
    S({ trig = "\\coloremojiline", dscr = "" }, { t("\\coloremojiline") }),
    S({ trig = "\\coloremojilist", dscr = "\\begin{coloremojilist}{emoji name}" }, { t("\\begin{coloremojilist}{"), i(1, "emoji name"), t({ "}", "\t" }), i(2), t({ "", "\\end{coloremojilist}" }) }),
    S({ trig = "\\coloremojiautolist", dscr = "\\begin{coloremojiautolist}{emoji name}" }, { t("\\begin{coloremojiautolist}{"), i(1, "emoji name"), t({ "}", "\t" }), i(2), t({ "", "\\end{coloremojiautolist}" }) }),
    S({ trig = "\\coloremojicodefill", dscr = "{code value list}" }, { t("\\coloremojicodefill{"), i(1, "code value list"), t("}") }),
    S({ trig = "\\coloremojicodeline", dscr = "{code value list}" }, { t("\\coloremojicodeline{"), i(1, "code value list"), t("}") }),
    S({ trig = "\\coloremojicodelist", dscr = "\\begin{coloremojicodelist}{code value list}" }, { t("\\begin{coloremojicodelist}{"), i(1, "code value list"), t({ "}", "\t" }), i(2), t({ "", "\\end{coloremojicodelist}" }) }),
    S({ trig = "\\coloremojicodeautolist", dscr = "\\begin{coloremojicodeautolist}{code value list}" }, { t("\\begin{coloremojicodeautolist}{"), i(1, "code value list"), t({ "}", "\t" }), i(2), t({ "", "\\end{coloremojicodeautolist}" }) }),
    S({ trig = "\\coloremojiSetAbsolutePath", dscr = "{family}{directory}" }, { t("\\coloremojiSetAbsolutePath{"), i(1, "family"), t("}{"), i(2, "directory"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/bxcoloremoji#c",
      lines = {
        "jatype=#auto,true,false",
        "names#true,false",
        "nodvidriver",
        "resetdvidriver",
        "preload-names=#auto,true,false",
        "bbparam=#auto,true,false",
        "bxghost=#auto,true,false",
        "pua=",
        "dvisvgm-adjust#true,false",
      },
    },
    {
      targets = "\\usepackage/bxcoloremoji#c,\\coloremojisetup,\\coloremoji,\\coloremoji*,\\coloremojicode,\\coloremojicode*,\\coloremojikeycapof,\\coloremojikeycapof*,\\coloremojikeycap,\\coloremojikeycap*",
      lines = {
        "twemojis",
        "family=%<family%>",
        "no-image",
        "twemoji-pdf",
        "twemoji-png",
        "size=##L",
        "size*=##L",
        "scale=%<factor%>",
      },
    },
    {
      targets = "\\pagenumbering#c",
      lines = {
        "coloremojikeycap",
      },
    },
  },
}
