-- Generated by snipgen 1 from bxjaprnind.cwl; do not edit, regenerate.
-- source: TeXstudio completion/bxjaprnind.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 2c1e3e4726e3741637997238eb863bceaef4ce8c10e270278ad0cfd201c5de7c
-- cwl-header:
--   # bxjaprnind package
--   # Matthew Bertucci 2022/05/31 for v0.4a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "bxjaprnind",
  includes = { "bxtoolbox", "everyhook" },
  lists = {},
  snippets = {
    S({ trig = "\\useparheadparenindent", dscr = "" }, { t("\\useparheadparenindent") }),
    S({ trig = "\\nouseparheadparenindent", dscr = "" }, { t("\\nouseparheadparenindent") }),
    S({ trig = "\\uselineheadparenindent", dscr = "" }, { t("\\uselineheadparenindent") }),
    S({ trig = "\\nouselineheadparenindent", dscr = "" }, { t("\\nouselineheadparenindent") }),
    S({ trig = "\\usedialogueparenindent", dscr = "" }, { t("\\usedialogueparenindent") }),
    S({ trig = "\\nousedialogueparenindent", dscr = "" }, { t("\\nousedialogueparenindent") }),
    S({ trig = "\\parheadparenindentamount", dscr = "{real number}" }, { t("\\parheadparenindentamount{"), i(1, "real number"), t("}") }),
    S({ trig = "\\lineheadparenindentamount", dscr = "{real number}" }, { t("\\lineheadparenindentamount{"), i(1, "real number"), t("}") }),
    S({ trig = "\\lineheadforceindentamount", dscr = "{real number}" }, { t("\\lineheadforceindentamount{"), i(1, "real number"), t("}") }),
    S({ trig = "\\dialogueparenindentamount", dscr = "{real number}" }, { t("\\dialogueparenindentamount{"), i(1, "real number"), t("}") }),
    S({ trig = "\\prnind", dscr = "" }, { t("\\prnind") }),
    S({ trig = "\\prnind", dscr = "[real number]" }, { t("\\prnind["), i(1, "real number"), t("]") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/bxjaprnind#c",
      lines = {
        "force",
      },
    },
  },
}
