-- Generated by snipgen 1 from calcfrac.cwl; do not edit, regenerate.
-- source: TeXstudio completion/calcfrac.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: a686c99f05ac73b716fe8cd96c9f6c8ea4fbd003e471f75a197ad92dd5d71054
-- cwl-header:
--   # calcfrac package
--   # Matthew Bertucci 2023/10/31 for v0.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "calcfrac",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\cfdisp", dscr = "{sign}{num1}{num2} ∗", priority = 900 }, { t("\\cfdisp{"), i(1, "sign"), t("}{"), i(2, "num1"), t("}{"), i(3, "num2"), t("}") }, "*"),
    S({ trig = "\\calcfrac", dscr = "{expression}" }, { t("\\calcfrac{"), i(1, "expression"), t("}") }),
  },
  keyvals = {},
}
