-- Generated by snipgen 1 from canoniclayout.cwl; do not edit, regenerate.
-- source: TeXstudio completion/canoniclayout.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: d06db93e9a02ef8e04041af475fd7f33bcd09a1887f0af98a77e0cb7e0b168fc
-- cwl-header:
--   # canoniclayout package
--   # Matthew Bertucci 2022/11/01 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "canoniclayout",
  includes = { "etoolbox", "pict2e", "xcolor" },
  lists = {},
  snippets = {
    S({ trig = "\\currentfontletters", dscr = "" }, { t("\\currentfontletters") }),
    S({ trig = "\\charactersperpage", dscr = "" }, { t("\\charactersperpage") }),
    S({ trig = "\\CLstartdrawings", dscr = "∗", priority = 900 }, { t("\\CLstartdrawings") }, "*"),
    S({ trig = "\\CLstopdrawings", dscr = "∗", priority = 900 }, { t("\\CLstopdrawings") }, "*"),
  },
  keyvals = {},
}
