-- Generated by snipgen 1 from Carrickc.cwl; do not edit, regenerate.
-- source: TeXstudio completion/Carrickc.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: dc3b2a072a955db505e8a1cb9f20a4f42af857665ed3d5ca32db3ebd5fa0e5ff
-- cwl-header:
--   # Carrickc package
--   # Matthew Bertucci 8/27/2021 for v1.01
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "Carrickc",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\Carrickcfamily", dscr = "" }, { t("\\Carrickcfamily") }, "n"),
    S({ trig = "\\carr", dscr = "{text}" }, { t("\\carr{"), i(1, "text"), t("}") }, "n"),
  },
  keyvals = {},
}
