-- Generated by snipgen 1 from chemformula.cwl; do not edit, regenerate.
-- source: TeXstudio completion/chemformula.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: e6646de0d31e84dd176acf3a4e8c5edeabf64d1eac85e4754e90467a20f411cf
-- cwl-header:
--   # package chemformula v4.17
--   # typeset chemical compounds and reactions
--   # Clemens Niederberger 01/07/2016
--   # URL: http://www.ctan.org/pkg/chemformula
--   # URL: http://www.mychemistry.eu/forums/forum/chemformula/
--   # Contact: contact@mychemistry.eu
--   # File written on 02/23/2016
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "chemformula",
  includes = { "tikz", "amsmath", "xfrac", "nicefrac" },
  lists = {},
  snippets = {
    S({ trig = "\\setchemformula", dscr = "{options}" }, { t("\\setchemformula{"), i(1, "options"), t("}") }),
    S({ trig = "\\ch", dscr = "{formula}" }, { t("\\ch{"), i(1, "formula"), t("}") }),
    S({ trig = "\\ch", dscr = "[options]{formula}" }, { t("\\ch["), i(1, "options"), t("]{"), i(2, "formula"), t("}") }),
    S({ trig = "\\bond", dscr = "{bond name}" }, { t("\\bond{"), i(1, "bond name"), t("}") }),
    S({ trig = "\\NewChemBond", dscr = "{name}{code}" }, { t("\\NewChemBond{"), i(1, "name"), t("}{"), i(2, "code"), t("}") }),
    S({ trig = "\\DeclareChemBond", dscr = "{name}{code} ∗", priority = 900 }, { t("\\DeclareChemBond{"), i(1, "name"), t("}{"), i(2, "code"), t("}") }, "*"),
    S({ trig = "\\RenewChemBond", dscr = "{name}{code} ∗", priority = 900 }, { t("\\RenewChemBond{"), i(1, "name"), t("}{"), i(2, "code"), t("}") }, "*"),
    S({ trig = "\\ProvideChemBond", dscr = "{name}{code} ∗", priority = 900 }, { t("\\ProvideChemBond{"), i(1, "name"), t("}{"), i(2, "code"), t("}") }, "*"),
    S({ trig = "\\NewChemBondAlias", dscr = "{new name}{old name}" }, { t("\\NewChemBondAlias{"), i(1, "new name"), t("}{"), i(2, "old name"), t("}") }),
    S({ trig = "\\DeclareChemBondAlias", dscr = "{new name}{old name} ∗", priority = 900 }, { t("\\DeclareChemBondAlias{"), i(1, "new name"), t("}{"), i(2, "old name"), t("}") }, "*"),
    S({ trig = "\\ShowChemBond", dscr = "{name} ∗", priority = 900 }, { t("\\ShowChemBond{"), i(1, "name"), t("}") }, "*"),
    S({ trig = "\\chcpd", dscr = "{compound}" }, { t("\\chcpd{"), i(1, "compound"), t("}") }),
    S({ trig = "\\chcpd", dscr = "[options]{compound}" }, { t("\\chcpd["), i(1, "options"), t("]{"), i(2, "compound"), t("}") }),
    S({ trig = "\\NewChemCompoundProperty", dscr = "{token}{replacement}" }, { t("\\NewChemCompoundProperty{"), i(1, "token"), t("}{"), i(2, "replacement"), t("}") }),
    S({ trig = "\\ProvideChemCompoundProperty", dscr = "{token}{replacement} ∗", priority = 900 }, { t("\\ProvideChemCompoundProperty{"), i(1, "token"), t("}{"), i(2, "replacement"), t("}") }, "*"),
    S({ trig = "\\RenewChemCompoundProperty", dscr = "{token}{replacement} ∗", priority = 900 }, { t("\\RenewChemCompoundProperty{"), i(1, "token"), t("}{"), i(2, "replacement"), t("}") }, "*"),
    S({ trig = "\\DeclareChemCompoundProperty", dscr = "{token}{replacement} ∗", priority = 900 }, { t("\\DeclareChemCompoundProperty{"), i(1, "token"), t("}{"), i(2, "replacement"), t("}") }, "*"),
    S({ trig = "\\RemoveChemCompoundProperty", dscr = "{token} ∗", priority = 900 }, { t("\\RemoveChemCompoundProperty{"), i(1, "token"), t("}") }, "*"),
    S({ trig = "\\NewChemAdditionSymbol", dscr = "{name}{input}{output}" }, { t("\\NewChemAdditionSymbol{"), i(1, "name"), t("}{"), i(2, "input"), t("}{"), i(3, "output"), t("}") }),
    S({ trig = "\\ProvideChemAdditionSymbol", dscr = "{name}{input}{output} ∗", priority = 900 }, { t("\\ProvideChemAdditionSymbol{"), i(1, "name"), t("}{"), i(2, "input"), t("}{"), i(3, "output"), t("}") }, "*"),
    S({ trig = "\\RenewChemAdditionSymbol", dscr = "{name}{input}{output} ∗", priority = 900 }, { t("\\RenewChemAdditionSymbol{"), i(1, "name"), t("}{"), i(2, "input"), t("}{"), i(3, "output"), t("}") }, "*"),
    S({ trig = "\\DeclareChemAdditionSymbol", dscr = "{name}{input}{output} ∗", priority = 900 }, { t("\\DeclareChemAdditionSymbol{"), i(1, "name"), t("}{"), i(2, "input"), t("}{"), i(3, "output"), t("}") }, "*"),
    S({ trig = "\\NewChemSymbol", dscr = "{input}{output}" }, { t("\\NewChemSymbol{"), i(1, "input"), t("}{"), i(2, "output"), t("}") }),
    S({ trig = "\\ProvideChemSymbol", dscr = "{input}{output} ∗", priority = 900 }, { t("\\ProvideChemSymbol{"), i(1, "input"), t("}{"), i(2, "output"), t("}") }, "*"),
    S({ trig = "\\RenewChemSymbol", dscr = "{input}{output} ∗", priority = 900 }, { t("\\RenewChemSymbol{"), i(1, "input"), t("}{"), i(2, "output"), t("}") }, "*"),
    S({ trig = "\\DeclareChemSymbol", dscr = "{input}{output} ∗", priority = 900 }, { t("\\DeclareChemSymbol{"), i(1, "input"), t("}{"), i(2, "output"), t("}") }, "*"),
    S({ trig = "\\NewChemArrow", dscr = "{type}{TikZ}" }, { t("\\NewChemArrow{"), i(1, "type"), t("}{"), i(2, "TikZ"), t("}") }),
    S({ trig = "\\ProvideChemArrow", dscr = "{type}{TikZ} ∗", priority = 900 }, { t("\\ProvideChemArrow{"), i(1, "type"), t("}{"), i(2, "TikZ"), t("}") }, "*"),
    S({ trig = "\\DeclareChemArrow", dscr = "{type}{TikZ} ∗", priority = 900 }, { t("\\DeclareChemArrow{"), i(1, "type"), t("}{"), i(2, "TikZ"), t("}") }, "*"),
    S({ trig = "\\RenewChemArrow", dscr = "{type}{TikZ} ∗", priority = 900 }, { t("\\RenewChemArrow{"), i(1, "type"), t("}{"), i(2, "TikZ"), t("}") }, "*"),
    S({ trig = "\\ShowChemArrow", dscr = "{type} ∗", priority = 900 }, { t("\\ShowChemArrow{"), i(1, "type"), t("}") }, "*"),
    S({ trig = "\\charrow", dscr = "{type}" }, { t("\\charrow{"), i(1, "type"), t("}") }),
    S({ trig = "\\charrow", dscr = "{type}[above]" }, { t("\\charrow{"), i(1, "type"), t("}["), i(2, "above"), t("]") }),
    S({ trig = "\\charrow", dscr = "{type}[above][below]" }, { t("\\charrow{"), i(1, "type"), t("}["), i(2, "above"), t("]["), i(3, "below"), t("]") }),
    S({ trig = "\\chname", dscr = "(text 1)(text 2)" }, { t("\\chname("), i(1, "text 1"), t(")("), i(2, "text 2"), t(")") }),
    S({ trig = "\\chlewis", dscr = "{electron spec}{atom}" }, { t("\\chlewis{"), i(1, "electron spec"), t("}{"), i(2, "atom"), t("}") }),
    S({ trig = "\\chlewis", dscr = "[options]{electron spec}{atom}" }, { t("\\chlewis["), i(1, "options"), t("]{"), i(2, "electron spec"), t("}{"), i(3, "atom"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\ch,\\setchemformula,\\chcpd",
      lines = {
        "decimal-marker={%<marker%>}",
        "frac-style=#math,xfrac,nicefrac",
        "frac-math-cmd={%<command sequence%>}",
        "stoich-space={%<skip%>}",
        "stoich-paren-parse=#true,false",
        "stoich-format={%<code%>}",
      },
    },
    {
      targets = "\\ch,\\setchemformula,\\chcpd",
      lines = {
        "circled=#formal,all,none",
        "circletype=#chem,math",
        "charge-hshift=##L",
      },
    },
    {
      targets = "\\ch,\\setchemformula,\\chcpd",
      lines = {
        "subscript-vshift=##L",
        "subscript-style=#text,math",
        "charge-hshift=##L",
        "charge-vshift=##L",
        "charge-style=#text,math",
        "math-scripts#true,false",
        "adduct-space=##L",
        "adduct-penalty={%<num%>}",
        "bond-length=##L",
        "bond-offset=##L",
        "bond-style={%<TikZ%>}",
        "bond-penalty={%<num%>}",
        "radical-style={%<TikZ%>}",
        "radical-radius=##L",
        "radical-hshift=##L",
        "radical-vshift=##L",
        "radical-space=##L",
      },
    },
    {
      targets = "\\ch,\\setchemformula,\\chcpd",
      lines = {
        "plus-space={%<skip%>}",
        "plus-penalty={%<num%>}",
        "plus-output-symbol={%<code%>}",
        "minus-space={%<skip%>}",
        "minus-penalty={%<num%>}",
        "minus-output-symbol={%<code%>}",
      },
    },
    {
      targets = "\\ch,\\setchemformula,\\chcpd",
      lines = {
        "math-space={%<skip%>}",
      },
    },
    {
      targets = "\\ch,\\setchemformula,\\chcpd",
      lines = {
        "arrow-offset=##L",
        "arrow-min-length=##L",
        "arrow-yshift=##L",
        "arrow-ratio={%<factor%>}",
        "compound-sep=##L",
        "label-offset=##L",
        "label-style={%<font command%>}",
        "arrow-penalty={%<num%>}",
        "arrow-style={%<TikZ%>}",
      },
    },
    {
      targets = "\\ch,\\setchemformula,\\chcpd",
      lines = {
        "name-format={%<commands%>}",
        "name-width=##L,auto",
      },
    },
    {
      targets = "\\ch,\\setchemformula,\\chcpd",
      lines = {
        "format={%<code%>}",
        "atom-format={%<code%>}",
        "font-family={%<family%>}",
        "font-series={%<series%>}",
        "font-shape={%<shape%>}",
        "font-spec={%<font%>}",
        "font-spec={[%<options%>]%<font%>}",
      },
    },
    {
      targets = "\\setchemformula",
      lines = {
        "tikz-external-disable=#true,false",
      },
    },
    {
      targets = "\\chlewis,\\setchemformula",
      lines = {
        "lewis-default=#.,:,|,o,single,pair,{pair (dotted)},{pair (line)},empty#c",
        "lewis-distance=##L",
        "lewis-line-length=##L",
        "lewis-line-width=##L",
        "lewis-offset=##L",
        "radical-radius=##L",
      },
    },
    {
      targets = "\\ch,\\setchemformula",
      lines = {
        "kroeger-vink=#true,false",
        "kv-positive-style={%<TikZ%>}",
        "kv-positive-radius=##L",
        "kv-positive-hshift=##L",
        "kv-positive-vshift=##L",
        "kv-positive-offset=##L",
        "kv-positive-symbol={%<TeX code%>}",
      },
    },
  },
}
