-- Generated by snipgen 1 from CJK.cwl; do not edit, regenerate.
-- source: TeXstudio completion/CJK.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b94cc0f9649e0c7c23f24b61b2b1aee264f2b859d9d27c53f4b25abea4498ae1
-- cwl-header:
--   # CJK package
--   # Matthew Bertucci 2022/05/09 for v4.8.5
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "CJK",
  includes = { "MULEenc" },
  lists = {},
  snippets = {
    S({ trig = "\\CJKbold", dscr = "" }, { t("\\CJKbold") }),
    S({ trig = "\\CJKnormal", dscr = "" }, { t("\\CJKnormal") }),
    S({ trig = "\\CJKboldshift", dscr = "∗", priority = 900 }, { t("\\CJKboldshift") }, "*"),
    S({ trig = "\\CJKsymbol", dscr = "{n}" }, { t("\\CJKsymbol{"), i(1, "n"), t("}") }),
    S({ trig = "\\CJKpunctsymbol", dscr = "{n} ∗", priority = 900 }, { t("\\CJKpunctsymbol{"), i(1, "n"), t("}") }, "*"),
    S({ trig = "\\CJKsymbols", dscr = "{codepoint1}{codepoint2} ∗", priority = 900 }, { t("\\CJKsymbols{"), i(1, "codepoint1"), t("}{"), i(2, "codepoint2"), t("}") }, "*"),
    S({ trig = "\\CJKchar", dscr = "{byte1}{byte2}" }, { t("\\CJKchar{"), i(1, "byte1"), t("}{"), i(2, "byte2"), t("}") }),
    S({ trig = "\\CJKchar", dscr = "[UTF8]{byte1}{byte2}" }, { t("\\CJKchar["), i(1, "UTF8"), t("]{"), i(2, "byte1"), t("}{"), i(3, "byte2"), t("}") }),
    S({ trig = "\\Unicode", dscr = "{byte1}{byte2}" }, { t("\\Unicode{"), i(1, "byte1"), t("}{"), i(2, "byte2"), t("}") }),
    S({ trig = "\\CJKCJKchar", dscr = "" }, { t("\\CJKCJKchar") }),
    S({ trig = "\\CJKhangulchar", dscr = "" }, { t("\\CJKhangulchar") }),
    S({ trig = "\\CJKlatinchar", dscr = "" }, { t("\\CJKlatinchar") }),
    S({ trig = "\\CJKhwkatakana", dscr = "" }, { t("\\CJKhwkatakana") }),
    S({ trig = "\\CJKnohwkatakana", dscr = "" }, { t("\\CJKnohwkatakana") }),
    S({ trig = "\\CJKenc", dscr = "{encoding}" }, { t("\\CJKenc{"), i(1, "encoding"), t("}") }),
    S({ trig = "\\CJKfontenc", dscr = "{encoding}{font encoding}" }, { t("\\CJKfontenc{"), i(1, "encoding"), t("}{"), i(2, "font encoding"), t("}") }),
    S({ trig = "\\CJKfamily", dscr = "{family}" }, { t("\\CJKfamily{"), i(1, "family"), t("}") }),
    S({ trig = "\\CJKencfamily", dscr = "{encoding}{family}" }, { t("\\CJKencfamily{"), i(1, "encoding"), t("}{"), i(2, "family"), t("}") }),
    S({ trig = "\\CJKencfamily", dscr = "[font encoding]{encoding}{family}" }, { t("\\CJKencfamily["), i(1, "font encoding"), t("]{"), i(2, "encoding"), t("}{"), i(3, "family"), t("}") }),
    S({ trig = "\\CJKshape", dscr = "{family} ∗", priority = 900 }, { t("\\CJKshape{"), i(1, "family"), t("}") }, "*"),
    S({ trig = "\\CJKencshape", dscr = "{encoding}{family} ∗", priority = 900 }, { t("\\CJKencshape{"), i(1, "encoding"), t("}{"), i(2, "family"), t("}") }, "*"),
    S({ trig = "\\CJKencshape", dscr = "[font encoding]{encoding}{family} ∗", priority = 900 }, { t("\\CJKencshape["), i(1, "font encoding"), t("]{"), i(2, "encoding"), t("}{"), i(3, "family"), t("}") }, "*"),
    S({ trig = "\\CJKaddEncHook", dscr = "{encoding}{code} ∗", priority = 900 }, { t("\\CJKaddEncHook{"), i(1, "encoding"), t("}{"), i(2, "code"), t("}") }, "*"),
    S({ trig = "\\CJKhanja", dscr = "" }, { t("\\CJKhanja") }),
    S({ trig = "\\CJKhangul", dscr = "" }, { t("\\CJKhangul") }),
    S({ trig = "\\CJKkern", dscr = "" }, { t("\\CJKkern") }),
    S({ trig = "\\CJKglue", dscr = "" }, { t("\\CJKglue") }),
    S({ trig = "\\CJKtolerance", dscr = "∗", priority = 900 }, { t("\\CJKtolerance") }, "*"),
    S({ trig = "\\nbs", dscr = "" }, { t("\\nbs") }),
    S({ trig = "\\CJKtilde", dscr = "" }, { t("\\CJKtilde") }),
    S({ trig = "\\standardtilde", dscr = "" }, { t("\\standardtilde") }),
    S({ trig = "\\CJKspace", dscr = "" }, { t("\\CJKspace") }),
    S({ trig = "\\CJKnospace", dscr = "" }, { t("\\CJKnospace") }),
    S({ trig = "\\CJKindent", dscr = "∗", priority = 900 }, { t("\\CJKindent") }, "*"),
    S({ trig = "\\CJK", dscr = "\\begin{CJK}{encoding}{family}" }, { t("\\begin{CJK}{"), i(1, "encoding"), t("}{"), i(2, "family"), t({ "}", "\t" }), i(3), t({ "", "\\end{CJK}" }) }),
    S({ trig = "\\CJK", dscr = "\\begin{CJK}[font encoding]{encoding}{family}" }, { t("\\begin{CJK}["), i(1, "font encoding"), t("]{"), i(2, "encoding"), t("}{"), i(3, "family"), t({ "}", "\t" }), i(4), t({ "", "\\end{CJK}" }) }),
    S({ trig = "\\CJK*", dscr = "\\begin{CJK*}{encoding}{family}" }, { t("\\begin{CJK*}{"), i(1, "encoding"), t("}{"), i(2, "family"), t({ "}", "\t" }), i(3), t({ "", "\\end{CJK*}" }) }),
    S({ trig = "\\CJK*", dscr = "\\begin{CJK*}[font encoding]{encoding}{family}" }, { t("\\begin{CJK*}["), i(1, "font encoding"), t("]{"), i(2, "encoding"), t("}{"), i(3, "family"), t({ "}", "\t" }), i(4), t({ "", "\\end{CJK*}" }) }),
    S({ trig = "\\CJKcaption", dscr = "{caption}" }, { t("\\CJKcaption{"), i(1, "caption"), t("}") }),
    S({ trig = "\\CJKhdef", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\CJKhdef{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\CJKhlet", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\CJKhlet{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\CJKvdef", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\CJKvdef{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\CJKvlet", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\CJKvlet{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/CJK#c",
      lines = {
        "lowercase",
        "global",
        "local",
        "active",
        "encapsulated",
      },
    },
  },
}
