-- Generated by snipgen 1 from CJKfntef.cwl; do not edit, regenerate.
-- source: TeXstudio completion/CJKfntef.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 00dc03cd47044ce09a0e4a9ce00aac11f5d5f4a8872f351ef9eec1756b41ce9f
-- cwl-header:
--   # CJKfntef package
--   # Matthew Bertucci 2022/07/21 for v4.8.5
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "CJKfntef",
  includes = { "CJK", "CJKulem" },
  lists = {},
  snippets = {
    S({ trig = "\\CJKunderdot", dscr = "{contents}" }, { t("\\CJKunderdot{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKunderline", dscr = "{contents}" }, { t("\\CJKunderline{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKunderline*", dscr = "{contents}" }, { t("\\CJKunderline*{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKunderdblline", dscr = "{contents}" }, { t("\\CJKunderdblline{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKunderdblline*", dscr = "{contents}" }, { t("\\CJKunderdblline*{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKunderwave", dscr = "{contents}" }, { t("\\CJKunderwave{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKunderwave*", dscr = "{contents}" }, { t("\\CJKunderwave*{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKsout", dscr = "{contents}" }, { t("\\CJKsout{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKsout*", dscr = "{contents}" }, { t("\\CJKsout*{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKxout", dscr = "{contents}" }, { t("\\CJKxout{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKxout*", dscr = "{contents}" }, { t("\\CJKxout*{"), i(1, "contents"), t("}") }),
    S({ trig = "\\varCJKunderline", dscr = "{contents}" }, { t("\\varCJKunderline{"), i(1, "contents"), t("}") }),
    S({ trig = "\\CJKunderanyline", dscr = "{depth}{underline code}{contents}" }, { t("\\CJKunderanyline{"), i(1, "depth"), t("}{"), i(2, "underline code"), t("}{"), i(3, "contents"), t("}") }),
    S({ trig = "\\CJKunderanysymbol", dscr = "{depth}{under-symbol code}{contents}" }, { t("\\CJKunderanysymbol{"), i(1, "depth"), t("}{"), i(2, "under-symbol code"), t("}{"), i(3, "contents"), t("}") }),
    S({ trig = "\\CJKfilltwosides", dscr = "\\begin{CJKfilltwosides}{width}" }, { t("\\begin{CJKfilltwosides}{"), i(1, "width"), t({ "}", "\t" }), i(2), t({ "", "\\end{CJKfilltwosides}" }) }),
    S({ trig = "\\CJKsoutcolor", dscr = "∗", priority = 900 }, { t("\\CJKsoutcolor") }, "*"),
    S({ trig = "\\CJKsoutheight", dscr = "∗", priority = 900 }, { t("\\CJKsoutheight") }, "*"),
    S({ trig = "\\CJKulineleftskip", dscr = "∗", priority = 900 }, { t("\\CJKulineleftskip") }, "*"),
    S({ trig = "\\CJKulinerightskip", dscr = "∗", priority = 900 }, { t("\\CJKulinerightskip") }, "*"),
    S({ trig = "\\CJKunderdbllinebasesep", dscr = "∗", priority = 900 }, { t("\\CJKunderdbllinebasesep") }, "*"),
    S({ trig = "\\CJKunderdbllinecolor", dscr = "∗", priority = 900 }, { t("\\CJKunderdbllinecolor") }, "*"),
    S({ trig = "\\CJKunderdbllinesep", dscr = "∗", priority = 900 }, { t("\\CJKunderdbllinesep") }, "*"),
    S({ trig = "\\CJKunderdotbasesep", dscr = "∗", priority = 900 }, { t("\\CJKunderdotbasesep") }, "*"),
    S({ trig = "\\CJKunderdotcolor", dscr = "∗", priority = 900 }, { t("\\CJKunderdotcolor") }, "*"),
    S({ trig = "\\CJKunderdotsep", dscr = "∗", priority = 900 }, { t("\\CJKunderdotsep") }, "*"),
    S({ trig = "\\CJKunderlinebasesep", dscr = "∗", priority = 900 }, { t("\\CJKunderlinebasesep") }, "*"),
    S({ trig = "\\CJKunderlinecolor", dscr = "∗", priority = 900 }, { t("\\CJKunderlinecolor") }, "*"),
    S({ trig = "\\CJKunderlinesep", dscr = "∗", priority = 900 }, { t("\\CJKunderlinesep") }, "*"),
    S({ trig = "\\CJKunderwavebasesep", dscr = "∗", priority = 900 }, { t("\\CJKunderwavebasesep") }, "*"),
    S({ trig = "\\CJKunderwavecolor", dscr = "∗", priority = 900 }, { t("\\CJKunderwavecolor") }, "*"),
    S({ trig = "\\CJKunderwavesep", dscr = "∗", priority = 900 }, { t("\\CJKunderwavesep") }, "*"),
    S({ trig = "\\CJKxoutcolor", dscr = "∗", priority = 900 }, { t("\\CJKxoutcolor") }, "*"),
  },
  keyvals = {},
}
