-- Generated by snipgen 1 from class-tikz-kalender.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-tikz-kalender.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 5916203c83dc7c70e63913b72dd11a74483bf2dc3568297c5fa9a98b059796d9
-- cwl-header:
--   # tikz-kalender class
--   # Matthew Bertucci 2026/07/24 for v0.7a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-tikz-kalender",
  includes = { "ifluatex", "ifxetex", "pgfkeys", "etoolbox", "ragged2e", "easter", "fontenc", "lmodern", "tgheros", "geometry", "inputenc", "babel", "translator", "tikz", "tikzlibrarycalendar" },
  lists = {},
  snippets = {
    S({ trig = "\\setup", dscr = "{options}" }, { t("\\setup{"), i(1, "options"), t("}") }),
    S({ trig = "\\makeKalender", dscr = "" }, { t("\\makeKalender") }),
    S({ trig = "\\period", dscr = "{date1}{date2} ∗", priority = 900 }, { t("\\period{"), i(1, "date1"), t("}{"), i(2, "date2"), t("}") }, "*"),
    S({ trig = "\\period", dscr = "{date1}{date2}[options] ∗", priority = 900 }, { t("\\period{"), i(1, "date1"), t("}{"), i(2, "date2"), t("}["), i(3, "options"), t("]") }, "*"),
    S({ trig = "\\event", dscr = "{date}{text} ∗", priority = 900 }, { t("\\event{"), i(1, "date"), t("}{"), i(2, "text"), t("}") }, "*"),
    S({ trig = "\\event", dscr = "{date}{text}[options] ∗", priority = 900 }, { t("\\event{"), i(1, "date"), t("}{"), i(2, "text"), t("}["), i(3, "options"), t("]") }, "*"),
    S({ trig = "\\theweeknumber", dscr = "∗", priority = 900 }, { t("\\theweeknumber") }, "*"),
    S({ trig = "\\calYearFont", dscr = "∗", priority = 900 }, { t("\\calYearFont") }, "*"),
    S({ trig = "\\calYear", dscr = "∗", priority = 900 }, { t("\\calYear") }, "*"),
    S({ trig = "\\calYearText", dscr = "∗", priority = 900 }, { t("\\calYearText") }, "*"),
    S({ trig = "\\DH", dscr = "" }, { t("\\DH") }, "n"),
    S({ trig = "\\dh", dscr = "" }, { t("\\dh") }, "n"),
    S({ trig = "\\dj", dscr = "" }, { t("\\dj") }, "n"),
    S({ trig = "\\DJ", dscr = "" }, { t("\\DJ") }, "n"),
    S({ trig = "\\guillemetleft", dscr = "" }, { t("\\guillemetleft") }, "n"),
    S({ trig = "\\guillemetright", dscr = "" }, { t("\\guillemetright") }, "n"),
    S({ trig = "\\guillemotleft", dscr = "∗", priority = 900 }, { t("\\guillemotleft") }, "*n"),
    S({ trig = "\\guillemotright", dscr = "∗", priority = 900 }, { t("\\guillemotright") }, "*n"),
    S({ trig = "\\guilsinglleft", dscr = "" }, { t("\\guilsinglleft") }, "n"),
    S({ trig = "\\guilsinglright", dscr = "" }, { t("\\guilsinglright") }, "n"),
    S({ trig = "\\Hwithstroke", dscr = "" }, { t("\\Hwithstroke") }, "n"),
    S({ trig = "\\hwithstroke", dscr = "" }, { t("\\hwithstroke") }, "n"),
    S({ trig = "\\k", dscr = "{arg}" }, { t("\\k{"), i(1, "arg"), t("}") }, "n"),
    S({ trig = "\\NG", dscr = "" }, { t("\\NG") }, "n"),
    S({ trig = "\\ng", dscr = "" }, { t("\\ng") }, "n"),
    S({ trig = "\\quotedblbase", dscr = "" }, { t("\\quotedblbase") }, "n"),
    S({ trig = "\\quotesinglbase", dscr = "" }, { t("\\quotesinglbase") }, "n"),
    S({ trig = "\\textogonekcentered", dscr = "{arg}" }, { t("\\textogonekcentered{"), i(1, "arg"), t("}") }, "n"),
    S({ trig = "\\textquotedbl", dscr = "" }, { t("\\textquotedbl") }, "n"),
    S({ trig = "\\th", dscr = "" }, { t("\\th") }, "n"),
    S({ trig = "\\TH", dscr = "" }, { t("\\TH") }, "n"),
  },
  keyvals = {
    {
      targets = "\\setup#c",
      lines = {
        "lang={%<babel options%>}",
        "paper=#a0,a1,a2,a3,a4,a5,a6,b0,b1,b2,b3,b4,b5,b6,c0,c1,c2,c3,c4,c5,c6,b0j,b1j,b2j,b3j,b4j,b5j,b6j,ansia,ansib,ansic,ansid,ansie,letter,executive,legal",
        "showweeknumbers#true,false",
        "print#true,false",
        "events={%<.events files%>}",
        "titleFont=%<font commands%>",
        "yearFont=%<font commands%>",
        "monthFont=%<font commands%>",
        "dayFont=%<font commands%>",
        "dayNbFont=%<font commands%>",
        "weekNbFont=%<font commands%>",
        "eventFont=%<font commands%>",
        "title=%<text%>",
        "year=%<year%>",
        "yearText=%<text%>",
        "titleColor=#%color",
        "eventColor=#%color",
        "periodColor=#%color",
        "monthBGcolor=#%color",
        "monthColor=#%color",
        "workdayColor=#%color",
        "saturdayColor=#%color",
        "sundayColor=#%color",
        "xcoloroptions={%<xcolor options%>}",
        "onePageOnly#true,false",
      },
    },
  },
}
