-- Generated by snipgen 1 from class-BHCexam.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-BHCexam.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: bfa6c8f28357cd6e778e7362a4324edf91e5567e5f477b790e7271117591e0bb
-- cwl-header:
--   # BHCexam class
--   # Matthew Bertucci 2022/08/10 for v1.7
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-BHCexam",
  includes = { "ctex", "tabularx", "ifthen", "xcolor", "graphicx", "caption", "geometry", "fancyhdr", "etoolbox", "amsmath", "amssymb", "unicode-math", "pifont", "bbding", "romannum", "enumitem" },
  lists = {},
  snippets = {
    S({ trig = "\\groups", dscr = "\\begin{groups}" }, { t({ "\\begin{groups}", "\t" }), i(1), t({ "", "\\end{groups}" }) }),
    S({ trig = "\\questions", dscr = "\\begin{questions}" }, { t({ "\\begin{questions}", "\t" }), i(1), t({ "", "\\end{questions}" }) }),
    S({ trig = "\\questions", dscr = "\\begin{questions}[可选参数]" }, { t("\\begin{questions}["), i(1, "可选参数"), t({ "]", "\t" }), i(2), t({ "", "\\end{questions}" }) }),
    S({ trig = "\\solution", dscr = "\\begin{solution}{vspace}" }, { t("\\begin{solution}{"), i(1, "vspace"), t({ "}", "\t" }), i(2), t({ "", "\\end{solution}" }) }),
    S({ trig = "\\subquestions", dscr = "\\begin{subquestions}" }, { t({ "\\begin{subquestions}", "\t" }), i(1), t({ "", "\\end{subquestions}" }) }),
    S({ trig = "\\abs", dscr = "{arg}" }, h.mathwrap({ t("\\abs{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\build", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\build{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\choicelengtha", dscr = "∗", priority = 900 }, { t("\\choicelengtha") }, "*"),
    S({ trig = "\\choicelengthb", dscr = "∗", priority = 900 }, { t("\\choicelengthb") }, "*"),
    S({ trig = "\\choicelengthc", dscr = "∗", priority = 900 }, { t("\\choicelengthc") }, "*"),
    S({ trig = "\\choicelengthd", dscr = "∗", priority = 900 }, { t("\\choicelengthd") }, "*"),
    S({ trig = "\\choicelengthe", dscr = "∗", priority = 900 }, { t("\\choicelengthe") }, "*"),
    S({ trig = "\\example", dscr = "" }, { t("\\example") }),
    S({ trig = "\\example", dscr = "[score]" }, { t("\\example["), i(1, "score"), t("]") }),
    S({ trig = "\\exercise", dscr = "" }, { t("\\exercise") }),
    S({ trig = "\\exercise", dscr = "[score]" }, { t("\\exercise["), i(1, "score"), t("]") }),
    S({ trig = "\\fivechoices", dscr = "{opt1}{opt2}{opt3}{opt4}{opt5}" }, { t("\\fivechoices{"), i(1, "opt1"), t("}{"), i(2, "opt2"), t("}{"), i(3, "opt3"), t("}{"), i(4, "opt4"), t("}{"), i(5, "opt5"), t("}") }),
    S({ trig = "\\fourchoices", dscr = "{opt1}{opt2}{opt3}{opt4}" }, { t("\\fourchoices{"), i(1, "opt1"), t("}{"), i(2, "opt2"), t("}{"), i(3, "opt3"), t("}{"), i(4, "opt4"), t("}") }),
    S({ trig = "\\group", dscr = "{题组}{题组的描述}" }, { t("\\group{"), i(1, "题组"), t("}{"), i(2, "题组的描述"), t("}") }),
    S({ trig = "\\gt", dscr = "" }, { t("\\gt") }),
    S({ trig = "\\hint", dscr = "" }, { t("\\hint") }),
    S({ trig = "\\key", dscr = "{key}" }, { t("\\key{"), i(1, "key"), t("}") }),
    S({ trig = "\\keylength", dscr = "∗", priority = 900 }, { t("\\keylength") }, "*"),
    S({ trig = "\\lt", dscr = "" }, { t("\\lt") }),
    S({ trig = "\\maxlength", dscr = "∗", priority = 900 }, { t("\\maxlength") }, "*"),
    S({ trig = "\\method", dscr = "" }, { t("\\method") }),
    S({ trig = "\\methodonly", dscr = "" }, { t("\\methodonly") }),
    S({ trig = "\\myvertspace", dscr = "∗", priority = 900 }, { t("\\myvertspace") }, "*"),
    S({ trig = "\\notice", dscr = "{text}" }, { t("\\notice{"), i(1, "text"), t("}") }),
    S({ trig = "\\question", dscr = "" }, { t("\\question") }),
    S({ trig = "\\question", dscr = "[score]" }, { t("\\question["), i(1, "score"), t("]") }),
    S({ trig = "\\score", dscr = "{step}{total}" }, { t("\\score{"), i(1, "step"), t("}{"), i(2, "total"), t("}") }),
    S({ trig = "\\sixchoices", dscr = "{opt1}{opt2}{opt3}{opt4}{opt5}{opt6}" }, { t("\\sixchoices{"), i(1, "opt1"), t("}{"), i(2, "opt2"), t("}{"), i(3, "opt3"), t("}{"), i(4, "opt4"), t("}{"), i(5, "opt5"), t("}{"), i(6, "opt6"), t("}") }),
    S({ trig = "\\subquestion", dscr = "" }, { t("\\subquestion") }),
    S({ trig = "\\subtitle", dscr = "{text}" }, { t("\\subtitle{"), i(1, "text"), t("}") }),
    S({ trig = "\\theExample", dscr = "∗", priority = 900 }, { t("\\theExample") }, "*"),
    S({ trig = "\\theExercise", dscr = "∗", priority = 900 }, { t("\\theExercise") }, "*"),
    S({ trig = "\\theGroup", dscr = "∗", priority = 900 }, { t("\\theGroup") }, "*"),
    S({ trig = "\\theMethod", dscr = "∗", priority = 900 }, { t("\\theMethod") }, "*"),
    S({ trig = "\\theQuestion", dscr = "∗", priority = 900 }, { t("\\theQuestion") }, "*"),
    S({ trig = "\\threechoices", dscr = "{opt1}{opt2}{opt3}" }, { t("\\threechoices{"), i(1, "opt1"), t("}{"), i(2, "opt2"), t("}{"), i(3, "opt3"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\documentclass/BHCexam#c",
      lines = {
        "answers",
        "adobe",
        "ubuntu",
        "mac",
        "windows",
        "fandol",
        "twocolumn",
        "list",
      },
    },
  },
}
