-- Generated by snipgen 1 from class-tudasciposter.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-tudasciposter.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f778167d170a575362d5785ad55754d9ed4dc3fd1420fd991ced4095f2635b51
-- cwl-header:
--   # tudasciposter class
--   # Matthew Bertucci 2022/08/17 for v3.27
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-tudasciposter",
  includes = { "l3keys2e", "class-scrartcl", "tudafonts", "tikz", "tikzlibrarycalc", "tcolorbox", "tcolorboxlibraryposter", "pdfcol", "geometry", "tudarules", "tudacolors", "qrcode", "hyperref" },
  lists = {},
  snippets = {
    S({ trig = "\\footergraphics", dscr = "{graphics code}" }, { t("\\footergraphics{"), i(1, "graphics code"), t("}") }),
    S({ trig = "\\footer", dscr = "{text}" }, { t("\\footer{"), i(1, "text"), t("}") }),
    S({ trig = "\\footerqrcode", dscr = "{URL}" }, { t("\\footerqrcode{"), i(1, "URL"), t("}") }, "U"),
    S({ trig = "\\footerqrcode*", dscr = "{URL}" }, { t("\\footerqrcode*{"), i(1, "URL"), t("}") }, "U"),
    S({ trig = "\\Metadata", dscr = "{keyvals}" }, { t("\\Metadata{"), i(1, "keyvals"), t("}") }),
    S({ trig = "\\authorandname", dscr = "∗", priority = 900 }, { t("\\authorandname") }, "*"),
    S({ trig = "\\titlegraphic", dscr = "{graphics code}" }, { t("\\titlegraphic{"), i(1, "graphics code"), t("}") }),
    S({ trig = "\\institute", dscr = "{Einrichtung}" }, { t("\\institute{"), i(1, "Einrichtung"), t("}") }),
    S({ trig = "\\inst", dscr = "{arg}" }, { t("\\inst{"), i(1, "arg"), t("}") }),
    S({ trig = "\\contentwidth", dscr = "" }, { t("\\contentwidth") }, "L"),
    S({ trig = "\\contentheight", dscr = "" }, { t("\\contentheight") }, "L"),
  },
  keyvals = {
    {
      targets = "\\documentclass/tudasciposter#c",
      lines = {
        "color=#%color",
        "accentcolor=#%color",
        "textaccentcolor=#%color",
        "identbarcolor=#%color",
        "footer#true,false",
        "pdfa#true,false",
        "boxstyle=#official,colored,boxed,default",
        "paper=#a0,a1,a2,a3",
        "fontsize=##L",
        "logofile=%<Dateipfad%>",
        "title=#default,large,small",
        "colorback#true,false",
      },
    },
    {
      targets = "\\posterbox,\\begin{posterboxenv}",
      lines = {
        "TUDa",
        "TUDa-inner",
        "TUDa-colored",
        "TUDa-colored-inner",
        "TUDa-boxed",
        "TUDa-boxed-inner",
      },
    },
  },
}
