-- Generated by snipgen 1 from class-cours.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-cours.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 30a0f53e3823764c6c40b4ecf90f233bbe37a5445596e9ff995f38a6d433c4ed
-- cwl-header:
--   # cours class
--   # Matthew Bertucci 4/18/2022 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-cours",
  includes = { "mafr" },
  lists = {},
  snippets = {
    S({ trig = "\\chapitre", dscr = "{number}{title}" }, { t("\\chapitre{"), i(1, "number"), t("}{"), i(2, "title"), t("}") }, "L1"),
  },
  keyvals = {},
}
