-- Generated by snipgen 1 from class-hgbthesis.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-hgbthesis.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 3e17f81c4a4b3c881e59daeb01b2bc2ceb57d2c51a30771e01fc5450ee99edf4
-- cwl-header:
--   # hgbthesis class
--   # Matthew Bertucci 2023/02/13
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-hgbthesis",
  includes = { "xifthen", "ifpdf", "class-book", "geometry", "hgb", "hgbmath", "hgbalgo", "hgbheadings", "hgbabbrev", "hgblistings", "hgbbib" },
  lists = {},
  snippets = {
    S({ trig = "\\advisor", dscr = "{name}" }, { t("\\advisor{"), i(1, "name"), t("}") }),
    S({ trig = "\\cclicense", dscr = "" }, { t("\\cclicense") }),
    S({ trig = "\\companyName", dscr = "{name}" }, { t("\\companyName{"), i(1, "name"), t("}") }),
    S({ trig = "\\companyUrl", dscr = "{URL}" }, { t("\\companyUrl{"), i(1, "URL"), t("}") }, "U"),
    S({ trig = "\\dateofsubmission", dscr = "{YYYY}{MM}{DD}" }, { t("\\dateofsubmission{"), i(1, "YYYY"), t("}{"), i(2, "MM"), t("}{"), i(3, "DD"), t("}") }),
    S({ trig = "\\leadingzero", dscr = "{count} ∗", priority = 900 }, { t("\\leadingzero{"), i(1, "count"), t("}") }, "*"),
    S({ trig = "\\license", dscr = "{text}" }, { t("\\license{"), i(1, "text"), t("}") }),
    S({ trig = "\\logofile", dscr = "{imagefile}" }, { t("\\logofile{"), i(1, "imagefile"), t("}") }, "g"),
    S({ trig = "\\makelogo", dscr = "∗", priority = 900 }, { t("\\makelogo") }, "*"),
    S({ trig = "\\placeofstudy", dscr = "{place}" }, { t("\\placeofstudy{"), i(1, "place"), t("}") }),
    S({ trig = "\\programname", dscr = "{name}" }, { t("\\programname{"), i(1, "name"), t("}") }),
    S({ trig = "\\programtype", dscr = "{type}" }, { t("\\programtype{"), i(1, "type"), t("}") }),
    S({ trig = "\\strictlicense", dscr = "" }, { t("\\strictlicense") }),
  },
  keyvals = {
    {
      targets = "\\documentclass/hgbthesis#c",
      lines = {
        "bachelor",
        "master",
        "diploma",
        "internship",
        "apa",
        "proposal",
        "english",
        "german",
        "smartquotes",
        "noUpdateCheck",
      },
    },
  },
}
