-- Generated by snipgen 1 from class-guitbeamer.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-guitbeamer.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: dce60ec0d860c61c92b90119a7438102d696adc139109e4dce36137074743296
-- cwl-header:
--   # guitbeamer class
--   # Matthew Bertucci 2022/06/03 for v0.4.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-guitbeamer",
  includes = { "xcolor", "class-beamer", "graphicx", "guit" },
  lists = {},
  snippets = {
    S({ trig = "\\aalert", dscr = "{highlighted text}" }, { t("\\aalert{"), i(1, "highlighted text"), t("}") }),
    S({ trig = "\\aalert", dscr = "<overlay specification>{highlighted text}" }, { t("\\aalert<"), i(1, "overlay specification"), t(">{"), i(2, "highlighted text"), t("}") }),
    S({ trig = "\\bs", dscr = "∗", priority = 900 }, { t("\\bs") }, "*"),
    S({ trig = "\\lb", dscr = "∗", priority = 900 }, { t("\\lb") }, "*"),
    S({ trig = "\\rb", dscr = "∗", priority = 900 }, { t("\\rb") }, "*"),
    S({ trig = "\\ls", dscr = "∗", priority = 900 }, { t("\\ls") }, "*"),
    S({ trig = "\\rs", dscr = "∗", priority = 900 }, { t("\\rs") }, "*"),
    S({ trig = "\\Lsty", dscr = "{package}" }, { t("\\Lsty{"), i(1, "package"), t("}") }),
    S({ trig = "\\Lsty", dscr = "<overlay specification>{package}" }, { t("\\Lsty<"), i(1, "overlay specification"), t(">{"), i(2, "package"), t("}") }),
    S({ trig = "\\Lcls", dscr = "{class}" }, { t("\\Lcls{"), i(1, "class"), t("}") }),
    S({ trig = "\\Lcls", dscr = "<overlay specification>{class}" }, { t("\\Lcls<"), i(1, "overlay specification"), t(">{"), i(2, "class"), t("}") }),
    S({ trig = "\\Lopt", dscr = "{option}" }, { t("\\Lopt{"), i(1, "option"), t("}") }),
    S({ trig = "\\Lenv", dscr = "{envname}" }, { t("\\Lenv{"), i(1, "envname"), t("}") }),
    S({ trig = "\\LaTeXcode", dscr = "\\begin{LaTeXcode}" }, { t({ "\\begin{LaTeXcode}", "\t" }), i(1), t({ "", "\\end{LaTeXcode}" }) }),
    S({ trig = "\\LaTeXcode", dscr = "\\begin{LaTeXcode}<overlay specification>" }, { t("\\begin{LaTeXcode}<"), i(1, "overlay specification"), t({ ">", "\t" }), i(2), t({ "", "\\end{LaTeXcode}" }) }),
    S({ trig = "\\LaTeXcode", dscr = "\\begin{LaTeXcode}[title]" }, { t("\\begin{LaTeXcode}["), i(1, "title"), t({ "]", "\t" }), i(2), t({ "", "\\end{LaTeXcode}" }) }),
    S({ trig = "\\LaTeXcode", dscr = "\\begin{LaTeXcode}[title]<overlay specification>" }, { t("\\begin{LaTeXcode}["), i(1, "title"), t("]<"), i(2, "overlay specification"), t({ ">", "\t" }), i(3), t({ "", "\\end{LaTeXcode}" }) }),
    S({ trig = "\\n", dscr = "", show_condition = h.in_env({ "LaTeXcode" }) }, { t("\\n") }, "/LaTeXcode"),
    S({ trig = "\\nn", dscr = "", show_condition = h.in_env({ "LaTeXcode" }) }, { t("\\nn") }, "/LaTeXcode"),
    S({ trig = "\\LaTeXoutput", dscr = "\\begin{LaTeXoutput}" }, { t({ "\\begin{LaTeXoutput}", "\t" }), i(1), t({ "", "\\end{LaTeXoutput}" }) }),
    S({ trig = "\\LaTeXoutput", dscr = "\\begin{LaTeXoutput}<overlay specification>" }, { t("\\begin{LaTeXoutput}<"), i(1, "overlay specification"), t({ ">", "\t" }), i(2), t({ "", "\\end{LaTeXoutput}" }) }),
    S({ trig = "\\LaTeXoutput", dscr = "\\begin{LaTeXoutput}[title]" }, { t("\\begin{LaTeXoutput}["), i(1, "title"), t({ "]", "\t" }), i(2), t({ "", "\\end{LaTeXoutput}" }) }),
    S({ trig = "\\LaTeXoutput", dscr = "\\begin{LaTeXoutput}[title]<overlay specification>" }, { t("\\begin{LaTeXoutput}["), i(1, "title"), t("]<"), i(2, "overlay specification"), t({ ">", "\t" }), i(3), t({ "", "\\end{LaTeXoutput}" }) }),
    S({ trig = "\\fakeind", dscr = "", show_condition = h.in_env({ "LaTeXoutput" }) }, { t("\\fakeind") }, "/LaTeXoutput"),
    S({ trig = "\\LCmd", dscr = "{csname}" }, { t("\\LCmd{"), i(1, "csname"), t("}") }),
    S({ trig = "\\LCmd", dscr = "[prefix char]{csname}" }, { t("\\LCmd["), i(1, "prefix char"), t("]{"), i(2, "csname"), t("}") }),
    S({ trig = "\\LCmdArg", dscr = "{csname}{arg}" }, { t("\\LCmdArg{"), i(1, "csname"), t("}{"), i(2, "arg"), t("}") }),
    S({ trig = "\\tbs", dscr = "∗", priority = 900 }, { t("\\tbs") }, "*"),
    S({ trig = "\\tlb", dscr = "∗", priority = 900 }, { t("\\tlb") }, "*"),
    S({ trig = "\\trb", dscr = "∗", priority = 900 }, { t("\\trb") }, "*"),
    S({ trig = "\\tls", dscr = "∗", priority = 900 }, { t("\\tls") }, "*"),
    S({ trig = "\\trs", dscr = "∗", priority = 900 }, { t("\\trs") }, "*"),
    S({ trig = "\\ncGuIT", dscr = "" }, { t("\\ncGuIT") }),
  },
  keyvals = {
    {
      targets = "\\documentclass/guitbeamer#c",
      lines = {
        "usepdftitle#true,false",
        "envcountsect",
        "notheorems",
        "noamsthm",
        "compress",
        "t",
        "c",
        "leqno",
        "fleqn",
        "handout",
        "trans",
        "pdftex",
        "nativepdf",
        "pdfmark",
        "dvips",
        "dviwindo",
        "dvipsone",
        "vtex",
        "ps2pdf",
        "ignorenonframetext",
        "noamssymb",
        "bigger",
        "smaller",
        "8pt",
        "9pt",
        "10pt",
        "11pt",
        "12pt",
        "14pt",
        "17pt",
        "20pt",
        "draft",
        "CJK",
        "cjk",
        "onlytextwidth",
        "pgf={%<pgf options%>}",
        "hyperref={%<hyperref options%>}",
        "color={%<color options%>}",
        "xcolor={%<xcolor options%>}",
        "ucs",
        "utf8x",
        "utf8",
        "aspectratio=#2013,1610,169,149,141,54,43,32,%<xxxx%>",
      },
    },
  },
}
