-- Generated by snipgen 1 from class-aalok.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-aalok.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 211408b037d1c3d73276ed90f638810568462c5a6d347c5d3836cdd4041fa038
-- cwl-header:
--   # aalok class
--   # Matthew Bertucci 2022/07/29 for v0.6
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-aalok",
  includes = { "class-memoir", "expex", "xcolor", "marathi", "microtype", "fontawesome5", "diagbox", "fancyhdr", "float", "paracol", "tcolorbox", "tcolorboxlibrarymost", "tikz", "graphicx", "mdframed", "etoolbox", "hyperref", "biblatex", "tocloft", "minitoc" },
  lists = {},
  snippets = {
    S({ trig = "\\प", dscr = "ुष्प{पुष्पक्रमांक}" }, { t("\\पुष्प{"), i(1, "पुष्पक्रमांक"), t("}") }),
    S({ trig = "\\आ", dscr = "कडीपुष्प{पुष्पक्रमांक आकडी}" }, { t("\\आकडीपुष्प{"), i(1, "पुष्पक्रमांक आकडी"), t("}") }),
    S({ trig = "\\त", dscr = "िथी{प्रकाशनाची तिथी}" }, { t("\\तिथी{"), i(1, "प्रकाशनाची तिथी"), t("}") }),
    S({ trig = "\\आ", dscr = "वृत्ती{आवृत्तिक्रमांक अक्षरांत}" }, { t("\\आवृत्ती{"), i(1, "आवृत्तिक्रमांक अक्षरांत"), t("}") }),
    S({ trig = "\\प", dscr = "्रकाशनवर्ष{प्रकाशनवर्ष}" }, { t("\\प्रकाशनवर्ष{"), i(1, "प्रकाशनवर्ष"), t("}") }),
    S({ trig = "\\ज", dscr = "यंती{कितवी जयंती}" }, { t("\\जयंती{"), i(1, "कितवी जयंती"), t("}") }),
    S({ trig = "\\द", dscr = "िनांक{प्रकाशनाचा दिनांक}" }, { t("\\दिनांक{"), i(1, "प्रकाशनाचा दिनांक"), t("}") }),
    S({ trig = "\\आ", dscr = "कडीदिनांक{प्रकाशनाचा दिनांक (आकडी)}" }, { t("\\आकडीदिनांक{प्रकाशनाचा दिनांक ("), i(1, "आकडी"), t(")}") }),
    S({ trig = "\\ल", dscr = "ेख{लेखाचे शीर्षक}" }, { t("\\लेख{"), i(1, "लेखाचे शीर्षक"), t("}") }),
    S({ trig = "\\अ", dscr = "भ्यासक{अभ्यासकाचे नाव}" }, { t("\\अभ्यासक{"), i(1, "अभ्यासकाचे नाव"), t("}") }),
    S({ trig = "\\इ", dscr = "पत्ता{इपत्ता}{दृश्यरूपातील इपत्ता}" }, { t("\\इपत्ता{"), i(1, "इपत्ता"), t("}{"), i(2, "दृश्यरूपातील इपत्ता"), t("}") }, "U"),
    S({ trig = "\\orcid", dscr = "{orcid क्रमांक}" }, { t("\\orcid{"), i(1, "orcid क्रमांक"), t("}") }),
    S({ trig = "\\श", dscr = "ीर्षक" }, { t("\\शीर्षक") }),
    S({ trig = "\\अ", dscr = "नुक्रमणिका" }, { t("\\अनुक्रमणिका") }),
    S({ trig = "\\citetitleyear", dscr = "[postnote]{bibid} ∗", priority = 900 }, { t("\\citetitleyear["), i(1, "postnote"), t("]{"), i(2, "bibid"), t("}") }, "*C"),
    S({ trig = "\\citetitleyear", dscr = "[prenote][postnote]{bibid} ∗", priority = 900 }, { t("\\citetitleyear["), i(1, "prenote"), t("]["), i(2, "postnote"), t("]{"), i(3, "bibid"), t("}") }, "*C"),
    S({ trig = "\\citetitleyear", dscr = "{bibid} ∗", priority = 900 }, { t("\\citetitleyear{"), i(1, "bibid"), t("}") }, "*C"),
    S({ trig = "\\if", dscr = "खासगीवितरण ∗", priority = 900 }, { t("\\ifखासगीवितरण") }, "*"),
    S({ trig = "\\if", dscr = "छापील ∗", priority = 900 }, { t("\\ifछापील") }, "*"),
    S({ trig = "\\if", dscr = "सुटालेख ∗", priority = 900 }, { t("\\ifसुटालेख") }, "*"),
    S({ trig = "\\if", dscr = "स्थान ∗", priority = 900 }, { t("\\ifस्थान") }, "*"),
    S({ trig = "\\orcidlogo", dscr = "∗", priority = 900 }, { t("\\orcidlogo") }, "*"),
    S({ trig = "\\orcidno", dscr = "∗", priority = 900 }, { t("\\orcidno") }, "*"),
    S({ trig = "\\अ", dscr = "क्षरीमूल्यकिती ∗", priority = 900 }, { t("\\अक्षरीमूल्यकिती") }, "*"),
    S({ trig = "\\अ", dscr = "भ्यासकाचाइपत्तादुवा ∗", priority = 900 }, { t("\\अभ्यासकाचाइपत्तादुवा") }, "*"),
    S({ trig = "\\अ", dscr = "भ्यासकाचाइपत्तापाठ्य ∗", priority = 900 }, { t("\\अभ्यासकाचाइपत्तापाठ्य") }, "*"),
    S({ trig = "\\अ", dscr = "भ्यासकाचेनाव ∗", priority = 900 }, { t("\\अभ्यासकाचेनाव") }, "*"),
    S({ trig = "\\आ", dscr = "कडीमूल्यकिती ∗", priority = 900 }, { t("\\आकडीमूल्यकिती") }, "*"),
    S({ trig = "\\क", dscr = "ितवीआवृत्ती ∗", priority = 900 }, { t("\\कितवीआवृत्ती") }, "*"),
    S({ trig = "\\क", dscr = "ितवीजयंती ∗", priority = 900 }, { t("\\कितवीजयंती") }, "*"),
    S({ trig = "\\क", dscr = "ोणतादिनांक ∗", priority = 900 }, { t("\\कोणतादिनांक") }, "*"),
    S({ trig = "\\क", dscr = "ोणतीतिथी ∗", priority = 900 }, { t("\\कोणतीतिथी") }, "*"),
    S({ trig = "\\क", dscr = "ोणतेप्रकाशनवर्ष ∗", priority = 900 }, { t("\\कोणतेप्रकाशनवर्ष") }, "*"),
    S({ trig = "\\ख", dscr = "ासगीवितरणfalse ∗", priority = 900 }, { t("\\खासगीवितरणfalse") }, "*"),
    S({ trig = "\\ख", dscr = "ासगीवितरणtrue ∗", priority = 900 }, { t("\\खासगीवितरणtrue") }, "*"),
    S({ trig = "\\छ", dscr = "ापीलfalse ∗", priority = 900 }, { t("\\छापीलfalse") }, "*"),
    S({ trig = "\\छ", dscr = "ापीलtrue ∗", priority = 900 }, { t("\\छापीलtrue") }, "*"),
    S({ trig = "\\द", dscr = "िनांकआकडी ∗", priority = 900 }, { t("\\दिनांकआकडी") }, "*"),
    S({ trig = "\\प", dscr = "ुष्पसंख्या ∗", priority = 900 }, { t("\\पुष्पसंख्या") }, "*"),
    S({ trig = "\\प", dscr = "ुष्पसंख्याआकडी ∗", priority = 900 }, { t("\\पुष्पसंख्याआकडी") }, "*"),
    S({ trig = "\\प", dscr = "्रीत्यर्थ{arg1} ∗", priority = 900 }, { t("\\प्रीत्यर्थ{"), i(1, "arg1"), t("}") }, "*"),
    S({ trig = "\\म", dscr = "ूल्य{arg1}{arg2} ∗", priority = 900 }, { t("\\मूल्य{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\ल", dscr = "ेखाचेनाव ∗", priority = 900 }, { t("\\लेखाचेनाव") }, "*"),
    S({ trig = "\\ल", dscr = "ेखाचेशीर्षक ∗", priority = 900 }, { t("\\लेखाचेशीर्षक") }, "*"),
    S({ trig = "\\व", dscr = "िद्वान ∗", priority = 900 }, { t("\\विद्वान") }, "*"),
    S({ trig = "\\स", dscr = "ंदर्भसूची ∗", priority = 900 }, { t("\\संदर्भसूची") }, "*"),
    S({ trig = "\\स", dscr = "ुटालेखfalse ∗", priority = 900 }, { t("\\सुटालेखfalse") }, "*"),
    S({ trig = "\\स", dscr = "ुटालेखtrue ∗", priority = 900 }, { t("\\सुटालेखtrue") }, "*"),
    S({ trig = "\\स", dscr = "्थानfalse ∗", priority = 900 }, { t("\\स्थानfalse") }, "*"),
    S({ trig = "\\स", dscr = "्थानtrue ∗", priority = 900 }, { t("\\स्थानtrue") }, "*"),
  },
  keyvals = {
    {
      targets = "\\documentclass/aalok#c",
      lines = {
        "खासगीवितरण",
        "छापील",
        "सुटालेख",
        "रेगे",
        "राजवाडे",
      },
    },
  },
}
