-- Generated by snipgen 1 from class-udiss.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-udiss.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: d6c3043fabf6fcf122a9932f5cf6ba54dd29f4b251c3f34087f080b25aceaad5
-- cwl-header:
--   # udiss class
--   # Matthew Bertucci 2024/10/02 for v0.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-udiss",
  includes = { "class-memoir", "expkv-def", "expkv-opt", "iftex", "babel", "iflang", "unicode-math", "graphicx", "xcolor", "csquotes", "hyperref", "hyperxmp" },
  lists = {},
  snippets = {
    S({ trig = "\\pronouns", dscr = "{pronouns}" }, { t("\\pronouns{"), i(1, "pronouns"), t("}") }),
    S({ trig = "\\subtitle", dscr = "{text}" }, { t("\\subtitle{"), i(1, "text"), t("}") }),
    S({ trig = "\\shorttitle", dscr = "{text}" }, { t("\\shorttitle{"), i(1, "text"), t("}") }),
    S({ trig = "\\stream", dscr = "{stream}" }, { t("\\stream{"), i(1, "stream"), t("}") }),
    S({ trig = "\\discipline", dscr = "{discipline}" }, { t("\\discipline{"), i(1, "discipline"), t("}") }),
    S({ trig = "\\degree", dscr = "{degree}" }, { t("\\degree{"), i(1, "degree"), t("}") }),
    S({ trig = "\\supervisor", dscr = "{supervisor}" }, { t("\\supervisor{"), i(1, "supervisor"), t("}") }),
    S({ trig = "\\university", dscr = "{university}" }, { t("\\university{"), i(1, "university"), t("}") }),
    S({ trig = "\\department", dscr = "{department}" }, { t("\\department{"), i(1, "department"), t("}") }),
    S({ trig = "\\logo", dscr = "{imagefile}" }, { t("\\logo{"), i(1, "imagefile"), t("}") }, "g"),
    S({ trig = "\\logo*", dscr = "{code}" }, { t("\\logo*{"), i(1, "code"), t("}") }),
    S({ trig = "\\dissertationstyle", dscr = "{style}" }, { t("\\dissertationstyle{"), i(1, "style"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\documentclass/udiss#c",
      lines = {
        "title={%<text%>}",
        "author={%<author%>}",
        "pronouns={%<pronouns%>}",
        "subtitle={%<text%>}",
        "shorttitle={%<text%>}",
        "stream={%<stream%>}",
        "discipline={%<discipline%>}",
        "degree={%<degree%>}",
        "supervisor={%<supervisor%>}",
        "university={%<university%>}",
        "department={%<department%>}",
        "logo=%<imagefile%>",
        "logo*=%<code%>",
        "language={%<babel language names%>}",
        "ldfbabel={%<babel ldf language names%>}",
        "nofontwarning#true,false",
        "license=#all-rights-reserved,CC-BY-SA,GFDL",
        "copyright-yrs=%<years%>",
        "localcopyright=%<word%>",
        "placeholders",
        "lot#true,false",
        "lof#true,false",
        "declaration#true,false",
        "declarationtxt=%<text%>",
        "decllocal=%<word%>",
        "blind#true,false",
        "framed-title#true,false",
        "print#true,false",
        "norefcolors#true,false",
        "udisslinkclr=#%color",
        "udissurlclr=#%color",
        "udissciteclr=#%color",
        "oldstylenumoff#true,false",
        "oldone#true,false",
        "fulfilment=%<text%>",
        "explicitext#true,false",
        "ignorefsoff#true,false",
        "rmfeatures={%<font features%>}",
        "sffeatures={%<font features%>}",
        "ttfeatures={%<font features%>}",
        "mathfeatures={%<font features%>}",
        "rmfntext=#ttf,otf",
        "sffntext=#ttf,otf",
        "ttfntext=#ttf,otf",
        "mathfntext=#ttf,otf",
        "logowidth=%<factor%>",
        "logoheight=%<factor%>",
      },
    },
  },
}
