-- Generated by snipgen 1 from class-grant-nsf.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-grant-nsf.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: a1a489c8936d7e2f987c38e296e89e8db3403c6a83e4ac553a130fd285a50fc6
-- cwl-header:
--   # grant-nsf class
--   # Matthew Bertucci 2022/05/19 for v0.0.5
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-grant-nsf",
  includes = { "class-grant" },
  lists = {},
  snippets = {
    S({ trig = "\\draftstatus", dscr = "∗", priority = 900 }, { t("\\draftstatus") }, "*"),
    S({ trig = "\\whitepaperstatus", dscr = "∗", priority = 900 }, { t("\\whitepaperstatus") }, "*"),
    S({ trig = "\\sectioncompactstatus", dscr = "∗", priority = 900 }, { t("\\sectioncompactstatus") }, "*"),
    S({ trig = "\\bibcompactstatus", dscr = "∗", priority = 900 }, { t("\\bibcompactstatus") }, "*"),
  },
  keyvals = {
    {
      targets = "\\documentclass/grant-nsf#c",
      lines = {
        "isdraft",
        "isnotdraft",
        "iswhitepaper",
        "isnotwhitepaper",
        "issectioncompact",
        "isnotsectioncompact",
        "isbibcompact",
        "isnotbibcompact",
      },
    },
  },
}
