-- Generated by snipgen 1 from class-standalone.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-standalone.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 588fa9c30be766fc3fe274cb8cf9122f0ecb505f1ce5c83432fbb9accd12e85a
-- cwl-header:
--   # standalone class
--   # Matthew Bertucci 2025/02/21 for v1.5
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-standalone",
  includes = { "ifluatex", "ifpdf", "ifxetex", "shellesc", "xkeyval" },
  lists = {},
  snippets = {
    S({ trig = "\\standaloneconfig", dscr = "{options}" }, { t("\\standaloneconfig{"), i(1, "options"), t("}") }),
    S({ trig = "\\standaloneenv", dscr = "{envname1,envname2,...}" }, { t("\\standaloneenv{"), i(1, "envname1,envname2,..."), t("}") }),
    S({ trig = "\\standaloneignore", dscr = "∗", priority = 900 }, { t("\\standaloneignore") }, "*"),
    S({ trig = "\\standalone", dscr = "\\begin{standalone} ∗", priority = 900 }, { t({ "\\begin{standalone}", "\t" }), i(1), t({ "", "\\end{standalone}" }) }, "*"),
    S({ trig = "\\thesapage", dscr = "∗", priority = 900 }, { t("\\thesapage") }, "*"),
    S({ trig = "\\ifstandalone", dscr = "∗", priority = 900 }, { t("\\ifstandalone") }, "*"),
    S({ trig = "\\standalonetrue", dscr = "∗", priority = 900 }, { t("\\standalonetrue") }, "*"),
    S({ trig = "\\standalonefalse", dscr = "∗", priority = 900 }, { t("\\standalonefalse") }, "*"),
    S({ trig = "\\ifstandalonebeamer", dscr = "∗", priority = 900 }, { t("\\ifstandalonebeamer") }, "*"),
    S({ trig = "\\standalonebeamertrue", dscr = "∗", priority = 900 }, { t("\\standalonebeamertrue") }, "*"),
    S({ trig = "\\standalonebeamerfalse", dscr = "∗", priority = 900 }, { t("\\standalonebeamerfalse") }, "*"),
    S({ trig = "\\IfStandalone", dscr = "{code for standalone}{code for main document} ∗", priority = 900 }, { t("\\IfStandalone{"), i(1, "code for standalone"), t("}{"), i(2, "code for main document"), t("}") }, "*"),
    S({ trig = "\\onlyifstandalone", dscr = "{code} ∗", priority = 900 }, { t("\\onlyifstandalone{"), i(1, "code"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\documentclass/standalone,\\standaloneconfig",
      lines = {
        "beamer#true,false",
        "border=##L",
        "border={%<<l/r> <t/b>%>}",
        "border={%<<l> <b> <r> <t>%>}",
        "class=%<class name%>",
        "convert#true,false",
        "convert={%<conversion options%>}",
        "crop#true,false",
        "emf#true,false",
        "emf={%<conversion options%>}",
        "float#true,false",
        "float#true,false",
        "gif#true,false",
        "gif={%<conversion options%>}",
        "ignoreempty#true,false",
        "ignorerest#true,false",
        "jpg#true,false",
        "jpg={%<conversion options%>}",
        "margin=##L",
        "math#true,false",
        "multi#true,false",
        "multi={%<envname1,envname2,...%>}",
        "multido#true,false",
        "png#true,false",
        "png={%<conversion options%>}",
        "preview#true,false",
        "pstricks#true,false",
        "svg#true,false",
        "svg={%<conversion options%>}",
        "tikz#true,false",
        "varwidth#true,false",
        "varwidth=##L",
      },
    },
    {
      targets = "\\documentclass/standalone",
      lines = {
        "10pt",
        "11pt",
        "12pt",
      },
    },
  },
}
