-- Generated by snipgen 1 from class-leadsheet.cwl; do not edit, regenerate.
-- source: TeXstudio completion/class-leadsheet.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 1029ef243c6a564ef5f1a49f95f0103cc839a9e542d257554895808bf894d231
-- cwl-header:
--   # leadsheet class
--   # Matthew Bertucci 12/22/2021 for v0.5c
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "class-leadsheet",
  includes = { "class-scrartcl", "etoolbox", "leadsheets", "scrlayer-scrpage", "translations", "zref-totpages" },
  lists = {},
  snippets = {
    S({ trig = "\\prechorus", dscr = "\\begin{prechorus}" }, { t({ "\\begin{prechorus}", "\t" }), i(1), t({ "", "\\end{prechorus}" }) }),
    S({ trig = "\\prechorus", dscr = "\\begin{prechorus}[options]" }, { t("\\begin{prechorus}["), i(1, "options"), t({ "]", "\t" }), i(2), t({ "", "\\end{prechorus}" }) }),
    S({ trig = "\\instruction", dscr = "{text}" }, { t("\\instruction{"), i(1, "text"), t("}") }),
    S({ trig = "\\choir", dscr = "{text}" }, { t("\\choir{"), i(1, "text"), t("}") }),
    S({ trig = "\\lsenparen", dscr = "{text}" }, { t("\\lsenparen{"), i(1, "text"), t("}") }),
    S({ trig = "\\mkinstruction", dscr = "{text} ∗", priority = 900 }, { t("\\mkinstruction{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\mkchoir", dscr = "{text} ∗", priority = 900 }, { t("\\mkchoir{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\mklsenparens", dscr = "∗", priority = 900 }, { t("\\mklsenparens") }, "*"),
    S({ trig = "\\mklsenparen", dscr = "{open paren}{closing paren}{text} ∗", priority = 900 }, { t("\\mklsenparen{"), i(1, "open paren"), t("}{"), i(2, "closing paren"), t("}{"), i(3, "text"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\begin{prechorus}",
      lines = {
        "format={%<code%>}",
        "label-format={%<code%>}",
        "class={%<class name%>}",
        "after-label={%<code%>}",
        "name=%<name%>",
        "template=%<template%>",
        "numbered#true,false",
        "named#true,false",
        "recall-chords={%<env-class%>}",
        "verses-format={%<code%>}",
        "verses-label-format={%<code%>}",
        "verses-after-label={%<code%>}",
      },
    },
  },
}
