-- Generated by snipgen 1 from cleanthesis.cwl; do not edit, regenerate.
-- source: TeXstudio completion/cleanthesis.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 93c472168389a2b399f3d334c59ab89765436d16584d2365cceece77339fcec4
-- cwl-header:
--   # cleanthesis package
--   # Matthew Bertucci 1/8/2021 for v0.4.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "cleanthesis",
  includes = { "xkeyval", "xcolor", "fontenc", "lmodern", "charter", "microtype", "setspace", "graphicx", "tabularx", "enumitem", "blindtext", "hyperref", "scrlayer-scrpage", "caption", "csquotes", "tocloft" },
  lists = {},
  snippets = {
    S({ trig = "\\cthesissetcolor", dscr = "{model}{color1}{color2} ∗", priority = 900 }, { t("\\cthesissetcolor{"), i(1, "model"), t("}{"), i(2, "color1"), t("}{"), i(3, "color2"), t("}") }, "*"),
    S({ trig = "\\cthesissetcolorbluemagenta", dscr = "∗", priority = 900 }, { t("\\cthesissetcolorbluemagenta") }, "*"),
    S({ trig = "\\cthesissetcolorbluegreen", dscr = "∗", priority = 900 }, { t("\\cthesissetcolorbluegreen") }, "*"),
    S({ trig = "\\my_list", dscr = "\\begin{my_list} ∗", priority = 900 }, { t({ "\\begin{my_list}", "\t" }), i(1), t({ "", "\\end{my_list}" }) }, "*"),
    S({ trig = "\\my_list_num", dscr = "\\begin{my_list_num} ∗", priority = 900 }, { t({ "\\begin{my_list_num}", "\t" }), i(1), t({ "", "\\end{my_list_num}" }) }, "*"),
    S({ trig = "\\my_list_item", dscr = "\\begin{my_list_item} ∗", priority = 900 }, { t({ "\\begin{my_list_item}", "\t" }), i(1), t({ "", "\\end{my_list_item}" }) }, "*"),
    S({ trig = "\\ct_version_list", dscr = "\\begin{ct_version_list} ∗", priority = 900 }, { t({ "\\begin{ct_version_list}", "\t" }), i(1), t({ "", "\\end{ct_version_list}" }) }, "*"),
    S({ trig = "\\ct_version_list_sub", dscr = "\\begin{ct_version_list_sub} ∗", priority = 900 }, { t({ "\\begin{ct_version_list_sub}", "\t" }), i(1), t({ "", "\\end{ct_version_list_sub}" }) }, "*"),
    S({ trig = "\\my_list_desc", dscr = "\\begin{my_list_desc} ∗", priority = 900 }, { t({ "\\begin{my_list_desc}", "\t" }), i(1), t({ "", "\\end{my_list_desc}" }) }, "*"),
    S({ trig = "\\lensectionnumber", dscr = "∗", priority = 900 }, { t("\\lensectionnumber") }, "*"),
    S({ trig = "\\ctfooterline", dscr = "∗", priority = 900 }, { t("\\ctfooterline") }, "*"),
    S({ trig = "\\ctfooterrightpagenumber", dscr = "∗", priority = 900 }, { t("\\ctfooterrightpagenumber") }, "*"),
    S({ trig = "\\ctfooterleftpagenumber", dscr = "∗", priority = 900 }, { t("\\ctfooterleftpagenumber") }, "*"),
    S({ trig = "\\TODO", dscr = "{text}" }, { t("\\TODO{"), i(1, "text"), t("}") }, "D"),
    S({ trig = "\\tabref", dscr = "{label} ∗", priority = 900 }, { t("\\tabref{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\tableref", dscr = "{label} ∗", priority = 900 }, { t("\\tableref{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\tref", dscr = "{label} ∗", priority = 900 }, { t("\\tref{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\treft", dscr = "{label} ∗", priority = 900 }, { t("\\treft{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\textref", dscr = "{label} ∗", priority = 900 }, { t("\\textref{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\textreft", dscr = "{label} ∗", priority = 900 }, { t("\\textreft{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\fref", dscr = "{label} ∗", priority = 900 }, { t("\\fref{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\frefadd", dscr = "{label}{text} ∗", priority = 900 }, { t("\\frefadd{"), i(1, "label"), t("}{"), i(2, "text"), t("}") }, "*r"),
    S({ trig = "\\figref", dscr = "{label} ∗", priority = 900 }, { t("\\figref{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\figrefadd", dscr = "{label}{text} ∗", priority = 900 }, { t("\\figrefadd{"), i(1, "label"), t("}{"), i(2, "text"), t("}") }, "*r"),
    S({ trig = "\\figreft", dscr = "{label} ∗", priority = 900 }, { t("\\figreft{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\figrefaddt", dscr = "{label}{text} ∗", priority = 900 }, { t("\\figrefaddt{"), i(1, "label"), t("}{"), i(2, "text"), t("}") }, "*r"),
    S({ trig = "\\seepage", dscr = "{label} ∗", priority = 900 }, { t("\\seepage{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\ctSetFont", dscr = "{arg1}{arg2}{arg3} ∗", priority = 900 }, { t("\\ctSetFont{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}{"), i(3, "arg3"), t("}") }, "*"),
    S({ trig = "\\helv", dscr = "∗", priority = 900 }, { t("\\helv") }, "*"),
    S({ trig = "\\book", dscr = "∗", priority = 900 }, { t("\\book") }, "*"),
    S({ trig = "\\tgherosfont", dscr = "∗", priority = 900 }, { t("\\tgherosfont") }, "*"),
    S({ trig = "\\thesispartlabelfont", dscr = "∗", priority = 900 }, { t("\\thesispartlabelfont") }, "*"),
    S({ trig = "\\thesispartfont", dscr = "∗", priority = 900 }, { t("\\thesispartfont") }, "*"),
    S({ trig = "\\thesischapterfont", dscr = "∗", priority = 900 }, { t("\\thesischapterfont") }, "*"),
    S({ trig = "\\thesissectionfont", dscr = "∗", priority = 900 }, { t("\\thesissectionfont") }, "*"),
    S({ trig = "\\thesissubsectionfont", dscr = "∗", priority = 900 }, { t("\\thesissubsectionfont") }, "*"),
    S({ trig = "\\thesisparagraphfont", dscr = "∗", priority = 900 }, { t("\\thesisparagraphfont") }, "*"),
    S({ trig = "\\ctfontfooterpagenumber", dscr = "∗", priority = 900 }, { t("\\ctfontfooterpagenumber") }, "*"),
    S({ trig = "\\ctfontfootertext", dscr = "∗", priority = 900 }, { t("\\ctfontfootertext") }, "*"),
    S({ trig = "\\ctchapternumber", dscr = "{arg} ∗", priority = 900 }, { t("\\ctchapternumber{"), i(1, "arg"), t("}") }, "*"),
    S({ trig = "\\ctchaptertitle", dscr = "{text} ∗", priority = 900 }, { t("\\ctchaptertitle{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\hugequote", dscr = "∗", priority = 900 }, { t("\\hugequote") }, "*"),
    S({ trig = "\\cleanchapterquote", dscr = "{text1}{text2}{text3} ∗", priority = 900 }, { t("\\cleanchapterquote{"), i(1, "text1"), t("}{"), i(2, "text2"), t("}{"), i(3, "text3"), t("}") }, "*"),
    S({ trig = "\\thesis_quotation", dscr = "\\begin{thesis_quotation} ∗", priority = 900 }, { t({ "\\begin{thesis_quotation}", "\t" }), i(1), t({ "", "\\end{thesis_quotation}" }) }, "*"),
    S({ trig = "\\cthesisorigin", dscr = "{text} ∗", priority = 900 }, { t("\\cthesisorigin{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\DH", dscr = "" }, { t("\\DH") }, "n"),
    S({ trig = "\\NG", dscr = "" }, { t("\\NG") }, "n"),
    S({ trig = "\\dj", dscr = "" }, { t("\\dj") }, "n"),
    S({ trig = "\\ng", dscr = "" }, { t("\\ng") }, "n"),
    S({ trig = "\\k", dscr = "{arg}" }, { t("\\k{"), i(1, "arg"), t("}") }, "n"),
    S({ trig = "\\guillemotleft", dscr = "∗", priority = 900 }, { t("\\guillemotleft") }, "*n"),
    S({ trig = "\\guillemotright", dscr = "∗", priority = 900 }, { t("\\guillemotright") }, "*n"),
    S({ trig = "\\guilsinglleft", dscr = "" }, { t("\\guilsinglleft") }, "n"),
    S({ trig = "\\guilsinglright", dscr = "" }, { t("\\guilsinglright") }, "n"),
    S({ trig = "\\quotedblbase", dscr = "" }, { t("\\quotedblbase") }, "n"),
    S({ trig = "\\quotesinglbase", dscr = "" }, { t("\\quotesinglbase") }, "n"),
    S({ trig = "\\textquotedbl", dscr = "" }, { t("\\textquotedbl") }, "n"),
    S({ trig = "\\DJ", dscr = "" }, { t("\\DJ") }, "n"),
    S({ trig = "\\th", dscr = "" }, { t("\\th") }, "n"),
    S({ trig = "\\TH", dscr = "" }, { t("\\TH") }, "n"),
    S({ trig = "\\dh", dscr = "" }, { t("\\dh") }, "n"),
    S({ trig = "\\Hwithstroke", dscr = "∗", priority = 900 }, { t("\\Hwithstroke") }, "*n"),
    S({ trig = "\\hwithstroke", dscr = "∗", priority = 900 }, { t("\\hwithstroke") }, "*n"),
    S({ trig = "\\textogonekcentered", dscr = "{arg} ∗", priority = 900 }, { t("\\textogonekcentered{"), i(1, "arg"), t("}") }, "*n"),
    S({ trig = "\\guillemetleft", dscr = "" }, { t("\\guillemetleft") }, "n"),
    S({ trig = "\\guillemetright", dscr = "" }, { t("\\guillemetright") }, "n"),
  },
  keyvals = {
    {
      targets = "\\usepackage/cleanthesis#c",
      lines = {
        "hangfigurecaption#true,false",
        "hangsection#true,false",
        "hangsubsection#true,false",
        "sansserif#true,false",
        "configurelistings#true,false",
        "figuresep=#none,colon,period,space,quad,endash",
        "colorize=#full,reduced,bw",
        "colortheme=#bluemagenta,bluegreen",
        "quotesstyle=%<csquotes style options%>",
        "configurebiblatex#true,false",
        "bibsys=#biber,bibtex",
        "bibfile=%<file name%>",
        "bibstyle=%<biblatex style options%>",
        "bibsorting=#nty,nyt,nyvt,anyt,anyvt,ynt,ydnt,none,debug",
      },
    },
  },
}
