-- Generated by snipgen 1 from cleveref-forward.cwl; do not edit, regenerate.
-- source: TeXstudio completion/cleveref-forward.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 4a12f1df5534b54874c5f499a917d904907873ecbb57ee1182294ebaff512460
-- cwl-header:
--   # cleveref-forward package
--   # Matthew Bertucci 2024/02/25 for v2024/02/24
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "cleveref-forward",
  includes = { "cleveref", "iflang", "regexpatch" },
  lists = {},
  snippets = {
    S({ trig = "\\cref", dscr = "[option]{labellist}" }, { t("\\cref["), i(1, "option"), t("]{"), i(2, "labellist"), t("}") }, "r"),
    S({ trig = "\\cref*", dscr = "[option]{labellist}" }, { t("\\cref*["), i(1, "option"), t("]{"), i(2, "labellist"), t("}") }, "r"),
    S({ trig = "\\Cref", dscr = "[option]{labellist}" }, { t("\\Cref["), i(1, "option"), t("]{"), i(2, "labellist"), t("}") }, "r"),
    S({ trig = "\\Cref*", dscr = "[option]{labellist}" }, { t("\\Cref*["), i(1, "option"), t("]{"), i(2, "labellist"), t("}") }, "r"),
    S({ trig = "\\labelcref", dscr = "[option]{labellist}" }, { t("\\labelcref["), i(1, "option"), t("]{"), i(2, "labellist"), t("}") }, "r"),
    S({ trig = "\\SetUsedOnMessageText", dscr = "{text}" }, { t("\\SetUsedOnMessageText{"), i(1, "text"), t("}") }),
    S({ trig = "\\SetUsedByMessageText", dscr = "{text}" }, { t("\\SetUsedByMessageText{"), i(1, "text"), t("}") }),
    S({ trig = "\\SetUsedByAndOnMessageText", dscr = "{text}" }, { t("\\SetUsedByAndOnMessageText{"), i(1, "text"), t("}") }),
    S({ trig = "\\SetForwardReferenceStyle", dscr = "{code}" }, { t("\\SetForwardReferenceStyle{"), i(1, "code"), t("}") }),
    S({ trig = "\\SetForwardReferenceStyleInsideMath", dscr = "{code}" }, { t("\\SetForwardReferenceStyleInsideMath{"), i(1, "code"), t("}") }),
    S({ trig = "\\SetForwardReferenceStyleOutsideMath", dscr = "{code}" }, { t("\\SetForwardReferenceStyleOutsideMath{"), i(1, "code"), t("}") }),
    S({ trig = "\\SetForwardReferenceRefForm", dscr = "{code}" }, { t("\\SetForwardReferenceRefForm{"), i(1, "code"), t("}") }),
    S({ trig = "\\SetForwardReferencePagerefForm", dscr = "{code}" }, { t("\\SetForwardReferencePagerefForm{"), i(1, "code"), t("}") }),
    S({ trig = "\\restorelabel", dscr = "{label}" }, { t("\\restorelabel{"), i(1, "label"), t("}") }, "r"),
  },
  keyvals = {
    {
      targets = "\\usepackage/cleveref-forward#c",
      lines = {
        "default=#used on,used by,used by and on",
        "crefthe#true,false",
      },
    },
    {
      targets = "\\cref#c,\\cref*#c,\\Cref#c,\\Cref*#c,\\labelcref#c",
      lines = {
        "used on",
        "used by",
        "used by and on",
        "no use",
      },
    },
  },
}
