-- Generated by snipgen 1 from clrscode3e.cwl; do not edit, regenerate.
-- source: TeXstudio completion/clrscode3e.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c51a5d2d449546f5ce5f25583bbef04d913ca918a073c341c7b1e0a205e3a7e4
-- cwl-header:
--   # clrscode3e package
--   # Matthew Bertucci 2922/07/16
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "clrscode3e",
  includes = { "graphics" },
  lists = {},
  snippets = {
    S({ trig = "\\id", dscr = "{identifier}" }, { t("\\id{"), i(1, "identifier"), t("}") }),
    S({ trig = "\\proc", dscr = "{procedure}" }, { t("\\proc{"), i(1, "procedure"), t("}") }),
    S({ trig = "\\const", dscr = "{constant}" }, { t("\\const{"), i(1, "constant"), t("}") }),
    S({ trig = "\\func", dscr = "{function}" }, { t("\\func{"), i(1, "function"), t("}") }),
    S({ trig = "\\attrib", dscr = "{object}{attribute}" }, { t("\\attrib{"), i(1, "object"), t("}{"), i(2, "attribute"), t("}") }),
    S({ trig = "\\attribxi", dscr = "{object}{attribute}" }, { t("\\attribxi{"), i(1, "object"), t("}{"), i(2, "attribute"), t("}") }),
    S({ trig = "\\attribxx", dscr = "{object}{attribute}" }, { t("\\attribxx{"), i(1, "object"), t("}{"), i(2, "attribute"), t("}") }),
    S({ trig = "\\attribii", dscr = "{object}{attribute}" }, { t("\\attribii{"), i(1, "object"), t("}{"), i(2, "attribute"), t("}") }),
    S({ trig = "\\attribix", dscr = "{object}{attribute}" }, { t("\\attribix{"), i(1, "object"), t("}{"), i(2, "attribute"), t("}") }),
    S({ trig = "\\attribb", dscr = "{object}{attribute1}{attribute2}" }, { t("\\attribb{"), i(1, "object"), t("}{"), i(2, "attribute1"), t("}{"), i(3, "attribute2"), t("}") }),
    S({ trig = "\\attribbb", dscr = "{object}{attribute1}{attribute2}{attribute3}" }, { t("\\attribbb{"), i(1, "object"), t("}{"), i(2, "attribute1"), t("}{"), i(3, "attribute2"), t("}{"), i(4, "attribute3"), t("}") }),
    S({ trig = "\\attribbbb", dscr = "{object}{attribute1}{attribute2}{attribute3}{attribute4}" }, { t("\\attribbbb{"), i(1, "object"), t("}{"), i(2, "attribute1"), t("}{"), i(3, "attribute2"), t("}{"), i(4, "attribute3"), t("}{"), i(5, "attribute4"), t("}") }),
    S({ trig = "\\attribbxxi", dscr = "{object}{attribute1}{attribute2}" }, { t("\\attribbxxi{"), i(1, "object"), t("}{"), i(2, "attribute1"), t("}{"), i(3, "attribute2"), t("}") }),
    S({ trig = "\\attribe", dscr = "{vertex1}{vertex2}{attribute}" }, { t("\\attribe{"), i(1, "vertex1"), t("}{"), i(2, "vertex2"), t("}{"), i(3, "attribute"), t("}") }),
    S({ trig = "\\attribex", dscr = "{vertex1}{vertex2}{attribute}" }, { t("\\attribex{"), i(1, "vertex1"), t("}{"), i(2, "vertex2"), t("}{"), i(3, "attribute"), t("}") }),
    S({ trig = "\\twodots", dscr = "" }, h.mathwrap({ t("\\twodots") }), "m"),
    S({ trig = "\\isequal", dscr = "" }, h.mathwrap({ t("\\isequal") }), "m"),
    S({ trig = "\\codebox", dscr = "\\begin{codebox}" }, { t({ "\\begin{codebox}", "\t" }), i(1), t({ "", "\\end{codebox}" }) }, "\\tabbing"),
    S({ trig = "\\Procname", dscr = "{procedure}" }, { t("\\Procname{"), i(1, "procedure"), t("}") }),
    S({ trig = "\\li", dscr = "" }, { t("\\li") }),
    S({ trig = "\\zi", dscr = "" }, { t("\\zi") }),
    S({ trig = "\\kw", dscr = "{keyword}" }, { t("\\kw{"), i(1, "keyword"), t("}") }),
    S({ trig = "\\For", dscr = "" }, { t("\\For") }),
    S({ trig = "\\To", dscr = "" }, { t("\\To") }),
    S({ trig = "\\Downto", dscr = "" }, { t("\\Downto") }),
    S({ trig = "\\By", dscr = "" }, { t("\\By") }),
    S({ trig = "\\While", dscr = "" }, { t("\\While") }),
    S({ trig = "\\If", dscr = "" }, { t("\\If") }),
    S({ trig = "\\Return", dscr = "" }, { t("\\Return") }),
    S({ trig = "\\Goto", dscr = "" }, { t("\\Goto") }),
    S({ trig = "\\Error", dscr = "" }, { t("\\Error") }),
    S({ trig = "\\Spawn", dscr = "" }, { t("\\Spawn") }),
    S({ trig = "\\Sync", dscr = "" }, { t("\\Sync") }),
    S({ trig = "\\Parfor", dscr = "" }, { t("\\Parfor") }),
    S({ trig = "\\Comment", dscr = "" }, { t("\\Comment") }),
    S({ trig = "\\CommentSymbol", dscr = "" }, { t("\\CommentSymbol") }),
    S({ trig = "\\Do", dscr = "" }, { t("\\Do") }),
    S({ trig = "\\End", dscr = "" }, { t("\\End") }),
    S({ trig = "\\Repeat", dscr = "" }, { t("\\Repeat") }),
    S({ trig = "\\Until", dscr = "" }, { t("\\Until") }),
    S({ trig = "\\Then", dscr = "" }, { t("\\Then") }),
    S({ trig = "\\Else", dscr = "" }, { t("\\Else") }),
    S({ trig = "\\ElseIf", dscr = "" }, { t("\\ElseIf") }),
    S({ trig = "\\ElseNoIf", dscr = "" }, { t("\\ElseNoIf") }),
    S({ trig = "\\Indentmore", dscr = "" }, { t("\\Indentmore") }),
    S({ trig = "\\RComment", dscr = "" }, { t("\\RComment") }),
    S({ trig = "\\setlinenumber", dscr = "{label}" }, { t("\\setlinenumber{"), i(1, "label"), t("}") }, "r"),
    S({ trig = "\\setlinenumberplus", dscr = "{label}{integer}" }, { t("\\setlinenumberplus{"), i(1, "label"), t("}{"), i(2, "integer"), t("}") }, "r"),
    S({ trig = "\\Startalign", dscr = "{content}" }, { t("\\Startalign{"), i(1, "content"), t("}") }),
    S({ trig = "\\Stopalign", dscr = "" }, { t("\\Stopalign") }),
    S({ trig = "\\codeboxwidth", dscr = "∗", priority = 900 }, { t("\\codeboxwidth") }, "*"),
    S({ trig = "\\codeindent", dscr = "∗", priority = 900 }, { t("\\codeindent") }, "*"),
    S({ trig = "\\digitwidth", dscr = "∗", priority = 900 }, { t("\\digitwidth") }, "*"),
    S({ trig = "\\EndTest", dscr = "∗", priority = 900 }, { t("\\EndTest") }, "*"),
    S({ trig = "\\FakeIndent", dscr = "∗", priority = 900 }, { t("\\FakeIndent") }, "*"),
    S({ trig = "\\firstcodelinefalse", dscr = "∗", priority = 900 }, { t("\\firstcodelinefalse") }, "*"),
    S({ trig = "\\firstcodelinetrue", dscr = "∗", priority = 900 }, { t("\\firstcodelinetrue") }, "*"),
    S({ trig = "\\iffirstcodeline", dscr = "∗", priority = 900 }, { t("\\iffirstcodeline") }, "*"),
    S({ trig = "\\ifnumberedline", dscr = "∗", priority = 900 }, { t("\\ifnumberedline") }, "*"),
    S({ trig = "\\ifprocname", dscr = "∗", priority = 900 }, { t("\\ifprocname") }, "*"),
    S({ trig = "\\Indent", dscr = "∗", priority = 900 }, { t("\\Indent") }, "*"),
    S({ trig = "\\liprint", dscr = "∗", priority = 900 }, { t("\\liprint") }, "*"),
    S({ trig = "\\lispace", dscr = "{length} ∗", priority = 900 }, { t("\\lispace{"), i(1, "length"), t("}") }, "*"),
    S({ trig = "\\numberedlinefalse", dscr = "∗", priority = 900 }, { t("\\numberedlinefalse") }, "*"),
    S({ trig = "\\numberedlinetrue", dscr = "∗", priority = 900 }, { t("\\numberedlinetrue") }, "*"),
    S({ trig = "\\numref", dscr = "{label} ∗", priority = 900 }, { t("\\numref{"), i(1, "label"), t("}") }, "*r"),
    S({ trig = "\\procnamefalse", dscr = "∗", priority = 900 }, { t("\\procnamefalse") }, "*"),
    S({ trig = "\\procnametrue", dscr = "∗", priority = 900 }, { t("\\procnametrue") }, "*"),
    S({ trig = "\\putfakeindents", dscr = "∗", priority = 900 }, { t("\\putfakeindents") }, "*"),
    S({ trig = "\\putindents", dscr = "∗", priority = 900 }, { t("\\putindents") }, "*"),
    S({ trig = "\\savecode", dscr = "∗", priority = 900 }, { t("\\savecode") }, "*"),
    S({ trig = "\\saveprocname", dscr = "∗", priority = 900 }, { t("\\saveprocname") }, "*"),
    S({ trig = "\\thecodelinenumber", dscr = "∗", priority = 900 }, { t("\\thecodelinenumber") }, "*"),
    S({ trig = "\\theindent", dscr = "∗", priority = 900 }, { t("\\theindent") }, "*"),
    S({ trig = "\\thethisindent", dscr = "∗", priority = 900 }, { t("\\thethisindent") }, "*"),
    S({ trig = "\\useregularv", dscr = "∗", priority = 900 }, { t("\\useregularv") }, "*"),
    S({ trig = "\\zeroli", dscr = "∗", priority = 900 }, { t("\\zeroli") }, "*"),
  },
  keyvals = {},
}
