-- Generated by snipgen 1 from cnltx-names.cwl; do not edit, regenerate.
-- source: TeXstudio completion/cnltx-names.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 351005edee978a1cb84f529fdf8cab1f2d009155ad503d6b0cbb1e15f5702a80
-- cwl-header:
--   # cnltx-names package
--   # Matthew Bertucci 10/18/2021 for v0.15
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "cnltx-names",
  includes = { "cnltx-base" },
  lists = {},
  snippets = {
    S({ trig = "\\newfirstformat", dscr = "{cmd}" }, { t("\\newfirstformat{"), i(1, "cmd"), t("}") }, "d"),
    S({ trig = "\\writename", dscr = "{text}" }, { t("\\writename{"), i(1, "text"), t("}") }),
    S({ trig = "\\defnameformat", dscr = "{format name}{first}{middle}{last}" }, { t("\\defnameformat{"), i(1, "format name"), t("}{"), i(2, "first"), t("}{"), i(3, "middle"), t("}{"), i(4, "last"), t("}") }),
    S({ trig = "\\writenameformat", dscr = "{format name}" }, { t("\\writenameformat{"), i(1, "format name"), t("}") }),
    S({ trig = "\\name", dscr = "{text}" }, { t("\\name{"), i(1, "text"), t("}") }),
    S({ trig = "\\name*", dscr = "{text}" }, { t("\\name*{"), i(1, "text"), t("}") }),
    S({ trig = "\\nameformat", dscr = "" }, { t("\\nameformat") }),
    S({ trig = "\\namefirstformat", dscr = "" }, { t("\\namefirstformat") }),
    S({ trig = "\\resetname", dscr = "" }, { t("\\resetname") }),
    S({ trig = "\\newname", dscr = "{cmd}{text}" }, { t("\\newname{"), i(1, "cmd"), t("}{"), i(2, "text"), t("}") }, "d"),
  },
  keyvals = {},
}
