-- Generated by snipgen 1 from codedescribe.cwl; do not edit, regenerate.
-- source: TeXstudio completion/codedescribe.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: e19d50d694605f1647adfcee247e5d7c605d3380f810e4c4a52f23a97b83afd4
-- cwl-header:
--   # codedescribe package
--   # Matthew Bertucci 2025/09/26 for v1.12
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "codedescribe",
  includes = { "xcolor", "pifont", "codelisting" },
  lists = {},
  snippets = {
    S({ trig = "\\defgroupfmt", dscr = "{format-group}{format-keys}" }, { t("\\defgroupfmt{"), i(1, "format-group"), t("}{"), i(2, "format-keys"), t("}") }),
    S({ trig = "\\defobjectfmt", dscr = "{obj-type}{format-group}{format-keys}" }, { t("\\defobjectfmt{"), i(1, "obj-type"), t("}{"), i(2, "format-group"), t("}{"), i(3, "format-keys"), t("}") }),
    S({ trig = "\\codedescribe", dscr = "\\begin{codedescribe}{csv-list}" }, { t("\\begin{codedescribe}{"), i(1, "csv-list"), t({ "}", "\t" }), i(2), t({ "", "\\end{codedescribe}" }) }),
    S({ trig = "\\codedescribe", dscr = "\\begin{codedescribe}[obj-type]{csv-list}" }, { t("\\begin{codedescribe}["), i(1, "obj-type"), t("]{"), i(2, "csv-list"), t({ "}", "\t" }), i(3), t({ "", "\\end{codedescribe}" }) }),
    S({ trig = "\\codesyntax", dscr = "\\begin{codesyntax}" }, { t({ "\\begin{codesyntax}", "\t" }), i(1), t({ "", "\\end{codesyntax}" }) }),
    S({ trig = "\\describelist", dscr = "\\begin{describelist}{obj-type}" }, { t("\\begin{describelist}{"), i(1, "obj-type"), t({ "}", "\t" }), i(2), t({ "", "\\end{describelist}" }) }),
    S({ trig = "\\describelist", dscr = "\\begin{describelist}[item-indent]{obj-type}" }, { t("\\begin{describelist}["), i(1, "item-indent"), t("]{"), i(2, "obj-type"), t({ "}", "\t" }), i(3), t({ "", "\\end{describelist}" }) }),
    S({ trig = "\\describelist*", dscr = "\\begin{describelist*}{obj-type}" }, { t("\\begin{describelist*}{"), i(1, "obj-type"), t({ "}", "\t" }), i(2), t({ "", "\\end{describelist*}" }) }),
    S({ trig = "\\describelist*", dscr = "\\begin{describelist*}[item-indent]{obj-type}" }, { t("\\begin{describelist*}["), i(1, "item-indent"), t("]{"), i(2, "obj-type"), t({ "}", "\t" }), i(3), t({ "", "\\end{describelist*}" }) }),
    S({ trig = "\\describe", dscr = "{item-name}{item-description}" }, { t("\\describe{"), i(1, "item-name"), t("}{"), i(2, "item-description"), t("}") }),
    S({ trig = "\\typesetobj", dscr = "{csv-list} ∗", priority = 900 }, { t("\\typesetobj{"), i(1, "csv-list"), t("}") }, "*"),
    S({ trig = "\\typesetobj", dscr = "[obj-type]{csv-list} ∗", priority = 900 }, { t("\\typesetobj["), i(1, "obj-type"), t("]{"), i(2, "csv-list"), t("}") }, "*"),
    S({ trig = "\\tsobj", dscr = "{csv-list}" }, { t("\\tsobj{"), i(1, "csv-list"), t("}") }),
    S({ trig = "\\tsobj", dscr = "[obj-type]{csv-list}" }, { t("\\tsobj["), i(1, "obj-type"), t("]{"), i(2, "csv-list"), t("}") }),
    S({ trig = "\\typesetargs", dscr = "{csv-list} ∗", priority = 900 }, { t("\\typesetargs{"), i(1, "csv-list"), t("}") }, "*"),
    S({ trig = "\\typesetargs", dscr = "[obj-type]{csv-list} ∗", priority = 900 }, { t("\\typesetargs["), i(1, "obj-type"), t("]{"), i(2, "csv-list"), t("}") }, "*"),
    S({ trig = "\\tsargs", dscr = "{csv-list}" }, { t("\\tsargs{"), i(1, "csv-list"), t("}") }),
    S({ trig = "\\tsargs", dscr = "[obj-type]{csv-list}" }, { t("\\tsargs["), i(1, "obj-type"), t("]{"), i(2, "csv-list"), t("}") }),
    S({ trig = "\\typesetmacro", dscr = "{macro-list}{csv-list} ∗", priority = 900 }, { t("\\typesetmacro{"), i(1, "macro-list"), t("}{"), i(2, "csv-list"), t("}") }, "*"),
    S({ trig = "\\typesetmacro", dscr = "{macro-list}[oargs-list]{margs-list} ∗", priority = 900 }, { t("\\typesetmacro{"), i(1, "macro-list"), t("}["), i(2, "oargs-list"), t("]{"), i(3, "margs-list"), t("}") }, "*"),
    S({ trig = "\\tsmacro", dscr = "{macro-list}{csv-list}" }, { t("\\tsmacro{"), i(1, "macro-list"), t("}{"), i(2, "csv-list"), t("}") }),
    S({ trig = "\\tsmacro", dscr = "{macro-list}[oargs-list]{margs-list}" }, { t("\\tsmacro{"), i(1, "macro-list"), t("}["), i(2, "oargs-list"), t("]{"), i(3, "margs-list"), t("}") }),
    S({ trig = "\\typesetmeta", dscr = "{name} ∗", priority = 900 }, { t("\\typesetmeta{"), i(1, "name"), t("}") }, "*"),
    S({ trig = "\\tsmeta", dscr = "{name}" }, { t("\\tsmeta{"), i(1, "name"), t("}") }),
    S({ trig = "\\typesetverb", dscr = "{verbatim text} ∗", priority = 900 }, { t("\\typesetverb{"), i(1, "verbatim text"), t("}") }, "*"),
    S({ trig = "\\typesetverb", dscr = "[obj-type]{verbatim text} ∗", priority = 900 }, { t("\\typesetverb["), i(1, "obj-type"), t("]{"), i(2, "verbatim text"), t("}") }, "*"),
    S({ trig = "\\tsverb", dscr = "{verbatim text}" }, { t("\\tsverb{"), i(1, "verbatim text"), t("}") }),
    S({ trig = "\\tsverb", dscr = "[obj-type]{verbatim text}" }, { t("\\tsverb["), i(1, "obj-type"), t("]{"), i(2, "verbatim text"), t("}") }),
    S({ trig = "\\typesetmarginnote", dscr = "{note} ∗", priority = 900 }, { t("\\typesetmarginnote{"), i(1, "note"), t("}") }, "*"),
    S({ trig = "\\tsmarginnote", dscr = "{note}" }, { t("\\tsmarginnote{"), i(1, "note"), t("}") }),
    S({ trig = "\\tsremark", dscr = "\\begin{tsremark}" }, { t({ "\\begin{tsremark}", "\t" }), i(1), t({ "", "\\end{tsremark}" }) }),
    S({ trig = "\\tsremark", dscr = "\\begin{tsremark}[NB]" }, { t("\\begin{tsremark}["), i(1, "NB"), t({ "]", "\t" }), i(2), t({ "", "\\end{tsremark}" }) }),
    S({ trig = "\\typesettitle", dscr = "{title-keys} ∗", priority = 900 }, { t("\\typesettitle{"), i(1, "title-keys"), t("}") }, "*"),
    S({ trig = "\\tstitle", dscr = "{title-keys}" }, { t("\\tstitle{"), i(1, "title-keys"), t("}") }),
    S({ trig = "\\typesetabstract", dscr = "\\begin{typesetabstract} ∗", priority = 900 }, { t({ "\\begin{typesetabstract}", "\t" }), i(1), t({ "", "\\end{typesetabstract}" }) }, "*"),
    S({ trig = "\\tsabstract", dscr = "\\begin{tsabstract}" }, { t({ "\\begin{tsabstract}", "\t" }), i(1), t({ "", "\\end{tsabstract}" }) }),
    S({ trig = "\\typesetdate", dscr = "∗", priority = 900 }, { t("\\typesetdate") }, "*"),
    S({ trig = "\\tsdate", dscr = "" }, { t("\\tsdate") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/codedescribe#c",
      lines = {
        "nolisting",
        "base skip=##L",
        "strict",
        "color scheme=#black,default,brighter,darker",
      },
    },
    {
      targets = "\\defgroupfmt#c,\\defobjectfmt#c",
      lines = {
        "meta",
        "xmeta",
        "verb",
        "xverb",
        "code",
        "nofmt",
        "slshape",
        "itshape",
        "noshape",
        "lbracket=%<symbol%>",
        "rbracket=%<symbol%>",
        "color=#%color",
      },
    },
    {
      targets = "\\begin{codedescribe}#c,\\begin{describelist}#c,\\begin{describelist*}#c,\\typesetobj#c,\\tsobj#c,\\typesetargs#c,\\tsargs#c,\\typesetverb#c,\\tsverb#c",
      lines = {
        "arg",
        "meta",
        "verb",
        "xverb",
        "marg",
        "oarg",
        "parg",
        "xarg",
        "code",
        "macro",
        "function",
        "syntax",
        "keyval",
        "key",
        "keys",
        "value",
        "option",
        "defaultval",
        "env",
        "pkg",
        "pack",
      },
    },
    {
      targets = "\\begin{codedescribe}#c",
      lines = {
        "new=%<date%>",
        "update=%<date%>",
        "note=%<text%>",
        "rulecolor=%<color%>",
        "EXP",
        "rEXP",
      },
    },
    {
      targets = "\\typesetobj#c,\\tsobj#c",
      lines = {
        "mid sep=%<separator%>",
        "sep=%<separator%>",
        "comma",
        "bnf or",
        "meta or",
        "par or",
      },
    },
    {
      targets = "\\typesettitle,\\tstitle",
      lines = {
        "title=%<text%>",
        "author=%<name%>",
        "date=%<date%>",
      },
    },
  },
}
