-- Generated by snipgen 1 from color-edits.cwl; do not edit, regenerate.
-- source: TeXstudio completion/color-edits.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 5061a24202b22610606904c3cc5c7175f3753cd374996bb0b3832c16474b9862
-- cwl-header:
--   # color-edits package
--   # Matthew Bertucci 2026/07/06 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "color-edits",
  includes = { "color", "etoolbox", "pdfcolfoot" },
  lists = {},
  snippets = {
    S({ trig = "\\addauthor", dscr = "{author}{color}" }, { t("\\addauthor{"), i(1, "author"), t("}{"), i(2, "color"), t("}") }),
    S({ trig = "\\addauthor", dscr = "[author name]{author}{color}" }, { t("\\addauthor["), i(1, "author name"), t("]{"), i(2, "author"), t("}{"), i(3, "color"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/color-edits#c",
      lines = {
        "suppress",
        "revert",
        "showdeletions",
        "inlinedeletions",
      },
    },
  },
}
