-- Generated by snipgen 1 from colordvi.cwl; do not edit, regenerate.
-- source: TeXstudio completion/colordvi.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: e90d849ef9e519a8e6a27560e396e831def7a2499608e73b0a0dacb47e7c48cb
-- cwl-header:
--   # colordvi package
--   # Matthew Bertucci 2022/06/25
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "colordvi",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\background", dscr = "{color}" }, { t("\\background{"), i(1, "color"), t("}") }),
    S({ trig = "\\subdef", dscr = "{color} ∗", priority = 900 }, { t("\\subdef{"), i(1, "color"), t("}") }, "*"),
    S({ trig = "\\textColor", dscr = "{c m y k}" }, { t("\\textColor{"), i(1, "c m y k"), t("}") }),
    S({ trig = "\\Color", dscr = "{c m y k}{content}" }, { t("\\Color{"), i(1, "c m y k"), t("}{"), i(2, "content"), t("}") }),
    S({ trig = "\\newColor", dscr = "ColorName" }, { t("\\newColor "), i(1, "ColorName") }),
    S({ trig = "\\GreenYellow", dscr = "{content}" }, { t("\\GreenYellow{"), i(1, "content"), t("}") }),
    S({ trig = "\\Yellow", dscr = "{content}" }, { t("\\Yellow{"), i(1, "content"), t("}") }),
    S({ trig = "\\Goldenrod", dscr = "{content}" }, { t("\\Goldenrod{"), i(1, "content"), t("}") }),
    S({ trig = "\\Dandelion", dscr = "{content}" }, { t("\\Dandelion{"), i(1, "content"), t("}") }),
    S({ trig = "\\Apricot", dscr = "{content}" }, { t("\\Apricot{"), i(1, "content"), t("}") }),
    S({ trig = "\\Peach", dscr = "{content}" }, { t("\\Peach{"), i(1, "content"), t("}") }),
    S({ trig = "\\Melon", dscr = "{content}" }, { t("\\Melon{"), i(1, "content"), t("}") }),
    S({ trig = "\\YellowOrange", dscr = "{content}" }, { t("\\YellowOrange{"), i(1, "content"), t("}") }),
    S({ trig = "\\Orange", dscr = "{content}" }, { t("\\Orange{"), i(1, "content"), t("}") }),
    S({ trig = "\\BurntOrange", dscr = "{content}" }, { t("\\BurntOrange{"), i(1, "content"), t("}") }),
    S({ trig = "\\Bittersweet", dscr = "{content}" }, { t("\\Bittersweet{"), i(1, "content"), t("}") }),
    S({ trig = "\\RedOrange", dscr = "{content}" }, { t("\\RedOrange{"), i(1, "content"), t("}") }),
    S({ trig = "\\Mahogany", dscr = "{content}" }, { t("\\Mahogany{"), i(1, "content"), t("}") }),
    S({ trig = "\\Maroon", dscr = "{content}" }, { t("\\Maroon{"), i(1, "content"), t("}") }),
    S({ trig = "\\BrickRed", dscr = "{content}" }, { t("\\BrickRed{"), i(1, "content"), t("}") }),
    S({ trig = "\\Red", dscr = "{content}" }, { t("\\Red{"), i(1, "content"), t("}") }),
    S({ trig = "\\OrangeRed", dscr = "{content}" }, { t("\\OrangeRed{"), i(1, "content"), t("}") }),
    S({ trig = "\\RubineRed", dscr = "{content}" }, { t("\\RubineRed{"), i(1, "content"), t("}") }),
    S({ trig = "\\WildStrawberry", dscr = "{content}" }, { t("\\WildStrawberry{"), i(1, "content"), t("}") }),
    S({ trig = "\\Salmon", dscr = "{content}" }, { t("\\Salmon{"), i(1, "content"), t("}") }),
    S({ trig = "\\CarnationPink", dscr = "{content}" }, { t("\\CarnationPink{"), i(1, "content"), t("}") }),
    S({ trig = "\\Magenta", dscr = "{content}" }, { t("\\Magenta{"), i(1, "content"), t("}") }),
    S({ trig = "\\VioletRed", dscr = "{content}" }, { t("\\VioletRed{"), i(1, "content"), t("}") }),
    S({ trig = "\\Rhodamine", dscr = "{content}" }, { t("\\Rhodamine{"), i(1, "content"), t("}") }),
    S({ trig = "\\Mulberry", dscr = "{content}" }, { t("\\Mulberry{"), i(1, "content"), t("}") }),
    S({ trig = "\\RedViolet", dscr = "{content}" }, { t("\\RedViolet{"), i(1, "content"), t("}") }),
    S({ trig = "\\Fuchsia", dscr = "{content}" }, { t("\\Fuchsia{"), i(1, "content"), t("}") }),
    S({ trig = "\\Lavender", dscr = "{content}" }, { t("\\Lavender{"), i(1, "content"), t("}") }),
    S({ trig = "\\Thistle", dscr = "{content}" }, { t("\\Thistle{"), i(1, "content"), t("}") }),
    S({ trig = "\\Orchid", dscr = "{content}" }, { t("\\Orchid{"), i(1, "content"), t("}") }),
    S({ trig = "\\DarkOrchid", dscr = "{content}" }, { t("\\DarkOrchid{"), i(1, "content"), t("}") }),
    S({ trig = "\\Purple", dscr = "{content}" }, { t("\\Purple{"), i(1, "content"), t("}") }),
    S({ trig = "\\Plum", dscr = "{content}" }, { t("\\Plum{"), i(1, "content"), t("}") }),
    S({ trig = "\\Violet", dscr = "{content}" }, { t("\\Violet{"), i(1, "content"), t("}") }),
    S({ trig = "\\RoyalPurple", dscr = "{content}" }, { t("\\RoyalPurple{"), i(1, "content"), t("}") }),
    S({ trig = "\\BlueViolet", dscr = "{content}" }, { t("\\BlueViolet{"), i(1, "content"), t("}") }),
    S({ trig = "\\Periwinkle", dscr = "{content}" }, { t("\\Periwinkle{"), i(1, "content"), t("}") }),
    S({ trig = "\\CadetBlue", dscr = "{content}" }, { t("\\CadetBlue{"), i(1, "content"), t("}") }),
    S({ trig = "\\CornflowerBlue", dscr = "{content}" }, { t("\\CornflowerBlue{"), i(1, "content"), t("}") }),
    S({ trig = "\\MidnightBlue", dscr = "{content}" }, { t("\\MidnightBlue{"), i(1, "content"), t("}") }),
    S({ trig = "\\NavyBlue", dscr = "{content}" }, { t("\\NavyBlue{"), i(1, "content"), t("}") }),
    S({ trig = "\\RoyalBlue", dscr = "{content}" }, { t("\\RoyalBlue{"), i(1, "content"), t("}") }),
    S({ trig = "\\Blue", dscr = "{content}" }, { t("\\Blue{"), i(1, "content"), t("}") }),
    S({ trig = "\\Cerulean", dscr = "{content}" }, { t("\\Cerulean{"), i(1, "content"), t("}") }),
    S({ trig = "\\Cyan", dscr = "{content}" }, { t("\\Cyan{"), i(1, "content"), t("}") }),
    S({ trig = "\\ProcessBlue", dscr = "{content}" }, { t("\\ProcessBlue{"), i(1, "content"), t("}") }),
    S({ trig = "\\SkyBlue", dscr = "{content}" }, { t("\\SkyBlue{"), i(1, "content"), t("}") }),
    S({ trig = "\\Turquoise", dscr = "{content}" }, { t("\\Turquoise{"), i(1, "content"), t("}") }),
    S({ trig = "\\TealBlue", dscr = "{content}" }, { t("\\TealBlue{"), i(1, "content"), t("}") }),
    S({ trig = "\\Aquamarine", dscr = "{content}" }, { t("\\Aquamarine{"), i(1, "content"), t("}") }),
    S({ trig = "\\BlueGreen", dscr = "{content}" }, { t("\\BlueGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\Emerald", dscr = "{content}" }, { t("\\Emerald{"), i(1, "content"), t("}") }),
    S({ trig = "\\JungleGreen", dscr = "{content}" }, { t("\\JungleGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\SeaGreen", dscr = "{content}" }, { t("\\SeaGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\Green", dscr = "{content}" }, { t("\\Green{"), i(1, "content"), t("}") }),
    S({ trig = "\\ForestGreen", dscr = "{content}" }, { t("\\ForestGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\PineGreen", dscr = "{content}" }, { t("\\PineGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\LimeGreen", dscr = "{content}" }, { t("\\LimeGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\YellowGreen", dscr = "{content}" }, { t("\\YellowGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\SpringGreen", dscr = "{content}" }, { t("\\SpringGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\OliveGreen", dscr = "{content}" }, { t("\\OliveGreen{"), i(1, "content"), t("}") }),
    S({ trig = "\\RawSienna", dscr = "{content}" }, { t("\\RawSienna{"), i(1, "content"), t("}") }),
    S({ trig = "\\Sepia", dscr = "{content}" }, { t("\\Sepia{"), i(1, "content"), t("}") }),
    S({ trig = "\\Brown", dscr = "{content}" }, { t("\\Brown{"), i(1, "content"), t("}") }),
    S({ trig = "\\Tan", dscr = "{content}" }, { t("\\Tan{"), i(1, "content"), t("}") }),
    S({ trig = "\\Gray", dscr = "{content}" }, { t("\\Gray{"), i(1, "content"), t("}") }),
    S({ trig = "\\Black", dscr = "{content}" }, { t("\\Black{"), i(1, "content"), t("}") }),
    S({ trig = "\\White", dscr = "{content}" }, { t("\\White{"), i(1, "content"), t("}") }),
  },
  keyvals = {},
}
