-- Generated by snipgen 1 from CoverPage.cwl; do not edit, regenerate.
-- source: TeXstudio completion/CoverPage.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c2d327bacf5b903a87328bb14e77337aa33311eb54185d640e0ffa53b72cddd3
-- cwl-header:
--   # CoverPage package
--   # Matthew Bertucci 4/11/2022 for v1.01
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "CoverPage",
  includes = { "keyval", "url", "verbatim" },
  lists = {},
  snippets = {
    S({ trig = "\\CoverPageSetup", dscr = "{options}" }, { t("\\CoverPageSetup{"), i(1, "options"), t("}") }),
    S({ trig = "\\BibTeX", dscr = "" }, { t("\\BibTeX") }),
    S({ trig = "\\CPTitleFont", dscr = "∗", priority = 900 }, { t("\\CPTitleFont") }, "*"),
    S({ trig = "\\CPAuthorFont", dscr = "∗", priority = 900 }, { t("\\CPAuthorFont") }, "*"),
    S({ trig = "\\CPInstituteFont", dscr = "∗", priority = 900 }, { t("\\CPInstituteFont") }, "*"),
    S({ trig = "\\CPInSourceFont", dscr = "∗", priority = 900 }, { t("\\CPInSourceFont") }, "*"),
    S({ trig = "\\CPCopyrightFont", dscr = "∗", priority = 900 }, { t("\\CPCopyrightFont") }, "*"),
    S({ trig = "\\CoverPageHeader", dscr = "∗", priority = 900 }, { t("\\CoverPageHeader") }, "*"),
    S({ trig = "\\CoverPageBody", dscr = "∗", priority = 900 }, { t("\\CoverPageBody") }, "*"),
    S({ trig = "\\CoverPageFooter", dscr = "∗", priority = 900 }, { t("\\CoverPageFooter") }, "*"),
    S({ trig = "\\CoverPageFooterLogo", dscr = "∗", priority = 900 }, { t("\\CoverPageFooterLogo") }, "*"),
    S({ trig = "\\CPProcessBibEntry", dscr = "∗", priority = 900 }, { t("\\CPProcessBibEntry") }, "*"),
    S({ trig = "\\CPPublisherCheck", dscr = "∗", priority = 900 }, { t("\\CPPublisherCheck") }, "*"),
    S({ trig = "\\CoverPageFooterInfo", dscr = "∗", priority = 900 }, { t("\\CoverPageFooterInfo") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/CoverPage#c",
      lines = {
        "german",
        "english",
        "twoside",
        "nobib",
      },
    },
    {
      targets = "\\CoverPageSetup",
      lines = {
        "title=%<text%>",
        "author=%<text%>",
        "institute=%<text%>",
        "insource=%<text%>",
        "copyright=%<text%>",
        "year=%<year%>",
        "publisher=#Springer,Kluwer,SPIE,IEEE",
        "booktitle=%<text%>",
        "journal=%<text%>",
      },
    },
  },
}
