-- Generated by snipgen 1 from ctable.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ctable.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 863b1034fb0b0a6935671399eb670404ccd9f5f0f3b9b67ff5d3e643dd64dd46
-- cwl-header:
--   # ctable package
--   # Matthew Bertucci 10/1/2021 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ctable",
  includes = { "ifpdf", "etoolbox", "xcolor", "array", "tabularx", "booktabs", "rotating", "transparent" },
  lists = {},
  snippets = {
    S({ trig = "\\setupctable", dscr = "{options}" }, { t("\\setupctable{"), i(1, "options"), t("}") }),
    S({ trig = "\\ctable", dscr = "{preamble}{tnote cmds}{table}" }, { t("\\ctable{"), i(1, "preamble"), t("}{"), i(2, "tnote cmds"), t("}{"), i(3, "table"), t("}") }),
    S({ trig = "\\ctable", dscr = "[options]{preamble}{tnote cmds}{table}" }, { t("\\ctable["), i(1, "options"), t("]{"), i(2, "preamble"), t("}{"), i(3, "tnote cmds"), t("}{"), i(4, "table"), t("}") }),
    S({ trig = "\\tnote", dscr = "{footnote text}" }, { t("\\tnote{"), i(1, "footnote text"), t("}") }),
    S({ trig = "\\tnote", dscr = "[label]{footnote text}" }, { t("\\tnote["), i(1, "label"), t("]{"), i(2, "footnote text"), t("}") }),
    S({ trig = "\\tmark", dscr = "" }, { t("\\tmark") }),
    S({ trig = "\\tmark", dscr = "[label]" }, { t("\\tmark["), i(1, "label"), t("]") }),
    S({ trig = "\\NN", dscr = "" }, { t("\\NN") }),
    S({ trig = "\\FL", dscr = "" }, { t("\\FL") }),
    S({ trig = "\\ML", dscr = "" }, { t("\\ML") }),
    S({ trig = "\\LL", dscr = "" }, { t("\\LL") }),
  },
  keyvals = {
    {
      targets = "\\setupctable,\\ctable",
      lines = {
        "bgopacity=",
        "botcap",
        "captionskip=##L",
        "center",
        "continued",
        "continued=",
        "doinside=%<code%>",
        "figure",
        "footerwidth=##L",
        "framebg=%<r g b%>",
        "framefg=%<r g b%>",
        "framerule=##L",
        "framesep=##L",
        "left",
        "maxwidth=##L",
        "mincapwidth=##L",
        "nonotespar",
        "nosideways",
        "nostar",
        "nosuper",
        "notespar",
        "pos=",
        "right",
        "sidecap",
        "sideways",
        "star",
        "super",
        "table",
        "topcap",
        "width=##L",
      },
    },
    {
      targets = "\\setupctable",
      lines = {
        "captionsleft",
        "captionsright",
        "captionsinside",
      },
    },
    {
      targets = "\\ctable",
      lines = {
        "caption=%<text%>",
        "cap=%<short caption text%>",
        "label=##l",
      },
    },
  },
}
