-- Generated by snipgen 1 from cursor.cwl; do not edit, regenerate.
-- source: TeXstudio completion/cursor.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 6ea197438c5606d6eaf700453abfd395d973dc986099aac12c2978537b2f5c4e
-- cwl-header:
--   # cursor package
--   # Matthew Bertucci 10/17/2021 for v1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "cursor",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\cursorformula", dscr = "{formula}" }, { t("\\cursorformula{"), i(1, "formula"), t("}") }),
    S({ trig = "\\Lc", dscr = "{arg}" }, { t("\\Lc{"), i(1, "arg"), t("}") }),
    S({ trig = "\\Rc", dscr = "{arg}" }, { t("\\Rc{"), i(1, "arg"), t("}") }),
    S({ trig = "\\LRc", dscr = "{arg1}{arg2}" }, { t("\\LRc{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }),
    S({ trig = "\\cursorheight", dscr = "{arg} ∗", priority = 900 }, { t("\\cursorheight{"), i(1, "arg"), t("}") }, "*"),
    S({ trig = "\\ruled", dscr = "∗", priority = 900 }, { t("\\ruled") }, "*"),
    S({ trig = "\\ruleh", dscr = "∗", priority = 900 }, { t("\\ruleh") }, "*"),
    S({ trig = "\\rulew", dscr = "∗", priority = 900 }, { t("\\rulew") }, "*"),
    S({ trig = "\\rulewr", dscr = "∗", priority = 900 }, { t("\\rulewr") }, "*"),
    S({ trig = "\\rulewl", dscr = "∗", priority = 900 }, { t("\\rulewl") }, "*"),
    S({ trig = "\\cursorlinew", dscr = "∗", priority = 900 }, { t("\\cursorlinew") }, "*"),
  },
  keyvals = {},
}
