-- Generated by snipgen 1 from dashundergaps.cwl; do not edit, regenerate.
-- source: TeXstudio completion/dashundergaps.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f9b4bcd2a0ea2ad8f129f1adefa62b0c70a21273c415972e5f36874d34957f68
-- cwl-header:
--   # dashundergaps package
--   # Matthew Bertucci 9/11/2021 for v2.0h
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "dashundergaps",
  includes = { "l3keys2e", "ulem", "underscore" },
  lists = {},
  snippets = {
    S({ trig = "\\gap", dscr = "{text}" }, { t("\\gap{"), i(1, "text"), t("}") }),
    S({ trig = "\\gap", dscr = "[style]{text}" }, { t("\\gap["), i(1, "style"), t("]{"), i(2, "text"), t("}") }),
    S({ trig = "\\gap*", dscr = "{text}" }, { t("\\gap*{"), i(1, "text"), t("}") }),
    S({ trig = "\\gap*", dscr = "[style]{text}" }, { t("\\gap*["), i(1, "style"), t("]{"), i(2, "text"), t("}") }),
    S({ trig = "\\TeacherModeOn", dscr = "∗", priority = 900 }, { t("\\TeacherModeOn") }, "*"),
    S({ trig = "\\TeacherModeOff", dscr = "∗", priority = 900 }, { t("\\TeacherModeOff") }, "*"),
    S({ trig = "\\dashundergapssetup", dscr = "{options}" }, { t("\\dashundergapssetup{"), i(1, "options"), t("}") }),
    S({ trig = "\\thegapnumber", dscr = "∗", priority = 900 }, { t("\\thegapnumber") }, "*"),
    S({ trig = "\\thetotalgapnumber", dscr = "∗", priority = 900 }, { t("\\thetotalgapnumber") }, "*"),
  },
  keyvals = {
    {
      targets = "\\gap,\\gap*",
      lines = {
        "u",
        "d",
        "w",
        "b",
        "-",
        ".",
      },
    },
    {
      targets = "\\dashundergapssetup",
      lines = {
        "teacher-mode#true,false",
        "gap-mode#true,false",
        "teachermode#true,false",
        "gap-format=#underline,double-underline,dash,dot,wave,blank",
        "gap-format-adjust#true,false",
        "teacher-gap-format=#underline,double-underline,dash,dot,wave,blank",
        "gap-font=",
        "dash",
        "dot",
        "gap-numbers#true,false",
        "gap-number-format=",
        "numbers#true,false",
        "display-total-gaps#true,false",
        "displaynbgaps#true,false",
        "gap-widen#true,false",
        "gap-extend-minimum=##L",
        "gap-extend-percent=",
        "widen#true,false",
      },
    },
  },
}
