-- Generated by snipgen 1 from decision-table.cwl; do not edit, regenerate.
-- source: TeXstudio completion/decision-table.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9bfec835943f8f101c016dfb307e52c5c1ada6eb926a8b46b361146981abe68f
-- cwl-header:
--   # decision-table package
--   # Matthew Bertucci 10/4/2021 for v0.0.4
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "decision-table",
  includes = { "nicematrix", "l3keys2e" },
  lists = {},
  snippets = {
    S({ trig = "\\dmntable", dscr = "{title}{hit policy}{input}{output}{entries}" }, { t("\\dmntable{"), i(1, "title"), t("}{"), i(2, "hit policy"), t("}{"), i(3, "input"), t("}{"), i(4, "output"), t("}{"), i(5, "entries"), t("}") }),
    S({ trig = "\\dmnoutputtable", dscr = "{title}{hit policy}{output}{entries}" }, { t("\\dmnoutputtable{"), i(1, "title"), t("}{"), i(2, "hit policy"), t("}{"), i(3, "output"), t("}{"), i(4, "entries"), t("}") }),
    S({ trig = "\\glossarytable", dscr = "{title}{subtitles}{entries}" }, { t("\\glossarytable{"), i(1, "title"), t("}{"), i(2, "subtitles"), t("}{"), i(3, "entries"), t("}") }),
    S({ trig = "\\goaltable", dscr = "{title}{entries}" }, { t("\\goaltable{"), i(1, "title"), t("}{"), i(2, "entries"), t("}") }),
    S({ trig = "\\pdmntable", dscr = "{title}{hit policy}{inputs}{outputs}{output vals}{entries}" }, { t("\\pdmntable{"), i(1, "title"), t("}{"), i(2, "hit policy"), t("}{"), i(3, "inputs"), t("}{"), i(4, "outputs"), t("}{"), i(5, "output vals"), t("}{"), i(6, "entries"), t("}") }),
    S({ trig = "\\pdmnoutputtable", dscr = "{title}{hit policy}{output}{output val}{probabilities}" }, { t("\\pdmnoutputtable{"), i(1, "title"), t("}{"), i(2, "hit policy"), t("}{"), i(3, "output"), t("}{"), i(4, "output val"), t("}{"), i(5, "probabilities"), t("}") }),
  },
  keyvals = {},
}
