-- Generated by snipgen 1 from dhucs-setspace.cwl; do not edit, regenerate.
-- source: TeXstudio completion/dhucs-setspace.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: e4c92c619bd7b19d9aa7d94575aebfe06c0126cc4ab5bb188c80972d362827e1
-- cwl-header:
--   # dhucs-setspace package
--   # Matthew Bertucci 2022/05/04 for v0.11
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "dhucs-setspace",
  includes = { "setspace" },
  lists = {},
  snippets = {
    S({ trig = "\\SetHangulspace", dscr = "{factor1}{factor2}" }, { t("\\SetHangulspace{"), i(1, "factor1"), t("}{"), i(2, "factor2"), t("}") }),
    S({ trig = "\\SetHangulVerbatimSpace", dscr = "{factor}" }, { t("\\SetHangulVerbatimSpace{"), i(1, "factor"), t("}") }),
    S({ trig = "\\hangulspacing", dscr = "" }, { t("\\hangulspacing") }),
    S({ trig = "\\hangulfspacing", dscr = "" }, { t("\\hangulfspacing") }),
    S({ trig = "\\hangulverbspacing", dscr = "" }, { t("\\hangulverbspacing") }),
    S({ trig = "\\ucsfninterwordhook", dscr = "∗", priority = 900 }, { t("\\ucsfninterwordhook") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/dhucs-setspace#c",
      lines = {
        "nofloatspacing",
        "noquotespacing",
        "hangul",
        "adjustfootnotesep",
        "adjustverbatim",
        "nodisplayskipstretch",
        "singlespacing",
        "onehalfspacing",
        "doublespacing",
      },
    },
  },
}
