-- Generated by snipgen 1 from droidserif.cwl; do not edit, regenerate.
-- source: TeXstudio completion/droidserif.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 6e7752feb47bfeb937c4d3747c11962fe6cf8a6f16d2fe1613c1001e44570f7f
-- cwl-header:
--   # droidserif package
--   # Matthew Bertucci 7/27/2021
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "droidserif",
  includes = { "ifluatex", "ifxetex", "xkeyval" },
  lists = {},
  snippets = {
    S({ trig = "\\droidserif", dscr = "" }, { t("\\droidserif") }),
    S({ trig = "\\droidseriffamily", dscr = "∗", priority = 900 }, { t("\\droidseriffamily") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/droidserif#c",
      lines = {
        "scale=%<factor%>",
        "scaled=%<factor%>",
        "default",
        "type1",
      },
    },
  },
}
