-- Generated by snipgen 1 from dspblocks.cwl; do not edit, regenerate.
-- source: TeXstudio completion/dspblocks.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 2bc76f2e711ddcd3bb0cf1a3f483330c2b77f382f5407646bb642f77cbb43a73
-- cwl-header:
--   # dspblocks package
--   # Matthew Bertucci 2023/11/10 for v1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "dspblocks",
  includes = { "calc", "fp", "pst-xkey", "fmtcount", "ifthen" },
  lists = {},
  snippets = {
    S({ trig = "\\dspBlocks", dscr = "\\begin{dspBlocks}{x}{y}" }, { t("\\begin{dspBlocks}{"), i(1, "x"), t("}{"), i(2, "y"), t({ "}", "\t" }), i(3), t({ "", "\\end{dspBlocks}" }) }, "\\array"),
    S({ trig = "\\BDConnHNext", dscr = "{n}{m}" }, { t("\\BDConnHNext{"), i(1, "n"), t("}{"), i(2, "m"), t("}") }),
    S({ trig = "\\BDConnH", dscr = "{n}{m}{p}{label text}" }, { t("\\BDConnH{"), i(1, "n"), t("}{"), i(2, "m"), t("}{"), i(3, "p"), t("}{"), i(4, "label text"), t("}") }),
    S({ trig = "\\BDConnH", dscr = "[options]{n}{m}{p}{label text}" }, { t("\\BDConnH["), i(1, "options"), t("]{"), i(2, "n"), t("}{"), i(3, "m"), t("}{"), i(4, "p"), t("}{"), i(5, "label text"), t("}") }),
    S({ trig = "\\BDConnV", dscr = "{n}{m}{q}{label text}" }, { t("\\BDConnV{"), i(1, "n"), t("}{"), i(2, "m"), t("}{"), i(3, "q"), t("}{"), i(4, "label text"), t("}") }),
    S({ trig = "\\BDConnV", dscr = "[options]{n}{m}{q}{label text}" }, { t("\\BDConnV["), i(1, "options"), t("]{"), i(2, "n"), t("}{"), i(3, "m"), t("}{"), i(4, "q"), t("}{"), i(5, "label text"), t("}") }),
    S({ trig = "\\BDsplit", dscr = "" }, { t("\\BDsplit") }),
    S({ trig = "\\BDadd", dscr = "" }, { t("\\BDadd") }),
    S({ trig = "\\BDsub", dscr = "" }, { t("\\BDsub") }),
    S({ trig = "\\BDmul", dscr = "" }, { t("\\BDmul") }),
    S({ trig = "\\BDdelay", dscr = "" }, { t("\\BDdelay") }),
    S({ trig = "\\BDdelayN", dscr = "{N}" }, { t("\\BDdelayN{"), i(1, "N"), t("}") }),
    S({ trig = "\\BDfilter", dscr = "{label text}" }, { t("\\BDfilter{"), i(1, "label text"), t("}") }),
    S({ trig = "\\BDfilterMulti", dscr = "{label text}" }, { t("\\BDfilterMulti{"), i(1, "label text"), t("}") }),
    S({ trig = "\\BDlowpass", dscr = "" }, { t("\\BDlowpass") }),
    S({ trig = "\\BDlowpass", dscr = "[size]" }, { t("\\BDlowpass["), i(1, "size"), t("]") }),
    S({ trig = "\\BDsampler", dscr = "" }, { t("\\BDsampler") }),
    S({ trig = "\\BDsamplerFramed", dscr = "" }, { t("\\BDsamplerFramed") }),
    S({ trig = "\\BDsamplerFramed", dscr = "[size]" }, { t("\\BDsamplerFramed["), i(1, "size"), t("]") }),
    S({ trig = "\\BDsinc", dscr = "" }, { t("\\BDsinc") }),
    S({ trig = "\\BDsinc", dscr = "[size]" }, { t("\\BDsinc["), i(1, "size"), t("]") }),
    S({ trig = "\\BDupsmp", dscr = "{N}" }, { t("\\BDupsmp{"), i(1, "N"), t("}") }),
    S({ trig = "\\BDdwsmp", dscr = "{N}" }, { t("\\BDdwsmp{"), i(1, "N"), t("}") }),
    S({ trig = "\\BDwidth", dscr = "" }, { t("\\BDwidth") }, "L"),
    S({ trig = "\\BDclip", dscr = "∗", priority = 900 }, { t("\\BDclip") }, "*"),
    S({ trig = "\\BDclip", dscr = "[length] ∗", priority = 900 }, { t("\\BDclip["), i(1, "length"), t("]") }, "*"),
  },
  keyvals = {},
}
