-- Generated by snipgen 1 from easylist.cwl; do not edit, regenerate.
-- source: TeXstudio completion/easylist.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 5b689616fc74bd94b45b9d09794676a468b0bb8206735f8029ff15a6457e7b0e
-- cwl-header:
--   # easylist package
--   # Matthew Bertucci 11/6/2021 for v1.4
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "easylist",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\easylist", dscr = "\\begin{easylist}" }, { t({ "\\begin{easylist}", "\t" }), i(1), t({ "", "\\end{easylist}" }) }),
    S({ trig = "\\easylist", dscr = "\\begin{easylist}[style]" }, { t("\\begin{easylist}["), i(1, "style"), t({ "]", "\t" }), i(2), t({ "", "\\end{easylist}" }) }),
    S({ trig = "\\ListProperties", dscr = "(options)" }, { t("\\ListProperties("), i(1, "options"), t(")") }),
    S({ trig = "\\NewList", dscr = "(options)" }, { t("\\NewList("), i(1, "options"), t(")") }),
    S({ trig = "\\ifPilcrow", dscr = "∗", priority = 900 }, { t("\\ifPilcrow") }, "*"),
    S({ trig = "\\Pilcrowtrue", dscr = "∗", priority = 900 }, { t("\\Pilcrowtrue") }, "*"),
    S({ trig = "\\Pilcrowfalse", dscr = "∗", priority = 900 }, { t("\\Pilcrowfalse") }, "*"),
    S({ trig = "\\ifAt", dscr = "∗", priority = 900 }, { t("\\ifAt") }, "*"),
    S({ trig = "\\Attrue", dscr = "∗", priority = 900 }, { t("\\Attrue") }, "*"),
    S({ trig = "\\Atfalse", dscr = "∗", priority = 900 }, { t("\\Atfalse") }, "*"),
    S({ trig = "\\ifSharp", dscr = "∗", priority = 900 }, { t("\\ifSharp") }, "*"),
    S({ trig = "\\Sharptrue", dscr = "∗", priority = 900 }, { t("\\Sharptrue") }, "*"),
    S({ trig = "\\Sharpfalse", dscr = "∗", priority = 900 }, { t("\\Sharpfalse") }, "*"),
    S({ trig = "\\ifAmpersand", dscr = "∗", priority = 900 }, { t("\\ifAmpersand") }, "*"),
    S({ trig = "\\Ampersandtrue", dscr = "∗", priority = 900 }, { t("\\Ampersandtrue") }, "*"),
    S({ trig = "\\Ampersandfalse", dscr = "∗", priority = 900 }, { t("\\Ampersandfalse") }, "*"),
    S({ trig = "\\ifDubiousFigure", dscr = "∗", priority = 900 }, { t("\\ifDubiousFigure") }, "*"),
    S({ trig = "\\DubiousFiguretrue", dscr = "∗", priority = 900 }, { t("\\DubiousFiguretrue") }, "*"),
    S({ trig = "\\DubiousFigurefalse", dscr = "∗", priority = 900 }, { t("\\DubiousFigurefalse") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/easylist#c",
      lines = {
        "pilcrow",
        "at",
        "sharp",
        "ampersand",
        "%<number of counters%>",
      },
    },
    {
      targets = "\\begin{easylist}#c",
      lines = {
        "tractatus",
        "checklist",
        "booktoc",
        "articletoc",
        "enumerate",
        "itemize",
      },
    },
    {
      targets = "\\ListProperties#c,\\NewList#c",
      lines = {
        "Start%<n%>=%<number%>",
        "Start%<n%>*=%<counter%>",
        "Mark=%<punctuation%>",
        "Mark%<n%>=%<punctuation%>",
        "FinalMark=%<punctuation%>",
        "FinalMark%<n%>=%<punctuation%>",
        "Numbers=#r,R,l,L,z,a",
        "Numbers%<n%>=#r,R,l,L,z,a",
        "Hide=%<number%>",
        "Hide%<n%>=%<number%>",
        "Style=%<format%>",
        "Style%<n%>=%<format%>",
        "Style*=%<format%>",
        "Style%<n%>*=%<format%>",
        "Style**=%<format%>",
        "Style%<n%>**=%<format%>",
        "CtrCom=%<command%>",
        "CtrCom%<n%>=%<command%>",
        "Hang#true,false",
        "Hang%<n%>#true,false",
        "Align=%<move, fixed, or <dimen>%>",
        "Align%<n%>=%<move, fixed, or <dimen>%>",
        "Margin=##L",
        "Margin%<n%>=##L",
        "Progressive=##L",
        "Progressive%<n%>=##L",
        "Space=##L",
        "Space%<n%>=##L",
        "Space*=##L",
        "Space%<n%>*=##L",
        "Indent=##L",
        "Indent%<n%>=##L",
        "FinalSpace=##L",
        "FinalSpace%<n%>=##L",
      },
    },
  },
}
