-- Generated by snipgen 1 from econlipsum.cwl; do not edit, regenerate.
-- source: TeXstudio completion/econlipsum.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 2b3cb5b2d2d48e47f3dbc470c8aa9260730953ad524fa7a2602899f450a71ba7
-- cwl-header:
--   # econlipsum package
--   # Matthew Bertucci 9/22/2021 for v0.8.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "econlipsum",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\econ", dscr = "" }, { t("\\econ") }),
    S({ trig = "\\econ", dscr = "[num]" }, { t("\\econ["), i(1, "num"), t("]") }),
    S({ trig = "\\econ", dscr = "[num][num]" }, { t("\\econ["), i(1, "num"), t("]["), i(2, "num"), t("]") }),
    S({ trig = "\\econ", dscr = "[num-num]" }, { t("\\econ["), i(1, "num"), t("-"), i(2, "num"), t("]") }),
    S({ trig = "\\econ", dscr = "[num-num][num-num]" }, { t("\\econ["), i(1, "num"), t("-"), i(2, "num"), t("]["), i(3, "num"), t("-"), i(4, "num"), t("]") }),
    S({ trig = "\\econ*", dscr = "" }, { t("\\econ*") }),
    S({ trig = "\\econ*", dscr = "[num]" }, { t("\\econ*["), i(1, "num"), t("]") }),
    S({ trig = "\\econ*", dscr = "[num-num]" }, { t("\\econ*["), i(1, "num"), t("-"), i(2, "num"), t("]") }),
    S({ trig = "\\econ*", dscr = "[num-num][num-num]" }, { t("\\econ*["), i(1, "num"), t("-"), i(2, "num"), t("]["), i(3, "num"), t("-"), i(4, "num"), t("]") }),
    S({ trig = "\\econdef", dscr = "{cmd}{num} ∗", priority = 900 }, { t("\\econdef{"), i(1, "cmd"), t("}{"), i(2, "num"), t("}") }, "*d"),
  },
  keyvals = {
    {
      targets = "\\usepackage/econlipsum#c",
      lines = {
        "par",
        "nopar",
        "numbers",
        "index",
      },
    },
  },
}
