-- Generated by snipgen 1 from efbox.cwl; do not edit, regenerate.
-- source: TeXstudio completion/efbox.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 08d3f45394edd1bba50da8a64a161492e68c952ef7c815227049d3481b7993dc
-- cwl-header:
--   # efbox package
--   # Matthew Bertucci 9/9/2021 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "efbox",
  includes = { "color", "pgfkeys" },
  lists = {},
  snippets = {
    S({ trig = "\\efbox", dscr = "{text}" }, { t("\\efbox{"), i(1, "text"), t("}") }),
    S({ trig = "\\efbox", dscr = "[options]{text}" }, { t("\\efbox["), i(1, "options"), t("]{"), i(2, "text"), t("}") }),
    S({ trig = "\\efboxsetup", dscr = "{options}" }, { t("\\efboxsetup{"), i(1, "options"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\efbox,\\efboxsetup",
      lines = {
        "leftline#true,false",
        "rightline#true,false",
        "topline#true,false",
        "bottomline#true,false",
        "hidealllines#true,false",
        "backgroundcolor=#%color",
        "linecolor=#%color",
        "linewidth=##L",
        "margin=##L",
        "font=",
        "baselinestretch=",
      },
    },
  },
}
