-- Generated by snipgen 1 from embedall.cwl; do not edit, regenerate.
-- source: TeXstudio completion/embedall.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: e03f256cad0712791c53ef037159b6fd89672cec4121d23abad907f9ae65db0a
-- cwl-header:
--   # embedall package
--   # Matthew Bertucci 11/10/2021 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "embedall",
  includes = { "embedfile", "filehook", "currfile", "etoolbox" },
  lists = {},
  snippets = {
    S({ trig = "\\embedsource", dscr = "" }, { t("\\embedsource") }),
    S({ trig = "\\embedsource", dscr = "[options]" }, { t("\\embedsource["), i(1, "options"), t("]") }),
    S({ trig = "\\embedinput", dscr = "{file} ∗", priority = 900 }, { t("\\embedinput{"), i(1, "file"), t("}") }, "*i"),
    S({ trig = "\\embedinput", dscr = "[options]{file} ∗", priority = 900 }, { t("\\embedinput["), i(1, "options"), t("]{"), i(2, "file"), t("}") }, "*i"),
  },
  keyvals = {
    {
      targets = "\\usepackage/embedall#c",
      lines = {
        "all",
        "notall",
        "main",
        "input",
        "include",
        "graphicx",
        "csvsimple",
        "compat",
      },
    },
    {
      targets = "\\embedsource#c,\\embedinput#c",
      lines = {
        "filespec=",
        "ucfilespec=",
        "filesystem=",
        "mimetype=",
        "desc=%<description%>",
        "afrelationship=%<PDF name%>",
        "stringmethod=#psd,escape",
        "id=",
      },
    },
  },
}
