-- Generated by snipgen 1 from enumitem.cwl; do not edit, regenerate.
-- source: TeXstudio completion/enumitem.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: fae6f6813398b9e13d4bf9e01619bd9c7db4513c6db145aeddf714ddda21fbad
-- cwl-header:
--   # thatlittleboy/2018-11-25 for enumitem v3.5.2
--   # muzimuzhi/15 Sep 2020 for enumitem v3.9
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "enumitem",
  includes = {},
  lists = { "description", "enumerate", "itemize" },
  snippets = {
    S({ trig = "\\enumerate", dscr = "\\begin{enumerate}[options]" }, { t("\\begin{enumerate}["), i(1, "options"), t({ "]", "\t\\item " }), i(2), t({ "", "\\end{enumerate}" }) }),
    S({ trig = "\\itemize", dscr = "\\begin{itemize}[options]" }, { t("\\begin{itemize}["), i(1, "options"), t({ "]", "\t\\item " }), i(2), t({ "", "\\end{itemize}" }) }),
    S({ trig = "\\description", dscr = "\\begin{description}[options]" }, { t("\\begin{description}["), i(1, "options"), t({ "]", "\t\\item " }), i(2), t({ "", "\\end{description}" }) }),
    S({ trig = "\\newlist", dscr = "{name}{type}{max-depth}" }, { t("\\newlist{"), i(1, "name"), t("}{"), i(2, "type"), t("}{"), i(3, "max-depth"), t("}") }, "N"),
    S({ trig = "\\renewlist", dscr = "{name}{type}{max-depth}" }, { t("\\renewlist{"), i(1, "name"), t("}{"), i(2, "type"), t("}{"), i(3, "max-depth"), t("}") }),
    S({ trig = "\\setlist", dscr = "{options}" }, { t("\\setlist{"), i(1, "options"), t("}") }),
    S({ trig = "\\setlist*", dscr = "{options}" }, { t("\\setlist*{"), i(1, "options"), t("}") }),
    S({ trig = "\\setlist", dscr = "[names, levels]{options}" }, { t("\\setlist["), i(1, "names"), t(", "), i(2, "levels"), t("]{"), i(3, "options"), t("}") }),
    S({ trig = "\\setlist*", dscr = "[names, levels]{options}" }, { t("\\setlist*["), i(1, "names"), t(", "), i(2, "levels"), t("]{"), i(3, "options"), t("}") }),
    S({ trig = "\\restartlist", dscr = "{list name}" }, { t("\\restartlist{"), i(1, "list name"), t("}") }),
    S({ trig = "\\EnumitemId", dscr = "∗", priority = 900 }, { t("\\EnumitemId") }, "*"),
    S({ trig = "\\SetLabelAlign", dscr = "{value}{commands} ∗", priority = 900 }, { t("\\SetLabelAlign{"), i(1, "value"), t("}{"), i(2, "commands"), t("}") }, "*"),
    S({ trig = "\\labelindent", dscr = "∗", priority = 900 }, { t("\\labelindent") }, "*"),
    S({ trig = "\\SetEnumerateShortLabel", dscr = "{key}{replacement} ∗", priority = 900 }, { t("\\SetEnumerateShortLabel{"), i(1, "key"), t("}{"), i(2, "replacement"), t("}") }, "*"),
    S({ trig = "\\setlistdepth", dscr = "{integer}" }, { t("\\setlistdepth{"), i(1, "integer"), t("}") }),
    S({ trig = "\\AddEnumerateCounter", dscr = "{LaTeX-cmd}{internal-cmd}{widest label} ∗", priority = 900 }, { t("\\AddEnumerateCounter{"), i(1, "LaTeX-cmd"), t("}{"), i(2, "internal-cmd"), t("}{"), i(3, "widest label"), t("}") }, "*"),
    S({ trig = "\\AddEnumerateCounter*", dscr = "{LaTeX-cmd}{internal-cmd}{integer} ∗", priority = 900 }, { t("\\AddEnumerateCounter*{"), i(1, "LaTeX-cmd"), t("}{"), i(2, "internal-cmd"), t("}{"), i(3, "integer"), t("}") }, "*"),
    S({ trig = "\\SetEnumitemKey", dscr = "{key}{replacement options} ∗", priority = 900 }, { t("\\SetEnumitemKey{"), i(1, "key"), t("}{"), i(2, "replacement options"), t("}") }, "*s#%enumitemkey"),
    S({ trig = "\\SetEnumitemValue", dscr = "{key}{string-value}{replacement} ∗", priority = 900 }, { t("\\SetEnumitemValue{"), i(1, "key"), t("}{"), i(2, "string-value"), t("}{"), i(3, "replacement"), t("}") }, "*"),
    S({ trig = "\\SetEnumitemSize", dscr = "{name}{selector} ∗", priority = 900 }, { t("\\SetEnumitemSize{"), i(1, "name"), t("}{"), i(2, "selector"), t("}") }, "*"),
    S({ trig = "\\DrawEnumitemLabel", dscr = "∗", priority = 900 }, { t("\\DrawEnumitemLabel") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/enumitem#c",
      lines = {
        "shortlabels",
        "inline",
        "sizes",
        "ignoredisplayed",
        "includedisplayed",
        "series=override",
        "loadonly",
      },
    },
    {
      targets = "\\newlist#c,\\renewlist#c",
      lines = {
        "enumerate",
        "itemize",
        "description",
        "enumerate*",
        "itemize*",
        "description*",
      },
    },
    {
      targets = "\\setlist,\\setlist*,\\SetEnumitemKey,\\begin{enumerate}#c,\\begin{itemize}#c,\\begin{description}#c,\\begin{enumerate*}#c,\\begin{itemize*}#c,\\begin{description*}#c",
      lines = {
        "topsep=##L",
        "partopsep=##L",
        "parsep=##L",
        "itemsep=##L",
        "leftmargin=##L",
        "rightmargin=##L",
        "listparindent=##L",
        "labelwidth=##L",
        "labelsep=##L",
        "itemindent=##L",
        "label=%<commands%>",
        "label*=%<commands%>",
        "ref=%<commands%>",
        "font=%<commands%>",
        "format=%<commands%>",
        "align=#left,right,parleft",
        "labelindent=##L",
        "left=%<labelindent%>",
        "left=%<labelindent%> .. %<leftmargin%>",
        "widest",
        "widest=%<string%>",
        "widest*=%<integer%>",
        "labelsep*=##L",
        "labelindent*=##L",
        "start=%<integer%>",
        "resume",
        "resume=%<series name%>",
        "resume*",
        "resume*=%<series name%>",
        "series=%<series name%>",
        "beginpenalty=%<integer%>",
        "midpenalty=%<integer%>",
        "endpenalty=%<integer%>",
        "before=%<code%>",
        "before*=%<code%>",
        "after=%<code%>",
        "after*=%<code%>",
        "first=%<code%>",
        "first*=%<code%>",
        "style=#standard,unboxed,nextline,sameline,multiline",
        "noitemsep",
        "nosep",
        "wide",
        "wide=%<parindent%>",
        "itemjoin=%<string%>",
        "itemjoin*=%<string%>",
        "afterlabel=%<string%>",
        "mode=#unboxed,boxed",
        "%enumitemkey",
      },
    },
  },
}
