-- Generated by snipgen 1 from eqname.cwl; do not edit, regenerate.
-- source: TeXstudio completion/eqname.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 85729616461bc5ae1a561a68a7e55a3b6d1efe90f2d32b289427a56994ab962b
-- cwl-header:
--   # eqname package; Matthew Bertucci 2/27/2022
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "eqname",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\eqname", dscr = "{name}" }, { t("\\eqname{"), i(1, "name"), t("}") }),
  },
  keyvals = {},
}
