-- Generated by snipgen 1 from eqnalign.cwl; do not edit, regenerate.
-- source: TeXstudio completion/eqnalign.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 372f5ecdf2e60020f0f3ba7e2074c98714510ca255b888e6bb773d763dac02e3
-- cwl-header:
--   # eqnalign package
--   # Matthew Bertucci for v1.0a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "eqnalign",
  includes = { "amsmath" },
  lists = {},
  snippets = {
  },
  keyvals = {},
}
