-- Generated by snipgen 1 from esrelation.cwl; do not edit, regenerate.
-- source: TeXstudio completion/esrelation.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 5b6ef5c761d0e0b49dc6e4c264339491a5a4435afb0ac0a54a272ed2beb28e24
-- cwl-header:
--   # esrelation package
--   # Matthew Bertucci 8/22/2021 for v1.25
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "esrelation",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\relationrightproject", dscr = "{arg}" }, h.mathwrap({ t("\\relationrightproject{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\relationleftproject", dscr = "{arg}" }, h.mathwrap({ t("\\relationleftproject{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\relationlifting", dscr = "{arg}" }, h.mathwrap({ t("\\relationlifting{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\restrictwand", dscr = "{arg}" }, h.mathwrap({ t("\\restrictwand{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\restrictwandup", dscr = "{arg}" }, h.mathwrap({ t("\\restrictwandup{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\restrictbarb", dscr = "{arg}" }, h.mathwrap({ t("\\restrictbarb{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\restrictbarbup", dscr = "{arg}" }, h.mathwrap({ t("\\restrictbarbup{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\restrictmallet", dscr = "{arg}" }, h.mathwrap({ t("\\restrictmallet{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\restrictmalletup", dscr = "{arg}" }, h.mathwrap({ t("\\restrictmalletup{"), i(1, "arg"), t("}") }), "m"),
  },
  keyvals = {},
}
