-- Generated by snipgen 1 from exaccent.cwl; do not edit, regenerate.
-- source: TeXstudio completion/exaccent.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b6eb866a7d5c5d0ee0d6c73dd0ea4075b0643c41720ed1e4430d1d2f69907b2a
-- cwl-header:
--   # exaccent package
--   # Matthew Bertucci 2022/06/09 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "exaccent",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\upperaccent", dscr = "{slot}{char}" }, { t("\\upperaccent{"), i(1, "slot"), t("}{"), i(2, "char"), t("}") }),
    S({ trig = "\\upperaccent", dscr = "[shift]{slot}{char}" }, { t("\\upperaccent["), i(1, "shift"), t("]{"), i(2, "slot"), t("}{"), i(3, "char"), t("}") }),
    S({ trig = "\\Upperaccent", dscr = "{slot}{char}" }, { t("\\Upperaccent{"), i(1, "slot"), t("}{"), i(2, "char"), t("}") }),
    S({ trig = "\\Upperaccent", dscr = "[shift]{slot}{char}" }, { t("\\Upperaccent["), i(1, "shift"), t("]{"), i(2, "slot"), t("}{"), i(3, "char"), t("}") }),
    S({ trig = "\\loweraccent", dscr = "{slot}{char}" }, { t("\\loweraccent{"), i(1, "slot"), t("}{"), i(2, "char"), t("}") }),
    S({ trig = "\\loweraccent", dscr = "[shift]{slot}{char}" }, { t("\\loweraccent["), i(1, "shift"), t("]{"), i(2, "slot"), t("}{"), i(3, "char"), t("}") }),
    S({ trig = "\\Loweraccent", dscr = "{slot}{char}" }, { t("\\Loweraccent{"), i(1, "slot"), t("}{"), i(2, "char"), t("}") }),
    S({ trig = "\\Loweraccent", dscr = "[shift]{slot}{char}" }, { t("\\Loweraccent["), i(1, "shift"), t("]{"), i(2, "slot"), t("}{"), i(3, "char"), t("}") }),
  },
  keyvals = {},
}
