-- Generated by snipgen 1 from extarrows.cwl; do not edit, regenerate.
-- source: TeXstudio completion/extarrows.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 7eb358e19d155dfbf4df6807d986d6bb5e9cb5aea235c12108243a336aab5cc7
-- cwl-header:
--   # extarrows package
--   # Matthew Bertucci 10/17/2021 for v1.2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "extarrows",
  includes = { "amsmath" },
  lists = {},
  snippets = {
    S({ trig = "\\xlongequal", dscr = "{superscript}" }, h.mathwrap({ t("\\xlongequal{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xlongequal", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xlongequal["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
    S({ trig = "\\xLongleftarrow", dscr = "{superscript}" }, h.mathwrap({ t("\\xLongleftarrow{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xLongleftarrow", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xLongleftarrow["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
    S({ trig = "\\xLongrightarrow", dscr = "{superscript}" }, h.mathwrap({ t("\\xLongrightarrow{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xLongrightarrow", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xLongrightarrow["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
    S({ trig = "\\xLongleftrightarrow", dscr = "{superscript}" }, h.mathwrap({ t("\\xLongleftrightarrow{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xLongleftrightarrow", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xLongleftrightarrow["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
    S({ trig = "\\xLeftrightarrow", dscr = "{superscript}" }, h.mathwrap({ t("\\xLeftrightarrow{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xLeftrightarrow", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xLeftrightarrow["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
    S({ trig = "\\xlongleftrightarrow", dscr = "{superscript}" }, h.mathwrap({ t("\\xlongleftrightarrow{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xlongleftrightarrow", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xlongleftrightarrow["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
    S({ trig = "\\xlongrightarrow", dscr = "{superscript}" }, h.mathwrap({ t("\\xlongrightarrow{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xlongrightarrow", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xlongrightarrow["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
    S({ trig = "\\xleftrightarrow", dscr = "{superscript}" }, h.mathwrap({ t("\\xleftrightarrow{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xleftrightarrow", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xleftrightarrow["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
    S({ trig = "\\xlongleftarrow", dscr = "{superscript}" }, h.mathwrap({ t("\\xlongleftarrow{"), i(1, "superscript"), t("}") }), "m"),
    S({ trig = "\\xlongleftarrow", dscr = "[subscript]{superscript}" }, h.mathwrap({ t("\\xlongleftarrow["), i(1, "subscript"), t("]{"), i(2, "superscript"), t("}") }), "m"),
  },
  keyvals = {},
}
