-- Generated by snipgen 1 from farbe.cwl; do not edit, regenerate.
-- source: TeXstudio completion/farbe.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 0290f10e55ff1ca8d48b06067de039163888cb3a6c95a62988899fbc432e17d8
-- cwl-header:
--   # farbe package
--   # Matthew Bertucci 2025/06/08 for v0.2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "farbe",
  includes = { "luatex" },
  lists = {},
  snippets = {
    S({ trig = "\\FarbeImport", dscr = "{color}" }, { t("\\FarbeImport{"), i(1, "color"), t("}") }),
    S({ trig = "\\FarbeColor", dscr = "{color}" }, { t("\\FarbeColor{"), i(1, "color"), t("}") }),
    S({ trig = "\\FarbeColorEnd", dscr = "" }, { t("\\FarbeColorEnd") }),
    S({ trig = "\\FarbeTextColor", dscr = "{color}{text}" }, { t("\\FarbeTextColor{"), i(1, "color"), t("}{"), i(2, "text"), t("}") }),
    S({ trig = "\\FarbePdfLiteral", dscr = "{arg} ∗", priority = 900 }, { t("\\FarbePdfLiteral{"), i(1, "arg"), t("}") }, "*"),
    S({ trig = "\\FarbeBox", dscr = "{arg} ∗", priority = 900 }, { t("\\FarbeBox{"), i(1, "arg"), t("}") }, "*"),
  },
  keyvals = {},
}
