-- Generated by snipgen 1 from fcprefix.cwl; do not edit, regenerate.
-- source: TeXstudio completion/fcprefix.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 6ee3817e37f6be806faef3b3a067a911c35bb41b542359bf87e896bb5d75735c
-- cwl-header:
--   # fcprefix package
--   # Matthew Bertucci 2022/06/01 for v3.07
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "fcprefix",
  includes = { "ifthen", "keyval", "fcnumparser" },
  lists = {},
  snippets = {
    S({ trig = "\\latinnumeralstring", dscr = "{counter}" }, { t("\\latinnumeralstring{"), i(1, "counter"), t("}") }),
    S({ trig = "\\latinnumeralstring", dscr = "{counter}[prefix options]" }, { t("\\latinnumeralstring{"), i(1, "counter"), t("}["), i(2, "prefix options"), t("]") }),
    S({ trig = "\\latinnumeralstringnum", dscr = "{number}" }, { t("\\latinnumeralstringnum{"), i(1, "number"), t("}") }),
    S({ trig = "\\latinnumeralstringnum", dscr = "{number}[prefix options]" }, { t("\\latinnumeralstringnum{"), i(1, "number"), t("}["), i(2, "prefix options"), t("]") }),
  },
  keyvals = {
    {
      targets = "\\latinnumeralstring,\\latinnumeralstringnum",
      lines = {
        "use duode and unde=#below 20,never#c",
        "numeral u in duo#true,false",
        "e accute",
        "power of millia=#recursive,arabic,prefix",
      },
    },
  },
}
