-- Generated by snipgen 1 from fenixpar.cwl; do not edit, regenerate.
-- source: TeXstudio completion/fenixpar.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: a52df9534adbf0ed38ca3865c845d1b710e78176e8d3e5b9628674c841688d02
-- cwl-header:
--   # fenixpar package
--   # Matthew Bertucci 2022/05/31 for v0.92
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "fenixpar",
  includes = { "fenixtok" },
  lists = {},
  snippets = {
    S({ trig = "\\NewParType", dscr = "{type name}{code}" }, { t("\\NewParType{"), i(1, "type name"), t("}{"), i(2, "code"), t("}") }),
    S({ trig = "\\NextParL", dscr = "{type name}" }, { t("\\NextParL{"), i(1, "type name"), t("}") }),
    S({ trig = "\\NextParR", dscr = "{type name}" }, { t("\\NextParR{"), i(1, "type name"), t("}") }),
    S({ trig = "\\NextPar", dscr = "{type name} ∗", priority = 900 }, { t("\\NextPar{"), i(1, "type name"), t("}") }, "*"),
    S({ trig = "\\AllParsL", dscr = "{type name}" }, { t("\\AllParsL{"), i(1, "type name"), t("}") }),
    S({ trig = "\\AllParsR", dscr = "{type name}" }, { t("\\AllParsR{"), i(1, "type name"), t("}") }),
    S({ trig = "\\AllPars", dscr = "{type name} ∗", priority = 900 }, { t("\\AllPars{"), i(1, "type name"), t("}") }, "*"),
    S({ trig = "\\EndPars", dscr = "{type name}" }, { t("\\EndPars{"), i(1, "type name"), t("}") }),
    S({ trig = "\\nextpar", dscr = "{code}" }, { t("\\nextpar{"), i(1, "code"), t("}") }),
  },
  keyvals = {},
}
