-- Generated by snipgen 1 from floatflt.cwl; do not edit, regenerate.
-- source: TeXstudio completion/floatflt.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9ca0ef7e7b7e64527d10bb64497d48c2fa1a7073870b19cbd2f0bcc24083955b
-- cwl-header:
--   # floatflt package
--   # Matthew Bertucci 1/9/2021 for v1.31
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "floatflt",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\floatingfigure", dscr = "\\begin{floatingfigure}{width}" }, { t("\\begin{floatingfigure}{"), i(1, "width"), t({ "}", "\t" }), i(2), t({ "", "\\end{floatingfigure}" }) }),
    S({ trig = "\\floatingfigure", dscr = "\\begin{floatingfigure}[option]{width}" }, { t("\\begin{floatingfigure}["), i(1, "option"), t("]{"), i(2, "width"), t({ "}", "\t" }), i(3), t({ "", "\\end{floatingfigure}" }) }),
    S({ trig = "\\floatingtable", dscr = "\\begin{floatingtable}{tabular content}" }, { t("\\begin{floatingtable}{"), i(1, "tabular content"), t({ "}", "\t" }), i(2), t({ "", "\\end{floatingtable}" }) }),
    S({ trig = "\\floatingtable", dscr = "\\begin{floatingtable}[option]{tabular content}" }, { t("\\begin{floatingtable}["), i(1, "option"), t("]{"), i(2, "tabular content"), t({ "}", "\t" }), i(3), t({ "", "\\end{floatingtable}" }) }),
    S({ trig = "\\fltitem", dscr = "{text}" }, { t("\\fltitem{"), i(1, "text"), t("}") }),
    S({ trig = "\\fltitem", dscr = "[space]{text}" }, { t("\\fltitem["), i(1, "space"), t("]{"), i(2, "text"), t("}") }),
    S({ trig = "\\fltditem", dscr = "{label}{text}" }, { t("\\fltditem{"), i(1, "label"), t("}{"), i(2, "text"), t("}") }, "l"),
    S({ trig = "\\fltditem", dscr = "[space]{label}{text}" }, { t("\\fltditem["), i(1, "space"), t("]{"), i(2, "label"), t("}{"), i(3, "text"), t("}") }, "l"),
    S({ trig = "\\figbox", dscr = "∗", priority = 900 }, { t("\\figbox") }, "*"),
    S({ trig = "\\tabbox", dscr = "∗", priority = 900 }, { t("\\tabbox") }, "*"),
    S({ trig = "\\pagebox", dscr = "∗", priority = 900 }, { t("\\pagebox") }, "*"),
    S({ trig = "\\ffigcount", dscr = "∗", priority = 900 }, { t("\\ffigcount") }, "*"),
    S({ trig = "\\ftabcount", dscr = "∗", priority = 900 }, { t("\\ftabcount") }, "*"),
    S({ trig = "\\fftest", dscr = "∗", priority = 900 }, { t("\\fftest") }, "*"),
    S({ trig = "\\hangcount", dscr = "∗", priority = 900 }, { t("\\hangcount") }, "*"),
    S({ trig = "\\nosuccesstryfig", dscr = "∗", priority = 900 }, { t("\\nosuccesstryfig") }, "*"),
    S({ trig = "\\nosuccesstrytab", dscr = "∗", priority = 900 }, { t("\\nosuccesstrytab") }, "*"),
    S({ trig = "\\figgutter", dscr = "∗", priority = 900 }, { t("\\figgutter") }, "*"),
    S({ trig = "\\tabgutter", dscr = "∗", priority = 900 }, { t("\\tabgutter") }, "*"),
    S({ trig = "\\htdone", dscr = "∗", priority = 900 }, { t("\\htdone") }, "*"),
    S({ trig = "\\pageht", dscr = "∗", priority = 900 }, { t("\\pageht") }, "*"),
    S({ trig = "\\startpageht", dscr = "∗", priority = 900 }, { t("\\startpageht") }, "*"),
    S({ trig = "\\tabbredd", dscr = "∗", priority = 900 }, { t("\\tabbredd") }, "*"),
    S({ trig = "\\floatfltwidth", dscr = "∗", priority = 900 }, { t("\\floatfltwidth") }, "*"),
    S({ trig = "\\fltitemwidth", dscr = "∗", priority = 900 }, { t("\\fltitemwidth") }, "*"),
    S({ trig = "\\iftryingfig", dscr = "∗", priority = 900 }, { t("\\iftryingfig") }, "*"),
    S({ trig = "\\tryingfigfalse", dscr = "∗", priority = 900 }, { t("\\tryingfigfalse") }, "*"),
    S({ trig = "\\tryingfigtrue", dscr = "∗", priority = 900 }, { t("\\tryingfigtrue") }, "*"),
    S({ trig = "\\iftryingtab", dscr = "∗", priority = 900 }, { t("\\iftryingtab") }, "*"),
    S({ trig = "\\tryingtabfalse", dscr = "∗", priority = 900 }, { t("\\tryingtabfalse") }, "*"),
    S({ trig = "\\tryingtabtrue", dscr = "∗", priority = 900 }, { t("\\tryingtabtrue") }, "*"),
    S({ trig = "\\ifdoingfig", dscr = "∗", priority = 900 }, { t("\\ifdoingfig") }, "*"),
    S({ trig = "\\doingfigfalse", dscr = "∗", priority = 900 }, { t("\\doingfigfalse") }, "*"),
    S({ trig = "\\doingfigtrue", dscr = "∗", priority = 900 }, { t("\\doingfigtrue") }, "*"),
    S({ trig = "\\ifdoingtab", dscr = "∗", priority = 900 }, { t("\\ifdoingtab") }, "*"),
    S({ trig = "\\doingtabfalse", dscr = "∗", priority = 900 }, { t("\\doingtabfalse") }, "*"),
    S({ trig = "\\doingtabtrue", dscr = "∗", priority = 900 }, { t("\\doingtabtrue") }, "*"),
    S({ trig = "\\iffigprocessing", dscr = "∗", priority = 900 }, { t("\\iffigprocessing") }, "*"),
    S({ trig = "\\figprocessingfalse", dscr = "∗", priority = 900 }, { t("\\figprocessingfalse") }, "*"),
    S({ trig = "\\figprocessingtrue", dscr = "∗", priority = 900 }, { t("\\figprocessingtrue") }, "*"),
    S({ trig = "\\iftabprocessing", dscr = "∗", priority = 900 }, { t("\\iftabprocessing") }, "*"),
    S({ trig = "\\tabprocessingfalse", dscr = "∗", priority = 900 }, { t("\\tabprocessingfalse") }, "*"),
    S({ trig = "\\tabprocessingtrue", dscr = "∗", priority = 900 }, { t("\\tabprocessingtrue") }, "*"),
    S({ trig = "\\ifpageafterfig", dscr = "∗", priority = 900 }, { t("\\ifpageafterfig") }, "*"),
    S({ trig = "\\pageafterfigfalse", dscr = "∗", priority = 900 }, { t("\\pageafterfigfalse") }, "*"),
    S({ trig = "\\pageafterfigtrue", dscr = "∗", priority = 900 }, { t("\\pageafterfigtrue") }, "*"),
    S({ trig = "\\ifpageaftertab", dscr = "∗", priority = 900 }, { t("\\ifpageaftertab") }, "*"),
    S({ trig = "\\pageaftertabfalse", dscr = "∗", priority = 900 }, { t("\\pageaftertabfalse") }, "*"),
    S({ trig = "\\pageaftertabtrue", dscr = "∗", priority = 900 }, { t("\\pageaftertabtrue") }, "*"),
    S({ trig = "\\ifoddpages", dscr = "∗", priority = 900 }, { t("\\ifoddpages") }, "*"),
    S({ trig = "\\oddpagesfalse", dscr = "∗", priority = 900 }, { t("\\oddpagesfalse") }, "*"),
    S({ trig = "\\oddpagestrue", dscr = "∗", priority = 900 }, { t("\\oddpagestrue") }, "*"),
    S({ trig = "\\ifoutput", dscr = "∗", priority = 900 }, { t("\\ifoutput") }, "*"),
    S({ trig = "\\outputfalse", dscr = "∗", priority = 900 }, { t("\\outputfalse") }, "*"),
    S({ trig = "\\outputtrue", dscr = "∗", priority = 900 }, { t("\\outputtrue") }, "*"),
    S({ trig = "\\outputpretest", dscr = "∗", priority = 900 }, { t("\\outputpretest") }, "*"),
    S({ trig = "\\dofigtest", dscr = "∗", priority = 900 }, { t("\\dofigtest") }, "*"),
    S({ trig = "\\dohangf", dscr = "∗", priority = 900 }, { t("\\dohangf") }, "*"),
    S({ trig = "\\dohangt", dscr = "∗", priority = 900 }, { t("\\dohangt") }, "*"),
    S({ trig = "\\dotabtest", dscr = "∗", priority = 900 }, { t("\\dotabtest") }, "*"),
    S({ trig = "\\figinsert", dscr = "∗", priority = 900 }, { t("\\figinsert") }, "*"),
    S({ trig = "\\tabinsert", dscr = "∗", priority = 900 }, { t("\\tabinsert") }, "*"),
    S({ trig = "\\theOptionTest", dscr = "∗", priority = 900 }, { t("\\theOptionTest") }, "*"),
    S({ trig = "\\tryfig", dscr = "∗", priority = 900 }, { t("\\tryfig") }, "*"),
    S({ trig = "\\trytab", dscr = "∗", priority = 900 }, { t("\\trytab") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/floatflt#c",
      lines = {
        "rflt",
        "lflt",
        "vflt",
      },
    },
    {
      targets = "\\begin{floatingfigure},\\begin{floatingtable}",
      lines = {
        "r",
        "l",
        "p",
        "v",
      },
    },
  },
}
