-- Generated by snipgen 1 from floatrowbytocbasic.cwl; do not edit, regenerate.
-- source: TeXstudio completion/floatrowbytocbasic.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 2ced66308882cd260e450dc0db1fd75766bb41c8400270d9ce02c981ebb8f9ce
-- cwl-header:
--   # floatrowbytocbasic package
--   # Matthew Bertucci 2023/08/16 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "floatrowbytocbasic",
  includes = { "tocbasic", "floatrow", "xpatch" },
  lists = {},
  snippets = {
    S({ trig = "\\DeclareFloatType", dscr = "{envname}{options}" }, { t("\\DeclareFloatType{"), i(1, "envname"), t("}{"), i(2, "options"), t("}") }, "N"),
    S({ trig = "\\ProvideFloatType", dscr = "{envname}{options}" }, { t("\\ProvideFloatType{"), i(1, "envname"), t("}{"), i(2, "options"), t("}") }, "N"),
    S({ trig = "\\RedeclareFloatType", dscr = "{envname}{options}" }, { t("\\RedeclareFloatType{"), i(1, "envname"), t("}{"), i(2, "options"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\DeclareFloatType,\\ProvideFloatType,\\RedeclareFloatType",
      lines = {
        "placement=%<combination of t,b,h,p%>",
        "name=%<name%>",
        "fileext=%<ext%>",
        "within=%<counter%>",
        "relatedcapstyle=#yes,no",
      },
    },
  },
}
