-- Generated by snipgen 1 from footnotebackref.cwl; do not edit, regenerate.
-- source: TeXstudio completion/footnotebackref.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 0fb375c900f4a62a69a04e4904488b45dd5632b97e9daf2abe98352a7f06f8f9
-- cwl-header:
--   # footnotebackref package
--   # Matthew Bertucci 11/29/2021 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "footnotebackref",
  includes = { "letltxmacro", "hyperref", "kvoptions" },
  lists = {},
  snippets = {
    S({ trig = "\\BackrefFootnoteTag", dscr = "∗", priority = 900 }, { t("\\BackrefFootnoteTag") }, "*"),
    S({ trig = "\\theBackrefHyperFootnoteCounter", dscr = "∗", priority = 900 }, { t("\\theBackrefHyperFootnoteCounter") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/footnotebackref#c",
      lines = {
        "symbol=%<symbol%>",
        "numberlinked#true,false",
      },
    },
  },
}
