-- Generated by snipgen 1 from fp-upn.cwl; do not edit, regenerate.
-- source: TeXstudio completion/fp-upn.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 34de2fca65f03c0442483f16bd9d5dfe3883950743d1f46decc4e8e21bb342b8
-- cwl-header:
--   # fp-upn package
--   # Matthew Bertucci 9/21/2021 for v2.1d
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "fp-upn",
  includes = { "fp", "defpattern" },
  lists = {},
  snippets = {
    S({ trig = "\\FPupn", dscr = "{variable}{value}" }, { t("\\FPupn{"), i(1, "variable"), t("}{"), i(2, "value"), t("}") }, "d"),
  },
  keyvals = {},
}
