-- Generated by snipgen 1 from grabbox.cwl; do not edit, regenerate.
-- source: TeXstudio completion/grabbox.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: e4e0c746f02acf2f2e367af9a02ed7c6c4d5d1b59bac3116a8d9c7bac9f151a0
-- cwl-header:
--   # grabbox package
--   # Matthew Bertucci 11/2/2021 for v1.4
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "grabbox",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\grabbox", dscr = "{box register}{box type}{afterwards}" }, { t("\\grabbox{"), i(1, "box register"), t("}{"), i(2, "box type"), t("}{"), i(3, "afterwards"), t("}") }),
    S({ trig = "\\grabbox", dscr = "[pre pre]{box register}[pre]{box type}[post]{afterwards}" }, { t("\\grabbox["), i(1, "pre pre"), t("]{"), i(2, "box register"), t("}["), i(3, "pre"), t("]{"), i(4, "box type"), t("}["), i(5, "post"), t("]{"), i(6, "afterwards"), t("}") }),
    S({ trig = "\\grabbox*", dscr = "{box register}{box type}{afterwards}" }, { t("\\grabbox*{"), i(1, "box register"), t("}{"), i(2, "box type"), t("}{"), i(3, "afterwards"), t("}") }),
    S({ trig = "\\grabbox*", dscr = "[pre pre]{box register}[pre]{box type}[post]{afterwards}" }, { t("\\grabbox*["), i(1, "pre pre"), t("]{"), i(2, "box register"), t("}["), i(3, "pre"), t("]{"), i(4, "box type"), t("}["), i(5, "post"), t("]{"), i(6, "afterwards"), t("}") }),
  },
  keyvals = {},
}
