-- Generated by snipgen 1 from graph35.cwl; do not edit, regenerate.
-- source: TeXstudio completion/graph35.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b434719e5076a5f77f9dfb40a15b8d3b64ccb57cb85de07725376e4f20f7ae3e
-- cwl-header:
--   # graph35 package
--   # Matthew Bertucci 2022/11/30 for v0.1.3
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "graph35",
  includes = { "etoolbox", "pixelart0", "tikz", "tikzlibrarycalc", "pgfkeys", "amssymb", "amsbsy", "sansmath", "letterspace", "pgfopts", "graph35-pixelart", "graph35-keys" },
  lists = {},
  snippets = {
    S({ trig = "\\setgraphcolor", dscr = "{color setting}" }, { t("\\setgraphcolor{"), i(1, "color setting"), t("}") }),
    S({ trig = "\\calculator", dscr = "{model}" }, { t("\\calculator{"), i(1, "model"), t("}") }),
    S({ trig = "\\calculator", dscr = "[options]{model}" }, { t("\\calculator["), i(1, "options"), t("]{"), i(2, "model"), t("}") }),
    S({ trig = "\\tikzcalculator", dscr = "{model}" }, { t("\\tikzcalculator{"), i(1, "model"), t("}") }),
    S({ trig = "\\key", dscr = "{key}" }, { t("\\key{"), i(1, "key"), t("}") }),
    S({ trig = "\\key", dscr = "[options]{key}" }, { t("\\key["), i(1, "options"), t("]{"), i(2, "key"), t("}") }),
    S({ trig = "\\tikzkey", dscr = "{key}{coordinates}" }, { t("\\tikzkey{"), i(1, "key"), t("}{"), i(2, "coordinates"), t("}") }),
    S({ trig = "\\tikzkey", dscr = "[options]{key}{coordinates}" }, { t("\\tikzkey["), i(1, "options"), t("]{"), i(2, "key"), t("}{"), i(3, "coordinates"), t("}") }),
    S({ trig = "\\menu", dscr = "{icon}{shortcut}" }, { t("\\menu{"), i(1, "icon"), t("}{"), i(2, "shortcut"), t("}") }),
    S({ trig = "\\tikzmenu", dscr = "{icon}{shortcut}{coordinates}" }, { t("\\tikzmenu{"), i(1, "icon"), t("}{"), i(2, "shortcut"), t("}{"), i(3, "coordinates"), t("}") }),
    S({ trig = "\\tikzmenu", dscr = "[options]{icon}{shortcut}{coordinates}" }, { t("\\tikzmenu["), i(1, "options"), t("]{"), i(2, "icon"), t("}{"), i(3, "shortcut"), t("}{"), i(4, "coordinates"), t("}") }),
    S({ trig = "\\function", dscr = "{function}" }, { t("\\function{"), i(1, "function"), t("}") }),
    S({ trig = "\\tikzfunction", dscr = "{function}{coordinates}" }, { t("\\tikzfunction{"), i(1, "function"), t("}{"), i(2, "coordinates"), t("}") }),
    S({ trig = "\\tikzfunction", dscr = "[options]{function}{coordinates}" }, { t("\\tikzfunction["), i(1, "options"), t("]{"), i(2, "function"), t("}{"), i(3, "coordinates"), t("}") }),
    S({ trig = "\\battery", dscr = "{state}" }, { t("\\battery{"), i(1, "state"), t("}") }),
    S({ trig = "\\tikzbattery", dscr = "{state}{coordinates}" }, { t("\\tikzbattery{"), i(1, "state"), t("}{"), i(2, "coordinates"), t("}") }),
    S({ trig = "\\tikzbattery", dscr = "[options]{state}{coordinates}" }, { t("\\tikzbattery["), i(1, "options"), t("]{"), i(2, "state"), t("}{"), i(3, "coordinates"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/graph35#c",
      lines = {
        "color=#real,blackandwhite",
      },
    },
    {
      targets = "\\setgraphcolor#c",
      lines = {
        "real",
        "blackandwhite",
      },
    },
    {
      targets = "\\calculator",
      lines = {
        "color=#real,blackandwhite,default",
        "scale=%<factor%>",
      },
    },
    {
      targets = "\\key,\\tikzkey",
      lines = {
        "color=#real,blackandwhite,default",
        "scale=%<factor%>",
        "shift#true,false",
        "alpha#true,false",
        "prefix=%<anchor prefix%>",
        "suffix=%<anchor suffix%>",
      },
    },
    {
      targets = "\\tikzmenu,\\tikzfunction,\\tikzbattery",
      lines = {
        "color=#%color",
        "scale=%<factor%>",
        "raise=##L",
      },
    },
  },
}
