-- Generated by snipgen 1 from graphicx-psmin.cwl; do not edit, regenerate.
-- source: TeXstudio completion/graphicx-psmin.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: d885476a9897b526dafdce63fd1504f0a2ef2ce1fdd3b0e93b8bf9902ebb4ebb
-- cwl-header:
--   # graphicx-psmin package
--   # Matthew Bertucci 2/19/2022 for v1.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "graphicx-psmin",
  includes = { "graphicx" },
  lists = {},
  snippets = {
    S({ trig = "\\loadgraphics", dscr = "{list of graphics}" }, { t("\\loadgraphics{"), i(1, "list of graphics"), t("}") }),
    S({ trig = "\\loadgraphics", dscr = "[bb]{list of graphics}" }, { t("\\loadgraphics["), i(1, "bb"), t("]{"), i(2, "list of graphics"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/graphicx-psmin#c",
      lines = {
        "unknownkeysallowed",
        "draft",
        "final",
        "hiresbb",
        "demo",
        "setpagesize",
        "nosetpagesize",
        "dvips",
        "xdvi",
        "dvipdf",
        "dvipdfm",
        "dvipdfmx",
        "xetex",
        "pdftex",
        "luatex",
        "dvisvgm",
        "dvipsone",
        "dviwindo",
        "emtex",
        "dviwin",
        "oztex",
        "textures",
        "pctexps",
        "pctexwin",
        "pctexhp",
        "pctex32",
        "truetex",
        "tcidvi",
        "vtex",
        "debugshow",
        "hiderotate",
        "hidescale",
      },
    },
  },
}
