-- Generated by snipgen 1 from graphpap.cwl; do not edit, regenerate.
-- source: TeXstudio completion/graphpap.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 644fa3ade8e8f53e3789be21534ce03f8a90b947b93d03c3ce1d1646af00902d
-- cwl-header:
--   # graphpap package
--   # Matthew Bertucci 8/27/2021 for v1.0c
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "graphpap",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\graphpaper", dscr = "(x_init,y_init)(x_dimen,y_dimen)" }, { t("\\graphpaper("), i(1, "x_init,y_init"), t(")("), i(2, "x_dimen,y_dimen"), t(")") }),
    S({ trig = "\\graphpaper", dscr = "[spacing](x_init,y_init)(x_dimen,y_dimen)" }, { t("\\graphpaper["), i(1, "spacing"), t("]("), i(2, "x_init,y_init"), t(")("), i(3, "x_dimen,y_dimen"), t(")") }),
  },
  keyvals = {},
}
