-- Generated by snipgen 1 from hcycle.cwl; do not edit, regenerate.
-- source: TeXstudio completion/hcycle.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9ab9835bd92b426a74dfa2a0e7e5089c43bea6fc05ac6ef449dc9ce5bb0d44dc
-- cwl-header:
--   # hcycle package
--   # Matthew Bertucci 2022/05/18 for v5.01
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "hcycle",
  includes = { "chemstr" },
  lists = {},
  snippets = {
    S({ trig = "\\FiveSugarh", dscr = "{atomlist}{subslist}" }, { t("\\FiveSugarh{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\FiveSugarh", dscr = "{atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\FiveSugarh{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}["), i(3, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\FiveSugarh", dscr = "[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\FiveSugarh["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\FiveSugarh", dscr = "[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\FiveSugarh["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }),
    S({ trig = "\\FiveSugarh", dscr = "(skelbdlist){atomlist}{subslist} ∗", priority = 900 }, { t("\\FiveSugarh("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\FiveSugarh", dscr = "(skelbdlist){atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\FiveSugarh("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\FiveSugarh", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\FiveSugarh("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}") }, "*"),
    S({ trig = "\\FiveSugarh", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\FiveSugarh("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}["), i(5, "delbdlist"), t("]") }),
    S({ trig = "\\Furanose", dscr = "{subslist}" }, { t("\\Furanose{"), i(1, "subslist"), t("}") }),
    S({ trig = "\\Furanose", dscr = "[bondlist]{subslist}" }, { t("\\Furanose["), i(1, "bondlist"), t("]{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\Furanosew", dscr = "{subslist}" }, { t("\\Furanosew{"), i(1, "subslist"), t("}") }),
    S({ trig = "\\Furanosew", dscr = "[bondlist]{subslist}" }, { t("\\Furanosew["), i(1, "bondlist"), t("]{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\Pyranose", dscr = "{subslist}" }, { t("\\Pyranose{"), i(1, "subslist"), t("}") }),
    S({ trig = "\\Pyranose", dscr = "[bondlist]{subslist}" }, { t("\\Pyranose["), i(1, "bondlist"), t("]{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\Pyranosew", dscr = "{subslist}" }, { t("\\Pyranosew{"), i(1, "subslist"), t("}") }),
    S({ trig = "\\Pyranosew", dscr = "[bondlist]{subslist}" }, { t("\\Pyranosew["), i(1, "bondlist"), t("]{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\SixSugarh", dscr = "{atomlist}{subslist}" }, { t("\\SixSugarh{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\SixSugarh", dscr = "{atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\SixSugarh{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}["), i(3, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\SixSugarh", dscr = "[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\SixSugarh["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\SixSugarh", dscr = "[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\SixSugarh["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }),
    S({ trig = "\\SixSugarh", dscr = "(skelbdlist){atomlist}{subslist} ∗", priority = 900 }, { t("\\SixSugarh("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\SixSugarh", dscr = "(skelbdlist){atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\SixSugarh("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\SixSugarh", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\SixSugarh("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}") }, "*"),
    S({ trig = "\\SixSugarh", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\SixSugarh("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}["), i(5, "delbdlist"), t("]") }),
    S({ trig = "\\fivesugarh", dscr = "{atomlist}{subslist}" }, { t("\\fivesugarh{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\fivesugarh", dscr = "{atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\fivesugarh{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}["), i(3, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\fivesugarh", dscr = "[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\fivesugarh["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\fivesugarh", dscr = "[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\fivesugarh["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }),
    S({ trig = "\\fivesugarh", dscr = "(skelbdlist){atomlist}{subslist} ∗", priority = 900 }, { t("\\fivesugarh("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\fivesugarh", dscr = "(skelbdlist){atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\fivesugarh("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\fivesugarh", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\fivesugarh("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}") }, "*"),
    S({ trig = "\\fivesugarh", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\fivesugarh("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}["), i(5, "delbdlist"), t("]") }),
    S({ trig = "\\fivesugarhw", dscr = "{atomlist}{subslist}" }, { t("\\fivesugarhw{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\fivesugarhw", dscr = "{atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\fivesugarhw{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}["), i(3, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\fivesugarhw", dscr = "[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\fivesugarhw["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\fivesugarhw", dscr = "[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\fivesugarhw["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }),
    S({ trig = "\\fivesugarhw", dscr = "(skelbdlist){atomlist}{subslist} ∗", priority = 900 }, { t("\\fivesugarhw("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\fivesugarhw", dscr = "(skelbdlist){atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\fivesugarhw("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\fivesugarhw", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\fivesugarhw("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}") }, "*"),
    S({ trig = "\\fivesugarhw", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\fivesugarhw("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}["), i(5, "delbdlist"), t("]") }),
    S({ trig = "\\furanose", dscr = "{subslist}" }, { t("\\furanose{"), i(1, "subslist"), t("}") }),
    S({ trig = "\\furanose", dscr = "[bondlist]{subslist}" }, { t("\\furanose["), i(1, "bondlist"), t("]{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\furanosew", dscr = "{subslist}" }, { t("\\furanosew{"), i(1, "subslist"), t("}") }),
    S({ trig = "\\furanosew", dscr = "[bondlist]{subslist}" }, { t("\\furanosew["), i(1, "bondlist"), t("]{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\pyranose", dscr = "{subslist}" }, { t("\\pyranose{"), i(1, "subslist"), t("}") }),
    S({ trig = "\\pyranose", dscr = "[bondlist]{subslist}" }, { t("\\pyranose["), i(1, "bondlist"), t("]{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\pyranosew", dscr = "{subslist}" }, { t("\\pyranosew{"), i(1, "subslist"), t("}") }),
    S({ trig = "\\pyranosew", dscr = "[bondlist]{subslist}" }, { t("\\pyranosew["), i(1, "bondlist"), t("]{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\sixsugarh", dscr = "{atomlist}{subslist}" }, { t("\\sixsugarh{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\sixsugarh", dscr = "{atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\sixsugarh{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}["), i(3, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\sixsugarh", dscr = "[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\sixsugarh["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\sixsugarh", dscr = "[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\sixsugarh["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }),
    S({ trig = "\\sixsugarh", dscr = "(skelbdlist){atomlist}{subslist} ∗", priority = 900 }, { t("\\sixsugarh("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\sixsugarh", dscr = "(skelbdlist){atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\sixsugarh("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\sixsugarh", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\sixsugarh("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}") }, "*"),
    S({ trig = "\\sixsugarh", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\sixsugarh("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}["), i(5, "delbdlist"), t("]") }),
    S({ trig = "\\sixsugarhw", dscr = "{atomlist}{subslist}" }, { t("\\sixsugarhw{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}") }),
    S({ trig = "\\sixsugarhw", dscr = "{atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\sixsugarhw{"), i(1, "atomlist"), t("}{"), i(2, "subslist"), t("}["), i(3, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\sixsugarhw", dscr = "[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\sixsugarhw["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\sixsugarhw", dscr = "[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\sixsugarhw["), i(1, "bondlist"), t("]{"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }),
    S({ trig = "\\sixsugarhw", dscr = "(skelbdlist){atomlist}{subslist} ∗", priority = 900 }, { t("\\sixsugarhw("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}") }, "*"),
    S({ trig = "\\sixsugarhw", dscr = "(skelbdlist){atomlist}{subslist}[delbdlist] ∗", priority = 900 }, { t("\\sixsugarhw("), i(1, "skelbdlist"), t("){"), i(2, "atomlist"), t("}{"), i(3, "subslist"), t("}["), i(4, "delbdlist"), t("]") }, "*"),
    S({ trig = "\\sixsugarhw", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist} ∗", priority = 900 }, { t("\\sixsugarhw("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}") }, "*"),
    S({ trig = "\\sixsugarhw", dscr = "(skelbdlist)[bondlist]{atomlist}{subslist}[delbdlist]" }, { t("\\sixsugarhw("), i(1, "skelbdlist"), t(")["), i(2, "bondlist"), t("]{"), i(3, "atomlist"), t("}{"), i(4, "subslist"), t("}["), i(5, "delbdlist"), t("]") }),
  },
  keyvals = {},
}
