-- Generated by snipgen 1 from hep-math-font.cwl; do not edit, regenerate.
-- source: TeXstudio completion/hep-math-font.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 0e0582f0963726870b3d8ffca0378a52c45464a3e733ed31d323a7e1a28e3ea7
-- cwl-header:
--   # hep-math-font package
--   # Matthew Bertucci 2025/09/02 for v1.4
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "hep-math-font",
  includes = { "kvoptions", "iftex", "pdftexcmds", "xstring", "amssymb", "amstext", "fixmath", "textalpha", "substitutefont", "exscale", "bm" },
  lists = {},
  snippets = {
    S({ trig = "\\Alpha", dscr = "" }, { t("\\Alpha") }),
    S({ trig = "\\Beta", dscr = "" }, { t("\\Beta") }),
    S({ trig = "\\Epsilon", dscr = "" }, { t("\\Epsilon") }),
    S({ trig = "\\Zeta", dscr = "" }, { t("\\Zeta") }),
    S({ trig = "\\Eta", dscr = "" }, { t("\\Eta") }),
    S({ trig = "\\Iota", dscr = "" }, { t("\\Iota") }),
    S({ trig = "\\Kappa", dscr = "" }, { t("\\Kappa") }),
    S({ trig = "\\Mu", dscr = "" }, { t("\\Mu") }),
    S({ trig = "\\Nu", dscr = "" }, { t("\\Nu") }),
    S({ trig = "\\Omicron", dscr = "" }, { t("\\Omicron") }),
    S({ trig = "\\Rho", dscr = "" }, { t("\\Rho") }),
    S({ trig = "\\Tau", dscr = "" }, { t("\\Tau") }),
    S({ trig = "\\Chi", dscr = "" }, { t("\\Chi") }),
    S({ trig = "\\omicron", dscr = "" }, { t("\\omicron") }),
    S({ trig = "\\finalsigma", dscr = "" }, { t("\\finalsigma") }),
    S({ trig = "\\digamma", dscr = "" }, { t("\\digamma") }),
    S({ trig = "\\Digamma", dscr = "" }, { t("\\Digamma") }),
    S({ trig = "\\stigma", dscr = "" }, { t("\\stigma") }),
    S({ trig = "\\varstigma", dscr = "" }, { t("\\varstigma") }),
    S({ trig = "\\koppa", dscr = "" }, { t("\\koppa") }),
    S({ trig = "\\Koppa", dscr = "" }, { t("\\Koppa") }),
    S({ trig = "\\qoppa", dscr = "" }, { t("\\qoppa") }),
    S({ trig = "\\Qoppa", dscr = "" }, { t("\\Qoppa") }),
    S({ trig = "\\Stigma", dscr = "" }, { t("\\Stigma") }),
    S({ trig = "\\Sampi", dscr = "" }, { t("\\Sampi") }),
    S({ trig = "\\sampi", dscr = "" }, { t("\\sampi") }),
    S({ trig = "\\pisymbol", dscr = "∗", priority = 900 }, { t("\\pisymbol") }, "*"),
    S({ trig = "\\rhosymbol", dscr = "∗", priority = 900 }, { t("\\rhosymbol") }, "*"),
    S({ trig = "\\thetasymbol", dscr = "∗", priority = 900 }, { t("\\thetasymbol") }, "*"),
    S({ trig = "\\epsilonsymbol", dscr = "∗", priority = 900 }, { t("\\epsilonsymbol") }, "*"),
    S({ trig = "\\phisymbol", dscr = "∗", priority = 900 }, { t("\\phisymbol") }, "*"),
    S({ trig = "\\varbeta", dscr = "" }, { t("\\varbeta") }),
    S({ trig = "\\betasymbol", dscr = "∗", priority = 900 }, { t("\\betasymbol") }, "*"),
    S({ trig = "\\varkappa", dscr = "" }, { t("\\varkappa") }),
    S({ trig = "\\kappasymbol", dscr = "∗", priority = 900 }, { t("\\kappasymbol") }, "*"),
    S({ trig = "\\Thetasymbol", dscr = "∗", priority = 900 }, { t("\\Thetasymbol") }, "*"),
    S({ trig = "\\mathscr", dscr = "{text}" }, h.mathwrap({ t("\\mathscr{"), i(1, "text"), t("}") }), "m"),
    S({ trig = "\\mathsftext", dscr = "{text} ∗", priority = 900 }, h.mathwrap({ t("\\mathsftext{"), i(1, "text"), t("}") }), "*m"),
  },
  keyvals = {
    {
      targets = "\\usepackage/hep-math-font#c",
      lines = {
        "symbols=#ams,true,minion,false",
      },
    },
  },
}
