-- Generated by snipgen 1 from hitex.cwl; do not edit, regenerate.
-- source: TeXstudio completion/hitex.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c0ba559f1aef965194624e52b0f59b91845a8e4e0e3bcdf968c281d5c110e21e
-- cwl-header:
--   # hitex format
--   # Matthew Bertucci 2026/07/24 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "hitex",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\HINTversion", dscr = "∗", priority = 900 }, { t("\\HINTversion") }, "*"),
    S({ trig = "\\HINTminorversion", dscr = "∗", priority = 900 }, { t("\\HINTminorversion") }, "*"),
    S({ trig = "\\HiTeXversion", dscr = "∗", priority = 900 }, { t("\\HiTeXversion") }, "*"),
    S({ trig = "\\HINTimage", dscr = "= <name> <width> <height> ∗", priority = 900 }, { t("\\HINTimage "), i(1, "= <name> <width> <height>") }, "*"),
    S({ trig = "\\HINTstartlink", dscr = "<destination> ∗", priority = 900 }, { t("\\HINTstartlink "), i(1, "<destination>") }, "*"),
    S({ trig = "\\HINTendlink", dscr = "∗", priority = 900 }, { t("\\HINTendlink") }, "*"),
    S({ trig = "\\HINTdest", dscr = "<label> <placement> ∗", priority = 900 }, { t("\\HINTdest "), i(1, "<label> <placement>") }, "*"),
    S({ trig = "\\HINToutline", dscr = "<destination> <depth> {horizontal list} ∗", priority = 900 }, { t("\\HINToutline "), i(1, "<destination> <depth>"), t(" {"), i(2, "horizontal list"), t("}") }, "*"),
    S({ trig = "\\HINTsetpage", dscr = "<integer> = <name> <priority> <width> <height> {vertical list} ∗", priority = 900 }, { t("\\HINTsetpage "), i(1, "<integer> = <name> <priority> <width> <height>"), t(" {"), i(2, "vertical list"), t("}") }, "*"),
    S({ trig = "\\HINTstream", dscr = "<integer> ∗", priority = 900 }, { t("\\HINTstream "), i(1, "<integer>") }, "*"),
    S({ trig = "\\HINTbefore", dscr = "= {vertical list} ∗", priority = 900 }, { t("\\HINTbefore "), i(1, "= "), t("{"), i(2, "vertical list"), t("}") }, "*"),
    S({ trig = "\\HINTafter", dscr = "= {vertical list} ∗", priority = 900 }, { t("\\HINTafter "), i(1, "= "), t("{"), i(2, "vertical list"), t("}") }, "*"),
  },
  keyvals = {},
}
