-- Generated by snipgen 1 from hittype.cwl; do not edit, regenerate.
-- source: TeXstudio completion/hittype.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 0bd9cb91c9d934ff5449e8b49fe1a4758ba44af8668fd4f8289344b8f2c16318
-- cwl-header:
--   # hittype package
--   # Matthew Bertucci 2025/04/08 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "hittype",
  includes = { "fontspec" },
  lists = {},
  snippets = {
    S({ trig = "\\sumer", dscr = "{super}{normal}{italic}" }, { t("\\sumer{"), i(1, "super"), t("}{"), i(2, "normal"), t("}{"), i(3, "italic"), t("}") }),
    S({ trig = "\\badeq", dscr = "" }, { t("\\badeq") }),
    S({ trig = "\\funh", dscr = "" }, { t("\\funh") }),
    S({ trig = "\\funH", dscr = "" }, { t("\\funH") }),
    S({ trig = "\\hl", dscr = "" }, { t("\\hl") }),
    S({ trig = "\\hr", dscr = "" }, { t("\\hr") }),
    S({ trig = "\\tsup", dscr = "{super}" }, { t("\\tsup{"), i(1, "super"), t("}") }),
    S({ trig = "\\tsub", dscr = "{sub}" }, { t("\\tsub{"), i(1, "sub"), t("}") }),
    S({ trig = "\\bracks", dscr = "{arg}" }, { t("\\bracks{"), i(1, "arg"), t("}") }),
    S({ trig = "\\Hitt", dscr = "{cuneiform codes}" }, { t("\\Hitt{"), i(1, "cuneiform codes"), t("}") }),
    S({ trig = "\\Hitt", dscr = "[variant]{cuneiform codes}" }, { t("\\Hitt["), i(1, "variant"), t("]{"), i(2, "cuneiform codes"), t("}") }),
  },
  keyvals = {},
}
