-- Generated by snipgen 1 from ifluatex.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ifluatex.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 1a735e82fe8e1971bdac0711398e5dec8b8d9ff91a341b3abecf6140d7bd29e3
-- cwl-header:
--   # doncherry/2013-05-11 for ifluatex v1.3
--   # Matthew Bertucci 2022-03-26 for v1.5
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ifluatex",
  includes = { "iftex" },
  lists = {},
  snippets = {
  },
  keyvals = {},
}
