-- Generated by snipgen 1 from ifsym.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ifsym.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 8f1ea68896373e2188b9f2d8fa594bd2602665b7b883210ef490557e0090487c
-- cwl-header:
--   # ifsym package
--   # Matthew Bertucci 1/18/2022 for v1.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ifsym",
  includes = { "calc" },
  lists = {},
  snippets = {
    S({ trig = "\\ifsymfamily", dscr = "∗", priority = 900 }, { t("\\ifsymfamily") }, "*"),
    S({ trig = "\\ifgeofamily", dscr = "∗", priority = 900 }, { t("\\ifgeofamily") }, "*"),
    S({ trig = "\\narrowshape", dscr = "∗", priority = 900 }, { t("\\narrowshape") }, "*"),
    S({ trig = "\\wideshape", dscr = "∗", priority = 900 }, { t("\\wideshape") }, "*"),
    S({ trig = "\\textifsym", dscr = "{text} ∗", priority = 900 }, { t("\\textifsym{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\textifgeo", dscr = "{text} ∗", priority = 900 }, { t("\\textifgeo{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\textnarrow", dscr = "{text} ∗", priority = 900 }, { t("\\textnarrow{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\textwide", dscr = "{text} ∗", priority = 900 }, { t("\\textwide{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\textifsymbol", dscr = "{slot} ∗", priority = 900 }, { t("\\textifsymbol{"), i(1, "slot"), t("}") }, "*"),
    S({ trig = "\\textifsymbol", dscr = "[font family]{slot} ∗", priority = 900 }, { t("\\textifsymbol["), i(1, "font family"), t("]{"), i(2, "slot"), t("}") }, "*"),
    S({ trig = "\\theifsymcnt", dscr = "∗", priority = 900 }, { t("\\theifsymcnt") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/ifsym#c",
      lines = {
        "misc",
        "electronic",
        "alpine",
        "geometry",
        "clock",
        "weather",
      },
    },
  },
}
