-- Generated by snipgen 1 from igo.cwl; do not edit, regenerate.
-- source: TeXstudio completion/igo.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 82dbba554868fc846647c545a91468459b06205e2b65b20b3836a92c4d00509f
-- cwl-header:
--   # igo package
--   # Matthew Bertucci 2022/06/09 for v0.62
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "igo",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\black", dscr = "[glyph]{intersection-list}" }, { t("\\black["), i(1, "glyph"), t("]{"), i(2, "intersection-list"), t("}") }),
    S({ trig = "\\black", dscr = "{intersection-list}" }, { t("\\black{"), i(1, "intersection-list"), t("}") }),
    S({ trig = "\\blackstone", dscr = "" }, { t("\\blackstone") }),
    S({ trig = "\\blackstone", dscr = "[glyph]" }, { t("\\blackstone["), i(1, "glyph"), t("]") }),
    S({ trig = "\\clear", dscr = "{intersection-list}" }, { t("\\clear{"), i(1, "intersection-list"), t("}") }),
    S({ trig = "\\cleargoban", dscr = "" }, { t("\\cleargoban") }),
    S({ trig = "\\cleargoban", dscr = "[intersection-pair]" }, { t("\\cleargoban["), i(1, "intersection-pair"), t("]") }),
    S({ trig = "\\cleargobansymbols", dscr = "" }, { t("\\cleargobansymbols") }),
    S({ trig = "\\copyfromgoban", dscr = "{n}" }, { t("\\copyfromgoban{"), i(1, "n"), t("}") }),
    S({ trig = "\\copygoban", dscr = "{n} ∗", priority = 900 }, { t("\\copygoban{"), i(1, "n"), t("}") }, "*"),
    S({ trig = "\\copytogoban", dscr = "{n}" }, { t("\\copytogoban{"), i(1, "n"), t("}") }),
    S({ trig = "\\gobansize", dscr = "{n}" }, { t("\\gobansize{"), i(1, "n"), t("}") }),
    S({ trig = "\\gobansymbol", dscr = "{intersection-list}{symbol}" }, { t("\\gobansymbol{"), i(1, "intersection-list"), t("}{"), i(2, "symbol"), t("}") }),
    S({ trig = "\\gobansymbols", dscr = "{intersection-list}{symbol}" }, { t("\\gobansymbols{"), i(1, "intersection-list"), t("}{"), i(2, "symbol"), t("}") }),
    S({ trig = "\\hflipgoban", dscr = "" }, { t("\\hflipgoban") }),
    S({ trig = "\\igobreakafterdiagram", dscr = "∗", priority = 900 }, { t("\\igobreakafterdiagram") }, "*"),
    S({ trig = "\\igocircle", dscr = "" }, { t("\\igocircle") }),
    S({ trig = "\\igocross", dscr = "" }, { t("\\igocross") }),
    S({ trig = "\\igofontsize", dscr = "{n}" }, { t("\\igofontsize{"), i(1, "n"), t("}") }),
    S({ trig = "\\igonone", dscr = "" }, { t("\\igonone") }),
    S({ trig = "\\igosquare", dscr = "" }, { t("\\igosquare") }),
    S({ trig = "\\igotriangle", dscr = "" }, { t("\\igotriangle") }),
    S({ trig = "\\largegoban", dscr = "" }, { t("\\largegoban") }),
    S({ trig = "\\mirrorgoban", dscr = "" }, { t("\\mirrorgoban") }),
    S({ trig = "\\normalgoban", dscr = "" }, { t("\\normalgoban") }),
    S({ trig = "\\rotategoban", dscr = "" }, { t("\\rotategoban") }),
    S({ trig = "\\rotategobanleft", dscr = "" }, { t("\\rotategobanleft") }),
    S({ trig = "\\rotategobanright", dscr = "" }, { t("\\rotategobanright") }),
    S({ trig = "\\showfullgoban", dscr = "" }, { t("\\showfullgoban") }),
    S({ trig = "\\showgoban", dscr = "" }, { t("\\showgoban") }),
    S({ trig = "\\showgoban", dscr = "[intersection-pair]" }, { t("\\showgoban["), i(1, "intersection-pair"), t("]") }),
    S({ trig = "\\smallgoban", dscr = "" }, { t("\\smallgoban") }),
    S({ trig = "\\stonesize", dscr = "∗", priority = 900 }, { t("\\stonesize") }, "*"),
    S({ trig = "\\usegoban", dscr = "{n}" }, { t("\\usegoban{"), i(1, "n"), t("}") }),
    S({ trig = "\\vflipgoban", dscr = "" }, { t("\\vflipgoban") }),
    S({ trig = "\\white", dscr = "[glyph]{intersection-list}" }, { t("\\white["), i(1, "glyph"), t("]{"), i(2, "intersection-list"), t("}") }),
    S({ trig = "\\white", dscr = "{intersection-list}" }, { t("\\white{"), i(1, "intersection-list"), t("}") }),
    S({ trig = "\\whitestone", dscr = "" }, { t("\\whitestone") }),
    S({ trig = "\\whitestone", dscr = "[glyph]" }, { t("\\whitestone["), i(1, "glyph"), t("]") }),
    S({ trig = "\\breakrepeat", dscr = "∗", priority = 900 }, { t("\\breakrepeat") }, "*"),
    S({ trig = "\\by", dscr = "{step} ∗", priority = 900 }, { t("\\by{"), i(1, "step"), t("}") }, "*"),
    S({ trig = "\\downto", dscr = "{end} ∗", priority = 900 }, { t("\\downto{"), i(1, "end"), t("}") }, "*"),
    S({ trig = "\\for", dscr = "{var} ∗", priority = 900 }, { t("\\for{"), i(1, "var"), t("}") }, "*"),
    S({ trig = "\\from", dscr = "{start} ∗", priority = 900 }, { t("\\from{"), i(1, "start"), t("}") }, "*"),
    S({ trig = "\\repeat", dscr = "\\for{var} <loop specs> \\do{body} ∗", priority = 900 }, { t("\\repeat \\for{"), i(1, "var"), t("} "), i(2, "<loop specs>"), t(" \\do{"), i(3, "body"), t("}") }, "*"),
    S({ trig = "\\to", dscr = "{end} ∗", priority = 900 }, { t("\\to{"), i(1, "end"), t("}") }, "*"),
    S({ trig = "\\until", dscr = "{cond} ∗", priority = 900 }, { t("\\until{"), i(1, "cond"), t("}") }, "*"),
    S({ trig = "\\while", dscr = "{cond} ∗", priority = 900 }, { t("\\while{"), i(1, "cond"), t("}") }, "*"),
  },
  keyvals = {},
}
