-- Generated by snipgen 1 from inputnormalization.cwl; do not edit, regenerate.
-- source: TeXstudio completion/inputnormalization.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 278730be0149ade3db6268da82cf3678051fb8bd75174c206f96c43d8fb93208
-- cwl-header:
--   # inputnormalization package
--   # Matthew Bertucci 2/9/2022 for v0.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "inputnormalization",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\Uinputnormalization", dscr = "=<integer>" }, { t("\\Uinputnormalization="), i(1, "<integer>") }),
  },
  keyvals = {},
}
