-- Generated by snipgen 1 from inslrmin.cwl; do not edit, regenerate.
-- source: TeXstudio completion/inslrmin.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 4d828d6710390ccb0acd00f8b0ffce21716d73c4204cbf00ecf520a192ee6e2d
-- cwl-header:
--   # inslrmin package
--   # Matthew Bertucci 2/5/2022 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "inslrmin",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\iminfamily", dscr = "" }, { t("\\iminfamily") }),
    S({ trig = "\\textimin", dscr = "{text}" }, { t("\\textimin{"), i(1, "text"), t("}") }),
  },
  keyvals = {},
}
