-- Generated by snipgen 1 from interpreter.cwl; do not edit, regenerate.
-- source: TeXstudio completion/interpreter.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 01efc66d1400ec72a10acb5e35be9a5cc8b25b714c9b406e7c8c17025e7dfb4f
-- cwl-header:
--   # interpreter package
--   # Matthew Bertucci 11/6/2021 for v1.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "interpreter",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\interpretfile", dscr = "{language}{file}" }, { t("\\interpretfile{"), i(1, "language"), t("}{"), i(2, "file"), t("}") }, "i"),
    S({ trig = "\\interpretergobble", dscr = "{arg} ∗", priority = 900 }, { t("\\interpretergobble{"), i(1, "arg"), t("}") }, "*"),
    S({ trig = "\\interpreterinput", dscr = "{file} ∗", priority = 900 }, { t("\\interpreterinput{"), i(1, "file"), t("}") }, "*i"),
  },
  keyvals = {},
}
