-- Generated by snipgen 1 from ipsum.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ipsum.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: e43a59cf3403907d371470f38cb44b2bac00b1e76f7802013ad4e8c2e06253b2
-- cwl-header:
--   # ipsum package
--   # Matthew Bertucci 2025/07/15 for v0.1.3
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ipsum",
  includes = { "kvoptions", "xstring", "xintexpr", "simplekv" },
  lists = {},
  snippets = {
    S({ trig = "\\ipsum", dscr = "" }, { t("\\ipsum") }),
    S({ trig = "\\ipsum", dscr = "[range]" }, { t("\\ipsum["), i(1, "range"), t("]") }),
    S({ trig = "\\ipsum", dscr = "<keyvals>" }, { t("\\ipsum<"), i(1, "keyvals"), t(">") }),
    S({ trig = "\\ipsum", dscr = "<keyvals>[range]" }, { t("\\ipsum<"), i(1, "keyvals"), t(">["), i(2, "range"), t("]") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/ipsum#c",
      lines = {
        "lng=#all,{%<languages%>}",
      },
    },
    {
      targets = "\\ipsum",
      lines = {
        "Lang=#LAT,EN,FR,DE,ES,PT,IT,NL",
        "Type=#par,sent,enum,item",
      },
    },
  },
}
