-- Generated by snipgen 1 from jslogo.cwl; do not edit, regenerate.
-- source: TeXstudio completion/jslogo.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b14053467371736bc7c9007499e8eb1772a123338b268c5319d9f518b8a80268
-- cwl-header:
--   # jslogo package
--   # Matthew Bertucci 2022/06/01 for release 2019/07/25
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "jslogo",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\cmrTeX", dscr = "∗", priority = 900 }, { t("\\cmrTeX") }, "*"),
    S({ trig = "\\cmrLaTeX", dscr = "∗", priority = 900 }, { t("\\cmrLaTeX") }, "*"),
    S({ trig = "\\sfTeX", dscr = "∗", priority = 900 }, { t("\\sfTeX") }, "*"),
    S({ trig = "\\sfLaTeX", dscr = "∗", priority = 900 }, { t("\\sfLaTeX") }, "*"),
    S({ trig = "\\ptmTeX", dscr = "∗", priority = 900 }, { t("\\ptmTeX") }, "*"),
    S({ trig = "\\ptmLaTeX", dscr = "∗", priority = 900 }, { t("\\ptmLaTeX") }, "*"),
    S({ trig = "\\pncTeX", dscr = "∗", priority = 900 }, { t("\\pncTeX") }, "*"),
    S({ trig = "\\pncLaTeX", dscr = "∗", priority = 900 }, { t("\\pncLaTeX") }, "*"),
    S({ trig = "\\pplTeX", dscr = "∗", priority = 900 }, { t("\\pplTeX") }, "*"),
    S({ trig = "\\pplLaTeX", dscr = "∗", priority = 900 }, { t("\\pplLaTeX") }, "*"),
    S({ trig = "\\ugmTeX", dscr = "∗", priority = 900 }, { t("\\ugmTeX") }, "*"),
    S({ trig = "\\ugmLaTeX", dscr = "∗", priority = 900 }, { t("\\ugmLaTeX") }, "*"),
    S({ trig = "\\pTeX", dscr = "" }, { t("\\pTeX") }),
    S({ trig = "\\pLaTeX", dscr = "" }, { t("\\pLaTeX") }),
    S({ trig = "\\pLaTeXe", dscr = "" }, { t("\\pLaTeXe") }),
    S({ trig = "\\upTeX", dscr = "" }, { t("\\upTeX") }),
    S({ trig = "\\upLaTeX", dscr = "" }, { t("\\upLaTeX") }),
    S({ trig = "\\upLaTeXe", dscr = "" }, { t("\\upLaTeXe") }),
    S({ trig = "\\AmSTeX", dscr = "" }, { t("\\AmSTeX") }),
    S({ trig = "\\BibTeX", dscr = "" }, { t("\\BibTeX") }),
    S({ trig = "\\SliTeX", dscr = "" }, { t("\\SliTeX") }),
  },
  keyvals = {},
}
