-- Generated by snipgen 1 from jsmembertable.cwl; do not edit, regenerate.
-- source: TeXstudio completion/jsmembertable.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 92069f3f2138f924586f52b2c80184f777495632a0057446455e508a449b0d2c
-- cwl-header:
--   # jsmembertable package
--   # Matthew Bertucci 2024/03/08 for v1.14
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "jsmembertable",
  includes = { "ifthen", "calc", "array", "longtable", "hhline", "datatool" },
  lists = {},
  snippets = {
    S({ trig = "\\makemembertable", dscr = "{number of blank rows}" }, { t("\\makemembertable{"), i(1, "number of blank rows"), t("}") }),
    S({ trig = "\\makeprestable", dscr = "{number of blank rows}" }, { t("\\makeprestable{"), i(1, "number of blank rows"), t("}") }),
    S({ trig = "\\makeprestable", dscr = "[number of sessions]{number of blank rows}" }, { t("\\makeprestable["), i(1, "number of sessions"), t("]{"), i(2, "number of blank rows"), t("}") }),
    S({ trig = "\\makeprestable*", dscr = "{number of blank rows}" }, { t("\\makeprestable*{"), i(1, "number of blank rows"), t("}") }),
    S({ trig = "\\makeprestable*", dscr = "[number of sessions]{number of blank rows}" }, { t("\\makeprestable*["), i(1, "number of sessions"), t("]{"), i(2, "number of blank rows"), t("}") }),
    S({ trig = "\\jsmnameheader", dscr = "∗", priority = 900 }, { t("\\jsmnameheader") }, "*"),
    S({ trig = "\\jsmidheader", dscr = "∗", priority = 900 }, { t("\\jsmidheader") }, "*"),
    S({ trig = "\\jsemailheader", dscr = "∗", priority = 900 }, { t("\\jsemailheader") }, "*"),
    S({ trig = "\\jsmsession", dscr = "∗", priority = 900 }, { t("\\jsmsession") }, "*"),
    S({ trig = "\\jsmsessionheader", dscr = "∗", priority = 900 }, { t("\\jsmsessionheader") }, "*"),
    S({ trig = "\\jssigheader", dscr = "∗", priority = 900 }, { t("\\jssigheader") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/jsmembertable#c",
      lines = {
        "datafile=%<.csv file%>",
        "datakeys={%<key1,key2,...%>}",
      },
    },
  },
}
