-- Generated by snipgen 1 from jvlisting.cwl; do not edit, regenerate.
-- source: TeXstudio completion/jvlisting.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f4db7fc1a7a8bf84e5dfa33ba2b6840825470931685d0a197608a64edef1f57c
-- cwl-header:
--   # jvlisting package
--   # Matthew Bertucci 10/12/2021 for v0.7
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "jvlisting",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\listing", dscr = "\\begin{listing}" }, { t({ "\\begin{listing}", "\t" }), i(1), t({ "", "\\end{listing}" }) }, "V"),
    S({ trig = "\\filelisting", dscr = "{file}" }, { t("\\filelisting{"), i(1, "file"), t("}") }),
    S({ trig = "\\NewListingEnvironment", dscr = "{envname}{args}{before code}{init code}{line cmd}{after code}" }, { t("\\NewListingEnvironment{"), i(1, "envname"), t("}{"), i(2, "args"), t("}{"), i(3, "before code"), t("}{"), i(4, "init code"), t("}{"), i(5, "line cmd"), t("}{"), i(6, "after code"), t("}") }, "N"),
    S({ trig = "\\NewFileListingCommand", dscr = "{cmd}{args}{before code}{init code}{line cmd}{after code}" }, { t("\\NewFileListingCommand{"), i(1, "cmd"), t("}{"), i(2, "args"), t("}{"), i(3, "before code"), t("}{"), i(4, "init code"), t("}{"), i(5, "line cmd"), t("}{"), i(6, "after code"), t("}") }, "d"),
    S({ trig = "\\listingskipamount", dscr = "∗", priority = 900 }, { t("\\listingskipamount") }, "*"),
    S({ trig = "\\listingindent", dscr = "∗", priority = 900 }, { t("\\listingindent") }, "*"),
    S({ trig = "\\listingfont", dscr = "∗", priority = 900 }, { t("\\listingfont") }, "*"),
    S({ trig = "\\listingpenalty", dscr = "∗", priority = 900 }, { t("\\listingpenalty") }, "*"),
    S({ trig = "\\prelistingpenalty", dscr = "∗", priority = 900 }, { t("\\prelistingpenalty") }, "*"),
    S({ trig = "\\postlistingpenalty", dscr = "∗", priority = 900 }, { t("\\postlistingpenalty") }, "*"),
    S({ trig = "\\ListingTypesetLine", dscr = "{a} ∗", priority = 900 }, { t("\\ListingTypesetLine{"), i(1, "a"), t("}") }, "*"),
    S({ trig = "\\prelistingskip", dscr = "∗", priority = 900 }, { t("\\prelistingskip") }, "*"),
    S({ trig = "\\postlistingskip", dscr = "∗", priority = 900 }, { t("\\postlistingskip") }, "*"),
    S({ trig = "\\normallistingfont", dscr = "∗", priority = 900 }, { t("\\normallistingfont") }, "*"),
    S({ trig = "\\DisableLigatureFix", dscr = "∗", priority = 900 }, { t("\\DisableLigatureFix") }, "*"),
  },
  keyvals = {},
}
