-- Generated by snipgen 1 from kalendarium.cwl; do not edit, regenerate.
-- source: TeXstudio completion/kalendarium.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f33a9abdca17520c26895fe09d2eef7cfc2c2dee857d36d43ce6772838fd8372
-- cwl-header:
--   # kalendarium package
--   # Matthew Bertucci 12/26/2021 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "kalendarium",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\KalDate", dscr = "{year}{month}{day}" }, { t("\\KalDate{"), i(1, "year"), t("}{"), i(2, "month"), t("}{"), i(3, "day"), t("}") }),
    S({ trig = "\\KalDate", dscr = "[options]{year}{month}{day}" }, { t("\\KalDate["), i(1, "options"), t("]{"), i(2, "year"), t("}{"), i(3, "month"), t("}{"), i(4, "day"), t("}") }),
    S({ trig = "\\KalDateStr", dscr = "{format}{delimiter}{date string}" }, { t("\\KalDateStr{"), i(1, "format"), t("}{"), i(2, "delimiter"), t("}{"), i(3, "date string"), t("}") }),
    S({ trig = "\\KalDateStr", dscr = "[options]{format}{delimiter}{date string}" }, { t("\\KalDateStr["), i(1, "options"), t("]{"), i(2, "format"), t("}{"), i(3, "delimiter"), t("}{"), i(4, "date string"), t("}") }),
    S({ trig = "\\KalToday", dscr = "" }, { t("\\KalToday") }),
    S({ trig = "\\KalToday", dscr = "[options]" }, { t("\\KalToday["), i(1, "options"), t("]") }),
    S({ trig = "\\KalWeekday", dscr = "{year}{month}{day}" }, { t("\\KalWeekday{"), i(1, "year"), t("}{"), i(2, "month"), t("}{"), i(3, "day"), t("}") }),
    S({ trig = "\\KalWeekday", dscr = "[options]{year}{month}{day}" }, { t("\\KalWeekday["), i(1, "options"), t("]{"), i(2, "year"), t("}{"), i(3, "month"), t("}{"), i(4, "day"), t("}") }),
    S({ trig = "\\KalAbbrFormat", dscr = "{abbreviation} ∗", priority = 900 }, { t("\\KalAbbrFormat{"), i(1, "abbreviation"), t("}") }, "*"),
    S({ trig = "\\KalDayFormat", dscr = "{day} ∗", priority = 900 }, { t("\\KalDayFormat{"), i(1, "day"), t("}") }, "*"),
    S({ trig = "\\KalYearFormat", dscr = "{year} ∗", priority = 900 }, { t("\\KalYearFormat{"), i(1, "year"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/kalendarium#c,\\KalDate,\\KalDateStr,\\KalToday,\\KalWeekday",
      lines = {
        "abbreviate#true,false",
        "periods#true,false",
        "era=#ad,adshort,auc,secular,none",
        "julian#true,false",
        "dayfmt=#roman,latin,arabic",
        "yearfmt=#roman,arabic",
        "antediem#true,false",
        "bissextum#true,false",
        "oldmonths#true,false",
      },
    },
  },
}
