-- Generated by snipgen 1 from lastbib.cwl; do not edit, regenerate.
-- source: TeXstudio completion/lastbib.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b4de1fa2f8313cbb733f6038c0fdbcb66d1f4e5713b3c4a35108873121df0762
-- cwl-header:
--   # lastbib package
--   # Matthew Bertucci 2024/03/08 for v2.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "lastbib",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\LastBib", dscr = "" }, { t("\\LastBib") }),
  },
  keyvals = {},
}
