-- Generated by snipgen 1 from latexscreenshooter.cwl; do not edit, regenerate.
-- source: TeXstudio completion/latexscreenshooter.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 8f1ef3be41b844e736bccf15046eed63827330ab9cb33b53062aea592e991271
-- cwl-header:
--   # latexscreenshooter package
--   # Matthew Bertucci 2024/06/29 for v2024-05-06
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "latexscreenshooter",
  includes = { "graphicx", "catchfile" },
  lists = {},
  snippets = {
    S({ trig = "\\screenshooter", dscr = "{URL}{width}{height}{file name}{path}" }, { t("\\screenshooter{"), i(1, "URL"), t("}{"), i(2, "width"), t("}{"), i(3, "height"), t("}{"), i(4, "file name"), t("}{"), i(5, "path"), t("}") }, "U"),
  },
  keyvals = {},
}
