-- Generated by snipgen 1 from lexend.cwl; do not edit, regenerate.
-- source: TeXstudio completion/lexend.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 128918b1ea5d7866e9c16b807e5d982314ccd3a59d7ba684ababeaa174573c07
-- cwl-header:
--   # lexend package
--   # Matthew Bertucci 1/15/2021 for v1.1.0.70
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "lexend",
  includes = { "fontspec", "kvoptions" },
  lists = {},
  snippets = {
    S({ trig = "\\LexendDeca", dscr = "{text}" }, { t("\\LexendDeca{"), i(1, "text"), t("}") }),
    S({ trig = "\\LexendExa", dscr = "{text}" }, { t("\\LexendExa{"), i(1, "text"), t("}") }),
    S({ trig = "\\LexendGiga", dscr = "{text}" }, { t("\\LexendGiga{"), i(1, "text"), t("}") }),
    S({ trig = "\\LexendMega", dscr = "{text}" }, { t("\\LexendMega{"), i(1, "text"), t("}") }),
    S({ trig = "\\LexendPeta", dscr = "{text}" }, { t("\\LexendPeta{"), i(1, "text"), t("}") }),
    S({ trig = "\\LexendTera", dscr = "{text}" }, { t("\\LexendTera{"), i(1, "text"), t("}") }),
    S({ trig = "\\LexendZetta", dscr = "{text}" }, { t("\\LexendZetta{"), i(1, "text"), t("}") }),
    S({ trig = "\\LexendVariants", dscr = "∗", priority = 900 }, { t("\\LexendVariants") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/lexend#c",
      lines = {
        "main#true,false",
        "nomain",
        "sans#true,false",
        "nosans",
      },
    },
  },
}
