-- Generated by snipgen 1 from lie-hasse.cwl; do not edit, regenerate.
-- source: TeXstudio completion/lie-hasse.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 07ed8d060e0007d7022447a4aa119af728ad391760844eee107bf52ea39c19e1
-- cwl-header:
--   # lie-hasse package
--   # Matthew Bertucci 2024/07/09 for v1.01
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "lie-hasse",
  includes = { "xcolor", "dynkin-diagrams", "contour", "tikzlibrarypositioning", "tikzlibraryfadings", "tikzlibraryquotes" },
  lists = {},
  snippets = {
    S({ trig = "\\hasse", dscr = "{letter}{rank}" }, { t("\\hasse{"), i(1, "letter"), t("}{"), i(2, "rank"), t("}") }),
    S({ trig = "\\hasse", dscr = "[options]{letter}{rank}" }, { t("\\hasse["), i(1, "options"), t("]{"), i(2, "letter"), t("}{"), i(3, "rank"), t("}") }),
    S({ trig = "\\hasseDiagrams", dscr = "{type1;type2;...}" }, { t("\\hasseDiagrams{"), i(1, "type1;type2;..."), t("}") }),
    S({ trig = "\\rootSystemHeight", dscr = "{count register}" }, { t("\\rootSystemHeight{"), i(1, "count register"), t("}") }),
    S({ trig = "\\rootSystemHeight", dscr = "[letter][rank]{count register}" }, { t("\\rootSystemHeight["), i(1, "letter"), t("]["), i(2, "rank"), t("]{"), i(3, "count register"), t("}") }),
    S({ trig = "\\rootSystemWidthAtGrade", dscr = "{grade}{count register}" }, { t("\\rootSystemWidthAtGrade{"), i(1, "grade"), t("}{"), i(2, "count register"), t("}") }),
    S({ trig = "\\rootSystemWidthAtGrade", dscr = "[letter]{grade}{count register}" }, { t("\\rootSystemWidthAtGrade["), i(1, "letter"), t("]{"), i(2, "grade"), t("}{"), i(3, "count register"), t("}") }),
    S({ trig = "\\rootSystemWidthAtGrade", dscr = "[letter][rank]{grade}{count register}" }, { t("\\rootSystemWidthAtGrade["), i(1, "letter"), t("]["), i(2, "rank"), t("]{"), i(3, "grade"), t("}{"), i(4, "count register"), t("}") }),
    S({ trig = "\\rootSum", dscr = "{first-pos}{second-pos}{cmd}" }, { t("\\rootSum{"), i(1, "first-pos"), t("}{"), i(2, "second-pos"), t("}{"), i(3, "cmd"), t("}") }, "d"),
    S({ trig = "\\rootSum", dscr = "[letter]{first-pos}{second-pos}{cmd}" }, { t("\\rootSum["), i(1, "letter"), t("]{"), i(2, "first-pos"), t("}{"), i(3, "second-pos"), t("}{"), i(4, "cmd"), t("}") }, "d"),
    S({ trig = "\\rootSum", dscr = "[letter][rank]{first-pos}{second-pos}{cmd}" }, { t("\\rootSum["), i(1, "letter"), t("]["), i(2, "rank"), t("]{"), i(3, "first-pos"), t("}{"), i(4, "second-pos"), t("}{"), i(5, "cmd"), t("}") }, "d"),
    S({ trig = "\\drawRootAsDynkinSum", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\drawRootAsDynkinSum{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\edgeQuote", dscr = "{arg} ∗", priority = 900 }, { t("\\edgeQuote{"), i(1, "arg"), t("}") }, "*"),
    S({ trig = "\\forAllPositiveRoots", dscr = "{command} ∗", priority = 900 }, { t("\\forAllPositiveRoots{"), i(1, "command"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\hasse#c",
      lines = {
        "edge length=##L",
        "edge/.style={%<TikZ options%>}",
        "edge length=##L",
        "edge quotes/.style={%<TikZ options%>}",
        "compact edge/.style={%<TikZ options%>}",
        "noncompact edge/.style={%<TikZ options%>}",
        "attach Dynkin diagram#true,false",
        "three D#true,false",
        "z shift=%<factor%>",
        "top/.style={%<TikZ options%>}",
        "right/.style={%<TikZ options%>}",
        "left/.style={%<TikZ options%>}",
        "show ordering#true,false",
        "show name#true,false",
        "show widths#true,false",
        "show height#true,false",
        "show Levi#true,false",
        "show unipotent radical#true,false",
      },
    },
  },
}
