-- Generated by snipgen 1 from ligtype.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ligtype.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 6cc8287a53b0b61539fd1c3478320d158ee01255564fe5e205c14b5a7946d059
-- cwl-header:
--   # ligtype package
--   # Matthew Bertucci 2023/07/10 for v0.3
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ligtype",
  includes = { "ifluatex", "luatexbase" },
  lists = {},
  snippets = {
    S({ trig = "\\nolig", dscr = "{string}{string with |}" }, { t("\\nolig{"), i(1, "string"), t("}{"), i(2, "string with |"), t("}") }),
    S({ trig = "\\keeplig", dscr = "{string}{string with |}" }, { t("\\keeplig{"), i(1, "string"), t("}{"), i(2, "string with |"), t("}") }),
    S({ trig = "\\ligtypeon", dscr = "" }, { t("\\ligtypeon") }),
    S({ trig = "\\ligtypeoff", dscr = "" }, { t("\\ligtypeoff") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/ligtype#c",
      lines = {
        "noshortf",
        "allshortf",
        "makemarks",
        "kerntest",
        "nodefault",
        "liglist",
        "connotes",
      },
    },
  },
}
