-- Generated by snipgen 1 from listofitems.cwl; do not edit, regenerate.
-- source: TeXstudio completion/listofitems.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: e70f567d48c6a6bc78f23f91e6aac372a3251dc7da25cc1c92ef0faede0ab7d9
-- cwl-header:
--   # listofitems package
--   # Matthew Bertucci 10/11/2021 for v1.63
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "listofitems",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\setsepchar", dscr = "{character}" }, { t("\\setsepchar{"), i(1, "character"), t("}") }),
    S({ trig = "\\setsepchar", dscr = "[nested sep char]{character}" }, { t("\\setsepchar["), i(1, "nested sep char"), t("]{"), i(2, "character"), t("}") }),
    S({ trig = "\\readlist", dscr = "{cmd}{list}" }, { t("\\readlist{"), i(1, "cmd"), t("}{"), i(2, "list"), t("}") }, "d"),
    S({ trig = "\\readlist*", dscr = "{cmd}{list}" }, { t("\\readlist*{"), i(1, "cmd"), t("}{"), i(2, "list"), t("}") }, "d"),
    S({ trig = "\\greadlist", dscr = "{cmd}{list}" }, { t("\\greadlist{"), i(1, "cmd"), t("}{"), i(2, "list"), t("}") }, "d"),
    S({ trig = "\\greadlist*", dscr = "{cmd}{list}" }, { t("\\greadlist*{"), i(1, "cmd"), t("}{"), i(2, "list"), t("}") }, "d"),
    S({ trig = "\\showitems", dscr = "{list cmd}" }, { t("\\showitems{"), i(1, "list cmd"), t("}") }),
    S({ trig = "\\ignoreemptyitems", dscr = "∗", priority = 900 }, { t("\\ignoreemptyitems") }, "*"),
    S({ trig = "\\reademptyitems", dscr = "∗", priority = 900 }, { t("\\reademptyitems") }, "*"),
    S({ trig = "\\foreachitem", dscr = "\\var\\in\\list{code}" }, { t("\\foreachitem"), i(1, "\\var"), t("\\in"), i(2, "\\list"), t("{"), i(3, "code"), t("}") }),
    S({ trig = "\\itemtomacro", dscr = "{list cmd}[index]{cmd}" }, { t("\\itemtomacro{"), i(1, "list cmd"), t("}["), i(2, "index"), t("]{"), i(3, "cmd"), t("}") }, "d"),
    S({ trig = "\\gitemtomacro", dscr = "{list cmd}[index]{cmd}" }, { t("\\gitemtomacro{"), i(1, "list cmd"), t("}["), i(2, "index"), t("]{"), i(3, "cmd"), t("}") }, "d"),
    S({ trig = "\\listlen", dscr = "{list cmd}[index]" }, { t("\\listlen{"), i(1, "list cmd"), t("}["), i(2, "index"), t("]") }),
    S({ trig = "\\defpair", dscr = "{<tok1><tok2>...}" }, { t("\\defpair{"), i(1, "<tok1><tok2>..."), t("}") }),
    S({ trig = "\\insidepair", dscr = "<tok1><tok2>{expression}{cmd}" }, { t("\\insidepair"), i(1, "<tok1><tok2>"), t("{"), i(2, "expression"), t("}{"), i(3, "cmd"), t("}") }, "d"),
  },
  keyvals = {},
}
