-- Generated by snipgen 1 from lltjext.cwl; do not edit, regenerate.
-- source: TeXstudio completion/lltjext.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 06caade0a465e43dcd6e14d3aad3cef375ff1743b96dc1ee20d524d74af66a53
-- cwl-header:
--   # lltjext package
--   # Matthew Bertucci 2026/05/18 for v1.2k-ltj-20
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "lltjext",
  includes = { "luatexja", "array" },
  lists = {},
  snippets = {
    S({ trig = "\\tabular", dscr = "\\begin{tabular}<dir>{cols}" }, { t("\\begin{tabular}<"), i(1, "dir"), t(">{"), i(2, "cols"), t({ "}", "\t" }), i(3), t({ "", "\\end{tabular}" }) }),
    S({ trig = "\\tabular", dscr = "\\begin{tabular}<dir>[pos]{cols}" }, { t("\\begin{tabular}<"), i(1, "dir"), t(">["), i(2, "pos"), t("]{"), i(3, "cols"), t({ "}", "\t" }), i(4), t({ "", "\\end{tabular}" }) }),
    S({ trig = "\\tabular*", dscr = "\\begin{tabular*}<dir>{width}[pos]{cols}" }, { t("\\begin{tabular*}<"), i(1, "dir"), t(">{"), i(2, "width"), t("}["), i(3, "pos"), t("]{"), i(4, "cols"), t({ "}", "\t" }), i(5), t({ "", "\\end{tabular*}" }) }, "\\tabular"),
    S({ trig = "\\tabular*", dscr = "\\begin{tabular*}<dir>{width}{cols}" }, { t("\\begin{tabular*}<"), i(1, "dir"), t(">{"), i(2, "width"), t("}{"), i(3, "cols"), t({ "}", "\t" }), i(4), t({ "", "\\end{tabular*}" }) }, "\\tabular"),
    S({ trig = "\\array", dscr = "\\begin{array}<dir>{cols}" }, h.mathwrap({ t("\\begin{array}<"), i(1, "dir"), t(">{"), i(2, "cols"), t({ "}", "\t" }), i(3), t({ "", "\\end{array}" }) }), "m"),
    S({ trig = "\\array", dscr = "\\begin{array}<dir>[pos]{cols}" }, h.mathwrap({ t("\\begin{array}<"), i(1, "dir"), t(">["), i(2, "pos"), t("]{"), i(3, "cols"), t({ "}", "\t" }), i(4), t({ "", "\\end{array}" }) }), "m"),
    S({ trig = "\\minipage", dscr = "\\begin{minipage}<dir>{width}" }, { t("\\begin{minipage}<"), i(1, "dir"), t(">{"), i(2, "width"), t({ "}", "\t" }), i(3), t({ "", "\\end{minipage}" }) }),
    S({ trig = "\\minipage", dscr = "\\begin{minipage}<dir>[position]{width}" }, { t("\\begin{minipage}<"), i(1, "dir"), t(">["), i(2, "position"), t("]{"), i(3, "width"), t({ "}", "\t" }), i(4), t({ "", "\\end{minipage}" }) }),
    S({ trig = "\\minipage", dscr = "\\begin{minipage}<dir>[position][height]{width}" }, { t("\\begin{minipage}<"), i(1, "dir"), t(">["), i(2, "position"), t("]["), i(3, "height"), t("]{"), i(4, "width"), t({ "}", "\t" }), i(5), t({ "", "\\end{minipage}" }) }),
    S({ trig = "\\minipage", dscr = "\\begin{minipage}<dir>[position][height][inner pos]{width}" }, { t("\\begin{minipage}<"), i(1, "dir"), t(">["), i(2, "position"), t("]["), i(3, "height"), t("]["), i(4, "inner pos"), t("]{"), i(5, "width"), t({ "}", "\t" }), i(6), t({ "", "\\end{minipage}" }) }),
    S({ trig = "\\parbox", dscr = "<dir>{width}{text}" }, { t("\\parbox<"), i(1, "dir"), t(">{"), i(2, "width"), t("}{"), i(3, "text"), t("}") }),
    S({ trig = "\\parbox", dscr = "<dir>[position]{width}{text}" }, { t("\\parbox<"), i(1, "dir"), t(">["), i(2, "position"), t("]{"), i(3, "width"), t("}{"), i(4, "text"), t("}") }),
    S({ trig = "\\parbox", dscr = "<dir>[position][height]{width}{text}" }, { t("\\parbox<"), i(1, "dir"), t(">["), i(2, "position"), t("]["), i(3, "height"), t("]{"), i(4, "width"), t("}{"), i(5, "text"), t("}") }),
    S({ trig = "\\parbox", dscr = "<dir>[position][height][inner-pos]{width}{text}" }, { t("\\parbox<"), i(1, "dir"), t(">["), i(2, "position"), t("]["), i(3, "height"), t("]["), i(4, "inner-pos"), t("]{"), i(5, "width"), t("}{"), i(6, "text"), t("}") }),
    S({ trig = "\\pbox", dscr = "{contents}" }, { t("\\pbox{"), i(1, "contents"), t("}") }),
    S({ trig = "\\pbox", dscr = "[width]{contents}" }, { t("\\pbox["), i(1, "width"), t("]{"), i(2, "contents"), t("}") }),
    S({ trig = "\\pbox", dscr = "[width][pos]{contents}" }, { t("\\pbox["), i(1, "width"), t("]["), i(2, "pos"), t("]{"), i(3, "contents"), t("}") }),
    S({ trig = "\\pbox", dscr = "<dir>{contents}" }, { t("\\pbox<"), i(1, "dir"), t(">{"), i(2, "contents"), t("}") }),
    S({ trig = "\\pbox", dscr = "<dir>[width]{contents}" }, { t("\\pbox<"), i(1, "dir"), t(">["), i(2, "width"), t("]{"), i(3, "contents"), t("}") }),
    S({ trig = "\\pbox", dscr = "<dir>[width][pos]{contents}" }, { t("\\pbox<"), i(1, "dir"), t(">["), i(2, "width"), t("]["), i(3, "pos"), t("]{"), i(4, "contents"), t("}") }),
    S({ trig = "\\picture", dscr = "\\begin{picture}<dir>(width,height)" }, { t("\\begin{picture}<"), i(1, "dir"), t(">("), i(2, "width,height"), t({ ")", "\t" }), i(3), t({ "", "\\end{picture}" }) }),
    S({ trig = "\\picture", dscr = "\\begin{picture}<dir>(width,height)(xoffset,yoffset)" }, { t("\\begin{picture}<"), i(1, "dir"), t(">("), i(2, "width,height"), t(")("), i(3, "xoffset,yoffset"), t({ ")", "\t" }), i(4), t({ "", "\\end{picture}" }) }),
    S({ trig = "\\floatwidth", dscr = "∗", priority = 900 }, { t("\\floatwidth") }, "*"),
    S({ trig = "\\floatheight", dscr = "∗", priority = 900 }, { t("\\floatheight") }, "*"),
    S({ trig = "\\floatruletick", dscr = "∗", priority = 900 }, { t("\\floatruletick") }, "*"),
    S({ trig = "\\captionfloatsep", dscr = "∗", priority = 900 }, { t("\\captionfloatsep") }, "*"),
    S({ trig = "\\captiondir", dscr = "∗", priority = 900 }, { t("\\captiondir") }, "*"),
    S({ trig = "\\captionwidth", dscr = "∗", priority = 900 }, { t("\\captionwidth") }, "*"),
    S({ trig = "\\captionfontsetup", dscr = "∗", priority = 900 }, { t("\\captionfontsetup") }, "*"),
    S({ trig = "\\layoutfloat", dscr = "{content}" }, { t("\\layoutfloat{"), i(1, "content"), t("}") }),
    S({ trig = "\\layoutfloat", dscr = "[pos]{content}" }, { t("\\layoutfloat["), i(1, "pos"), t("]{"), i(2, "content"), t("}") }),
    S({ trig = "\\layoutfloat", dscr = "(x,y){content}" }, { t("\\layoutfloat("), i(1, "x,y"), t("){"), i(2, "content"), t("}") }),
    S({ trig = "\\layoutfloat", dscr = "(x,y)[pos]{content}" }, { t("\\layoutfloat("), i(1, "x,y"), t(")["), i(2, "pos"), t("]{"), i(3, "content"), t("}") }),
    S({ trig = "\\DeclareLayoutCaption", dscr = "{floatname}<dir>(width)[pos1pos2] ∗", priority = 900 }, { t("\\DeclareLayoutCaption{"), i(1, "floatname"), t("}<"), i(2, "dir"), t(">("), i(3, "width"), t(")["), i(4, "pos1pos2"), t("]") }, "*"),
    S({ trig = "\\layoutcaption", dscr = "∗", priority = 900 }, { t("\\layoutcaption") }, "*"),
    S({ trig = "\\pcaption", dscr = "{caption}" }, { t("\\pcaption{"), i(1, "caption"), t("}") }),
    S({ trig = "\\rensujiskip", dscr = "" }, { t("\\rensujiskip") }),
    S({ trig = "\\rensuji", dscr = "{contents}" }, { t("\\rensuji{"), i(1, "contents"), t("}") }),
    S({ trig = "\\rensuji", dscr = "[pos]{contents}" }, { t("\\rensuji["), i(1, "pos"), t("]{"), i(2, "contents"), t("}") }),
    S({ trig = "\\Kanji", dscr = "{counter}" }, { t("\\Kanji{"), i(1, "counter"), t("}") }),
    S({ trig = "\\kanji", dscr = "∗", priority = 900 }, { t("\\kanji") }, "*"),
    S({ trig = "\\boutenchar", dscr = "" }, { t("\\boutenchar") }),
    S({ trig = "\\bou", dscr = "{contents}" }, { t("\\bou{"), i(1, "contents"), t("}") }),
    S({ trig = "\\kasen", dscr = "{contents}" }, { t("\\kasen{"), i(1, "contents"), t("}") }),
  },
  keyvals = {},
}
