-- Generated by snipgen 1 from lscapeenhanced.cwl; do not edit, regenerate.
-- source: TeXstudio completion/lscapeenhanced.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 69cdb14485fde6f1f7303a6e57e1da89bfdbdaa10b9e9cb7a519f3c6f5b48af5
-- cwl-header:
--   # lscapeenhanced package
--   # Matthew Bertucci 2024/04/16 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "lscapeenhanced",
  includes = { "lscape", "xpatch" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\usepackage/lscapeenhanced#c",
      lines = {
        "pdflscape",
      },
    },
  },
}
