-- Generated by snipgen 1 from ltj-latex.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ltj-latex.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 4f10e41d2c1bd13c89308b274b503b164a9fb9c9ef50588c708d7047c26026ba
-- cwl-header:
--   # ltj-latex package
--   # Matthew Bertucci 4/9/2022 for v20220311.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ltj-latex",
  includes = { "lltjfont", "lltjdefs", "lltjcore", "lltjp-atbegshi", "lltjp-geometry" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\lstset,\\lstinline,\\begin{lstlisting},\\lstinputlisting,\\lstMakeShortInline,\\lstdefinelanguage,\\lstdefinestyle",
      lines = {
        "vsraw#true,false",
        "vscmd=%<cmd%>",
        "doubleletterspace=",
      },
    },
  },
}
