-- Generated by snipgen 1 from luabreakurl.cwl; do not edit, regenerate.
-- source: TeXstudio completion/luabreakurl.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 84e2a2b7cb642f1c092f32e6d6e85c04e703ce20dddd329ce90dbffb5a8becf8
-- cwl-header:
--   # luabreakurl package
--   # Matthew Bertucci 2026/07/26 for v1.00
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "luabreakurl",
  includes = { "hyperref" },
  lists = {},
  snippets = {
    S({ trig = "\\breakurl", dscr = "{URL}" }, { t("\\breakurl{"), i(1, "URL"), t("}") }, "U"),
    S({ trig = "\\luabreakurlsetup", dscr = "{keyvals}" }, { t("\\luabreakurlsetup{"), i(1, "keyvals"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\luabreakurlsetup",
      lines = {
        "continuation=%<symbol%>",
      },
    },
  },
}
