-- Generated by snipgen 1 from luamaths.cwl; do not edit, regenerate.
-- source: TeXstudio completion/luamaths.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 7e86f0b9b32b9f3a41a60ef1d2f87594c5e80bae61fb6e2e7fff38e4256f28dd
-- cwl-header:
--   # luamaths package
--   # Matthew Bertucci 2023/08/24 for v1.5
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "luamaths",
  includes = { "xkeyval", "amsmath", "luacode" },
  lists = {},
  snippets = {
    S({ trig = "\\mathOp", dscr = "{expression}" }, { t("\\mathOp{"), i(1, "expression"), t("}") }),
    S({ trig = "\\mathAbs", dscr = "{number}" }, { t("\\mathAbs{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathAcos", dscr = "{number}" }, { t("\\mathAcos{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathAsin", dscr = "{number}" }, { t("\\mathAsin{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathAtan", dscr = "{number}" }, { t("\\mathAtan{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathCeil", dscr = "{number}" }, { t("\\mathCeil{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathCos", dscr = "{number}" }, { t("\\mathCos{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathExp", dscr = "{number}" }, { t("\\mathExp{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathFloor", dscr = "{number}" }, { t("\\mathFloor{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathInf", dscr = "" }, { t("\\mathInf") }),
    S({ trig = "\\mathLog", dscr = "{number}" }, { t("\\mathLog{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathMax", dscr = "{num1,num2,...}" }, { t("\\mathMax{"), i(1, "num1,num2,..."), t("}") }),
    S({ trig = "\\mathMin", dscr = "{num1,num2,...}" }, { t("\\mathMin{"), i(1, "num1,num2,..."), t("}") }),
    S({ trig = "\\mathPi", dscr = "" }, { t("\\mathPi") }),
    S({ trig = "\\mathRandom", dscr = "{arg}" }, { t("\\mathRandom{"), i(1, "arg"), t("}") }),
    S({ trig = "\\mathSin", dscr = "{number}" }, { t("\\mathSin{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathSqrt", dscr = "{number}" }, { t("\\mathSqrt{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathTan", dscr = "{number}" }, { t("\\mathTan{"), i(1, "number"), t("}") }),
    S({ trig = "\\mathRad", dscr = "{degrees}" }, { t("\\mathRad{"), i(1, "degrees"), t("}") }),
    S({ trig = "\\mathRound", dscr = "{number}{digits}" }, { t("\\mathRound{"), i(1, "number"), t("}{"), i(2, "digits"), t("}") }),
    S({ trig = "\\imUnit", dscr = "∗", priority = 900 }, { t("\\imUnit") }, "*"),
    S({ trig = "\\complexRound", dscr = "{a+bi}{num digits}" }, { t("\\complexRound{"), i(1, "a+bi"), t("}{"), i(2, "num digits"), t("}") }),
    S({ trig = "\\luaChkeqnum", dscr = "{num1}{num2}" }, { t("\\luaChkeqnum{"), i(1, "num1"), t("}{"), i(2, "num2"), t("}") }),
  },
  keyvals = {},
}
