-- Generated by snipgen 1 from makebox.cwl; do not edit, regenerate.
-- source: TeXstudio completion/makebox.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 011e8d456bb08e69618b067416ef7921d492240498c9e1a9fa7cd3aa60237ae1
-- cwl-header:
--   # fancybox package
--   # Matthew Bertucci 9/9/2021 for v0.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "makebox",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\makebox*", dscr = "{reference_text}{text}" }, { t("\\makebox*{"), i(1, "reference_text"), t("}{"), i(2, "text"), t("}") }),
    S({ trig = "\\makebox*", dscr = "{reference_text}[pos]{text}" }, { t("\\makebox*{"), i(1, "reference_text"), t("}["), i(2, "pos"), t("]{"), i(3, "text"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\makebox*",
      lines = {
        "l",
        "r",
        "s",
      },
    },
  },
}
