-- Generated by snipgen 1 from malayalam.cwl; do not edit, regenerate.
-- source: TeXstudio completion/malayalam.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: dd6850b226e4fd7487a4dcbe24d2914f50975688cd06b6296810af102713c6ef
-- cwl-header:
--   # malayalam package
--   # Matthew Bertucci 2022/06/20 for v0.9.7
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "malayalam",
  includes = { "ifpdf" },
  lists = {},
  snippets = {
    S({ trig = "\\<", dscr = "slot>" }, { t("\\<"), i(1, "slot"), t(">") }),
    S({ trig = "\\B", dscr = "" }, { t("\\B") }),
    S({ trig = "\\C", dscr = "" }, { t("\\C") }),
    S({ trig = "\\D", dscr = "" }, { t("\\D") }),
    S({ trig = "\\E", dscr = "" }, { t("\\E") }),
    S({ trig = "\\F", dscr = "" }, { t("\\F") }),
    S({ trig = "\\K", dscr = "{number}" }, { t("\\K{"), i(1, "number"), t("}") }),
    S({ trig = "\\mm", dscr = "" }, { t("\\mm") }),
    S({ trig = "\\X", dscr = "{text}" }, { t("\\X{"), i(1, "text"), t("}") }),
    S({ trig = "\\ambili", dscr = "∗", priority = 900 }, { t("\\ambili") }, "*"),
    S({ trig = "\\ashtamudi", dscr = "∗", priority = 900 }, { t("\\ashtamudi") }, "*"),
    S({ trig = "\\aswathi", dscr = "∗", priority = 900 }, { t("\\aswathi") }, "*"),
    S({ trig = "\\bhanu", dscr = "∗", priority = 900 }, { t("\\bhanu") }, "*"),
    S({ trig = "\\chippi", dscr = "∗", priority = 900 }, { t("\\chippi") }, "*"),
    S({ trig = "\\karthika", dscr = "∗", priority = 900 }, { t("\\karthika") }, "*"),
    S({ trig = "\\kaumudi", dscr = "∗", priority = 900 }, { t("\\kaumudi") }, "*"),
    S({ trig = "\\kottakkal", dscr = "∗", priority = 900 }, { t("\\kottakkal") }, "*"),
    S({ trig = "\\makam", dscr = "∗", priority = 900 }, { t("\\makam") }, "*"),
    S({ trig = "\\malavika", dscr = "∗", priority = 900 }, { t("\\malavika") }, "*"),
    S({ trig = "\\mridula", dscr = "∗", priority = 900 }, { t("\\mridula") }, "*"),
    S({ trig = "\\payippad", dscr = "∗", priority = 900 }, { t("\\payippad") }, "*"),
    S({ trig = "\\periyar", dscr = "∗", priority = 900 }, { t("\\periyar") }, "*"),
    S({ trig = "\\revathi", dscr = "∗", priority = 900 }, { t("\\revathi") }, "*"),
    S({ trig = "\\sabari", dscr = "∗", priority = 900 }, { t("\\sabari") }, "*"),
    S({ trig = "\\sruthy", dscr = "∗", priority = 900 }, { t("\\sruthy") }, "*"),
    S({ trig = "\\aathira", dscr = "∗", priority = 900 }, { t("\\aathira") }, "*"),
    S({ trig = "\\anakha", dscr = "∗", priority = 900 }, { t("\\anakha") }, "*"),
    S({ trig = "\\ayilyambold", dscr = "∗", priority = 900 }, { t("\\ayilyambold") }, "*"),
    S({ trig = "\\bhavana", dscr = "∗", priority = 900 }, { t("\\bhavana") }, "*"),
    S({ trig = "\\gauri", dscr = "∗", priority = 900 }, { t("\\gauri") }, "*"),
    S({ trig = "\\gopika", dscr = "∗", priority = 900 }, { t("\\gopika") }, "*"),
    S({ trig = "\\indulekha", dscr = "∗", priority = 900 }, { t("\\indulekha") }, "*"),
    S({ trig = "\\ISMashtamudi", dscr = "∗", priority = 900 }, { t("\\ISMashtamudi") }, "*"),
    S({ trig = "\\ISMkarthika", dscr = "∗", priority = 900 }, { t("\\ISMkarthika") }, "*"),
    S({ trig = "\\ISMkaumudi", dscr = "∗", priority = 900 }, { t("\\ISMkaumudi") }, "*"),
    S({ trig = "\\ISMrevathi", dscr = "∗", priority = 900 }, { t("\\ISMrevathi") }, "*"),
    S({ trig = "\\jaya", dscr = "∗", priority = 900 }, { t("\\jaya") }, "*"),
    S({ trig = "\\ravivarma", dscr = "∗", priority = 900 }, { t("\\ravivarma") }, "*"),
    S({ trig = "\\sarada", dscr = "∗", priority = 900 }, { t("\\sarada") }, "*"),
    S({ trig = "\\thiruvathira", dscr = "∗", priority = 900 }, { t("\\thiruvathira") }, "*"),
    S({ trig = "\\bibname", dscr = "∗", priority = 900 }, { t("\\bibname") }, "*"),
    S({ trig = "\\chaptername", dscr = "∗", priority = 900 }, { t("\\chaptername") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/malayalam#c",
      lines = {
        "keli",
        "rachana",
        "ambili",
        "ashtamudi",
        "aswathi",
        "bhanu",
        "chippi",
        "karthika",
        "kaumudi",
        "kottakkal",
        "makam",
        "malavika",
        "mridula",
        "payippad",
        "periyar",
        "revathi",
        "sabari",
        "sruthy",
        "ISMkarthika",
        "jaya",
        "gopika",
        "ISMrevathi",
        "ISMashtamudi",
        "bhavana",
        "aathira",
        "ayilyambold",
        "anakha",
        "indulekha",
        "ISMkaumudi",
        "ravivarma",
        "thiruvathira",
        "sarada",
        "gauri",
        "english",
      },
    },
  },
}
