-- Generated by snipgen 1 from maybemath.cwl; do not edit, regenerate.
-- source: TeXstudio completion/maybemath.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 7745fd0db1c30bb739255237673d813dddb505ef1ac3a853bbc502c7562c826b
-- cwl-header:
--   # maybemath package
--   # Matthew Bertucci 3/8/2022 for release 2005-02-22
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "maybemath",
  includes = { "amsmath", "bm" },
  lists = {},
  snippets = {
    S({ trig = "\\maybebmsf", dscr = "{expr}" }, { t("\\maybebmsf{"), i(1, "expr"), t("}") }),
    S({ trig = "\\maybebm", dscr = "{expr}" }, { t("\\maybebm{"), i(1, "expr"), t("}") }),
    S({ trig = "\\maybeitrm", dscr = "{expr}" }, { t("\\maybeitrm{"), i(1, "expr"), t("}") }),
    S({ trig = "\\maybeitsubscript", dscr = "{expr}" }, { t("\\maybeitsubscript{"), i(1, "expr"), t("}") }),
    S({ trig = "\\maybeit", dscr = "{expr}" }, { t("\\maybeit{"), i(1, "expr"), t("}") }),
    S({ trig = "\\mayberm", dscr = "{expr}" }, { t("\\mayberm{"), i(1, "expr"), t("}") }),
    S({ trig = "\\maybesf", dscr = "{expr}" }, { t("\\maybesf{"), i(1, "expr"), t("}") }),
  },
  keyvals = {},
}
