-- Generated by snipgen 1 from mflogo.cwl; do not edit, regenerate.
-- source: TeXstudio completion/mflogo.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: d9876cf53075a7b802aee4c827a09ad4eff7e04d91429d1659b32bbdb45227bc
-- cwl-header:
--   # mflogo package
--   # Matthew Bertucci 10/14/2021 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "mflogo",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\MF", dscr = "" }, { t("\\MF") }),
    S({ trig = "\\MP", dscr = "" }, { t("\\MP") }),
    S({ trig = "\\logofamily", dscr = "∗", priority = 900 }, { t("\\logofamily") }, "*"),
    S({ trig = "\\textlogo", dscr = "{text} ∗", priority = 900 }, { t("\\textlogo{"), i(1, "text"), t("}") }, "*"),
  },
  keyvals = {},
}
