-- Generated by snipgen 1 from mwe.cwl; do not edit, regenerate.
-- source: TeXstudio completion/mwe.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 0fda4bc669c7a3d5d7c5c62ea7f4a83068daeb49e9fed2904e4b50ba18aad440
-- cwl-header:
--   # mwe package
--   # muzimuzhi/11 Aug 2019 for mwe v0.5
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "mwe",
  includes = { "graphicx", "lipsum", "blindtext" },
  lists = {},
  snippets = {
  },
  keyvals = {},
}
