-- Generated by snipgen 1 from MyriadPro-FontDef.cwl; do not edit, regenerate.
-- source: TeXstudio completion/MyriadPro-FontDef.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9c04b8d8a9401d14cbe957fed3a441c04d1bc4c4e550219b849d1246c736b92a
-- cwl-header:
--   # MyriadPro-FontDef package
--   # Matthew Bertucci 2022/05/08 for v0.3
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "MyriadPro-FontDef",
  includes = { "otfontdef", "fltpoint" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\usepackage/MyriadPro-FontDef#c",
      lines = {
        "noopticals",
        "smallfamily",
        "medfamily",
        "normalsize",
      },
    },
  },
}
