-- Generated by snipgen 1 from ncchdr.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ncchdr.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 8c0695121dcdd578362a31dbf6c060c6ebc9a0bdb953b32bb519847ea40f911a
-- cwl-header:
--   # ncchdr package
--   # Matthew Bertucci 2/3/2022 for v1.04
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ncchdr",
  includes = { "nccheadings", "nccfancyhdr" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\usepackage/ncchdr#c",
      lines = {
        "empty",
        "plain",
        "myheadings",
        "headings",
        "title",
      },
    },
  },
}
