-- Generated by snipgen 1 from newclude.cwl; do not edit, regenerate.
-- source: TeXstudio completion/newclude.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: d785da4a4e777832947c396306ec46019ecba54aa9b899204be9f7a08bd6afa6
-- cwl-header:
--   #cwl for newclude package, v.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "newclude",
  includes = { "moredefs", "afterpage" },
  lists = {},
  snippets = {
    S({ trig = "\\include", dscr = "[prehook]{file}" }, { t("\\include["), i(1, "prehook"), t("]{"), i(2, "file"), t("}") }, "i"),
    S({ trig = "\\include", dscr = "[prehook]{file}[posthook]" }, { t("\\include["), i(1, "prehook"), t("]{"), i(2, "file"), t("}["), i(3, "posthook"), t("]") }, "i"),
    S({ trig = "\\include*", dscr = "[prehook]{file}" }, { t("\\include*["), i(1, "prehook"), t("]{"), i(2, "file"), t("}") }, "i"),
    S({ trig = "\\include*", dscr = "[prehook]{file}[posthook]" }, { t("\\include*["), i(1, "prehook"), t("]{"), i(2, "file"), t("}["), i(3, "posthook"), t("]") }, "i"),
    S({ trig = "\\AtBeginInclude", dscr = "{tokens} ∗", priority = 900 }, { t("\\AtBeginInclude{"), i(1, "tokens"), t("}") }, "*"),
    S({ trig = "\\AtEndInclude", dscr = "{tokens} ∗", priority = 900 }, { t("\\AtEndInclude{"), i(1, "tokens"), t("}") }, "*"),
    S({ trig = "\\IncludeSurround", dscr = "∗", priority = 900 }, { t("\\IncludeSurround") }, "*"),
    S({ trig = "\\DefaultIncludeSurround", dscr = "∗", priority = 900 }, { t("\\DefaultIncludeSurround") }, "*"),
    S({ trig = "\\includeall", dscr = "" }, { t("\\includeall") }),
    S({ trig = "\\IncludeEnv", dscr = "{file}{envname}{instance} ∗", priority = 900 }, { t("\\IncludeEnv{"), i(1, "file"), t("}{"), i(2, "envname"), t("}{"), i(3, "instance"), t("}") }, "*i"),
    S({ trig = "\\IncludeEnv", dscr = "[prehook]{file}{envname}{instance} ∗", priority = 900 }, { t("\\IncludeEnv["), i(1, "prehook"), t("]{"), i(2, "file"), t("}{"), i(3, "envname"), t("}{"), i(4, "instance"), t("}") }, "*i"),
    S({ trig = "\\IncludeEnv", dscr = "[prehook]{file}{envname}{instance}[posthook] ∗", priority = 900 }, { t("\\IncludeEnv["), i(1, "prehook"), t("]{"), i(2, "file"), t("}{"), i(3, "envname"), t("}{"), i(4, "instance"), t("}["), i(5, "posthook"), t("]") }, "*i"),
    S({ trig = "\\IncludeEnv*", dscr = "{file}{envname}{instance} ∗", priority = 900 }, { t("\\IncludeEnv*{"), i(1, "file"), t("}{"), i(2, "envname"), t("}{"), i(3, "instance"), t("}") }, "*i"),
    S({ trig = "\\IncludeEnv*", dscr = "[prehook]{file}{envname}{instance} ∗", priority = 900 }, { t("\\IncludeEnv*["), i(1, "prehook"), t("]{"), i(2, "file"), t("}{"), i(3, "envname"), t("}{"), i(4, "instance"), t("}") }, "*i"),
    S({ trig = "\\IncludeEnv*", dscr = "[prehook]{file}{envname}{instance}[posthook] ∗", priority = 900 }, { t("\\IncludeEnv*["), i(1, "prehook"), t("]{"), i(2, "file"), t("}{"), i(3, "envname"), t("}{"), i(4, "instance"), t("}["), i(5, "posthook"), t("]") }, "*i"),
    S({ trig = "\\includedoc", dscr = "[prehook]{file}" }, { t("\\includedoc["), i(1, "prehook"), t("]{"), i(2, "file"), t("}") }, "i"),
    S({ trig = "\\includedoc", dscr = "[prehook]{file}[posthook]" }, { t("\\includedoc["), i(1, "prehook"), t("]{"), i(2, "file"), t("}["), i(3, "posthook"), t("]") }, "i"),
    S({ trig = "\\includedoc*", dscr = "[prehook]{file}" }, { t("\\includedoc*["), i(1, "prehook"), t("]{"), i(2, "file"), t("}") }, "i"),
    S({ trig = "\\includedoc*", dscr = "[prehook]{file}[posthook]" }, { t("\\includedoc*["), i(1, "prehook"), t("]{"), i(2, "file"), t("}["), i(3, "posthook"), t("]") }, "i"),
    S({ trig = "\\includedocskip", dscr = "[prehook]{file}[posthook] ∗", priority = 900 }, { t("\\includedocskip["), i(1, "prehook"), t("]{"), i(2, "file"), t("}["), i(3, "posthook"), t("]") }, "*i"),
    S({ trig = "\\includedocskip*", dscr = "[prehook]{file}[posthook] ∗", priority = 900 }, { t("\\includedocskip*["), i(1, "prehook"), t("]{"), i(2, "file"), t("}["), i(3, "posthook"), t("]") }, "*i"),
    S({ trig = "\\IfAllowed", dscr = "{part name}{true}{false} ∗", priority = 900 }, { t("\\IfAllowed{"), i(1, "part name"), t("}{"), i(2, "true"), t("}{"), i(3, "false"), t("}") }, "*"),
    S({ trig = "\\IncludeName", dscr = "∗", priority = 900 }, { t("\\IncludeName") }, "*"),
    S({ trig = "\\ParentName", dscr = "∗", priority = 900 }, { t("\\ParentName") }, "*"),
    S({ trig = "\\DeclareFormattingPackage", dscr = "{package name} ∗", priority = 900 }, { t("\\DeclareFormattingPackage{"), i(1, "package name"), t("}") }, "*"),
    S({ trig = "\\ifSkipPreamble", dscr = "∗", priority = 900 }, { t("\\ifSkipPreamble") }, "*"),
    S({ trig = "\\SkipPreambletrue", dscr = "∗", priority = 900 }, { t("\\SkipPreambletrue") }, "*"),
    S({ trig = "\\SkipPreamblefalse", dscr = "∗", priority = 900 }, { t("\\SkipPreamblefalse") }, "*"),
    S({ trig = "\\Disable", dscr = "{tokens} ∗", priority = 900 }, { t("\\Disable{"), i(1, "tokens"), t("}") }, "*"),
    S({ trig = "\\DisableAll", dscr = "∗", priority = 900 }, { t("\\DisableAll") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/newclude#c",
      lines = {
        "simple",
        "tag",
        "allocate",
      },
    },
  },
}
