-- Generated by snipgen 1 from nidanfloat.cwl; do not edit, regenerate.
-- source: TeXstudio completion/nidanfloat.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: fc83d61092551c459aa3d50a267c8cfba949246bad927dfb1995a1a9ca4e29d7
-- cwl-header:
--   # nidanfloat package
--   # Matthew Bertucci 2022/05/02 for v2.9
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "nidanfloat",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\dblbotfraction", dscr = "∗", priority = 900 }, { t("\\dblbotfraction") }, "*"),
    S({ trig = "\\balancenewpage", dscr = "" }, { t("\\balancenewpage") }),
    S({ trig = "\\balanceclearpage", dscr = "" }, { t("\\balanceclearpage") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/nidanfloat#c",
      lines = {
        "balance",
        "nobalance",
      },
    },
  },
}
