-- Generated by snipgen 1 from oldgerm.cwl; do not edit, regenerate.
-- source: TeXstudio completion/oldgerm.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 2bca689ffb10a90508023d7638c7cb52fed7c9cc875e12647d4ac14b8c4b4a5d
-- cwl-header:
--   # oldgerm package
--   # Matthew Bertucci 8/31/2021
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "oldgerm",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\gothfamily", dscr = "" }, { t("\\gothfamily") }),
    S({ trig = "\\frakfamily", dscr = "" }, { t("\\frakfamily") }),
    S({ trig = "\\swabfamily", dscr = "" }, { t("\\swabfamily") }),
    S({ trig = "\\textgoth", dscr = "{text}" }, { t("\\textgoth{"), i(1, "text"), t("}") }),
    S({ trig = "\\textfrak", dscr = "{text}" }, { t("\\textfrak{"), i(1, "text"), t("}") }),
    S({ trig = "\\textswab", dscr = "{text}" }, { t("\\textswab{"), i(1, "text"), t("}") }),
  },
  keyvals = {},
}
