-- Generated by snipgen 1 from OutilsGeomTikz.cwl; do not edit, regenerate.
-- source: TeXstudio completion/OutilsGeomTikz.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 864330e60ebe51900d9959ab17fb9363c744947db7254cdacad1aaff5610a654
-- cwl-header:
--   # OutilsGeomTikz package
--   # Matthew Bertucci 2025/05/27 for v0.1.6
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "OutilsGeomTikz",
  includes = { "tikz", "pgffor", "simplekv", "xstring", "nicefrac", "tikzlibrarycalc", "tikzlibrarypositioning" },
  lists = {},
  snippets = {
    S({ trig = "\\tkzCrayon", dscr = "" }, { t("\\tkzCrayon") }),
    S({ trig = "\\tkzCrayon", dscr = "[clés]" }, { t("\\tkzCrayon["), i(1, "clés"), t("]") }),
    S({ trig = "\\tkzRegle", dscr = "" }, { t("\\tkzRegle") }),
    S({ trig = "\\tkzRegle", dscr = "[clés]" }, { t("\\tkzRegle["), i(1, "clés"), t("]") }),
    S({ trig = "\\tkzRegleRepere", dscr = "" }, { t("\\tkzRegleRepere") }),
    S({ trig = "\\tkzRegleRepere", dscr = "[clés]" }, { t("\\tkzRegleRepere["), i(1, "clés"), t("]") }),
    S({ trig = "\\tkzEquerre", dscr = "" }, { t("\\tkzEquerre") }),
    S({ trig = "\\tkzEquerre", dscr = "[clés]" }, { t("\\tkzEquerre["), i(1, "clés"), t("]") }),
    S({ trig = "\\tkzRapporteur", dscr = "" }, { t("\\tkzRapporteur") }),
    S({ trig = "\\tkzRapporteur", dscr = "[clés]" }, { t("\\tkzRapporteur["), i(1, "clés"), t("]") }),
    S({ trig = "\\tkzPourcenteur", dscr = "" }, { t("\\tkzPourcenteur") }),
    S({ trig = "\\tkzPourcenteur", dscr = "[clés]" }, { t("\\tkzPourcenteur["), i(1, "clés"), t("]") }),
    S({ trig = "\\tkzRequerre", dscr = "" }, { t("\\tkzRequerre") }),
    S({ trig = "\\tkzRequerre", dscr = "[clés]" }, { t("\\tkzRequerre["), i(1, "clés"), t("]") }),
    S({ trig = "\\tkzRappEquerre", dscr = "" }, { t("\\tkzRappEquerre") }),
    S({ trig = "\\tkzRappEquerre", dscr = "[clés]" }, { t("\\tkzRappEquerre["), i(1, "clés"), t("]") }),
    S({ trig = "\\tkzCompas", dscr = "{pointe}{mine}" }, { t("\\tkzCompas{"), i(1, "pointe"), t("}{"), i(2, "mine"), t("}") }),
    S({ trig = "\\tkzCompas", dscr = "[clés]{pointe}{mine}" }, { t("\\tkzCompas["), i(1, "clés"), t("]{"), i(2, "pointe"), t("}{"), i(3, "mine"), t("}") }),
    S({ trig = "\\tkzMiniEquerre", dscr = "∗", priority = 900 }, { t("\\tkzMiniEquerre") }, "*"),
    S({ trig = "\\tkzMiniEquerre", dscr = "[clés] ∗", priority = 900 }, { t("\\tkzMiniEquerre["), i(1, "clés"), t("]") }, "*"),
    S({ trig = "\\tkzMiniRegle", dscr = "∗", priority = 900 }, { t("\\tkzMiniRegle") }, "*"),
    S({ trig = "\\tkzMiniRegle", dscr = "[clés] ∗", priority = 900 }, { t("\\tkzMiniRegle["), i(1, "clés"), t("]") }, "*"),
  },
  keyvals = {
    {
      targets = "\\tkzCrayon",
      lines = {
        "Longueur=%<nombre%>",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "Echelle=%<nombre%>",
        "Couleur=#%color",
      },
    },
    {
      targets = "\\tkzRegle",
      lines = {
        "Longueur=%<nombre%>",
        "Largeur=%<nombre%>",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "Echelle=%<nombre%>",
        "Couleur=#%color",
        "Fond#true,false",
        "CouleurFond=#%color",
        "Opacite=%<factor%>",
        "AfficheValeurs#true,false",
        "EchelleValeurs=%<factor%>",
        "PosVal=#h,m,b,hb",
      },
    },
    {
      targets = "\\tkzRegleRepere",
      lines = {
        "Longueur=%<nombre%>",
        "Largeur=%<nombre%>",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "Echelle=%<nombre%>",
        "Couleur=#%color",
        "Fond#true,false",
        "CouleurFond=#%color",
        "Opacite=%<factor%>",
        "AfficheValeurs#true,false",
        "EchelleValeurs=%<factor%>",
        "Retourne#true,false",
      },
    },
    {
      targets = "\\tkzEquerre",
      lines = {
        "Longueur=%<nombre%>",
        "Largeur=%<nombre%>",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "Echelle=%<nombre%>",
        "EchelleValeurs=%<factor%>",
        "Couleur=#%color",
        "Fond#true,false",
        "CouleurFond=#%color",
        "Opacite=%<factor%>",
        "AfficheValeurs#true,false",
        "PetitCote#true,false",
      },
    },
    {
      targets = "\\tkzRapporteur",
      lines = {
        "Complet#true,false",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "Echelle=%<nombre%>",
        "Couleur=#%color",
        "Fond#true,false",
        "CouleurFond=#%color",
        "Opacite=%<factor%>",
        "GraduationsInt#true,false",
        "AfficheAngles#true,false",
      },
    },
    {
      targets = "\\tkzPourcenteur",
      lines = {
        "Echelle=%<nombre%>",
        "EchelleAngle=%<nombre%>",
        "Couleur=#%color",
        "CouleurFond=#%color",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "AfficheValeurs#true,false",
        "Fond#true,false",
        "Opacite=%<factor%>",
        "Decoration#true,false",
      },
    },
    {
      targets = "\\tkzRequerre",
      lines = {
        "Longueur=%<nombre%>",
        "Largeur=%<nombre%>",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "Echelle=%<nombre%>",
        "Couleur=#%color",
        "Fond#true,false",
        "CouleurFond=#%color",
        "Opacite=%<factor%>",
        "AfficheValeurs#true,false",
        "EchelleValeurs=%<factor%>",
      },
    },
    {
      targets = "\\tkzRappEquerre",
      lines = {
        "Largeur=%<nombre%>",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "Echelle=%<nombre%>",
        "EchelleValeurs=%<nombre%>",
        "Couleur=#%color",
        "Fond#true,false",
        "CouleurFond=#%color",
        "Opacite=%<factor%>",
        "AfficheAngles#true,false",
        "AfficheValeurs#true,false",
        "Ombre#true,false",
      },
    },
    {
      targets = "\\tkzCompas",
      lines = {
        "AfficheCrayon#true,false",
        "EchelleCrayon=%<nombre%>",
        "CouleurCrayon=#%color",
        "LongueurCrayon=%<nombre%>",
        "LongueurBranches=%<nombre%>",
        "CouleurCompas=#%color",
        "Retourne#true,false",
        "Echelle=%<nombre%>",
        "UniteTikz=%<unité%>",
      },
    },
    {
      targets = "\\tkzMiniEquerre,\\tkzMiniRegle",
      lines = {
        "Echelle=%<nombre%>",
        "Couleur=#%color",
        "Origine={(%<x,y%>)}",
        "Rotation=%<degrees%>",
        "Ombre#true,false",
      },
    },
  },
}
