-- Generated by snipgen 1 from parallel.cwl; do not edit, regenerate.
-- source: TeXstudio completion/parallel.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: ec44b0ad48ea77b54ef623e4c619d04085886f9d57ab1d01f478a97f918975f1
-- cwl-header:
--   # parallel package
--   # Matthew Bertucci 11/17/2021
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "parallel",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\Parallel", dscr = "\\begin{Parallel}{left-width}{right-width}" }, { t("\\begin{Parallel}{"), i(1, "left-width"), t("}{"), i(2, "right-width"), t({ "}", "\t" }), i(3), t({ "", "\\end{Parallel}" }) }),
    S({ trig = "\\Parallel", dscr = "\\begin{Parallel}[options]{left-width}{right-width}" }, { t("\\begin{Parallel}["), i(1, "options"), t("]{"), i(2, "left-width"), t("}{"), i(3, "right-width"), t({ "}", "\t" }), i(4), t({ "", "\\end{Parallel}" }) }),
    S({ trig = "\\ParallelLText", dscr = "{text}" }, { t("\\ParallelLText{"), i(1, "text"), t("}") }),
    S({ trig = "\\ParallelRText", dscr = "{text}" }, { t("\\ParallelRText{"), i(1, "text"), t("}") }),
    S({ trig = "\\ParallelPar", dscr = "" }, { t("\\ParallelPar") }),
    S({ trig = "\\ParallelLWidth", dscr = "∗", priority = 900 }, { t("\\ParallelLWidth") }, "*"),
    S({ trig = "\\ParallelRWidth", dscr = "∗", priority = 900 }, { t("\\ParallelRWidth") }, "*"),
    S({ trig = "\\ParallelTextWidth", dscr = "∗", priority = 900 }, { t("\\ParallelTextWidth") }, "*"),
    S({ trig = "\\ParallelLeftMargin", dscr = "∗", priority = 900 }, { t("\\ParallelLeftMargin") }, "*"),
    S({ trig = "\\ParallelUserMidSkip", dscr = "∗", priority = 900 }, { t("\\ParallelUserMidSkip") }, "*"),
    S({ trig = "\\ParallelMainMidSkip", dscr = "∗", priority = 900 }, { t("\\ParallelMainMidSkip") }, "*"),
    S({ trig = "\\ParallelLBox", dscr = "∗", priority = 900 }, { t("\\ParallelLBox") }, "*"),
    S({ trig = "\\ParallelRBox", dscr = "∗", priority = 900 }, { t("\\ParallelRBox") }, "*"),
    S({ trig = "\\ParallelBoxVar", dscr = "∗", priority = 900 }, { t("\\ParallelBoxVar") }, "*"),
    S({ trig = "\\ParallelLTok", dscr = "∗", priority = 900 }, { t("\\ParallelLTok") }, "*"),
    S({ trig = "\\ParallelRTok", dscr = "∗", priority = 900 }, { t("\\ParallelRTok") }, "*"),
    S({ trig = "\\ParallelBoolVar", dscr = "∗", priority = 900 }, { t("\\ParallelBoolVar") }, "*"),
    S({ trig = "\\ParallelBoolMid", dscr = "∗", priority = 900 }, { t("\\ParallelBoolMid") }, "*"),
    S({ trig = "\\ParallelWhichBox", dscr = "∗", priority = 900 }, { t("\\ParallelWhichBox") }, "*"),
    S({ trig = "\\ParallelMainMode", dscr = "∗", priority = 900 }, { t("\\ParallelMainMode") }, "*"),
    S({ trig = "\\ParallelFNMode", dscr = "∗", priority = 900 }, { t("\\ParallelFNMode") }, "*"),
    S({ trig = "\\ParallelLFNCounter", dscr = "∗", priority = 900 }, { t("\\ParallelLFNCounter") }, "*"),
    S({ trig = "\\ParallelRFNCounter", dscr = "∗", priority = 900 }, { t("\\ParallelRFNCounter") }, "*"),
    S({ trig = "\\ParallelMaxFN", dscr = "∗", priority = 900 }, { t("\\ParallelMaxFN") }, "*"),
    S({ trig = "\\ParallelFNNumMode", dscr = "∗", priority = 900 }, { t("\\ParallelFNNumMode") }, "*"),
    S({ trig = "\\ParallelMessage", dscr = "{text} ∗", priority = 900 }, { t("\\ParallelMessage{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\ParallelLFootnote", dscr = "{text} ∗", priority = 900 }, { t("\\ParallelLFootnote{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\ParallelRFootnote", dscr = "{text} ∗", priority = 900 }, { t("\\ParallelRFootnote{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\ParallelFNEnviron", dscr = "\\begin{ParallelFNEnviron} ∗", priority = 900 }, { t({ "\\begin{ParallelFNEnviron}", "\t" }), i(1), t({ "", "\\end{ParallelFNEnviron}" }) }, "*"),
    S({ trig = "\\ParallelShowFNList", dscr = "∗", priority = 900 }, { t("\\ParallelShowFNList") }, "*"),
    S({ trig = "\\ParallelParOnePage", dscr = "∗", priority = 900 }, { t("\\ParallelParOnePage") }, "*"),
    S({ trig = "\\ParallelParTwoPages", dscr = "∗", priority = 900 }, { t("\\ParallelParTwoPages") }, "*"),
    S({ trig = "\\ParallelAfterText", dscr = "∗", priority = 900 }, { t("\\ParallelAfterText") }, "*"),
    S({ trig = "\\ParallelCheckOpenBrace", dscr = "∗", priority = 900 }, { t("\\ParallelCheckOpenBrace") }, "*"),
    S({ trig = "\\ParallelAtEnd", dscr = "∗", priority = 900 }, { t("\\ParallelAtEnd") }, "*"),
    S({ trig = "\\ParallelDot", dscr = "∗", priority = 900 }, { t("\\ParallelDot") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/parallel#c",
      lines = {
        "Verbose",
        "OldStyleNums",
        "RaiseNums",
        "ItalicNums",
        "RomanNums",
        "SeparatedFootnotes",
      },
    },
    {
      targets = "\\begin{Parallel}",
      lines = {
        "c",
        "v",
        "p",
      },
    },
  },
}
