-- Generated by snipgen 1 from pascaltriangle.cwl; do not edit, regenerate.
-- source: TeXstudio completion/pascaltriangle.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 8dd3c2c9c7e7cb7f6efaefc5365769ee23bd100f430e49023010b3d2abf1c5f1
-- cwl-header:
--   # pascaltriangle package
--   # Matthew Bertucci 1/8/2021 for v1.0.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "pascaltriangle",
  includes = { "amsmath", "tikz", "tikzlibraryshapes.geometric", "etoolbox" },
  lists = {},
  snippets = {
    S({ trig = "\\pascal", dscr = "{order}" }, { t("\\pascal{"), i(1, "order"), t("}") }),
    S({ trig = "\\pascal", dscr = "[options]{order}" }, { t("\\pascal["), i(1, "options"), t("]{"), i(2, "order"), t("}") }),
    S({ trig = "\\pascalset", dscr = "{options}" }, { t("\\pascalset{"), i(1, "options"), t("}") }),
    S({ trig = "\\binomc", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\binomc{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\pascal,\\pascalset",
      lines = {
        "shape=#iso,rt",
        "radius=##L",
        "fontsize=%<fontsize command%>",
        "withnum#true,false",
        "binom#true,false",
        "fillr=%<integer%>",
        "fillc=%<integer%>",
      },
    },
  },
}
