-- Generated by snipgen 1 from pbox.cwl; do not edit, regenerate.
-- source: TeXstudio completion/pbox.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: eefd7c1ebaf20dd1356587dcf66305039bfe4e097f8dd1a65272d1ca0b2c0204
-- cwl-header:
--   # pbox package
--   # Matthew Bertucci 9/11/2021 for v1.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "pbox",
  includes = { "calc" },
  lists = {},
  snippets = {
    S({ trig = "\\pbox", dscr = "{width}{contents}" }, { t("\\pbox{"), i(1, "width"), t("}{"), i(2, "contents"), t("}") }),
    S({ trig = "\\pbox", dscr = "[position]{width}{contents}" }, { t("\\pbox["), i(1, "position"), t("]{"), i(2, "width"), t("}{"), i(3, "contents"), t("}") }),
    S({ trig = "\\pbox", dscr = "[position][height]{width}{contents}" }, { t("\\pbox["), i(1, "position"), t("]["), i(2, "height"), t("]{"), i(3, "width"), t("}{"), i(4, "contents"), t("}") }),
    S({ trig = "\\pbox", dscr = "[position][height][inner-pos]{width}{contents}" }, { t("\\pbox["), i(1, "position"), t("]["), i(2, "height"), t("]["), i(3, "inner-pos"), t("]{"), i(4, "width"), t("}{"), i(5, "contents"), t("}") }),
    S({ trig = "\\settominwidth", dscr = "{cmd}{text} ∗", priority = 900 }, { t("\\settominwidth{"), i(1, "cmd"), t("}{"), i(2, "text"), t("}") }, "*"),
    S({ trig = "\\settominwidth", dscr = "[max-width]{cmd}{text} ∗", priority = 900 }, { t("\\settominwidth["), i(1, "max-width"), t("]{"), i(2, "cmd"), t("}{"), i(3, "text"), t("}") }, "*"),
    S({ trig = "\\widthofpbox", dscr = "{text} ∗", priority = 900 }, { t("\\widthofpbox{"), i(1, "text"), t("}") }, "*"),
  },
  keyvals = {},
}
