-- Generated by snipgen 1 from phaistos.cwl; do not edit, regenerate.
-- source: TeXstudio completion/phaistos.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 1a74b35dfde3dbabaa03e767492b6a9a236e3722db7e88133b5a3532b2a93f41
-- cwl-header:
--   # phaistos package
--   # Matthew Bertucci 8/6/2021
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "phaistos",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\PHarrow", dscr = "" }, { t("\\PHarrow") }),
    S({ trig = "\\PHbee", dscr = "" }, { t("\\PHbee") }),
    S({ trig = "\\PHbeehive", dscr = "" }, { t("\\PHbeehive") }),
    S({ trig = "\\PHboomerang", dscr = "" }, { t("\\PHboomerang") }),
    S({ trig = "\\PHbow", dscr = "" }, { t("\\PHbow") }),
    S({ trig = "\\PHbullLeg", dscr = "" }, { t("\\PHbullLeg") }),
    S({ trig = "\\PHcaptive", dscr = "" }, { t("\\PHcaptive") }),
    S({ trig = "\\PHcarpentryPlane", dscr = "" }, { t("\\PHcarpentryPlane") }),
    S({ trig = "\\PHcat", dscr = "" }, { t("\\PHcat") }),
    S({ trig = "\\PHchild", dscr = "" }, { t("\\PHchild") }),
    S({ trig = "\\PHclub", dscr = "" }, { t("\\PHclub") }),
    S({ trig = "\\PHcolumn", dscr = "" }, { t("\\PHcolumn") }),
    S({ trig = "\\PHcomb", dscr = "" }, { t("\\PHcomb") }),
    S({ trig = "\\PHdolium", dscr = "" }, { t("\\PHdolium") }),
    S({ trig = "\\PHdove", dscr = "" }, { t("\\PHdove") }),
    S({ trig = "\\PHeagle", dscr = "" }, { t("\\PHeagle") }),
    S({ trig = "\\PHflute", dscr = "" }, { t("\\PHflute") }),
    S({ trig = "\\PHgaunlet", dscr = "" }, { t("\\PHgaunlet") }),
    S({ trig = "\\PHgrater", dscr = "" }, { t("\\PHgrater") }),
    S({ trig = "\\PHhelmet", dscr = "" }, { t("\\PHhelmet") }),
    S({ trig = "\\PHhide", dscr = "" }, { t("\\PHhide") }),
    S({ trig = "\\PHhorn", dscr = "" }, { t("\\PHhorn") }),
    S({ trig = "\\PHlid", dscr = "" }, { t("\\PHlid") }),
    S({ trig = "\\PHlily", dscr = "" }, { t("\\PHlily") }),
    S({ trig = "\\PHmanacles", dscr = "" }, { t("\\PHmanacles") }),
    S({ trig = "\\PHmattock", dscr = "" }, { t("\\PHmattock") }),
    S({ trig = "\\PHoxBack", dscr = "" }, { t("\\PHoxBack") }),
    S({ trig = "\\PHpapyrus", dscr = "" }, { t("\\PHpapyrus") }),
    S({ trig = "\\PHpedestrian", dscr = "" }, { t("\\PHpedestrian") }),
    S({ trig = "\\PHplaneTree", dscr = "" }, { t("\\PHplaneTree") }),
    S({ trig = "\\PHplumedHead", dscr = "" }, { t("\\PHplumedHead") }),
    S({ trig = "\\PHram", dscr = "" }, { t("\\PHram") }),
    S({ trig = "\\PHrosette", dscr = "" }, { t("\\PHrosette") }),
    S({ trig = "\\PHsaw", dscr = "" }, { t("\\PHsaw") }),
    S({ trig = "\\PHshield", dscr = "" }, { t("\\PHshield") }),
    S({ trig = "\\PHship", dscr = "" }, { t("\\PHship") }),
    S({ trig = "\\PHsling", dscr = "" }, { t("\\PHsling") }),
    S({ trig = "\\PHsmallAxe", dscr = "" }, { t("\\PHsmallAxe") }),
    S({ trig = "\\PHstrainer", dscr = "" }, { t("\\PHstrainer") }),
    S({ trig = "\\PHtattooedHead", dscr = "" }, { t("\\PHtattooedHead") }),
    S({ trig = "\\PHtiara", dscr = "" }, { t("\\PHtiara") }),
    S({ trig = "\\PHtunny", dscr = "" }, { t("\\PHtunny") }),
    S({ trig = "\\PHvine", dscr = "" }, { t("\\PHvine") }),
    S({ trig = "\\PHwavyBand", dscr = "" }, { t("\\PHwavyBand") }),
    S({ trig = "\\PHwoman", dscr = "" }, { t("\\PHwoman") }),
  },
  keyvals = {},
}
