-- Generated by snipgen 1 from phfquotetext.cwl; do not edit, regenerate.
-- source: TeXstudio completion/phfquotetext.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 04d0b28020f3dc1d590160a985ebcce99909e7da8d5338429b2cec586bf9cae9
-- cwl-header:
--   # phfquotetext package
--   # Matthew Bertucci 10/5/2021 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "phfquotetext",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\quotetext", dscr = "\\begin{quotetext}" }, { t({ "\\begin{quotetext}", "\t" }), i(1), t({ "", "\\end{quotetext}" }) }, "V"),
    S({ trig = "\\quotetextfont", dscr = "∗", priority = 900 }, { t("\\quotetextfont") }, "*"),
    S({ trig = "\\quotetextstart", dscr = "∗", priority = 900 }, { t("\\quotetextstart") }, "*"),
    S({ trig = "\\quotetextend", dscr = "∗", priority = 900 }, { t("\\quotetextend") }, "*"),
    S({ trig = "\\quotetextcatcodedefs", dscr = "∗", priority = 900 }, { t("\\quotetextcatcodedefs") }, "*"),
  },
  keyvals = {},
}
