-- Generated by snipgen 1 from platex.cwl; do not edit, regenerate.
-- source: TeXstudio completion/platex.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 5d9764382a6208b591f35f5bf1e4c0e06769933feb4cddff1e04de58353cb514
-- cwl-header:
--   # pLaTeX commands
--   # Matthew Bertucci 2022/07/21 for v2021-11-15
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "platex",
  includes = { "ptex", "latex-document", "latex-dev" },
  lists = {},
  snippets = {
    S({ trig = "\\pfmtname", dscr = "∗", priority = 900 }, { t("\\pfmtname") }, "*"),
    S({ trig = "\\pfmtversion", dscr = "∗", priority = 900 }, { t("\\pfmtversion") }, "*"),
    S({ trig = "\\plIncludeInRelease", dscr = "{date}{command}{description} ∗", priority = 900 }, { t("\\plIncludeInRelease{"), i(1, "date"), t("}{"), i(2, "command"), t("}{"), i(3, "description"), t("}") }, "*"),
    S({ trig = "\\plEndIncludeInRelease", dscr = "∗", priority = 900 }, { t("\\plEndIncludeInRelease") }, "*"),
    S({ trig = "\\Cht", dscr = "∗", priority = 900 }, { t("\\Cht") }, "*"),
    S({ trig = "\\cht", dscr = "∗", priority = 900 }, { t("\\cht") }, "*"),
    S({ trig = "\\Cdp", dscr = "∗", priority = 900 }, { t("\\Cdp") }, "*"),
    S({ trig = "\\cdp", dscr = "∗", priority = 900 }, { t("\\cdp") }, "*"),
    S({ trig = "\\Cwd", dscr = "∗", priority = 900 }, { t("\\Cwd") }, "*"),
    S({ trig = "\\cwd", dscr = "∗", priority = 900 }, { t("\\cwd") }, "*"),
    S({ trig = "\\Cvs", dscr = "∗", priority = 900 }, { t("\\Cvs") }, "*"),
    S({ trig = "\\cvs", dscr = "∗", priority = 900 }, { t("\\cvs") }, "*"),
    S({ trig = "\\Chs", dscr = "∗", priority = 900 }, { t("\\Chs") }, "*"),
    S({ trig = "\\chs", dscr = "∗", priority = 900 }, { t("\\chs") }, "*"),
    S({ trig = "\\cHT", dscr = "∗", priority = 900 }, { t("\\cHT") }, "*"),
    S({ trig = "\\afont", dscr = "∗", priority = 900 }, { t("\\afont") }, "*"),
    S({ trig = "\\tstrutbox", dscr = "∗", priority = 900 }, { t("\\tstrutbox") }, "*"),
    S({ trig = "\\zstrutbox", dscr = "∗", priority = 900 }, { t("\\zstrutbox") }, "*"),
    S({ trig = "\\ystrutbox", dscr = "∗", priority = 900 }, { t("\\ystrutbox") }, "*"),
    S({ trig = "\\tstrut", dscr = "∗", priority = 900 }, { t("\\tstrut") }, "*"),
    S({ trig = "\\zstrut", dscr = "∗", priority = 900 }, { t("\\zstrut") }, "*"),
    S({ trig = "\\ystrut", dscr = "∗", priority = 900 }, { t("\\ystrut") }, "*"),
    S({ trig = "\\DeclareYokoKanjiEncoding", dscr = "{encoding}{text-settings}{math-settings} ∗", priority = 900 }, { t("\\DeclareYokoKanjiEncoding{"), i(1, "encoding"), t("}{"), i(2, "text-settings"), t("}{"), i(3, "math-settings"), t("}") }, "*"),
    S({ trig = "\\DeclareTateKanjiEncoding", dscr = "{encoding}{text-settings}{math-settings} ∗", priority = 900 }, { t("\\DeclareTateKanjiEncoding{"), i(1, "encoding"), t("}{"), i(2, "text-settings"), t("}{"), i(3, "math-settings"), t("}") }, "*"),
    S({ trig = "\\DeclareKanjiEncodingDefaults", dscr = "{text-settings}{math-settings} ∗", priority = 900 }, { t("\\DeclareKanjiEncodingDefaults{"), i(1, "text-settings"), t("}{"), i(2, "math-settings"), t("}") }, "*"),
    S({ trig = "\\KanjiEncodingPair", dscr = "{encoding1}{encoding2} ∗", priority = 900 }, { t("\\KanjiEncodingPair{"), i(1, "encoding1"), t("}{"), i(2, "encoding2"), t("}") }, "*"),
    S({ trig = "\\DeclareKanjiFamily", dscr = "{encoding}{family}{loading-settings} ∗", priority = 900 }, { t("\\DeclareKanjiFamily{"), i(1, "encoding"), t("}{"), i(2, "family"), t("}{"), i(3, "loading-settings"), t("}") }, "*"),
    S({ trig = "\\DeclareKanjiSubstitution", dscr = "{encoding}{family}{series}{shape} ∗", priority = 900 }, { t("\\DeclareKanjiSubstitution{"), i(1, "encoding"), t("}{"), i(2, "family"), t("}{"), i(3, "series"), t("}{"), i(4, "shape"), t("}") }, "*"),
    S({ trig = "\\DeclareErrorKanjiFont", dscr = "{encoding}{family}{series}{shape}{size} ∗", priority = 900 }, { t("\\DeclareErrorKanjiFont{"), i(1, "encoding"), t("}{"), i(2, "family"), t("}{"), i(3, "series"), t("}{"), i(4, "shape"), t("}{"), i(5, "size"), t("}") }, "*"),
    S({ trig = "\\reDeclareMathAlphabet", dscr = "{math-alph}{latin-math-alph}{japanese-math-alph} ∗", priority = 900 }, { t("\\reDeclareMathAlphabet{"), i(1, "math-alph"), t("}{"), i(2, "latin-math-alph"), t("}{"), i(3, "japanese-math-alph"), t("}") }, "*d"),
    S({ trig = "\\DeclareRelationFont", dscr = "{enc1}{fam1}{series1}{shape1}{enc2}{fam2}{series2}{shape2} ∗", priority = 900 }, { t("\\DeclareRelationFont{"), i(1, "enc1"), t("}{"), i(2, "fam1"), t("}{"), i(3, "series1"), t("}{"), i(4, "shape1"), t("}{"), i(5, "enc2"), t("}{"), i(6, "fam2"), t("}{"), i(7, "series2"), t("}{"), i(8, "shape2"), t("}") }, "*"),
    S({ trig = "\\SetRelationFont", dscr = "{enc1}{fam1}{series1}{shape1}{enc2}{fam2}{series2}{shape2} ∗", priority = 900 }, { t("\\SetRelationFont{"), i(1, "enc1"), t("}{"), i(2, "fam1"), t("}{"), i(3, "series1"), t("}{"), i(4, "shape1"), t("}{"), i(5, "enc2"), t("}{"), i(6, "fam2"), t("}{"), i(7, "series2"), t("}{"), i(8, "shape2"), t("}") }, "*"),
    S({ trig = "\\userelfont", dscr = "" }, { t("\\userelfont") }),
    S({ trig = "\\adjustbaseline", dscr = "" }, { t("\\adjustbaseline") }),
    S({ trig = "\\romanencoding", dscr = "{encoding}" }, { t("\\romanencoding{"), i(1, "encoding"), t("}") }),
    S({ trig = "\\kanjiencoding", dscr = "{encoding}" }, { t("\\kanjiencoding{"), i(1, "encoding"), t("}") }),
    S({ trig = "\\romanfamily", dscr = "{family}" }, { t("\\romanfamily{"), i(1, "family"), t("}") }),
    S({ trig = "\\kanjifamily", dscr = "{family}" }, { t("\\kanjifamily{"), i(1, "family"), t("}") }),
    S({ trig = "\\romanseries", dscr = "{series}" }, { t("\\romanseries{"), i(1, "series"), t("}") }),
    S({ trig = "\\kanjiseries", dscr = "{series}" }, { t("\\kanjiseries{"), i(1, "series"), t("}") }),
    S({ trig = "\\romanseriesforce", dscr = "{series} ∗", priority = 900 }, { t("\\romanseriesforce{"), i(1, "series"), t("}") }, "*"),
    S({ trig = "\\kanjiseriesforce", dscr = "{series} ∗", priority = 900 }, { t("\\kanjiseriesforce{"), i(1, "series"), t("}") }, "*"),
    S({ trig = "\\romanshape", dscr = "{shape}" }, { t("\\romanshape{"), i(1, "shape"), t("}") }),
    S({ trig = "\\kanjishape", dscr = "{shape}" }, { t("\\kanjishape{"), i(1, "shape"), t("}") }),
    S({ trig = "\\romanshapeforce", dscr = "{shape} ∗", priority = 900 }, { t("\\romanshapeforce{"), i(1, "shape"), t("}") }, "*"),
    S({ trig = "\\kanjishapeforce", dscr = "{shape} ∗", priority = 900 }, { t("\\kanjishapeforce{"), i(1, "shape"), t("}") }, "*"),
    S({ trig = "\\usekanji", dscr = "{encoding}{family}{series}{shape} ∗", priority = 900 }, { t("\\usekanji{"), i(1, "encoding"), t("}{"), i(2, "family"), t("}{"), i(3, "series"), t("}{"), i(4, "shape"), t("}") }, "*"),
    S({ trig = "\\useroman", dscr = "{encoding}{family}{series}{shape} ∗", priority = 900 }, { t("\\useroman{"), i(1, "encoding"), t("}{"), i(2, "family"), t("}{"), i(3, "series"), t("}{"), i(4, "shape"), t("}") }, "*"),
    S({ trig = "\\kanjiseriesdefault", dscr = "∗", priority = 900 }, { t("\\kanjiseriesdefault") }, "*"),
    S({ trig = "\\mcfamily", dscr = "" }, { t("\\mcfamily") }),
    S({ trig = "\\gtfamily", dscr = "" }, { t("\\gtfamily") }),
    S({ trig = "\\mathmc", dscr = "{text}" }, h.mathwrap({ t("\\mathmc{"), i(1, "text"), t("}") }), "m"),
    S({ trig = "\\mathgt", dscr = "{text}" }, h.mathwrap({ t("\\mathgt{"), i(1, "text"), t("}") }), "m"),
    S({ trig = "\\textmc", dscr = "{text}" }, { t("\\textmc{"), i(1, "text"), t("}") }),
    S({ trig = "\\textgt", dscr = "{text}" }, { t("\\textgt{"), i(1, "text"), t("}") }),
    S({ trig = "\\fixcompositeaccent", dscr = "∗", priority = 900 }, { t("\\fixcompositeaccent") }, "*"),
    S({ trig = "\\nofixcompositeaccent", dscr = "∗", priority = 900 }, { t("\\nofixcompositeaccent") }, "*"),
    S({ trig = "\\<", dscr = "∗", priority = 900 }, { t("\\<") }, "*"),
    S({ trig = "\\removejfmglue", dscr = "∗", priority = 900 }, { t("\\removejfmglue") }, "*"),
    S({ trig = "\\iftombow", dscr = "∗", priority = 900 }, { t("\\iftombow") }, "*"),
    S({ trig = "\\tombowfalse", dscr = "∗", priority = 900 }, { t("\\tombowfalse") }, "*"),
    S({ trig = "\\tombowtrue", dscr = "∗", priority = 900 }, { t("\\tombowtrue") }, "*"),
    S({ trig = "\\iftombowdate", dscr = "∗", priority = 900 }, { t("\\iftombowdate") }, "*"),
    S({ trig = "\\tombowdatetrue", dscr = "∗", priority = 900 }, { t("\\tombowdatetrue") }, "*"),
    S({ trig = "\\tombowdatefalse", dscr = "∗", priority = 900 }, { t("\\tombowdatefalse") }, "*"),
    S({ trig = "\\maketombowbox", dscr = "∗", priority = 900 }, { t("\\maketombowbox") }, "*"),
    S({ trig = "\\printglossary", dscr = "" }, { t("\\printglossary") }),
    S({ trig = "\\hour", dscr = "∗", priority = 900 }, { t("\\hour") }, "*"),
    S({ trig = "\\minute", dscr = "∗", priority = 900 }, { t("\\minute") }, "*"),
    S({ trig = "\\mcdefault", dscr = "∗", priority = 900 }, { t("\\mcdefault") }, "*"),
    S({ trig = "\\gtdefault", dscr = "∗", priority = 900 }, { t("\\gtdefault") }, "*"),
    S({ trig = "\\kanjiencodingdefault", dscr = "∗", priority = 900 }, { t("\\kanjiencodingdefault") }, "*"),
    S({ trig = "\\kanjifamilydefault", dscr = "∗", priority = 900 }, { t("\\kanjifamilydefault") }, "*"),
    S({ trig = "\\kanjishapedefault", dscr = "∗", priority = 900 }, { t("\\kanjishapedefault") }, "*"),
  },
  keyvals = {},
}
