-- Generated by snipgen 1 from Play.cwl; do not edit, regenerate.
-- source: TeXstudio completion/Play.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 61a17c279316c201529614d2dad9a2052c4ef1ee942e4989c44616b5a72e85df
-- cwl-header:
--   # Play package
--   # Matthew Bertucci 10/6/2021
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "Play",
  includes = { "xkeyval", "fontenc", "ifthen", "mweights", "fontaxes" },
  lists = {},
  snippets = {
    S({ trig = "\\sufigures", dscr = "" }, { t("\\sufigures") }),
    S({ trig = "\\supfigures", dscr = "∗", priority = 900 }, { t("\\supfigures") }, "*"),
    S({ trig = "\\textsu", dscr = "{text}" }, { t("\\textsu{"), i(1, "text"), t("}") }),
    S({ trig = "\\textsup", dscr = "{text} ∗", priority = 900 }, { t("\\textsup{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\textsuperior", dscr = "{text} ∗", priority = 900 }, { t("\\textsuperior{"), i(1, "text"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/Play#c",
      lines = {
        "scale=#%<factor%>,MatchLowercase",
        "scaled=#%<factor%>,MatchLowercase",
        "lining",
        "oldstyle",
        "tabular",
        "proportional",
        "mainfont",
        "bold",
        "regular",
      },
    },
  },
}
