-- Generated by snipgen 1 from pldocverb.cwl; do not edit, regenerate.
-- source: TeXstudio completion/pldocverb.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c14c7c4f188948e98606110c65c8ddce072a89977feb0c35931f65ef015657e5
-- cwl-header:
--   # pldocverb package
--   # Matthew Bertucci 2023/02/26 for v0.2a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "pldocverb",
  includes = { "doc", "pxmulticol" },
  lists = {},
  snippets = {
  },
  keyvals = {},
}
