-- Generated by snipgen 1 from plex-serif.cwl; do not edit, regenerate.
-- source: TeXstudio completion/plex-serif.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c808403e25138150cb175247429f4b32523689a1fb366151a014087e2acd45d9
-- cwl-header:
--   # plex-serif package
--   # Matthew Bertucci 2023/09/09
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "plex-serif",
  includes = { "ifxetex", "ifluatex", "xkeyval", "fontenc", "fontaxes", "mweights" },
  lists = {},
  snippets = {
    S({ trig = "\\plexserif", dscr = "" }, { t("\\plexserif") }),
    S({ trig = "\\plexseriflgr", dscr = "" }, { t("\\plexseriflgr") }),
    S({ trig = "\\plexseriffamily", dscr = "∗", priority = 900 }, { t("\\plexseriffamily") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/plex-serif#c",
      lines = {
        "scale=%<factor%>",
        "type1",
        "thin",
        "t",
        "extralight",
        "el",
        "light",
        "l",
        "text",
        "tx",
        "textmd",
        "txmd",
        "medium",
        "m",
        "semibold",
        "sb",
      },
    },
  },
}
