-- Generated by snipgen 1 from powerdot-klope.cwl; do not edit, regenerate.
-- source: TeXstudio completion/powerdot-klope.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: fc81dbf5d01840537620c0c2e7fb09bd9b5215a9fdd053c0bd5913c218904893
-- cwl-header:
--   # powerdot-klope package
--   # Matthew Bertucci 2022/06/03 for v1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "powerdot-klope",
  includes = { "pifont", "pst-slpe" },
  lists = {},
  snippets = {
    S({ trig = "\\titleslide", dscr = "\\begin{titleslide}{title}" }, { t("\\begin{titleslide}{"), i(1, "title"), t({ "}", "\t" }), i(2), t({ "", "\\end{titleslide}" }) }),
    S({ trig = "\\titleslide", dscr = "\\begin{titleslide}[options]{title}" }, { t("\\begin{titleslide}["), i(1, "options"), t("]{"), i(2, "title"), t({ "}", "\t" }), i(3), t({ "", "\\end{titleslide}" }) }),
    S({ trig = "\\basic", dscr = "\\begin{basic}{title} ∗", priority = 900 }, { t("\\begin{basic}{"), i(1, "title"), t({ "}", "\t" }), i(2), t({ "", "\\end{basic}" }) }, "*"),
    S({ trig = "\\basic", dscr = "\\begin{basic}[options]{title} ∗", priority = 900 }, { t("\\begin{basic}["), i(1, "options"), t("]{"), i(2, "title"), t({ "}", "\t" }), i(3), t({ "", "\\end{basic}" }) }, "*"),
    S({ trig = "\\wideslide", dscr = "\\begin{wideslide}{title}" }, { t("\\begin{wideslide}{"), i(1, "title"), t({ "}", "\t" }), i(2), t({ "", "\\end{wideslide}" }) }),
    S({ trig = "\\wideslide", dscr = "\\begin{wideslide}[options]{title}" }, { t("\\begin{wideslide}["), i(1, "options"), t("]{"), i(2, "title"), t({ "}", "\t" }), i(3), t({ "", "\\end{wideslide}" }) }),
    S({ trig = "\\slide", dscr = "\\begin{slide}{title}" }, { t("\\begin{slide}{"), i(1, "title"), t({ "}", "\t" }), i(2), t({ "", "\\end{slide}" }) }),
    S({ trig = "\\slide", dscr = "\\begin{slide}[options]{title}" }, { t("\\begin{slide}["), i(1, "options"), t("]{"), i(2, "title"), t({ "}", "\t" }), i(3), t({ "", "\\end{slide}" }) }),
    S({ trig = "\\sectionslide", dscr = "\\begin{sectionslide}{title}" }, { t("\\begin{sectionslide}{"), i(1, "title"), t({ "}", "\t" }), i(2), t({ "", "\\end{sectionslide}" }) }),
    S({ trig = "\\sectionslide", dscr = "\\begin{sectionslide}[options]{title}" }, { t("\\begin{sectionslide}["), i(1, "options"), t("]{"), i(2, "title"), t({ "}", "\t" }), i(3), t({ "", "\\end{sectionslide}" }) }),
  },
  keyvals = {},
}
