-- Generated by snipgen 1 from progressbar.cwl; do not edit, regenerate.
-- source: TeXstudio completion/progressbar.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 3128ce48c6a796179d851e1dfd43d231187331f2b6ed0f3157a7bd9c8e7c6c8f
-- cwl-header:
--   # progressbar package
--   # Matthew Bertucci 9/2/2021 for v1.0b
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "progressbar",
  includes = { "tikz", "calc" },
  lists = {},
  snippets = {
    S({ trig = "\\progressbar", dscr = "{number}" }, { t("\\progressbar{"), i(1, "number"), t("}") }),
    S({ trig = "\\progressbar", dscr = "[options]{number}" }, { t("\\progressbar["), i(1, "options"), t("]{"), i(2, "number"), t("}") }),
    S({ trig = "\\progressbarchange", dscr = "{options}" }, { t("\\progressbarchange{"), i(1, "options"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\progressbar,\\progressbarchange",
      lines = {
        "heightr=",
        "heighta=##L",
        "roundnessr=",
        "roundnessa=##L",
        "width=##L",
        "borderwidth=##L",
        "subdivisions=##L",
        "tickswidth=##L",
        "ticksheight=##L",
        "linecolor=#%color",
        "tickscolor=#%color",
        "emptycolor=#%color",
        "filledcolor=#%color",
      },
    },
  },
}
