-- Generated by snipgen 1 from pst-diffraction.cwl; do not edit, regenerate.
-- source: TeXstudio completion/pst-diffraction.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: bf84d4cf447d7a229f2ae5394742ec8f71af9e178b7173e9fef4bae0a674c102
-- cwl-header:
--   # pst-diffraction package
--   # Matthew Bertucci 2/25/2022 for v1.02
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "pst-diffraction",
  includes = { "pstricks", "pst-3dplot", "pst-xkey" },
  lists = {},
  snippets = {
    S({ trig = "\\psdiffractionRectangle", dscr = "" }, { t("\\psdiffractionRectangle") }),
    S({ trig = "\\psdiffractionRectangle", dscr = "[options]" }, { t("\\psdiffractionRectangle["), i(1, "options"), t("]") }),
    S({ trig = "\\psdiffractionCircular", dscr = "" }, { t("\\psdiffractionCircular") }),
    S({ trig = "\\psdiffractionCircular", dscr = "[options]" }, { t("\\psdiffractionCircular["), i(1, "options"), t("]") }),
    S({ trig = "\\psdiffractionTriangle", dscr = "" }, { t("\\psdiffractionTriangle") }),
    S({ trig = "\\psdiffractionTriangle", dscr = "[options]" }, { t("\\psdiffractionTriangle["), i(1, "options"), t("]") }),
  },
  keyvals = {
    {
      targets = "\\psdiffractionRectangle",
      lines = {
        "a=%<area%>",
        "Alpha=%<number%>",
        "colorMode=#0,1,2,3",
        "contrast=%<number%>",
        "f=%<focal length%>",
        "IIID#true,false",
        "k=%<height%>",
        "lambda=%<wavelength in nm%>",
        "pixel=%<factor%>",
        "s=%<distance%>",
        "twoSlit",
      },
    },
    {
      targets = "\\psdiffractionCircular",
      lines = {
        "colorMode=#0,1,2,3",
        "contrast=%<number%>",
        "d=%<distance%>",
        "f=%<focal length%>",
        "IIID#true,false",
        "lambda=%<wavelength in nm%>",
        "pixel=%<factor%>",
        "r=%<radius%>",
        "twoHole",
      },
    },
    {
      targets = "\\psdiffractionTriangle",
      lines = {
        "colorMode=#0,1,2,3",
        "contrast=%<number%>",
        "f=%<focal length%>",
        "h=%<height%>",
        "scale=%<factor%>",
        "IIID#true,false",
        "lambda=%<wavelength in nm%>",
      },
    },
  },
}
