-- Generated by snipgen 1 from pst-fit.cwl; do not edit, regenerate.
-- source: TeXstudio completion/pst-fit.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 4472892147c64d968b3e5e0b8191effa625637ae8807b32595ef4d51a65baf9c
-- cwl-header:
--   # pst-fit package
--   # Matthew Bertucci 2024/03/18 for v0.03
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "pst-fit",
  includes = { "pstricks", "pst-tools", "pstricks-add", "pst-xkey" },
  lists = {},
  snippets = {
  },
  keyvals = {},
}
