-- Generated by snipgen 1 from pst-spinner.cwl; do not edit, regenerate.
-- source: TeXstudio completion/pst-spinner.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b04865a57dedaee717d5e9699885da594501bf87f2286a2526d0bbf6c3f699cb
-- cwl-header:
--   # pst-spinner package
--   # Matthew Bertucci 2/22/2022 for v1.02
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "pst-spinner",
  includes = { "pstricks", "pst-node", "pst-xkey" },
  lists = {},
  snippets = {
    S({ trig = "\\psFidgetSpinner", dscr = "" }, { t("\\psFidgetSpinner") }),
    S({ trig = "\\psFidgetSpinner", dscr = "(x,y)" }, { t("\\psFidgetSpinner("), i(1, "x,y"), t(")") }),
    S({ trig = "\\psFidgetSpinner", dscr = "[options]" }, { t("\\psFidgetSpinner["), i(1, "options"), t("]") }),
    S({ trig = "\\psFidgetSpinner", dscr = "[options](x,y)" }, { t("\\psFidgetSpinner["), i(1, "options"), t("]("), i(2, "x,y"), t(")") }),
  },
  keyvals = {
    {
      targets = "\\psFidgetSpinner#c",
      lines = {
        "R=%<radius%>",
        "color0=#%color",
        "color1=#%color",
        "color2=#%color",
        "color3=#%color",
        "colorMask=#%color",
        "rotation=%<degrees%>",
        "mask#true,false",
        "customize#true,false",
        "customizeMask#true,false",
        "image=%<imagefile%>",
        "fillcolor=#%color",
        "linecolor=#%color",
        "linewidth=##L",
      },
    },
  },
}
