-- Generated by snipgen 1 from pymacros.cwl; do not edit, regenerate.
-- source: TeXstudio completion/pymacros.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: ad5ca27a12c2eada77de26f8405d50805e582599db13efe850ab4c7f18f03943
-- cwl-header:
--   # pymacros package
--   # Matthew Bertucci 12/16/2021 for v0.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "pymacros",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\colonEq", dscr = "" }, h.mathwrap({ t("\\colonEq") }), "m"),
    S({ trig = "\\pytag", dscr = "{tag}{code}" }, { t("\\pytag{"), i(1, "tag"), t("}{"), i(2, "code"), t("}") }),
    S({ trig = "\\py", dscr = "{tag}" }, { t("\\py{"), i(1, "tag"), t("}") }),
    S({ trig = "\\py*", dscr = "{tag}" }, { t("\\py*{"), i(1, "tag"), t("}") }),
    S({ trig = "\\Py", dscr = "{tag}" }, { t("\\Py{"), i(1, "tag"), t("}") }),
    S({ trig = "\\Py*", dscr = "{tag}" }, { t("\\Py*{"), i(1, "tag"), t("}") }),
    S({ trig = "\\Py*", dscr = "[space]{tag}" }, { t("\\Py*["), i(1, "space"), t("]{"), i(2, "tag"), t("}") }),
    S({ trig = "\\Dmath", dscr = "{formula}" }, { t("\\Dmath{"), i(1, "formula"), t("}") }),
    S({ trig = "\\Dmath", dscr = "[options]{formula}" }, { t("\\Dmath["), i(1, "options"), t("]{"), i(2, "formula"), t("}") }),
    S({ trig = "\\Dmath*", dscr = "{formula}" }, { t("\\Dmath*{"), i(1, "formula"), t("}") }),
    S({ trig = "\\Dmath*", dscr = "[options]{formula}" }, { t("\\Dmath*["), i(1, "options"), t("]{"), i(2, "formula"), t("}") }),
    S({ trig = "\\ttTag", dscr = "{tag}" }, { t("\\ttTag{"), i(1, "tag"), t("}") }),
    S({ trig = "\\pglabel", dscr = "{label} ∗", priority = 900 }, { t("\\pglabel{"), i(1, "label"), t("}") }, "*l"),
  },
  keyvals = {
    {
      targets = "\\Dmath,\\Dmath*",
      lines = {
        "style=%<cmds%>",
        "number=%<text%>",
        "labelprefix=%<prefix%>",
        "label=##l",
        "indentstep=##L",
        "compact",
        "compact=%<number%>",
        "spread=##L",
        "frame",
        "frame=##L",
        "framesep=##L",
        "breakdepth=%<number%>",
        "shiftnumber",
        "holdnumber",
        "density=",
        "layout=",
        "shortskiplimit=##L",
        "background=#%color",
        "color=#%color",
        "center",
        "nocenter",
      },
    },
  },
}
