-- Generated by snipgen 1 from randtext.cwl; do not edit, regenerate.
-- source: TeXstudio completion/randtext.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 96baee0c169e1ad5831270125b5840bd899f7eeb95e7d92271386b569cbf527c
-- cwl-header:
--   # randtext package
--   # Matthew Bertucci 11/2/2021
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "randtext",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\randomize", dscr = "{text}" }, { t("\\randomize{"), i(1, "text"), t("}") }),
  },
  keyvals = {},
}
