-- Generated by snipgen 1 from rangen.cwl; do not edit, regenerate.
-- source: TeXstudio completion/rangen.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 424d43213ecb8fe99dabcf1b3ee4f190166907322a7cc38e63c18594b724a7d9
-- cwl-header:
--   # rangen package
--   # Matthew Bertucci 2022/05/10 for v1.4
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "rangen",
  includes = { "lcg" },
  lists = {},
  snippets = {
    S({ trig = "\\RandomZ", dscr = "{cmd}{int1}{int2}" }, { t("\\RandomZ{"), i(1, "cmd"), t("}{"), i(2, "int1"), t("}{"), i(3, "int2"), t("}") }, "d"),
    S({ trig = "\\RandomZ", dscr = "[options]{cmd}{int1}{int2}" }, { t("\\RandomZ["), i(1, "options"), t("]{"), i(2, "cmd"), t("}{"), i(3, "int1"), t("}{"), i(4, "int2"), t("}") }, "d"),
    S({ trig = "\\nOf", dscr = "{\\name}" }, { t("\\nOf{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\dOf", dscr = "{\\name}" }, { t("\\dOf{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\fmt", dscr = "{\\name}" }, { t("\\fmt{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\ds", dscr = "{\\name}" }, { t("\\ds{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\RandomQ", dscr = "{cmd}{num1}{num2}" }, { t("\\RandomQ{"), i(1, "cmd"), t("}{"), i(2, "num1"), t("}{"), i(3, "num2"), t("}") }, "d"),
    S({ trig = "\\RandomQ", dscr = "{cmd}[max denom]{num1}{num2}" }, { t("\\RandomQ{"), i(1, "cmd"), t("}["), i(2, "max denom"), t("]{"), i(3, "num1"), t("}{"), i(4, "num2"), t("}") }, "d"),
    S({ trig = "\\RandomZ", dscr = "[options]{cmd}{num1}{num2}" }, { t("\\RandomZ["), i(1, "options"), t("]{"), i(2, "cmd"), t("}{"), i(3, "num1"), t("}{"), i(4, "num2"), t("}") }, "d"),
    S({ trig = "\\RandomZ", dscr = "[options]{cmd}[max denom]{num1}{num2}" }, { t("\\RandomZ["), i(1, "options"), t("]{"), i(2, "cmd"), t("}["), i(3, "max denom"), t("]{"), i(4, "num1"), t("}{"), i(5, "num2"), t("}") }, "d"),
    S({ trig = "\\RandomR", dscr = "{cmd}{int1}{int2}" }, { t("\\RandomR{"), i(1, "cmd"), t("}{"), i(2, "int1"), t("}{"), i(3, "int2"), t("}") }, "d"),
    S({ trig = "\\RandomR", dscr = "[options]{cmd}{int1}{int2}" }, { t("\\RandomR["), i(1, "options"), t("]{"), i(2, "cmd"), t("}{"), i(3, "int1"), t("}{"), i(4, "int2"), t("}") }, "d"),
    S({ trig = "\\RNGpowerOfTen", dscr = "∗", priority = 900 }, { t("\\RNGpowerOfTen") }, "*"),
    S({ trig = "\\nDivisionsPowerOfTen", dscr = "{integer}" }, { t("\\nDivisionsPowerOfTen{"), i(1, "integer"), t("}") }),
    S({ trig = "\\RandomL", dscr = "{cmd}{n1,n2,...}" }, { t("\\RandomL{"), i(1, "cmd"), t("}{"), i(2, "n1,n2,..."), t("}") }, "d"),
    S({ trig = "\\RandomL", dscr = "[options]{cmd}{n1,n2,...}" }, { t("\\RandomL["), i(1, "options"), t("]{"), i(2, "cmd"), t("}{"), i(3, "n1,n2,..."), t("}") }, "d"),
    S({ trig = "\\RandomI", dscr = "{cmd}{integer}" }, { t("\\RandomI{"), i(1, "cmd"), t("}{"), i(2, "integer"), t("}") }, "d"),
    S({ trig = "\\RandomP", dscr = "{cmd}{list of literals}" }, { t("\\RandomP{"), i(1, "cmd"), t("}{"), i(2, "list of literals"), t("}") }, "d"),
    S({ trig = "\\RandomP", dscr = "[options]{cmd}{list of literals}" }, { t("\\RandomP["), i(1, "options"), t("]{"), i(2, "cmd"), t("}{"), i(3, "list of literals"), t("}") }, "d"),
    S({ trig = "\\iOf", dscr = "{\\name}" }, { t("\\iOf{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\RandomS", dscr = "{cmd}" }, { t("\\RandomS{"), i(1, "cmd"), t("}") }, "d"),
    S({ trig = "\\RandomS", dscr = "[dec]{cmd}" }, { t("\\RandomS["), i(1, "dec"), t("]{"), i(2, "cmd"), t("}") }, "d"),
    S({ trig = "\\cfmt", dscr = "{\\name}" }, { t("\\cfmt{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\efmt", dscr = "{\\name}" }, { t("\\efmt{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\cds", dscr = "{\\name}" }, { t("\\cds{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\eds", dscr = "{\\name}" }, { t("\\eds{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\typeOf", dscr = "{\\name}" }, { t("\\typeOf{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\defineZ", dscr = "{cmd}{integer}" }, { t("\\defineZ{"), i(1, "cmd"), t("}{"), i(2, "integer"), t("}") }, "d"),
    S({ trig = "\\defineQ", dscr = "{cmd}{numerator}{denominator}" }, { t("\\defineQ{"), i(1, "cmd"), t("}{"), i(2, "numerator"), t("}{"), i(3, "denominator"), t("}") }, "d"),
    S({ trig = "\\defineR", dscr = "{cmd}{number}" }, { t("\\defineR{"), i(1, "cmd"), t("}{"), i(2, "number"), t("}") }, "d"),
    S({ trig = "\\reduceFrac", dscr = "{numerator}{denominator}" }, { t("\\reduceFrac{"), i(1, "numerator"), t("}{"), i(2, "denominator"), t("}") }),
    S({ trig = "\\rfNumer", dscr = "" }, { t("\\rfNumer") }),
    S({ trig = "\\rfDenom", dscr = "" }, { t("\\rfDenom") }),
    S({ trig = "\\gcd", dscr = "{int1}{int2}" }, { t("\\gcd{"), i(1, "int1"), t("}{"), i(2, "int2"), t("}") }),
    S({ trig = "\\thegcd", dscr = "" }, { t("\\thegcd") }),
    S({ trig = "\\lcm", dscr = "{int1}{int2}" }, { t("\\lcm{"), i(1, "int1"), t("}{"), i(2, "int2"), t("}") }),
    S({ trig = "\\thelcm", dscr = "" }, { t("\\thelcm") }),
    S({ trig = "\\RNGprintf", dscr = "{string}" }, { t("\\RNGprintf{"), i(1, "string"), t("}") }),
    S({ trig = "\\defineDepQJS", dscr = "{cmd}{numerator}{denominator}{script}" }, { t("\\defineDepQJS{"), i(1, "cmd"), t("}{"), i(2, "numerator"), t("}{"), i(3, "denominator"), t("}{"), i(4, "script"), t("}") }, "d"),
    S({ trig = "\\js", dscr = "{\\name}" }, { t("\\js{"), i(1, "\\name"), t("}") }),
    S({ trig = "\\writeRVsTo", dscr = "\\begin{writeRVsTo}{quizzes|exercises}" }, { t("\\begin{writeRVsTo}{"), i(1, "quizzes|exercises"), t({ "}", "\t" }), i(2), t({ "", "\\end{writeRVsTo}" }) }),
    S({ trig = "\\RNGadd", dscr = "{\\name1}{\\name2}" }, { t("\\RNGadd{"), i(1, "\\name1"), t("}{"), i(2, "\\name2"), t("}") }),
    S({ trig = "\\zZero", dscr = "" }, { t("\\zZero") }),
    S({ trig = "\\zOne", dscr = "" }, { t("\\zOne") }),
    S({ trig = "\\zMinusOne", dscr = "" }, { t("\\zMinusOne") }),
    S({ trig = "\\rPI", dscr = "" }, { t("\\rPI") }),
    S({ trig = "\\rE", dscr = "" }, { t("\\rE") }),
    S({ trig = "\\amodb", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\amodb{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\cntNumDec", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\cntNumDec{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\convertRatTo", dscr = "{arg1}{arg2}{arg3} ∗", priority = 900 }, { t("\\convertRatTo{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}{"), i(3, "arg3"), t("}") }, "*"),
    S({ trig = "\\decPls", dscr = "∗", priority = 900 }, { t("\\decPls") }, "*"),
    S({ trig = "\\loopCnt", dscr = "∗", priority = 900 }, { t("\\loopCnt") }, "*"),
    S({ trig = "\\maxLoopLimit", dscr = "∗", priority = 900 }, { t("\\maxLoopLimit") }, "*"),
    S({ trig = "\\reseedEachRun", dscr = "∗", priority = 900 }, { t("\\reseedEachRun") }, "*"),
    S({ trig = "\\retnmod", dscr = "∗", priority = 900 }, { t("\\retnmod") }, "*"),
    S({ trig = "\\rndnDec", dscr = "∗", priority = 900 }, { t("\\rndnDec") }, "*"),
    S({ trig = "\\rndPower", dscr = "∗", priority = 900 }, { t("\\rndPower") }, "*"),
    S({ trig = "\\RNGparseRat", dscr = "{arg1} ∗", priority = 900 }, { t("\\RNGparseRat{"), i(1, "arg1"), t("}") }, "*"),
    S({ trig = "\\RNGround", dscr = "{arg1}{arg2}{arg3} ∗", priority = 900 }, { t("\\RNGround{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}{"), i(3, "arg3"), t("}") }, "*"),
    S({ trig = "\\seedCnt", dscr = "∗", priority = 900 }, { t("\\seedCnt") }, "*"),
    S({ trig = "\\simplifyCurrentQ", dscr = "∗", priority = 900 }, { t("\\simplifyCurrentQ") }, "*"),
    S({ trig = "\\simplifyCurrentR", dscr = "∗", priority = 900 }, { t("\\simplifyCurrentR") }, "*"),
    S({ trig = "\\syncronizeQs", dscr = "{arg1} ∗", priority = 900 }, { t("\\syncronizeQs{"), i(1, "arg1"), t("}") }, "*"),
    S({ trig = "\\theseDigits", dscr = "∗", priority = 900 }, { t("\\theseDigits") }, "*"),
    S({ trig = "\\thisseed", dscr = "∗", priority = 900 }, { t("\\thisseed") }, "*"),
    S({ trig = "\\typeCodeForq", dscr = "∗", priority = 900 }, { t("\\typeCodeForq") }, "*"),
    S({ trig = "\\typeCodeForr", dscr = "∗", priority = 900 }, { t("\\typeCodeForr") }, "*"),
    S({ trig = "\\typeCodeForz", dscr = "∗", priority = 900 }, { t("\\typeCodeForz") }, "*"),
    S({ trig = "\\updateQ", dscr = "{arg1}{arg2}{arg3} ∗", priority = 900 }, { t("\\updateQ{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}{"), i(3, "arg3"), t("}") }, "*"),
    S({ trig = "\\updateZ", dscr = "{arg1}{arg2} ∗", priority = 900 }, { t("\\updateZ{"), i(1, "arg1"), t("}{"), i(2, "arg2"), t("}") }, "*"),
    S({ trig = "\\varType", dscr = "∗", priority = 900 }, { t("\\varType") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/rangen#c",
      lines = {
        "testmode",
        "counter=%<counter%>",
        "first=%<integer%>",
        "last=%<integer%>",
        "seed=%<integer%>",
        "quiet",
      },
    },
    {
      targets = "\\RandomZ,\\RandomQ,\\RandomR",
      lines = {
        "ne=%<integer(s)%>",
      },
    },
    {
      targets = "\\RandomR",
      lines = {
        "round=%<integer%>",
        "showzeros#true,false",
      },
    },
    {
      targets = "\\RandomL,\\RandomP",
      lines = {
        "index=%<integer%>",
      },
    },
  },
}
