-- Generated by snipgen 1 from regexpatch.cwl; do not edit, regenerate.
-- source: TeXstudio completion/regexpatch.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 505b205c2c4eff289e1fbbea89d991cecdf35b0b2b39952b185e7f8526080a2b
-- cwl-header:
--   # regexpatch package
--   # muzimuzhi 18 Jan 2020, add cwl for regexpatch v0.2d
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "regexpatch",
  includes = { "patch-common" },
  lists = {},
  snippets = {
    S({ trig = "\\xpatchcmd*", dscr = "{command}{search}{replace all}{success}{failure}" }, { t("\\xpatchcmd*{"), i(1, "command"), t("}{"), i(2, "search"), t("}{"), i(3, "replace all"), t("}{"), i(4, "success"), t("}{"), i(5, "failure"), t("}") }),
    S({ trig = "\\xpatchbibmacro*", dscr = "{name}{search}{replace all}{success}{failure}" }, { t("\\xpatchbibmacro*{"), i(1, "name"), t("}{"), i(2, "search"), t("}{"), i(3, "replace all"), t("}{"), i(4, "success"), t("}{"), i(5, "failure"), t("}") }),
    S({ trig = "\\xpatchbibdriver*", dscr = "{name}{search}{replace all}{success}{failure}" }, { t("\\xpatchbibdriver*{"), i(1, "name"), t("}{"), i(2, "search"), t("}{"), i(3, "replace all"), t("}{"), i(4, "success"), t("}{"), i(5, "failure"), t("}") }),
    S({ trig = "\\xpatchfieldformat*", dscr = "[entry type]{name}{search}{replace all}{success}{failure}" }, { t("\\xpatchfieldformat*["), i(1, "entry type"), t("]{"), i(2, "name"), t("}{"), i(3, "search"), t("}{"), i(4, "replace all"), t("}{"), i(5, "success"), t("}{"), i(6, "failure"), t("}") }),
    S({ trig = "\\xpatchnameformat*", dscr = "[entry type]{name}{search}{replace all}{success}{failure}" }, { t("\\xpatchnameformat*["), i(1, "entry type"), t("]{"), i(2, "name"), t("}{"), i(3, "search"), t("}{"), i(4, "replace all"), t("}{"), i(5, "success"), t("}{"), i(6, "failure"), t("}") }),
    S({ trig = "\\xpatchlistformat*", dscr = "[entry type]{name}{search}{replace all}{success}{failure}" }, { t("\\xpatchlistformat*["), i(1, "entry type"), t("]{"), i(2, "name"), t("}{"), i(3, "search"), t("}{"), i(4, "replace all"), t("}{"), i(5, "success"), t("}{"), i(6, "failure"), t("}") }),
    S({ trig = "\\xpatchindexfieldformat*", dscr = "[entry type]{name}{search}{replace all}{success}{failure}" }, { t("\\xpatchindexfieldformat*["), i(1, "entry type"), t("]{"), i(2, "name"), t("}{"), i(3, "search"), t("}{"), i(4, "replace all"), t("}{"), i(5, "success"), t("}{"), i(6, "failure"), t("}") }),
    S({ trig = "\\xpatchindexnameformat*", dscr = "[entry type]{name}{search}{replace all}{success}{failure}" }, { t("\\xpatchindexnameformat*["), i(1, "entry type"), t("]{"), i(2, "name"), t("}{"), i(3, "search"), t("}{"), i(4, "replace all"), t("}{"), i(5, "success"), t("}{"), i(6, "failure"), t("}") }),
    S({ trig = "\\xpatchindexlistformat*", dscr = "[entry type]{name}{search}{replace all}{success}{failure}" }, { t("\\xpatchindexlistformat*["), i(1, "entry type"), t("]{"), i(2, "name"), t("}{"), i(3, "search"), t("}{"), i(4, "replace all"), t("}{"), i(5, "success"), t("}{"), i(6, "failure"), t("}") }),
    S({ trig = "\\regexpatchcmd", dscr = "{command}{search}{replace once}{success}{failure}" }, { t("\\regexpatchcmd{"), i(1, "command"), t("}{"), i(2, "search"), t("}{"), i(3, "replace once"), t("}{"), i(4, "success"), t("}{"), i(5, "failure"), t("}") }),
    S({ trig = "\\regexpatchcmd*", dscr = "{command}{search}{replace all}{success}{failure}" }, { t("\\regexpatchcmd*{"), i(1, "command"), t("}{"), i(2, "search"), t("}{"), i(3, "replace all"), t("}{"), i(4, "success"), t("}{"), i(5, "failure"), t("}") }),
    S({ trig = "\\regexpatchbibmacro", dscr = "{name}{search}{replace once}{success}{failure}" }, { t("\\regexpatchbibmacro{"), i(1, "name"), t("}{"), i(2, "search"), t("}{"), i(3, "replace once"), t("}{"), i(4, "success"), t("}{"), i(5, "failure"), t("}") }),
    S({ trig = "\\regexpatchbibmacro*", dscr = "{name}{search}{replace all}{success}{failure}" }, { t("\\regexpatchbibmacro*{"), i(1, "name"), t("}{"), i(2, "search"), t("}{"), i(3, "replace all"), t("}{"), i(4, "success"), t("}{"), i(5, "failure"), t("}") }),
    S({ trig = "\\xshowcmd*", dscr = "{command}" }, { t("\\xshowcmd*{"), i(1, "command"), t("}") }),
    S({ trig = "\\xpatchoptarg", dscr = "{name}{replace}" }, { t("\\xpatchoptarg{"), i(1, "name"), t("}{"), i(2, "replace"), t("}") }),
    S({ trig = "\\xpatchparametertext", dscr = "{name}{search}{replace}{success}{failure}" }, { t("\\xpatchparametertext{"), i(1, "name"), t("}{"), i(2, "search"), t("}{"), i(3, "replace"), t("}{"), i(4, "success"), t("}{"), i(5, "failure"), t("}") }),
    S({ trig = "\\checkpatchable", dscr = "{name}" }, { t("\\checkpatchable{"), i(1, "name"), t("}") }),
    S({ trig = "\\tracingxpatches", dscr = "" }, { t("\\tracingxpatches") }),
    S({ trig = "\\tracingxpatches", dscr = "[0 or 1]" }, { t("\\tracingxpatches["), i(1, "0 or 1"), t("]") }),
  },
  keyvals = {},
}
