-- Generated by snipgen 1 from romannum.cwl; do not edit, regenerate.
-- source: TeXstudio completion/romannum.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 0c7efbe4a603e9d58f9a4b20d17933f19f3ae5025dd665534f4dd80a4601d09f
-- cwl-header:
--   # romannum package
--   # Matthew Bertucci 9/2/2021 for v1.0b
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "romannum",
  includes = { "stdclsdv" },
  lists = {},
  snippets = {
    S({ trig = "\\Romannum", dscr = "{integer}" }, { t("\\Romannum{"), i(1, "integer"), t("}") }),
    S({ trig = "\\romannum", dscr = "{integer}" }, { t("\\romannum{"), i(1, "integer"), t("}") }),
  },
  keyvals = {},
}
