-- Generated by snipgen 1 from rviewport.cwl; do not edit, regenerate.
-- source: TeXstudio completion/rviewport.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9a0e7213f2fe5d419c384c1f2efa08009c932b2b39b8cb5addd25060a7877492
-- cwl-header:
--   # rviewport package
--   # Matthew Bertucci 2/2/2022 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "rviewport",
  includes = { "keyval" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\includegraphics",
      lines = {
        "rviewport=%<llx lly urx ury%>",
      },
    },
  },
}
