-- Generated by snipgen 1 from scrjura.cwl; do not edit, regenerate.
-- source: TeXstudio completion/scrjura.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9552cecba0177f336c50b963cfe99cb39a8c1f0b4ca7a42d119ff80834c16a2c
-- cwl-header:
--   # scrjura package
--   # Matthew Bertucci 2024/10/15 for v3.42
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "scrjura",
  includes = { "contract", "scrlogo" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\usepackage/scrjura#c",
      lines = {
        "juratotoc=%<true|false|<integer>%>",
        "juratocindent=##L",
        "juratocnumberwidth=##L",
        "contract",
        "juratitlepagebreak#true,false",
        "clausemark=#both,false,off,no,forceboth,forceright,right",
        "parnumber=#auto,true,false,manual",
        "ref=#long,numeric,clauseonly,onlyclause,ClauseOnly,OnlyClause,parlong,longpar,ParL,parnumeric,numericpar,ParN,paroff,nopar,parshort,shortpar,ParS,sentencelong,longsentence,SentenceL,sentencenumeric,numericsentence,SentenceN,sentenceoff,nosentence,sentenceshort,shortsentence,SentenceS,short",
      },
    },
  },
}
