-- Generated by snipgen 1 from sdapsarray.cwl; do not edit, regenerate.
-- source: TeXstudio completion/sdapsarray.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f171261c6ef4210bbec7933f124d50ef0b9ca47412548b31b7081d681e66e6bc
-- cwl-header:
--   # sdapsarray package
--   # Matthew Bertucci 12/18/2021 for v0.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "sdapsarray",
  includes = { "sdapsbase" },
  lists = {},
  snippets = {
    S({ trig = "\\sdapsarray", dscr = "\\begin{sdapsarray}" }, { t({ "\\begin{sdapsarray}", "\t" }), i(1), t({ "", "\\end{sdapsarray}" }) }, "\\tabular"),
    S({ trig = "\\sdapsarray", dscr = "\\begin{sdapsarray}[options]" }, { t("\\begin{sdapsarray}["), i(1, "options"), t({ "]", "\t" }), i(2), t({ "", "\\end{sdapsarray}" }) }, "\\tabular"),
    S({ trig = "\\sdapsnested", dscr = "{content}" }, { t("\\sdapsnested{"), i(1, "content"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\begin{sdapsarray}",
      lines = {
        "flip#true,false",
        "layouter=#default,rotated",
        "angle=%<angle%>",
        "align=%<string%>",
        "keepenv",
        "no_header#true,false",
        "colsep=##L",
        "rowsep=##L",
      },
    },
  },
}
