-- Generated by snipgen 1 from secdot.cwl; do not edit, regenerate.
-- source: TeXstudio completion/secdot.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 8301a3352a8f682ceff80cfd78898d5cf4c1896ba2ca0a54d2f3ba3a18de0cc2
-- cwl-header:
--   # secdot package
--   # Matthew Bertucci 4/4/2022 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "secdot",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\sectiondot", dscr = "{level}" }, { t("\\sectiondot{"), i(1, "level"), t("}") }),
    S({ trig = "\\sectionpunct", dscr = "{level}{punctuation}" }, { t("\\sectionpunct{"), i(1, "level"), t("}{"), i(2, "punctuation"), t("}") }),
  },
  keyvals = {},
}
