-- Generated by snipgen 1 from silence.cwl; do not edit, regenerate.
-- source: TeXstudio completion/silence.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 07bb46ddce66b3496746194a011fe84a923da447807d39261ecc542a152b464e
-- cwl-header:
--   # silence package
--   # Matthew Bertucci 11/6/2021 for v1.5b
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "silence",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\WarningsOff", dscr = "" }, { t("\\WarningsOff") }),
    S({ trig = "\\WarningsOff", dscr = "[list]" }, { t("\\WarningsOff["), i(1, "list"), t("]") }),
    S({ trig = "\\WarningsOff*", dscr = "" }, { t("\\WarningsOff*") }),
    S({ trig = "\\ErrorsOff", dscr = "" }, { t("\\ErrorsOff") }),
    S({ trig = "\\ErrorsOff", dscr = "[list]" }, { t("\\ErrorsOff["), i(1, "list"), t("]") }),
    S({ trig = "\\ErrorsOff*", dscr = "" }, { t("\\ErrorsOff*") }),
    S({ trig = "\\WarningsOn", dscr = "" }, { t("\\WarningsOn") }),
    S({ trig = "\\WarningsOn", dscr = "[list]" }, { t("\\WarningsOn["), i(1, "list"), t("]") }),
    S({ trig = "\\ErrorsOn", dscr = "" }, { t("\\ErrorsOn") }),
    S({ trig = "\\ErrorsOn", dscr = "[list]" }, { t("\\ErrorsOn["), i(1, "list"), t("]") }),
    S({ trig = "\\WarningFilter", dscr = "{package}{message}" }, { t("\\WarningFilter{"), i(1, "package"), t("}{"), i(2, "message"), t("}") }),
    S({ trig = "\\WarningFilter", dscr = "[family]{package}{message}" }, { t("\\WarningFilter["), i(1, "family"), t("]{"), i(2, "package"), t("}{"), i(3, "message"), t("}") }),
    S({ trig = "\\ErrorFilter", dscr = "{package}{message}" }, { t("\\ErrorFilter{"), i(1, "package"), t("}{"), i(2, "message"), t("}") }),
    S({ trig = "\\ErrorFilter", dscr = "[family]{package}{message}" }, { t("\\ErrorFilter["), i(1, "family"), t("]{"), i(2, "package"), t("}{"), i(3, "message"), t("}") }),
    S({ trig = "\\ActivateWarningFilters", dscr = "" }, { t("\\ActivateWarningFilters") }),
    S({ trig = "\\ActivateWarningFilters", dscr = "[list]" }, { t("\\ActivateWarningFilters["), i(1, "list"), t("]") }),
    S({ trig = "\\ActivateErrorFilters", dscr = "" }, { t("\\ActivateErrorFilters") }),
    S({ trig = "\\ActivateErrorFilters", dscr = "[list]" }, { t("\\ActivateErrorFilters["), i(1, "list"), t("]") }),
    S({ trig = "\\DeactivateWarningFilters", dscr = "" }, { t("\\DeactivateWarningFilters") }),
    S({ trig = "\\DeactivateWarningFilters", dscr = "[list]" }, { t("\\DeactivateWarningFilters["), i(1, "list"), t("]") }),
    S({ trig = "\\DeactivateErrorFilters", dscr = "" }, { t("\\DeactivateErrorFilters") }),
    S({ trig = "\\DeactivateErrorFilters", dscr = "[list]" }, { t("\\DeactivateErrorFilters["), i(1, "list"), t("]") }),
    S({ trig = "\\ActivateFilters", dscr = "" }, { t("\\ActivateFilters") }),
    S({ trig = "\\ActivateFilters", dscr = "[list]" }, { t("\\ActivateFilters["), i(1, "list"), t("]") }),
    S({ trig = "\\DeactivateFilters", dscr = "" }, { t("\\DeactivateFilters") }),
    S({ trig = "\\DeactivateFilters", dscr = "[list]" }, { t("\\DeactivateFilters["), i(1, "list"), t("]") }),
    S({ trig = "\\WarningFilter*", dscr = "{name}{message}" }, { t("\\WarningFilter*{"), i(1, "name"), t("}{"), i(2, "message"), t("}") }),
    S({ trig = "\\WarningFilter*", dscr = "[family]{name}{message}" }, { t("\\WarningFilter*["), i(1, "family"), t("]{"), i(2, "name"), t("}{"), i(3, "message"), t("}") }),
    S({ trig = "\\ErrorFilter*", dscr = "{name}{message}" }, { t("\\ErrorFilter*{"), i(1, "name"), t("}{"), i(2, "message"), t("}") }),
    S({ trig = "\\ErrorFilter*", dscr = "[family]{name}{message}" }, { t("\\ErrorFilter*["), i(1, "family"), t("]{"), i(2, "name"), t("}{"), i(3, "message"), t("}") }),
    S({ trig = "\\SafeMode", dscr = "" }, { t("\\SafeMode") }),
    S({ trig = "\\BoldMode", dscr = "" }, { t("\\BoldMode") }),
  },
  keyvals = {},
}
