-- Generated by snipgen 1 from sillypage.cwl; do not edit, regenerate.
-- source: TeXstudio completion/sillypage.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 1690f6c0afbbad0b7ee9d8f246b01ca1c24f6ca786fc03a03b4d8a42c6d1a6be
-- cwl-header:
--   # sillypage package
--   # Matthew Bertucci 2/3/2022 for v1.4
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "sillypage",
  includes = { "graphicx" },
  lists = {},
  snippets = {
    S({ trig = "\\silly", dscr = "{counter}" }, { t("\\silly{"), i(1, "counter"), t("}") }),
    S({ trig = "\\sillystep", dscr = "{integer}" }, { t("\\sillystep{"), i(1, "integer"), t("}") }),
    S({ trig = "\\sillynumeral", dscr = "{integer}" }, { t("\\sillynumeral{"), i(1, "integer"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\pagenumbering#c",
      lines = {
        "silly",
        "sillynumeral",
      },
    },
  },
}
