-- Generated by snipgen 1 from snaptodo.cwl; do not edit, regenerate.
-- source: TeXstudio completion/snaptodo.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: af8851f129586759171dc82127b0178f4a8cca0d7ba40d5e38c47d51b5afec4f
-- cwl-header:
--   # snaptodo package
--   # Matthew Bertucci 11/27/2021
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "snaptodo",
  includes = { "tikzpagenodes" },
  lists = {},
  snippets = {
    S({ trig = "\\snaptodo", dscr = "{text}" }, { t("\\snaptodo{"), i(1, "text"), t("}") }, "D"),
    S({ trig = "\\snaptodo", dscr = "[options]{text}" }, { t("\\snaptodo["), i(1, "options"), t("]{"), i(2, "text"), t("}") }, "D"),
    S({ trig = "\\snaptodoset", dscr = "{options}" }, { t("\\snaptodoset{"), i(1, "options"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\snaptodo,\\snaptodoset",
      lines = {
        "call chain/.style={%<TikZ styles%>}",
        "margin block/.style={%<TikZ styles%>}",
        "block sep=##L",
        "chain sep=##L",
        "chain bias=##L",
        "block rise=##L",
      },
    },
  },
}
