-- Generated by snipgen 1 from stacklet.cwl; do not edit, regenerate.
-- source: TeXstudio completion/stacklet.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 252fed8c15d03d3a3909ccd5f7bcbc3354c1c74649b6fdfe8ffdc0d8592e1164
-- cwl-header:
--   # stacklet package
--   # Matthew Bertucci 10/27/2021 for v0.3a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "stacklet",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\PushCatMakeLetter", dscr = "\\<char> ∗", priority = 900 }, { t("\\PushCatMakeLetter\\"), i(1, "<char>") }, "*"),
    S({ trig = "\\PopLetterCat", dscr = "\\<char> ∗", priority = 900 }, { t("\\PopLetterCat\\"), i(1, "<char>") }, "*"),
    S({ trig = "\\PushCatMakeLetterAt", dscr = "∗", priority = 900 }, { t("\\PushCatMakeLetterAt") }, "*"),
    S({ trig = "\\PopLetterCatAt", dscr = "∗", priority = 900 }, { t("\\PopLetterCatAt") }, "*"),
    S({ trig = "\\withcsname", dscr = "<cmd> ∗", priority = 900 }, { t("\\withcsname"), i(1, "<cmd>") }, "*"),
    S({ trig = "\\ifltx", dscr = "∗", priority = 900 }, { t("\\ifltx") }, "*"),
  },
  keyvals = {},
}
