-- Generated by snipgen 1 from steinmetz.cwl; do not edit, regenerate.
-- source: TeXstudio completion/steinmetz.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 891b42ad43e96e43933b4874d364c7e0b29c8f8e3b4b1b621b63d66f4bfc286b
-- cwl-header:
--   # steinmetz package
--   # Matthew Bertucci 8/23/2021 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local h = require("snippets.helpers")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "steinmetz",
  includes = { "pict2e" },
  lists = {},
  snippets = {
    S({ trig = "\\phase", dscr = "{arg}" }, h.mathwrap({ t("\\phase{"), i(1, "arg"), t("}") }), "m"),
    S({ trig = "\\phase", dscr = "[stylenum]{arg}" }, h.mathwrap({ t("\\phase["), i(1, "stylenum"), t("]{"), i(2, "arg"), t("}") }), "m"),
  },
  keyvals = {
    {
      targets = "\\phase",
      lines = {
        "0",
        "1",
        "2",
        "3",
      },
    },
  },
}
