-- Generated by snipgen 1 from tabls.cwl; do not edit, regenerate.
-- source: TeXstudio completion/tabls.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 109e451f2a28ceff825cd079277ef83b833fe9ea00ea2425c75e66b8deb9288a
-- cwl-header:
--   # tabls package
--   # Matthew Bertucci 11/11/2021 for v3.5
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "tabls",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\tablinesep", dscr = "" }, { t("\\tablinesep") }),
    S({ trig = "\\tablineskip", dscr = "∗", priority = 900 }, { t("\\tablineskip") }, "*"),
    S({ trig = "\\arraylinesep", dscr = "" }, { t("\\arraylinesep") }),
    S({ trig = "\\arraylineskip", dscr = "∗", priority = 900 }, { t("\\arraylineskip") }, "*"),
    S({ trig = "\\extrarulesep", dscr = "" }, { t("\\extrarulesep") }),
    S({ trig = "\\hline", dscr = "[extra]" }, { t("\\hline["), i(1, "extra"), t("]") }, "t"),
  },
  keyvals = {},
}
