-- Generated by snipgen 1 from tabularborder.cwl; do not edit, regenerate.
-- source: TeXstudio completion/tabularborder.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9f977fc10dbdc56683b13891135966d32d089503d7e54e6f493343b3bb12ab4b
-- cwl-header:
--   # tabularborder package
--   # Matthew Bertucci 2022/07/28 for v1.0a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "tabularborder",
  includes = { "booktabs", "array" },
  lists = {},
  snippets = {
    S({ trig = "\\tbon", dscr = "" }, { t("\\tbon") }),
    S({ trig = "\\tboff", dscr = "" }, { t("\\tboff") }),
    S({ trig = "\\tabcolwidthi", dscr = "" }, { t("\\tabcolwidthi") }, "L"),
    S({ trig = "\\tabcolwidthii", dscr = "" }, { t("\\tabcolwidthii") }, "L"),
    S({ trig = "\\tabcolwidthiii", dscr = "" }, { t("\\tabcolwidthiii") }, "L"),
    S({ trig = "\\tabcolwidthiv", dscr = "" }, { t("\\tabcolwidthiv") }, "L"),
  },
  keyvals = {},
}
