-- Generated by snipgen 1 from tcolorboxlibraryall.cwl; do not edit, regenerate.
-- source: TeXstudio completion/tcolorboxlibraryall.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 800a7c757e7b1de7b0fbfe30b1ac8378480c125eeb6966b5c89a6cbea63e5fa4
-- cwl-header:
--   # all tcolorboxlibrary
--   # 2022/12/12 for v5.1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "tcolorboxlibraryall",
  includes = { "tcolorboxlibrarymany", "tcolorboxlibraryminted", "tcolorboxlibrarylistingsutf8", "tcolorboxlibraryexternal", "tcolorboxlibrarymagazine", "tcolorboxlibraryvignette", "tcolorboxlibraryposter", "tcolorboxlibrarydocumentation" },
  lists = {},
  snippets = {
  },
  keyvals = {},
}
