-- Generated by snipgen 1 from textglos.cwl; do not edit, regenerate.
-- source: TeXstudio completion/textglos.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 4c435f653ece1105a624cadb8105f2517db84233d27fa000cfbeaa348f269c6f
-- cwl-header:
--   # textglos package
--   # Matthew Bertucci 1/27/2022 for v1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "textglos",
  includes = { "graphicx" },
  lists = {},
  snippets = {
    S({ trig = "\\gl", dscr = "{gloss}" }, { t("\\gl{"), i(1, "gloss"), t("}") }),
    S({ trig = "\\gl", dscr = "[postfix]{gloss}" }, { t("\\gl["), i(1, "postfix"), t("]{"), i(2, "gloss"), t("}") }),
    S({ trig = "\\gl", dscr = "[prefix][postfix]{gloss}" }, { t("\\gl["), i(1, "prefix"), t("]["), i(2, "postfix"), t("]{"), i(3, "gloss"), t("}") }),
    S({ trig = "\\xo", dscr = "{orthography}" }, { t("\\xo{"), i(1, "orthography"), t("}") }),
    S({ trig = "\\xo", dscr = "[postfix]{orthography}" }, { t("\\xo["), i(1, "postfix"), t("]{"), i(2, "orthography"), t("}") }),
    S({ trig = "\\xo", dscr = "[prefix][postfix]{orthography}" }, { t("\\xo["), i(1, "prefix"), t("]["), i(2, "postfix"), t("]{"), i(3, "orthography"), t("}") }),
    S({ trig = "\\xt", dscr = "{phonetic}" }, { t("\\xt{"), i(1, "phonetic"), t("}") }),
    S({ trig = "\\xt", dscr = "[postfix]{phonetic}" }, { t("\\xt["), i(1, "postfix"), t("]{"), i(2, "phonetic"), t("}") }),
    S({ trig = "\\xt", dscr = "[prefix][postfix]{phonetic}" }, { t("\\xt["), i(1, "prefix"), t("]["), i(2, "postfix"), t("]{"), i(3, "phonetic"), t("}") }),
    S({ trig = "\\xm", dscr = "{phonemic}" }, { t("\\xm{"), i(1, "phonemic"), t("}") }),
    S({ trig = "\\xm", dscr = "[postfix]{phonemic}" }, { t("\\xm["), i(1, "postfix"), t("]{"), i(2, "phonemic"), t("}") }),
    S({ trig = "\\xm", dscr = "[prefix][postfix]{phonemic}" }, { t("\\xm["), i(1, "prefix"), t("]["), i(2, "postfix"), t("]{"), i(3, "phonemic"), t("}") }),
    S({ trig = "\\xv", dscr = "{vernacular}" }, { t("\\xv{"), i(1, "vernacular"), t("}") }),
    S({ trig = "\\xv", dscr = "[postfix]{vernacular}" }, { t("\\xv["), i(1, "postfix"), t("]{"), i(2, "vernacular"), t("}") }),
    S({ trig = "\\xv", dscr = "[prefix][postfix]{vernacular}" }, { t("\\xv["), i(1, "prefix"), t("]["), i(2, "postfix"), t("]{"), i(3, "vernacular"), t("}") }),
    S({ trig = "\\xh", dscr = "{reconstruction}" }, { t("\\xh{"), i(1, "reconstruction"), t("}") }),
    S({ trig = "\\xh", dscr = "[postfix]{reconstruction}" }, { t("\\xh["), i(1, "postfix"), t("]{"), i(2, "reconstruction"), t("}") }),
    S({ trig = "\\xh", dscr = "[prefix][postfix]{reconstruction}" }, { t("\\xh["), i(1, "prefix"), t("]["), i(2, "postfix"), t("]{"), i(3, "reconstruction"), t("}") }),
    S({ trig = "\\lingprestyle", dscr = "{text} ∗", priority = 900 }, { t("\\lingprestyle{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\lingpoststyle", dscr = "{text} ∗", priority = 900 }, { t("\\lingpoststyle{"), i(1, "text"), t("}") }, "*"),
    S({ trig = "\\lingexample", dscr = "{csname}{template}" }, { t("\\lingexample{"), i(1, "csname"), t("}{"), i(2, "template"), t("}") }),
    S({ trig = "\\shorteq", dscr = "∗", priority = 900 }, { t("\\shorteq") }, "*"),
    S({ trig = "\\nbrhyph", dscr = "∗", priority = 900 }, { t("\\nbrhyph") }, "*"),
    S({ trig = "\\nbreq", dscr = "∗", priority = 900 }, { t("\\nbreq") }, "*"),
    S({ trig = "\\nbrpunct", dscr = "{arg} ∗", priority = 900 }, { t("\\nbrpunct{"), i(1, "arg"), t("}") }, "*"),
  },
  keyvals = {},
}
