-- Generated by snipgen 1 from textfrac.cwl; do not edit, regenerate.
-- source: TeXstudio completion/textfrac.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: ff8c2dc9e61ac018a59d12da094442e1732d2af84f6c68d137ea348bcb1e1612
-- cwl-header:
--   # textfrac package
--   # Matthew Bertucci 2022/05/09 for v1.01
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "textfrac",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\textfrac", dscr = "〈numerator〉/〈denominator〉" }, { t("\\textfrac"), i(1, "〈numerator〉"), t("/"), i(2, "〈denominator〉") }),
    S({ trig = "\\TextFrac", dscr = "{numerator}{denominator}" }, { t("\\TextFrac{"), i(1, "numerator"), t("}{"), i(2, "denominator"), t("}") }),
  },
  keyvals = {},
}
