-- Generated by snipgen 1 from theoremref.cwl; do not edit, regenerate.
-- source: TeXstudio completion/theoremref.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: cd7a9118adbb60ae5ca6b464cff5b283c1ec4cca71456d77f5389de8ea28b6e7
-- cwl-header:
--   # theoremref package
--   # Matthew Bertucci 1/8/2021
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "theoremref",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\thlabel", dscr = "{key}" }, { t("\\thlabel{"), i(1, "key"), t("}") }, "l"),
    S({ trig = "\\thref", dscr = "{labellist}" }, { t("\\thref{"), i(1, "labellist"), t("}") }, "r"),
    S({ trig = "\\thnameref", dscr = "{label}" }, { t("\\thnameref{"), i(1, "label"), t("}") }, "r"),
  },
  keyvals = {
    {
      targets = "\\usepackage/theoremref#c",
      lines = {
        "lowercase",
        "reftex",
      },
    },
  },
}
