-- Generated by snipgen 1 from threeparttable.cwl; do not edit, regenerate.
-- source: TeXstudio completion/threeparttable.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 5e27cd2825f99f539cc6e27e4388aca14a048e0f3ecd3c77564ecd14e2ed8aaf
-- cwl-header:
--   # threeparttable package
--   # Matthew Bertucci 10/24/2021 for v3.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "threeparttable",
  includes = {},
  lists = {},
  snippets = {
    S({ trig = "\\threeparttable", dscr = "\\begin{threeparttable}" }, { t({ "\\begin{threeparttable}", "\t" }), i(1), t({ "", "\\end{threeparttable}" }) }),
    S({ trig = "\\threeparttable", dscr = "\\begin{threeparttable}[pos]" }, { t("\\begin{threeparttable}["), i(1, "pos"), t({ "]", "\t" }), i(2), t({ "", "\\end{threeparttable}" }) }),
    S({ trig = "\\measuredfigure", dscr = "\\begin{measuredfigure}" }, { t({ "\\begin{measuredfigure}", "\t" }), i(1), t({ "", "\\end{measuredfigure}" }) }),
    S({ trig = "\\measuredfigure", dscr = "\\begin{measuredfigure}[pos]" }, { t("\\begin{measuredfigure}["), i(1, "pos"), t({ "]", "\t" }), i(2), t({ "", "\\end{measuredfigure}" }) }),
    S({ trig = "\\tablenotes", dscr = "\\begin{tablenotes}" }, { t({ "\\begin{tablenotes}", "\t" }), i(1), t({ "", "\\end{tablenotes}" }) }),
    S({ trig = "\\tablenotes", dscr = "\\begin{tablenotes}[options]" }, { t("\\begin{tablenotes}["), i(1, "options"), t({ "]", "\t" }), i(2), t({ "", "\\end{tablenotes}" }) }),
    S({ trig = "\\tnote", dscr = "{label}" }, { t("\\tnote{"), i(1, "label"), t("}") }),
    S({ trig = "\\TPTminimum", dscr = "∗", priority = 900 }, { t("\\TPTminimum") }, "*"),
    S({ trig = "\\TPToverlap", dscr = "∗", priority = 900 }, { t("\\TPToverlap") }, "*"),
    S({ trig = "\\TPTrlap", dscr = "∗", priority = 900 }, { t("\\TPTrlap") }, "*"),
    S({ trig = "\\TPTtagStyle", dscr = "∗", priority = 900 }, { t("\\TPTtagStyle") }, "*"),
    S({ trig = "\\TPTnoteLabel", dscr = "∗", priority = 900 }, { t("\\TPTnoteLabel") }, "*"),
    S({ trig = "\\TPTnoteSettings", dscr = "∗", priority = 900 }, { t("\\TPTnoteSettings") }, "*"),
    S({ trig = "\\TPTdoTablenotes", dscr = "∗", priority = 900 }, { t("\\TPTdoTablenotes") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/threeparttable#c",
      lines = {
        "para",
        "flushleft",
        "online",
        "normal",
      },
    },
    {
      targets = "\\begin{threeparttable},\\begin{measuredfigure}",
      lines = {
        "t",
        "b",
        "c",
      },
    },
    {
      targets = "\\begin{tablenotes}",
      lines = {
        "para",
        "flushleft",
        "online",
        "normal",
      },
    },
  },
}
