-- Generated by snipgen 1 from thumby.cwl; do not edit, regenerate.
-- source: TeXstudio completion/thumby.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b1b9463db724450f95954f2c10e43b7a7ea167d9de73fac6462fc79c9234baf2
-- cwl-header:
--   # thumby package
--   # Matthew Bertucci 1/28/2022 for v0.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "thumby",
  includes = { "tikz", "perltex", "bophook" },
  lists = {},
  snippets = {
    S({ trig = "\\thumbyNumberFormat", dscr = "{format}" }, { t("\\thumbyNumberFormat{"), i(1, "format"), t("}") }),
    S({ trig = "\\thumbySides", dscr = "{one or two}" }, { t("\\thumbySides{"), i(1, "one or two"), t("}") }),
    S({ trig = "\\thumbyBackground", dscr = "{color}" }, { t("\\thumbyBackground{"), i(1, "color"), t("}") }),
    S({ trig = "\\thumbyForeground", dscr = "{color}" }, { t("\\thumbyForeground{"), i(1, "color"), t("}") }),
    S({ trig = "\\thumbyPageHeight", dscr = "{points}" }, { t("\\thumbyPageHeight{"), i(1, "points"), t("}") }),
    S({ trig = "\\thumbyThumbWidth", dscr = "{points}" }, { t("\\thumbyThumbWidth{"), i(1, "points"), t("}") }),
    S({ trig = "\\thumbySetup", dscr = "" }, { t("\\thumbySetup") }),
    S({ trig = "\\thumbyTotalChapters", dscr = "{number}" }, { t("\\thumbyTotalChapters{"), i(1, "number"), t("}") }),
    S({ trig = "\\thumbychapnum", dscr = "∗", priority = 900 }, { t("\\thumbychapnum") }, "*"),
    S({ trig = "\\thumbyprintthumb", dscr = "{number}{left or right} ∗", priority = 900 }, { t("\\thumbyprintthumb{"), i(1, "number"), t("}{"), i(2, "left or right"), t("}") }, "*"),
    S({ trig = "\\thumbyprintthumbleft", dscr = "{number} ∗", priority = 900 }, { t("\\thumbyprintthumbleft{"), i(1, "number"), t("}") }, "*"),
    S({ trig = "\\thumbyprintthumbright", dscr = "{number} ∗", priority = 900 }, { t("\\thumbyprintthumbright{"), i(1, "number"), t("}") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/thumb#c",
      lines = {
        "minitoc",
        "box",
        "filledbox",
        "oval",
        "filledoval",
      },
    },
  },
}
