-- Generated by snipgen 1 from ticket.cwl; do not edit, regenerate.
-- source: TeXstudio completion/ticket.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9a16e603c636e444ddc8ed15aaeb40b8fc51d4774f9ca7f552b8bc0c301d1202
-- cwl-header:
--   # ticket package
--   # Matthew Bertucci 2022/07/24 for v0.4d
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "ticket",
  includes = { "ifthen", "calc" },
  lists = {},
  snippets = {
    S({ trig = "\\ticketdefault", dscr = "" }, { t("\\ticketdefault") }),
    S({ trig = "\\ticket", dscr = "{content}" }, { t("\\ticket{"), i(1, "content"), t("}") }),
    S({ trig = "\\ticketreset", dscr = "" }, { t("\\ticketreset") }),
    S({ trig = "\\backside", dscr = "" }, { t("\\backside") }),
    S({ trig = "\\ticketskip", dscr = "{number}" }, { t("\\ticketskip{"), i(1, "number"), t("}") }),
    S({ trig = "\\ticketNumbers", dscr = "{x}{y}" }, { t("\\ticketNumbers{"), i(1, "x"), t("}{"), i(2, "y"), t("}") }),
    S({ trig = "\\ticketWidth", dscr = "" }, { t("\\ticketWidth") }, "L"),
    S({ trig = "\\ticketHeight", dscr = "" }, { t("\\ticketHeight") }, "L"),
    S({ trig = "\\ticketSize", dscr = "{width}{height}" }, { t("\\ticketSize{"), i(1, "width"), t("}{"), i(2, "height"), t("}") }),
    S({ trig = "\\ticketDistance", dscr = "{x}{y}" }, { t("\\ticketDistance{"), i(1, "x"), t("}{"), i(2, "y"), t("}") }),
    S({ trig = "\\ticketToUse", dscr = "∗", priority = 900 }, { t("\\ticketToUse") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/ticket#c",
      lines = {
        "%<.tdf file%>",
        "boxed",
        "crossmark",
        "circlemark",
        "emptycrossmark",
        "cutmark",
        "rowmode",
      },
    },
  },
}
