-- Generated by snipgen 1 from tikzlibrarytikzphysics.optics.cwl; do not edit, regenerate.
-- source: TeXstudio completion/tikzlibrarytikzphysics.optics.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f1bb2736013f04bb7f0a4f910a72ad854f3ad2c1108ee320d01bcfc626337d0a
-- cwl-header:
--   # tikzphysics.optics tikzlibrary
--   # Matthew Bertucci 2026/09/04 for v1.1.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "tikzlibrarytikzphysics.optics",
  includes = { "tikzlibrarypatterns", "tikzlibrarycalc", "tikzlibrarytikzphysics.core" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\begin{tikzpicture}#c,\\tikz#c,\\node#c",
      lines = {
        "mirror radius=##L",
        "mirror thickness=##L",
        "mirror aperture angle=%<degrees%>",
        "convex lens radius=##L",
        "convex lens thickness=##L",
        "convex lens aperture angle=%<degrees%>",
        "concave lens radius=##L",
        "concave lens thickness=##L",
        "concave lens aperture angle=%<degrees%>",
        "slab width=##L",
        "slab height=##L",
        "prism width=##L",
        "prism height=##L",
        "prism apex angle=%<degrees%>",
      },
    },
    {
      targets = "\\node#c",
      lines = {
        "concave-mirror",
        "convex-mirror",
        "convex-lens",
        "concave-lens",
        "slab",
        "prism",
      },
    },
  },
}
