-- Generated by snipgen 1 from tikzcodeblocks.cwl; do not edit, regenerate.
-- source: TeXstudio completion/tikzcodeblocks.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c64b0d323058a379a1e76c3386ac69c620b52e6d8c5c72c9424cf97d7170cbb0
-- cwl-header:
--   # tikzcodeblocks package
--   # Matthew Bertucci 12/15/2021 for v0.13
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "tikzcodeblocks",
  includes = { "adjustbox", "xcolor", "colortbl", "fontawesome", "tikz", "longtable", "tikzlibrarymatrix", "tikzlibrarypositioning", "tikzlibraryfit", "tikzlibrarycalc", "tikzlibraryshapes", "tikzlibrarybackgrounds", "tikzlibrarymath", "tikzlibrarytrees", "tikzlibrarydecorations.markings", "tikzlibrarydecorations", "tikzlibrarydecorations.pathmorphing", "translations", "xspace", "ifthen" },
  lists = {},
  snippets = {
    S({ trig = "\\setcolor", dscr = "{name}{hex color code}" }, { t("\\setcolor{"), i(1, "name"), t("}{"), i(2, "hex color code"), t("}") }, "s#%color"),
    S({ trig = "\\dropdown", dscr = "{text}" }, { t("\\dropdown{"), i(1, "text"), t("}") }),
    S({ trig = "\\intbox", dscr = "{text}" }, { t("\\intbox{"), i(1, "text"), t("}") }),
    S({ trig = "\\intbox", dscr = "[options]{text}" }, { t("\\intbox["), i(1, "options"), t("]{"), i(2, "text"), t("}") }),
    S({ trig = "\\stringbox", dscr = "{text}" }, { t("\\stringbox{"), i(1, "text"), t("}") }),
    S({ trig = "\\stringbox", dscr = "[options]{text}" }, { t("\\stringbox["), i(1, "options"), t("]{"), i(2, "text"), t("}") }),
    S({ trig = "\\boolbox", dscr = "{text}" }, { t("\\boolbox{"), i(1, "text"), t("}") }),
    S({ trig = "\\boolbox", dscr = "[options]{text}" }, { t("\\boolbox["), i(1, "options"), t("]{"), i(2, "text"), t("}") }),
    S({ trig = "\\bild", dscr = "{content}" }, { t("\\bild{"), i(1, "content"), t("}") }),
    S({ trig = "\\bild", dscr = "[scale]{content}" }, { t("\\bild["), i(1, "scale"), t("]{"), i(2, "content"), t("}") }),
    S({ trig = "\\emptyled", dscr = "" }, { t("\\emptyled") }),
    S({ trig = "\\fullled", dscr = "" }, { t("\\fullled") }),
    S({ trig = "\\X", dscr = "" }, { t("\\X") }),
    S({ trig = "\\0", dscr = "" }, { t("\\0") }),
    S({ trig = "\\wenndann", dscr = "{text}{then node code}{node name}" }, { t("\\wenndann{"), i(1, "text"), t("}{"), i(2, "then node code"), t("}{"), i(3, "node name"), t("}") }),
    S({ trig = "\\wenndann", dscr = "[options]{text}{then node code}{node name}" }, { t("\\wenndann["), i(1, "options"), t("]{"), i(2, "text"), t("}{"), i(3, "then node code"), t("}{"), i(4, "node name"), t("}") }),
    S({ trig = "\\wenndannsonst", dscr = "{text}{then node code}{else node code}{node name}" }, { t("\\wenndannsonst{"), i(1, "text"), t("}{"), i(2, "then node code"), t("}{"), i(3, "else node code"), t("}{"), i(4, "node name"), t("}") }),
    S({ trig = "\\wenndannsonst", dscr = "[options]{text}{then node code}{else node code}{node name}" }, { t("\\wenndannsonst["), i(1, "options"), t("]{"), i(2, "text"), t("}{"), i(3, "then node code"), t("}{"), i(4, "else node code"), t("}{"), i(5, "node name"), t("}") }),
    S({ trig = "\\schleife", dscr = "{text}{then node code}{else node code}{node name}" }, { t("\\schleife{"), i(1, "text"), t("}{"), i(2, "then node code"), t("}{"), i(3, "else node code"), t("}{"), i(4, "node name"), t("}") }),
    S({ trig = "\\schleife", dscr = "[options]{text}{then node code}{else node code}{node name}" }, { t("\\schleife["), i(1, "options"), t("]{"), i(2, "text"), t("}{"), i(3, "then node code"), t("}{"), i(4, "else node code"), t("}{"), i(5, "node name"), t("}") }),
    S({ trig = "\\ifthenblocks", dscr = "{text}{then node code}{node name}" }, { t("\\ifthenblocks{"), i(1, "text"), t("}{"), i(2, "then node code"), t("}{"), i(3, "node name"), t("}") }),
    S({ trig = "\\ifthenblocks", dscr = "[options]{text}{then node code}{node name}" }, { t("\\ifthenblocks["), i(1, "options"), t("]{"), i(2, "text"), t("}{"), i(3, "then node code"), t("}{"), i(4, "node name"), t("}") }),
    S({ trig = "\\ifthenelseblocks", dscr = "{text}{then node code}{else node code}{node name}" }, { t("\\ifthenelseblocks{"), i(1, "text"), t("}{"), i(2, "then node code"), t("}{"), i(3, "else node code"), t("}{"), i(4, "node name"), t("}") }),
    S({ trig = "\\ifthenelseblocks", dscr = "[options]{text}{then node code}{else node code}{node name}" }, { t("\\ifthenelseblocks["), i(1, "options"), t("]{"), i(2, "text"), t("}{"), i(3, "then node code"), t("}{"), i(4, "else node code"), t("}{"), i(5, "node name"), t("}") }),
    S({ trig = "\\loopblocks", dscr = "{text}{then node code}{else node code}{node name}" }, { t("\\loopblocks{"), i(1, "text"), t("}{"), i(2, "then node code"), t("}{"), i(3, "else node code"), t("}{"), i(4, "node name"), t("}") }),
    S({ trig = "\\loopblocks", dscr = "[options]{text}{then node code}{else node code}{node name}" }, { t("\\loopblocks["), i(1, "options"), t("]{"), i(2, "text"), t("}{"), i(3, "then node code"), t("}{"), i(4, "else node code"), t("}{"), i(5, "node name"), t("}") }),
    S({ trig = "\\einruecken", dscr = "{nodes}" }, { t("\\einruecken{"), i(1, "nodes"), t("}") }),
    S({ trig = "\\moveindent", dscr = "{nodes}" }, { t("\\moveindent{"), i(1, "nodes"), t("}") }),
    S({ trig = "\\usb", dscr = "" }, { t("\\usb") }),
    S({ trig = "\\farbe", dscr = "{color}" }, { t("\\farbe{"), i(1, "color"), t("}") }),
    S({ trig = "\\setupquotes", dscr = "∗", priority = 900 }, { t("\\setupquotes") }, "*"),
    S({ trig = "\\myspace", dscr = "∗", priority = 900 }, { t("\\myspace") }, "*"),
    S({ trig = "\\myshift", dscr = "∗", priority = 900 }, { t("\\myshift") }, "*"),
    S({ trig = "\\blockhspace", dscr = "∗", priority = 900 }, { t("\\blockhspace") }, "*"),
    S({ trig = "\\blockhspaceoben", dscr = "∗", priority = 900 }, { t("\\blockhspaceoben") }, "*"),
    S({ trig = "\\blockhspaceunten", dscr = "∗", priority = 900 }, { t("\\blockhspaceunten") }, "*"),
    S({ trig = "\\blockvspace", dscr = "∗", priority = 900 }, { t("\\blockvspace") }, "*"),
    S({ trig = "\\dreieckseite", dscr = "∗", priority = 900 }, { t("\\dreieckseite") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/tikzcodeblocks#c",
      lines = {
        "print#true,false",
      },
    },
    {
      targets = "\\begin{tikzpicture}#c",
      lines = {
        "codeblocks",
        "openroberta",
        "eckig",
        "nocolor",
        "umgebung",
      },
    },
    {
      targets = "\\begin{tikzpicture}#c,\\node#c,\\intbox#c,\\stringbox#c,\\boolbox#c,\\wenndann#c,\\wenndannsonst#c,\\schleife#c,\\ifthenblocks#c,\\ifthenelseblocks#c,\\loopblocks#c",
      lines = {
        "grundlage",
        "eingabe",
        "schleife",
        "logik",
        "musik",
        "led",
        "platzhalter",
        "mathe",
        "funk",
        "motor",
        "zeichenkette",
        "spiel",
        "bild",
        "pins",
        "konsole",
        "steuerung",
        "bluetooth",
        "start",
        "aktion",
        "sensor",
        "kontrolle",
        "liste",
        "farbe",
        "bild",
        "variablen",
        "funktion",
        "nachricht",
        "unter={%<node%>}{%<x-factor%>}{%<y-factor%>}",
        "under={%<node%>}{%<x-factor%>}{%<y-factor%>}",
        "robertashape",
        "puzzleteil",
        "keinezacken",
        "pinlow",
        "pinhigh",
        "nopins",
        "square",
        "puzzlepiece",
        "boden",
        "floor",
      },
    },
  },
}
