-- Generated by snipgen 1 from tikzlibrarydecorations.footprints.cwl; do not edit, regenerate.
-- source: TeXstudio completion/tikzlibrarydecorations.footprints.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: f7a3177abcc5bc5bffc4394a1fda4ab1a49a49579fde83bdc9c9bf4938c22feb
-- cwl-header:
--   # decorations.footprints tikzlibrary
--   # 2022/11/20 for v3.1.9a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "tikzlibrarydecorations.footprints",
  includes = { "tikzlibrarydecorations" },
  lists = {},
  snippets = {
  },
  keyvals = {},
}
