-- Generated by snipgen 1 from tikzlibraryfill.rhombus.cwl; do not edit, regenerate.
-- source: TeXstudio completion/tikzlibraryfill.rhombus.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9a1aa661e51c943b1dedd14f80fa386ae4a235202fa931c8711ab426d803c0a0
-- cwl-header:
--   # fill.rhombus tikzlibrary
--   # 2022/11/24 for v1.0.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "tikzlibraryfill.rhombus",
  includes = { "tikzlibrarypatterns.meta" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\begin{tikzpicture}#c,\\tikz#c,\\begin{scope}#c,\\tikzset#c,\\scoped#c,\\path#c,\\draw#c,\\fill#c,\\filldraw#c,\\pattern#c,\\shade#c,\\shadedraw#c,\\clip#c,\\node#c,\\coordinate#c,\\nodepart#c,\\pic#c,\\matrix#c,\\calendar#c,\\chainin#c,\\arrow#c,\\arrowreversed#c",
      lines = {
        "pattern rhombus={%<pattern keys%>}",
      },
    },
  },
}
