-- Generated by snipgen 1 from tikzlibraryshapes.gates.logic.IEC.cwl; do not edit, regenerate.
-- source: TeXstudio completion/tikzlibraryshapes.gates.logic.IEC.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 3b9c8b2bf842f9b92385c9b3b1c4c9a6442c5d2eba5ccce7cdeb389e392596ce
-- cwl-header:
--   # shapes.gates.logic.IEC tikzlibrary
--   # 2022/11/21 for v3.1.9a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "tikzlibraryshapes.gates.logic.IEC",
  includes = { "tikzlibraryshapes.gates.logic" },
  lists = {},
  snippets = {
  },
  keyvals = {
    {
      targets = "\\begin{tikzpicture}#c,\\tikz#c,\\begin{scope}#c,\\tikzset#c,\\scoped#c,\\node#c,\\coordinate#c,\\nodepart#c",
      lines = {
        "and gate IEC symbol=%<text%>",
        "nand gate IEC symbol=%<text%>",
        "or gate IEC symbol=%<text%>",
        "nor gate IEC symbol=%<text%>",
        "xor gate IEC symbol=%<text%>",
        "xnor gate IEC symbol=%<text%>",
        "not gate IEC symbol=%<text%>",
        "buffer gate IEC symbol=%<text%>",
        "logic gate IEC symbol align=#top,bottom,left,right",
        "logic gate IEC symbol color=#%color",
      },
    },
    {
      targets = "\\node#c,\\coordinate#c,\\nodepart#c",
      lines = {
        "and gate IEC",
        "nand gate IEC",
        "or gate IEC",
        "xor gate IEC",
        "xnor gate IEC",
        "not gate IEC",
        "buffer gate IEC",
      },
    },
  },
}
