-- Generated by snipgen 1 from timeop.cwl; do not edit, regenerate.
-- source: TeXstudio completion/timeop.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c22e15f1caf08c25b87628314bcfc4949eb54fa209a0c78648f34a49ae7c0aee
-- cwl-header:
--   # timeop package
--   # Matthew Bertucci 2025/05/25 for v0.1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "timeop",
  includes = { "amsmath", "xstring", "xintexpr", "listofitems", "simplekv", "tcolorbox", "tcolorboxlibraryskins" },
  lists = {},
  snippets = {
    S({ trig = "\\boxhms", dscr = "{color}" }, { t("\\boxhms{"), i(1, "color"), t("}") }),
    S({ trig = "\\hmtos", dscr = "{hour,minute}" }, { t("\\hmtos{"), i(1, "hour,minute"), t("}") }),
    S({ trig = "\\hmtos", dscr = "{hour,minute}[\\macro]" }, { t("\\hmtos{"), i(1, "hour,minute"), t("}["), i(2, "\\macro"), t("]") }),
    S({ trig = "\\hmstos", dscr = "{hour,minute,second}" }, { t("\\hmstos{"), i(1, "hour,minute,second"), t("}") }),
    S({ trig = "\\hmstos", dscr = "{hour,minute,second}[\\macro]" }, { t("\\hmstos{"), i(1, "hour,minute,second"), t("}["), i(2, "\\macro"), t("]") }),
    S({ trig = "\\stohms", dscr = "{second}" }, { t("\\stohms{"), i(1, "second"), t("}") }),
    S({ trig = "\\stohms", dscr = "{second}[\\macro]" }, { t("\\stohms{"), i(1, "second"), t("}["), i(2, "\\macro"), t("]") }),
    S({ trig = "\\stohms", dscr = "[keyvals]{second}" }, { t("\\stohms["), i(1, "keyvals"), t("]{"), i(2, "second"), t("}") }),
    S({ trig = "\\stohms", dscr = "[keyvals]{second}[\\macro]" }, { t("\\stohms["), i(1, "keyvals"), t("]{"), i(2, "second"), t("}["), i(3, "\\macro"), t("]") }),
    S({ trig = "\\simpletimeop", dscr = "{h1,m1,s1}{h2,m2,s2}{h3,m3,s3}" }, { t("\\simpletimeop{"), i(1, "h1,m1,s1"), t("}{"), i(2, "h2,m2,s2"), t("}{"), i(3, "h3,m3,s3"), t("}") }),
    S({ trig = "\\simpletimeop", dscr = "[keyvals]{h1,m1,s1}{h2,m2,s2}{h3,m3,s3}" }, { t("\\simpletimeop["), i(1, "keyvals"), t("]{"), i(2, "h1,m1,s1"), t("}{"), i(3, "h2,m2,s2"), t("}{"), i(4, "h3,m3,s3"), t("}") }),
    S({ trig = "\\calctimeop", dscr = "{h1,m1,s1}{h2,m2,s2}" }, { t("\\calctimeop{"), i(1, "h1,m1,s1"), t("}{"), i(2, "h2,m2,s2"), t("}") }),
    S({ trig = "\\calctimeop", dscr = "[keyvals]{h1,m1,s1}{h2,m2,s2}" }, { t("\\calctimeop["), i(1, "keyvals"), t("]{"), i(2, "h1,m1,s1"), t("}{"), i(3, "h2,m2,s2"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/timeop#c",
      lines = {
        "noamsmath",
      },
    },
  },
}
