-- Generated by snipgen 1 from turnthepage.cwl; do not edit, regenerate.
-- source: TeXstudio completion/turnthepage.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: b45d730f83611d066fd4475d495a68c896d6a083e0af57a0d0fb90c586411a2f
-- cwl-header:
--   # turnthepage package
--   # Matthew Bertucci 2024/11/19 for v2.0a
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "turnthepage",
  includes = { "picture" },
  lists = {},
  snippets = {
    S({ trig = "\\turnthepage", dscr = "∗", priority = 900 }, { t("\\turnthepage") }, "*"),
  },
  keyvals = {
    {
      targets = "\\usepackage/turnthepage#c",
      lines = {
        "short",
        "english",
        "francais",
        "nederlands",
        "deutsch",
      },
    },
  },
}
