-- Generated by snipgen 1 from variablelm.cwl; do not edit, regenerate.
-- source: TeXstudio completion/variablelm.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 9940045733c45d004a111f09b4baf835f6af10640c513b22b7eeaff234798a75
-- cwl-header:
--   # variablelm package
--   # Matthew Bertucci 1/22/2022 for v1.2
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "variablelm",
  includes = { "xkeyval", "fontenc" },
  lists = {},
  snippets = {
    S({ trig = "\\DH", dscr = "" }, { t("\\DH") }, "n"),
    S({ trig = "\\NG", dscr = "" }, { t("\\NG") }, "n"),
    S({ trig = "\\dj", dscr = "" }, { t("\\dj") }, "n"),
    S({ trig = "\\ng", dscr = "" }, { t("\\ng") }, "n"),
    S({ trig = "\\k", dscr = "{arg}" }, { t("\\k{"), i(1, "arg"), t("}") }, "n"),
    S({ trig = "\\guillemotleft", dscr = "∗", priority = 900 }, { t("\\guillemotleft") }, "*n"),
    S({ trig = "\\guillemotright", dscr = "∗", priority = 900 }, { t("\\guillemotright") }, "*n"),
    S({ trig = "\\guilsinglleft", dscr = "" }, { t("\\guilsinglleft") }, "n"),
    S({ trig = "\\guilsinglright", dscr = "" }, { t("\\guilsinglright") }, "n"),
    S({ trig = "\\quotedblbase", dscr = "" }, { t("\\quotedblbase") }, "n"),
    S({ trig = "\\quotesinglbase", dscr = "" }, { t("\\quotesinglbase") }, "n"),
    S({ trig = "\\textquotedbl", dscr = "" }, { t("\\textquotedbl") }, "n"),
    S({ trig = "\\DJ", dscr = "" }, { t("\\DJ") }, "n"),
    S({ trig = "\\th", dscr = "" }, { t("\\th") }, "n"),
    S({ trig = "\\TH", dscr = "" }, { t("\\TH") }, "n"),
    S({ trig = "\\dh", dscr = "" }, { t("\\dh") }, "n"),
    S({ trig = "\\Hwithstroke", dscr = "∗", priority = 900 }, { t("\\Hwithstroke") }, "*n"),
    S({ trig = "\\hwithstroke", dscr = "∗", priority = 900 }, { t("\\hwithstroke") }, "*n"),
    S({ trig = "\\textogonekcentered", dscr = "{arg} ∗", priority = 900 }, { t("\\textogonekcentered{"), i(1, "arg"), t("}") }, "*n"),
    S({ trig = "\\guillemetleft", dscr = "" }, { t("\\guillemetleft") }, "n"),
    S({ trig = "\\guillemetright", dscr = "" }, { t("\\guillemetright") }, "n"),
  },
  keyvals = {
    {
      targets = "\\usepackage/variablelm#c",
      lines = {
        "scale=%<factor%>",
        "ttscale=%<factor%>",
        "sfscale=%<factor%>",
        "encoding=%<encoding%>",
        "variablett",
        "lighttt",
      },
    },
  },
}
