-- Generated by snipgen 1 from venturis.cwl; do not edit, regenerate.
-- source: TeXstudio completion/venturis.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: cb5e6ae02f6feb4524e1480e35ea49643001092c68c5332f6c8d62f5df16b984
-- cwl-header:
--   # venturis package
--   # Matthew Bertucci 2024/09/30 for v2.0
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "venturis",
  includes = { "svn-prov", "fontenc", "nfssext-cfr" },
  lists = {},
  snippets = {
    S({ trig = "\\sishape", dscr = "" }, { t("\\sishape") }),
    S({ trig = "\\textsi", dscr = "{text}" }, { t("\\textsi{"), i(1, "text"), t("}") }),
    S({ trig = "\\swashstyle", dscr = "" }, { t("\\swashstyle") }),
    S({ trig = "\\textswash", dscr = "{text}" }, { t("\\textswash{"), i(1, "text"), t("}") }),
    S({ trig = "\\lstyle", dscr = "" }, { t("\\lstyle") }),
    S({ trig = "\\textl", dscr = "{text}" }, { t("\\textl{"), i(1, "text"), t("}") }),
    S({ trig = "\\ostyle", dscr = "" }, { t("\\ostyle") }),
    S({ trig = "\\texto", dscr = "{text}" }, { t("\\texto{"), i(1, "text"), t("}") }),
    S({ trig = "\\tstyle", dscr = "" }, { t("\\tstyle") }),
    S({ trig = "\\textt", dscr = "{text}" }, { t("\\textt{"), i(1, "text"), t("}") }),
    S({ trig = "\\pstyle", dscr = "" }, { t("\\pstyle") }),
    S({ trig = "\\textp", dscr = "{text}" }, { t("\\textp{"), i(1, "text"), t("}") }),
    S({ trig = "\\tlstyle", dscr = "" }, { t("\\tlstyle") }),
    S({ trig = "\\texttl", dscr = "{text}" }, { t("\\texttl{"), i(1, "text"), t("}") }),
    S({ trig = "\\tostyle", dscr = "" }, { t("\\tostyle") }),
    S({ trig = "\\textto", dscr = "{text}" }, { t("\\textto{"), i(1, "text"), t("}") }),
    S({ trig = "\\plstyle", dscr = "" }, { t("\\plstyle") }),
    S({ trig = "\\textpl", dscr = "{text}" }, { t("\\textpl{"), i(1, "text"), t("}") }),
    S({ trig = "\\postyle", dscr = "" }, { t("\\postyle") }),
    S({ trig = "\\textpo", dscr = "{text}" }, { t("\\textpo{"), i(1, "text"), t("}") }),
    S({ trig = "\\instyle", dscr = "" }, { t("\\instyle") }),
    S({ trig = "\\textin", dscr = "{text}" }, { t("\\textin{"), i(1, "text"), t("}") }),
    S({ trig = "\\sustyle", dscr = "" }, { t("\\sustyle") }),
    S({ trig = "\\textsu", dscr = "{text}" }, { t("\\textsu{"), i(1, "text"), t("}") }),
    S({ trig = "\\regwidth", dscr = "" }, { t("\\regwidth") }),
    S({ trig = "\\textrw", dscr = "{text}" }, { t("\\textrw{"), i(1, "text"), t("}") }),
    S({ trig = "\\cdwidth", dscr = "" }, { t("\\cdwidth") }),
    S({ trig = "\\textcd", dscr = "{text}" }, { t("\\textcd{"), i(1, "text"), t("}") }),
    S({ trig = "\\etwidth", dscr = "" }, { t("\\etwidth") }),
    S({ trig = "\\textet", dscr = "{text}" }, { t("\\textet{"), i(1, "text"), t("}") }),
    S({ trig = "\\ucwidth", dscr = "" }, { t("\\ucwidth") }),
    S({ trig = "\\textuc", dscr = "{text}" }, { t("\\textuc{"), i(1, "text"), t("}") }),
    S({ trig = "\\lgweight", dscr = "" }, { t("\\lgweight") }),
    S({ trig = "\\textlg", dscr = "{text}" }, { t("\\textlg{"), i(1, "text"), t("}") }),
    S({ trig = "\\mbweight", dscr = "" }, { t("\\mbweight") }),
    S({ trig = "\\textmb", dscr = "{text}" }, { t("\\textmb{"), i(1, "text"), t("}") }),
    S({ trig = "\\dbweight", dscr = "" }, { t("\\dbweight") }),
    S({ trig = "\\textdb", dscr = "{text}" }, { t("\\textdb{"), i(1, "text"), t("}") }),
    S({ trig = "\\ebweight", dscr = "" }, { t("\\ebweight") }),
    S({ trig = "\\texteb", dscr = "{text}" }, { t("\\texteb{"), i(1, "text"), t("}") }),
    S({ trig = "\\olshape", dscr = "" }, { t("\\olshape") }),
    S({ trig = "\\textol", dscr = "{text}" }, { t("\\textol{"), i(1, "text"), t("}") }),
    S({ trig = "\\tistyle", dscr = "" }, { t("\\tistyle") }),
    S({ trig = "\\textti", dscr = "{text}" }, { t("\\textti{"), i(1, "text"), t("}") }),
    S({ trig = "\\altstyle", dscr = "" }, { t("\\altstyle") }),
    S({ trig = "\\textalt", dscr = "{text}" }, { t("\\textalt{"), i(1, "text"), t("}") }),
    S({ trig = "\\vtstyle", dscr = "" }, { t("\\vtstyle") }),
    S({ trig = "\\textvt", dscr = "{text}" }, { t("\\textvt{"), i(1, "text"), t("}") }),
    S({ trig = "\\textvtl", dscr = "{text}" }, { t("\\textvtl{"), i(1, "text"), t("}") }),
    S({ trig = "\\DH", dscr = "" }, { t("\\DH") }, "n"),
    S({ trig = "\\NG", dscr = "" }, { t("\\NG") }, "n"),
    S({ trig = "\\dj", dscr = "" }, { t("\\dj") }, "n"),
    S({ trig = "\\ng", dscr = "" }, { t("\\ng") }, "n"),
    S({ trig = "\\k", dscr = "{arg}" }, { t("\\k{"), i(1, "arg"), t("}") }, "n"),
    S({ trig = "\\guillemotleft", dscr = "∗", priority = 900 }, { t("\\guillemotleft") }, "*n"),
    S({ trig = "\\guillemotright", dscr = "∗", priority = 900 }, { t("\\guillemotright") }, "*n"),
    S({ trig = "\\guilsinglleft", dscr = "" }, { t("\\guilsinglleft") }, "n"),
    S({ trig = "\\guilsinglright", dscr = "" }, { t("\\guilsinglright") }, "n"),
    S({ trig = "\\quotedblbase", dscr = "" }, { t("\\quotedblbase") }, "n"),
    S({ trig = "\\quotesinglbase", dscr = "" }, { t("\\quotesinglbase") }, "n"),
    S({ trig = "\\textquotedbl", dscr = "" }, { t("\\textquotedbl") }, "n"),
    S({ trig = "\\DJ", dscr = "" }, { t("\\DJ") }, "n"),
    S({ trig = "\\th", dscr = "" }, { t("\\th") }, "n"),
    S({ trig = "\\TH", dscr = "" }, { t("\\TH") }, "n"),
    S({ trig = "\\dh", dscr = "" }, { t("\\dh") }, "n"),
    S({ trig = "\\Hwithstroke", dscr = "∗", priority = 900 }, { t("\\Hwithstroke") }, "*n"),
    S({ trig = "\\hwithstroke", dscr = "∗", priority = 900 }, { t("\\hwithstroke") }, "*n"),
    S({ trig = "\\textogonekcentered", dscr = "{arg} ∗", priority = 900 }, { t("\\textogonekcentered{"), i(1, "arg"), t("}") }, "*n"),
    S({ trig = "\\guillemetleft", dscr = "" }, { t("\\guillemetleft") }, "n"),
    S({ trig = "\\guillemetright", dscr = "" }, { t("\\guillemetright") }, "n"),
  },
  keyvals = {
    {
      targets = "\\usepackage/venturis#c",
      lines = {
        "osf#true,false",
        "lf#true,false",
        "scale=%<factor%>",
      },
    },
  },
}
