-- Generated by snipgen 1 from xcpdftips.cwl; do not edit, regenerate.
-- source: TeXstudio completion/xcpdftips.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 6401a773a9681ea5908231577e60e6124407febf00c02416c43711a8dcc46e8e
-- cwl-header:
--   # xcpdftips package
--   # Matthew Bertucci 1/22/2022 for v1.1
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "xcpdftips",
  includes = { "bibentry", "pdfcomment", "etoolbox" },
  lists = {},
  snippets = {
    S({ trig = "\\xpdfcite", dscr = "{keylist}" }, { t("\\xpdfcite{"), i(1, "keylist"), t("}") }, "c"),
    S({ trig = "\\xpdfcite", dscr = "[postfix]{keylist}" }, { t("\\xpdfcite["), i(1, "postfix"), t("]{"), i(2, "keylist"), t("}") }),
    S({ trig = "\\xpdfcite", dscr = "[prefix][postfix]{keylist}" }, { t("\\xpdfcite["), i(1, "prefix"), t("]["), i(2, "postfix"), t("]{"), i(3, "keylist"), t("}") }),
  },
  keyvals = {
    {
      targets = "\\usepackage/xcpdftips#c",
      lines = {
        "redefcite",
        "ocg",
        "tcolorbox",
      },
    },
  },
}
