-- Generated by snipgen 1 from xintbinhex.cwl; do not edit, regenerate.
-- source: TeXstudio completion/xintbinhex.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 34b5bca412aefc55c71d661f6c379e68aa6f1465fefc5a8d3e5f0f856ea7dfb7
-- cwl-header:
--   # xintbinhex package
--   # Matthew Bertucci 2025/09/06 for v1.4n
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "xintbinhex",
  includes = { "xintkernel" },
  lists = {},
  snippets = {
    S({ trig = "\\xintDecToHex", dscr = "{decimal integer}" }, { t("\\xintDecToHex{"), i(1, "decimal integer"), t("}") }),
    S({ trig = "\\xintDecToBin", dscr = "{decimal integer}" }, { t("\\xintDecToBin{"), i(1, "decimal integer"), t("}") }),
    S({ trig = "\\xintDecToOct", dscr = "{decimal integer}" }, { t("\\xintDecToOct{"), i(1, "decimal integer"), t("}") }),
    S({ trig = "\\xintHexToBin", dscr = "{binary integer}" }, { t("\\xintHexToBin{"), i(1, "binary integer"), t("}") }),
    S({ trig = "\\xintHexToDec", dscr = "{hex integer}" }, { t("\\xintHexToDec{"), i(1, "hex integer"), t("}") }),
    S({ trig = "\\xintHexToOct", dscr = "{hex integer}" }, { t("\\xintHexToOct{"), i(1, "hex integer"), t("}") }),
    S({ trig = "\\xintBinToDec", dscr = "{binary integer}" }, { t("\\xintBinToDec{"), i(1, "binary integer"), t("}") }),
    S({ trig = "\\xintBinToHex", dscr = "{binary integer}" }, { t("\\xintBinToHex{"), i(1, "binary integer"), t("}") }),
    S({ trig = "\\xintBinToOct", dscr = "{binary integer}" }, { t("\\xintBinToOct{"), i(1, "binary integer"), t("}") }),
    S({ trig = "\\xintCHexToBin", dscr = "{hex integer}" }, { t("\\xintCHexToBin{"), i(1, "hex integer"), t("}") }),
    S({ trig = "\\xintOctToDec", dscr = "{octal integer}" }, { t("\\xintOctToDec{"), i(1, "octal integer"), t("}") }),
    S({ trig = "\\xintOctToHex", dscr = "{octal integer}" }, { t("\\xintOctToHex{"), i(1, "octal integer"), t("}") }),
    S({ trig = "\\xintOctToBin", dscr = "{octal integer}" }, { t("\\xintOctToBin{"), i(1, "octal integer"), t("}") }),
    S({ trig = "\\xintCOctToBin", dscr = "{octal integer}" }, { t("\\xintCOctToBin{"), i(1, "octal integer"), t("}") }),
  },
  keyvals = {},
}
