-- Generated by snipgen 1 from xintlog.cwl; do not edit, regenerate.
-- source: TeXstudio completion/xintlog.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: d6ba47db12d8ba0fee83d018a0f32bd64a4c7a2e6358a4d773cc37186cffec13
-- cwl-header:
--   # xintlog package
--   # Matthew Bertucci 2022/06/12 for v1.4m
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "xintlog",
  includes = { "poormanlog" },
  lists = {},
  snippets = {
    S({ trig = "\\PoorManExp", dscr = "{A/B[n]} ∗", priority = 900 }, { t("\\PoorManExp{"), i(1, "A/B[n]"), t("}") }, "*"),
    S({ trig = "\\PoorManLogBaseTen", dscr = "{A/B[n]} ∗", priority = 900 }, { t("\\PoorManLogBaseTen{"), i(1, "A/B[n]"), t("}") }, "*"),
    S({ trig = "\\PoorManLog", dscr = "{A/B[n]} ∗", priority = 900 }, { t("\\PoorManLog{"), i(1, "A/B[n]"), t("}") }, "*"),
    S({ trig = "\\PoorManPowerOfTen", dscr = "{A/B[n]} ∗", priority = 900 }, { t("\\PoorManPowerOfTen{"), i(1, "A/B[n]"), t("}") }, "*"),
    S({ trig = "\\XINTinFloatExp", dscr = "{A/B[n]} ∗", priority = 900 }, { t("\\XINTinFloatExp{"), i(1, "A/B[n]"), t("}") }, "*"),
    S({ trig = "\\XINTinFloatLog", dscr = "{A/B[n]} ∗", priority = 900 }, { t("\\XINTinFloatLog{"), i(1, "A/B[n]"), t("}") }, "*"),
    S({ trig = "\\XINTinFloatLogTen", dscr = "{float} ∗", priority = 900 }, { t("\\XINTinFloatLogTen{"), i(1, "float"), t("}") }, "*"),
    S({ trig = "\\XINTinFloatPowTen", dscr = "{float} ∗", priority = 900 }, { t("\\XINTinFloatPowTen{"), i(1, "float"), t("}") }, "*"),
    S({ trig = "\\XINTinFloatSciPow", dscr = "{base}{exponent} ∗", priority = 900 }, { t("\\XINTinFloatSciPow{"), i(1, "base"), t("}{"), i(2, "exponent"), t("}") }, "*"),
    S({ trig = "\\xintreloadxintlog", dscr = "∗", priority = 900 }, { t("\\xintreloadxintlog") }, "*"),
    S({ trig = "\\XINTinfloatexp", dscr = "{A/B[n]}" }, { t("\\XINTinfloatexp{"), i(1, "A/B[n]"), t("}") }),
    S({ trig = "\\XINTinfloatlog", dscr = "{A/B[n]}" }, { t("\\XINTinfloatlog{"), i(1, "A/B[n]"), t("}") }),
  },
  keyvals = {},
}
