-- Generated by snipgen 1 from xintgcd.cwl; do not edit, regenerate.
-- source: TeXstudio completion/xintgcd.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: c8a2edf392e3e29daabb345d1f9e742c614a25ee2a5e0b01c59e408084419486
-- cwl-header:
--   # xintgcd package
--   # Matthew Bertucci 11/16/2021 for v1.4j
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "xintgcd",
  includes = { "xint", "xinttools" },
  lists = {},
  snippets = {
    S({ trig = "\\xintBezout", dscr = "{integer1}{integer2}" }, { t("\\xintBezout{"), i(1, "integer1"), t("}{"), i(2, "integer2"), t("}") }),
    S({ trig = "\\xintEuclideAlgorithm", dscr = "{integer1}{integer2}" }, { t("\\xintEuclideAlgorithm{"), i(1, "integer1"), t("}{"), i(2, "integer2"), t("}") }),
    S({ trig = "\\xintBezoutAlgorithm", dscr = "{integer1}{integer2}" }, { t("\\xintBezoutAlgorithm{"), i(1, "integer1"), t("}{"), i(2, "integer2"), t("}") }),
    S({ trig = "\\xintTypesetEuclideAlgorithm", dscr = "{integer1}{integer2}" }, { t("\\xintTypesetEuclideAlgorithm{"), i(1, "integer1"), t("}{"), i(2, "integer2"), t("}") }),
    S({ trig = "\\xintTypesetBezoutAlgorithm", dscr = "{integer1}{integer2}" }, { t("\\xintTypesetBezoutAlgorithm{"), i(1, "integer1"), t("}{"), i(2, "integer2"), t("}") }),
  },
  keyvals = {},
}
