-- Generated by snipgen 1 from zref-nextpage.cwl; do not edit, regenerate.
-- source: TeXstudio completion/zref-nextpage.cwl at commit 0362907c21d1f725288bb553c5360d1179b78c1b (2026-09-12)
-- cwl-sha256: 209eedfbda3b52dab5de429b1c0d630f3d1e282af3b08543e3320c1712b8bf7d
-- cwl-header:
--   # zref-nextpage package
--   # Matthew Bertucci 11/10/2021 for v2.32
-- licence: GPL-3; see NOTICE and COPYING beside the generated files

local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node
local function S(ctx, nodes, cls)
  local sn = s(ctx, nodes)
  sn.cls = cls
  return sn
end

return {
  package = "zref-nextpage",
  includes = { "zref-base", "zref-abspage", "zref-thepage", "zref-lastpage", "uniquecounter" },
  lists = {},
  snippets = {
    S({ trig = "\\znextpage", dscr = "" }, { t("\\znextpage") }),
    S({ trig = "\\zunknownnextpagename", dscr = "" }, { t("\\zunknownnextpagename") }),
    S({ trig = "\\znonextpagename", dscr = "" }, { t("\\znonextpagename") }),
    S({ trig = "\\znextpagesetup", dscr = "{unknown}{no next}{next}" }, { t("\\znextpagesetup{"), i(1, "unknown"), t("}{"), i(2, "no next"), t("}{"), i(3, "next"), t("}") }),
  },
  keyvals = {},
}
