-- Auto-generated from french-logic.sty
-- Regenerate via sty-lua-snippets.py

local ls = require("luasnip")
local s  = ls.snippet
local t  = ls.text_node
local i  = ls.insert_node

local snippets = {
  s({ trig = "\\ANDs~", wordTrig = true }, { t("\\ANDs") }),
  s({ trig = "\\AND~", wordTrig = true }, { t("\\AND") }),
  s({ trig = "\\Alphlist~", wordTrig = true }, { t({ "\\begin{Alphlist}", "\t\\item " }), i(1), t({ "", "\\end{Alphlist}" }) }),
  s({ trig = "\\A~", wordTrig = true }, { t("\\A") }),
  s({ trig = "\\B~", wordTrig = true }, { t("\\B") }),
  s({ trig = "\\CCls~", wordTrig = true }, { t("\\CCls") }),
  s({ trig = "\\CCl~", wordTrig = true }, { t("\\CCl") }),
  s({ trig = "\\CCrs~", wordTrig = true }, { t("\\CCrs") }),
  s({ trig = "\\CCr~", wordTrig = true }, { t("\\CCr") }),
  s({ trig = "\\CECN~", wordTrig = true }, { t("\\CECN") }),
  s({ trig = "\\CEC~", wordTrig = true }, { t("\\CEC") }),
  s({ trig = "\\CEMC~", wordTrig = true }, { t("\\CEMC") }),
  s({ trig = "\\CEMD~", wordTrig = true }, { t("\\CEMD") }),
  s({ trig = "\\CEMN~", wordTrig = true }, { t("\\CEMN") }),
  s({ trig = "\\CEMPs~", wordTrig = true }, { t("\\CEMPs") }),
  s({ trig = "\\CEMP~", wordTrig = true }, { t("\\CEMP") }),
  s({ trig = "\\CEM~", wordTrig = true }, { t("\\CEM") }),
  s({ trig = "\\CEN~", wordTrig = true }, { t("\\CEN") }),
  s({ trig = "\\CE~", wordTrig = true }, { t("\\CE") }),
  s({ trig = "\\CKD~", wordTrig = true }, { t("\\CKD") }),
  s({ trig = "\\CKPs~", wordTrig = true }, { t("\\CKPs") }),
  s({ trig = "\\CK~", wordTrig = true }, { t("\\CK") }),
  s({ trig = "\\CMls~", wordTrig = true }, { t("\\CMls") }),
  s({ trig = "\\CMl~", wordTrig = true }, { t("\\CMl") }),
  s({ trig = "\\CMrs~", wordTrig = true }, { t("\\CMrs") }),
  s({ trig = "\\CMr~", wordTrig = true }, { t("\\CMr") }),
  s({ trig = "\\CNlr~", wordTrig = true }, { t("\\CNlr") }),
  s({ trig = "\\CNl~", wordTrig = true }, { t("\\CNl") }),
  s({ trig = "\\CNra~", wordTrig = true }, { t("\\CNra") }),
  s({ trig = "\\CNr~", wordTrig = true }, { t("\\CNr") }),
  s({ trig = "\\COc~", wordTrig = true }, { t("\\COc") }),
  s({ trig = "\\COvf~", wordTrig = true }, { t("\\COvf{"), i(1), t("}") }),
  s({ trig = "\\CPs~", wordTrig = true }, { t("\\CPs") }),
  s({ trig = "\\CP~", wordTrig = true }, { t("\\CP") }),
  s({ trig = "\\CTh~", wordTrig = true }, { t("\\CTh") }),
  s({ trig = "\\CTs~", wordTrig = true }, { t("\\CTs") }),
  s({ trig = "\\CT~", wordTrig = true }, { t("\\CT") }),
  s({ trig = "\\Cl~", wordTrig = true }, { t("\\Cl{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\C~", wordTrig = true }, { t("\\C") }),
  s({ trig = "\\DDio~", wordTrig = true }, { t("\\DDio") }),
  s({ trig = "\\D~", wordTrig = true }, { t("\\D") }),
  s({ trig = "\\ECN~", wordTrig = true }, { t("\\ECN") }),
  s({ trig = "\\EC~", wordTrig = true }, { t("\\EC") }),
  s({ trig = "\\EMC~", wordTrig = true }, { t("\\EMC") }),
  s({ trig = "\\EMD~", wordTrig = true }, { t("\\EMD") }),
  s({ trig = "\\EMN~", wordTrig = true }, { t("\\EMN") }),
  s({ trig = "\\EMP~", wordTrig = true }, { t("\\EMP") }),
  s({ trig = "\\EM~", wordTrig = true }, { t("\\EM") }),
  s({ trig = "\\EN~", wordTrig = true }, { t("\\EN") }),
  s({ trig = "\\E~", wordTrig = true }, { t("\\E") }),
  s({ trig = "\\FDio~", wordTrig = true }, { t("\\FDio") }),
  s({ trig = "\\FNo~", wordTrig = true }, { t("\\FNo") }),
  s({ trig = "\\FNt~", wordTrig = true }, { t("\\FNt") }),
  s({ trig = "\\FN~", wordTrig = true }, { t("\\FN") }),
  s({ trig = "\\FRo~", wordTrig = true }, { t("\\FRo") }),
  s({ trig = "\\FRt~", wordTrig = true }, { t("\\FRt") }),
  s({ trig = "\\FR~", wordTrig = true }, { t("\\FR") }),
  s({ trig = "\\Fm~", wordTrig = true }, { t("\\Fm") }),
  s({ trig = "\\F~", wordTrig = true }, { t("\\F") }),
  s({ trig = "\\IOfn~", wordTrig = true }, { t("\\IOfn{"), i(1), t("}") }),
  s({ trig = "\\IOhn~", wordTrig = true }, { t("\\IOhn{"), i(1), t("}") }),
  s({ trig = "\\IOh~", wordTrig = true }, { t("\\IOh") }),
  s({ trig = "\\IOn~", wordTrig = true }, { t("\\IOn{"), i(1), t("}") }),
  s({ trig = "\\IOsn~", wordTrig = true }, { t("\\IOsn{"), i(1), t("}") }),
  s({ trig = "\\IOs~", wordTrig = true }, { t("\\IOs") }),
  s({ trig = "\\IO~", wordTrig = true }, { t("\\IO") }),
  s({ trig = "\\KB~", wordTrig = true }, { t("\\KB") }),
  s({ trig = "\\KDUWought~", wordTrig = true }, { t("\\KDUWought") }),
  s({ trig = "\\KDUW~", wordTrig = true }, { t("\\KDUW") }),
  s({ trig = "\\KDUought~", wordTrig = true }, { t("\\KDUought") }),
  s({ trig = "\\KDU~", wordTrig = true }, { t("\\KDU") }),
  s({ trig = "\\KDWought~", wordTrig = true }, { t("\\KDWought") }),
  s({ trig = "\\KDW~", wordTrig = true }, { t("\\KDW") }),
  s({ trig = "\\KDfourfive~", wordTrig = true }, { t("\\KDfourfive") }),
  s({ trig = "\\KDought~", wordTrig = true }, { t("\\KDought") }),
  s({ trig = "\\KD~", wordTrig = true }, { t("\\KD") }),
  s({ trig = "\\KT~", wordTrig = true }, { t("\\KT") }),
  s({ trig = "\\KUWought~", wordTrig = true }, { t("\\KUWought") }),
  s({ trig = "\\KUW~", wordTrig = true }, { t("\\KUW") }),
  s({ trig = "\\KUought~", wordTrig = true }, { t("\\KUought") }),
  s({ trig = "\\KU~", wordTrig = true }, { t("\\KU") }),
  s({ trig = "\\KWought~", wordTrig = true }, { t("\\KWought") }),
  s({ trig = "\\KW~", wordTrig = true }, { t("\\KW") }),
  s({ trig = "\\Kfive~", wordTrig = true }, { t("\\Kfive") }),
  s({ trig = "\\Kfourfive~", wordTrig = true }, { t("\\Kfourfive") }),
  s({ trig = "\\Kfour~", wordTrig = true }, { t("\\Kfour") }),
  s({ trig = "\\K~", wordTrig = true }, { t("\\K") }),
  s({ trig = "\\Lc~", wordTrig = true }, { t("\\Lc") }),
  s({ trig = "\\MNo~", wordTrig = true }, { t("\\MNo") }),
  s({ trig = "\\MNt~", wordTrig = true }, { t("\\MNt") }),
  s({ trig = "\\MN~", wordTrig = true }, { t("\\MN") }),
  s({ trig = "\\MRel~", wordTrig = true }, { t("\\MRel") }),
  s({ trig = "\\Mlog~", wordTrig = true }, { t("\\Mlog") }),
  s({ trig = "\\Mlr~", wordTrig = true }, { t("\\Mlr") }),
  s({ trig = "\\Mne~", wordTrig = true }, { t("\\Mne") }),
  s({ trig = "\\Mnw~", wordTrig = true }, { t("\\Mnw") }),
  s({ trig = "\\Mse~", wordTrig = true }, { t("\\Mse") }),
  s({ trig = "\\Msig~", wordTrig = true }, { t("\\Msig") }),
  s({ trig = "\\Msw~", wordTrig = true }, { t("\\Msw") }),
  s({ trig = "\\M~", wordTrig = true }, { t("\\M") }),
  s({ trig = "\\ORs~", wordTrig = true }, { t("\\ORs") }),
  s({ trig = "\\OR~", wordTrig = true }, { t("\\OR") }),
  s({ trig = "\\Romanlist~", wordTrig = true }, { t({ "\\begin{Romanlist}", "\t\\item " }), i(1), t({ "", "\\end{Romanlist}" }) }),
  s({ trig = "\\Rsig~", wordTrig = true }, { t("\\Rsig") }),
  s({ trig = "\\R~", wordTrig = true }, { t("\\R") }),
  s({ trig = "\\SDLplus~", wordTrig = true }, { t("\\SDLplus") }),
  s({ trig = "\\SDLt~", wordTrig = true }, { t("\\SDLt") }),
  s({ trig = "\\SDL~", wordTrig = true }, { t("\\SDL") }),
  s({ trig = "\\SIs~", wordTrig = true }, { t("\\SIs") }),
  s({ trig = "\\SI~", wordTrig = true }, { t("\\SI") }),
  s({ trig = "\\Sfive~", wordTrig = true }, { t("\\Sfive") }),
  s({ trig = "\\Sfour~", wordTrig = true }, { t("\\Sfour") }),
  s({ trig = "\\Slog~", wordTrig = true }, { t("\\Slog") }),
  s({ trig = "\\TOP~", wordTrig = true }, { t("\\TOP") }),
  s({ trig = "\\Ts~", wordTrig = true }, { t("\\Ts") }),
  s({ trig = "\\T~", wordTrig = true }, { t("\\T") }),
  s({ trig = "\\VW~", wordTrig = true }, { t("\\VW") }),
  s({ trig = "\\Val~", wordTrig = true }, { t("\\Val{"), i(1), t("}") }),
  s({ trig = "\\Vlog~", wordTrig = true }, { t("\\Vlog") }),
  s({ trig = "\\Vsig~", wordTrig = true }, { t("\\Vsig") }),
  s({ trig = "\\WOs~", wordTrig = true }, { t("\\WOs") }),
  s({ trig = "\\WO~", wordTrig = true }, { t("\\WO") }),
  s({ trig = "\\Wlog~", wordTrig = true }, { t("\\Wlog") }),
  s({ trig = "\\Wsig~", wordTrig = true }, { t("\\Wsig") }),
  s({ trig = "\\abreak~", wordTrig = true }, { t("\\abreak") }),
  s({ trig = "\\affirm~", wordTrig = true }, { t("\\affirm{"), i(1), t("}") }),
  s({ trig = "\\aff~", wordTrig = true }, { t("\\aff") }),
  s({ trig = "\\afland~", wordTrig = true }, { t("\\afland") }),
  s({ trig = "\\aflor~", wordTrig = true }, { t("\\aflor") }),
  s({ trig = "\\afneg~", wordTrig = true }, { t("\\afneg") }),
  s({ trig = "\\afto~", wordTrig = true }, { t("\\afto") }),
  s({ trig = "\\af~", wordTrig = true }, { t("\\af") }),
  s({ trig = "\\agent~", wordTrig = true }, { t("\\agent") }),
  s({ trig = "\\alphlistpar~", wordTrig = true }, { t({ "\\begin{alphlistpar}", "\t\\item " }), i(1), t({ "", "\\end{alphlistpar}" }) }),
  s({ trig = "\\answer~", wordTrig = true }, { t({ "\\begin{answer}", "\t" }), i(1), t({ "", "\\end{answer}" }) }),
  s({ trig = "\\arablistpar~", wordTrig = true }, { t({ "\\begin{arablistpar}", "\t\\item " }), i(1), t({ "", "\\end{arablistpar}" }) }),
  s({ trig = "\\arablist~", wordTrig = true }, { t({ "\\begin{arablist}", "\t\\item " }), i(1), t({ "", "\\end{arablist}" }) }),
  s({ trig = "\\asserts~", wordTrig = true }, { t("\\asserts") }),
  s({ trig = "\\atoms~", wordTrig = true }, { t("\\atoms") }),
  s({ trig = "\\believes~", wordTrig = true }, { t("\\believes{"), i(1), t("}") }),
  s({ trig = "\\believe~", wordTrig = true }, { t("\\believe") }),
  s({ trig = "\\better~", wordTrig = true }, { t("\\better{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\bisim~", wordTrig = true }, { t("\\bisim") }),
  s({ trig = "\\botg~", wordTrig = true }, { t("\\botg") }),
  s({ trig = "\\bott~", wordTrig = true }, { t("\\bott") }),
  s({ trig = "\\caxc~", wordTrig = true }, { t("\\caxc") }),
  s({ trig = "\\caxpar~", wordTrig = true }, { t("\\caxpar") }),
  s({ trig = "\\cax~", wordTrig = true }, { t("\\cax") }),
  s({ trig = "\\cbelieves~", wordTrig = true }, { t("\\cbelieves{"), i(1), t("}") }),
  s({ trig = "\\cbelieve~", wordTrig = true }, { t("\\cbelieve") }),
  s({ trig = "\\ccax~", wordTrig = true }, { t("\\ccax") }),
  s({ trig = "\\cclss~", wordTrig = true }, { t("\\cclss") }),
  s({ trig = "\\ccls~", wordTrig = true }, { t("\\ccls") }),
  s({ trig = "\\ccl~", wordTrig = true }, { t("\\ccl") }),
  s({ trig = "\\ccred~", wordTrig = true }, { t("\\ccred{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\ccrs~", wordTrig = true }, { t("\\ccrs") }),
  s({ trig = "\\ccr~", wordTrig = true }, { t("\\ccr") }),
  s({ trig = "\\cdax~", wordTrig = true }, { t("\\cdax") }),
  s({ trig = "\\cduax~", wordTrig = true }, { t("\\cduax") }),
  s({ trig = "\\cfact~", wordTrig = true }, { t("\\cfact") }),
  s({ trig = "\\choicema~", wordTrig = true }, { t("\\choicema") }),
  s({ trig = "\\choice~", wordTrig = true }, { t("\\choice") }),
  s({ trig = "\\cknows~", wordTrig = true }, { t("\\cknows{"), i(1), t("}") }),
  s({ trig = "\\cknow~", wordTrig = true }, { t("\\cknow") }),
  s({ trig = "\\clor~", wordTrig = true }, { t("\\clor") }),
  s({ trig = "\\close~", wordTrig = true }, { t("\\close{"), i(1), t("}") }),
  s({ trig = "\\cmaxi~", wordTrig = true }, { t("\\cmaxi") }),
  s({ trig = "\\cmlsss~", wordTrig = true }, { t("\\cmlsss") }),
  s({ trig = "\\cmlss~", wordTrig = true }, { t("\\cmlss") }),
  s({ trig = "\\cmls~", wordTrig = true }, { t("\\cmls") }),
  s({ trig = "\\cml~", wordTrig = true }, { t("\\cml") }),
  s({ trig = "\\cmrs~", wordTrig = true }, { t("\\cmrs") }),
  s({ trig = "\\cmr~", wordTrig = true }, { t("\\cmr") }),
  s({ trig = "\\cnax~", wordTrig = true }, { t("\\cnax") }),
  s({ trig = "\\cnecsolo~", wordTrig = true }, { t("\\cnecsolo") }),
  s({ trig = "\\cnecs~", wordTrig = true }, { t("\\cnecs") }),
  s({ trig = "\\cnlr~", wordTrig = true }, { t("\\cnlr") }),
  s({ trig = "\\cnl~", wordTrig = true }, { t("\\cnl") }),
  s({ trig = "\\cnr~", wordTrig = true }, { t("\\cnr") }),
  s({ trig = "\\cn~", wordTrig = true }, { t("\\cn{"), i(1), t("}") }),
  s({ trig = "\\cobsolo~", wordTrig = true }, { t("\\cobsolo") }),
  s({ trig = "\\cobs~", wordTrig = true }, { t("\\cobs") }),
  s({ trig = "\\condopsolo~", wordTrig = true }, { t("\\condopsolo{"), i(1), t("}") }),
  s({ trig = "\\condop~", wordTrig = true }, { t("\\condop{"), i(1), t("}") }),
  s({ trig = "\\cought~", wordTrig = true }, { t("\\cought{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\cperms~", wordTrig = true }, { t("\\cperms") }),
  s({ trig = "\\cpossolo~", wordTrig = true }, { t("\\cpossolo") }),
  s({ trig = "\\cposs~", wordTrig = true }, { t("\\cposs") }),
  s({ trig = "\\cprob~", wordTrig = true }, { t("\\cprob{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\cred~", wordTrig = true }, { t("\\cred{"), i(1), t("}") }),
  s({ trig = "\\cstito~", wordTrig = true }, { t("\\cstito") }),
  s({ trig = "\\cstit~", wordTrig = true }, { t("\\cstit{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\cthss~", wordTrig = true }, { t("\\cthss") }),
  s({ trig = "\\cths~", wordTrig = true }, { t("\\cths") }),
  s({ trig = "\\cth~", wordTrig = true }, { t("\\cth") }),
  s({ trig = "\\cto~", wordTrig = true }, { t("\\cto") }),
  s({ trig = "\\ctruthsetmm~", wordTrig = true }, { t("\\ctruthsetmm{"), i(1), t("}") }),
  s({ trig = "\\ctruthsetmsub~", wordTrig = true }, { t("\\ctruthsetmsub{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\ctruthsetm~", wordTrig = true }, { t("\\ctruthsetm{"), i(1), t("}") }),
  s({ trig = "\\ctruthset~", wordTrig = true }, { t("\\ctruthset{"), i(1), t("}") }),
  s({ trig = "\\daxc~", wordTrig = true }, { t("\\daxc") }),
  s({ trig = "\\daxpar~", wordTrig = true }, { t("\\daxpar") }),
  s({ trig = "\\dax~", wordTrig = true }, { t("\\dax") }),
  s({ trig = "\\defbyvar~", wordTrig = true }, { t("\\defbyvar") }),
  s({ trig = "\\defby~", wordTrig = true }, { t("\\defby") }),
  s({ trig = "\\deland~", wordTrig = true }, { t("\\deland") }),
  s({ trig = "\\delor~", wordTrig = true }, { t("\\delor") }),
  s({ trig = "\\deneg~", wordTrig = true }, { t("\\deneg") }),
  s({ trig = "\\deny~", wordTrig = true }, { t("\\deny{"), i(1), t("}") }),
  s({ trig = "\\den~", wordTrig = true }, { t("\\den") }),
  s({ trig = "\\derives~", wordTrig = true }, { t("\\derives") }),
  s({ trig = "\\derivi~", wordTrig = true }, { t("\\derivi{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\deriv~", wordTrig = true }, { t("\\deriv{"), i(1), t("}") }),
  s({ trig = "\\deto~", wordTrig = true }, { t("\\deto") }),
  s({ trig = "\\de~", wordTrig = true }, { t("\\de") }),
  s({ trig = "\\drulepar~", wordTrig = true }, { t("\\drulepar") }),
  s({ trig = "\\drule~", wordTrig = true }, { t("\\drule") }),
  s({ trig = "\\dsax~", wordTrig = true }, { t("\\dsax") }),
  s({ trig = "\\dstito~", wordTrig = true }, { t("\\dstito") }),
  s({ trig = "\\dstit~", wordTrig = true }, { t("\\dstit{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\duaxpar~", wordTrig = true }, { t("\\duaxpar") }),
  s({ trig = "\\duax~", wordTrig = true }, { t("\\duax") }),
  s({ trig = "\\dvbar~", wordTrig = true }, { t("\\dvbar") }),
  s({ trig = "\\ecu~", wordTrig = true }, { t("\\ecu") }),
  s({ trig = "\\emptytruthset~", wordTrig = true }, { t("\\emptytruthset") }),
  s({ trig = "\\ent~", wordTrig = true }, { t("\\ent") }),
  s({ trig = "\\eruledj~", wordTrig = true }, { t("\\eruledj{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\erulej~", wordTrig = true }, { t("\\erulej{"), i(1), t("}") }),
  s({ trig = "\\false~", wordTrig = true }, { t("\\false") }),
  s({ trig = "\\fd~", wordTrig = true }, { t("\\fd") }),
  s({ trig = "\\filter~", wordTrig = true }, { t("\\filter") }),
  s({ trig = "\\five~", wordTrig = true }, { t("\\five") }),
  s({ trig = "\\flog~", wordTrig = true }, { t("\\flog") }),
  s({ trig = "\\flr~", wordTrig = true }, { t("\\flr") }),
  s({ trig = "\\fmlafmla~", wordTrig = true }, { t("\\fmlafmla") }),
  s({ trig = "\\fmlaset~", wordTrig = true }, { t("\\fmlaset") }),
  s({ trig = "\\fm~", wordTrig = true }, { t("\\fm") }),
  s({ trig = "\\fne~", wordTrig = true }, { t("\\fne") }),
  s({ trig = "\\fnof~", wordTrig = true }, { t("\\fnof{"), i(1), t("}") }),
  s({ trig = "\\fnw~", wordTrig = true }, { t("\\fnw") }),
  s({ trig = "\\fn~", wordTrig = true }, { t("\\fn") }),
  s({ trig = "\\forbidden~", wordTrig = true }, { t("\\forbidden") }),
  s({ trig = "\\four~", wordTrig = true }, { t("\\four") }),
  s({ trig = "\\fr~", wordTrig = true }, { t("\\fr") }),
  s({ trig = "\\fse~", wordTrig = true }, { t("\\fse") }),
  s({ trig = "\\fsof~", wordTrig = true }, { t("\\fsof{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\fsub~", wordTrig = true }, { t("\\fsub{"), i(1), t("}") }),
  s({ trig = "\\fsw~", wordTrig = true }, { t("\\fsw") }),
  s({ trig = "\\fs~", wordTrig = true }, { t("\\fs") }),
  s({ trig = "\\gentzen~", wordTrig = true }, { t({ "\\begin{gentzen}", "\t" }), i(1), t({ "", "\\end{gentzen}" }) }),
  s({ trig = "\\gives~", wordTrig = true }, { t("\\gives") }),
  s({ trig = "\\gratuitous~", wordTrig = true }, { t("\\gratuitous") }),
  s({ trig = "\\henceforth~", wordTrig = true }, { t("\\henceforth") }),
  s({ trig = "\\hilbertlist~", wordTrig = true }, { t({ "\\begin{hilbertlist}", "\t\\item " }), i(1), t({ "", "\\end{hilbertlist}" }) }),
  s({ trig = "\\hitherto~", wordTrig = true }, { t("\\hitherto") }),
  s({ trig = "\\hk~", wordTrig = true }, { t("\\hk") }),
  s({ trig = "\\hyphantom~", wordTrig = true }, { t("\\hyphantom") }),
  s({ trig = "\\hyp~", wordTrig = true }, { t("\\hyp{"), i(1), t("}") }),
  s({ trig = "\\iff~", wordTrig = true }, { t("\\iff") }),
  s({ trig = "\\ilor~", wordTrig = true }, { t("\\ilor") }),
  s({ trig = "\\inclin~", wordTrig = true }, { t("\\inclin") }),
  s({ trig = "\\incomp~", wordTrig = true }, { t("\\incomp") }),
  s({ trig = "\\ind~", wordTrig = true }, { t("\\ind") }),
  s({ trig = "\\infer~", wordTrig = true }, { t("\\infer") }),
  s({ trig = "\\infr~", wordTrig = true }, { t("\\infr{"), i(1), t("}{"), i(2), t("}{"), i(3), t("}{"), i(4), t("}") }),
  s({ trig = "\\inf~", wordTrig = true }, { t("\\inf{"), i(1), t("}{"), i(2), t("}{"), i(3), t("}") }),
  s({ trig = "\\intersect~", wordTrig = true }, { t("\\intersect") }),
  s({ trig = "\\iput~", wordTrig = true }, { t("\\iput{"), i(1), t("}") }),
  s({ trig = "\\iruledj~", wordTrig = true }, { t("\\iruledj{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\irulej~", wordTrig = true }, { t("\\irulej{"), i(1), t("}") }),
  s({ trig = "\\itemlistflush~", wordTrig = true }, { t({ "\\begin{itemlistflush}", "\t\\item " }), i(1), t({ "", "\\end{itemlistflush}" }) }),
  s({ trig = "\\itemlist~", wordTrig = true }, { t({ "\\begin{itemlist}", "\t\\item " }), i(1), t({ "", "\\end{itemlist}" }) }),
  s({ trig = "\\ito~", wordTrig = true }, { t("\\ito") }),
  s({ trig = "\\kaxc~", wordTrig = true }, { t("\\kaxc") }),
  s({ trig = "\\kaxpar~", wordTrig = true }, { t("\\kaxpar") }),
  s({ trig = "\\kax~", wordTrig = true }, { t("\\kax") }),
  s({ trig = "\\knows~", wordTrig = true }, { t("\\knows{"), i(1), t("}") }),
  s({ trig = "\\know~", wordTrig = true }, { t("\\know") }),
  s({ trig = "\\krulepar~", wordTrig = true }, { t("\\krulepar") }),
  s({ trig = "\\krule~", wordTrig = true }, { t("\\krule") }),
  s({ trig = "\\langd~", wordTrig = true }, { t("\\langd") }),
  s({ trig = "\\langmd~", wordTrig = true }, { t("\\langmd") }),
  s({ trig = "\\langm~", wordTrig = true }, { t("\\langm") }),
  s({ trig = "\\langp~", wordTrig = true }, { t("\\langp") }),
  s({ trig = "\\lang~", wordTrig = true }, { t("\\lang") }),
  s({ trig = "\\logicp~", wordTrig = true }, { t("\\logicp") }),
  s({ trig = "\\logic~", wordTrig = true }, { t("\\logic") }),
  s({ trig = "\\manrule~", wordTrig = true }, { t("\\manrule{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\maxic~", wordTrig = true }, { t("\\maxic") }),
  s({ trig = "\\maxipar~", wordTrig = true }, { t("\\maxipar") }),
  s({ trig = "\\maxi~", wordTrig = true }, { t("\\maxi") }),
  s({ trig = "\\may~", wordTrig = true }, { t("\\may") }),
  s({ trig = "\\mcseti~", wordTrig = true }, { t("\\mcseti{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\mcslog~", wordTrig = true }, { t("\\mcslog") }),
  s({ trig = "\\minus~", wordTrig = true }, { t("\\minus") }),
  s({ trig = "\\mmodels~", wordTrig = true }, { t("\\mmodels") }),
  s({ trig = "\\mnmodels~", wordTrig = true }, { t("\\mnmodels") }),
  s({ trig = "\\mntruesat~", wordTrig = true }, { t("\\mntruesat{"), i(1), t("}") }),
  s({ trig = "\\modelsrel~", wordTrig = true }, { t("\\modelsrel{"), i(1), t("}") }),
  s({ trig = "\\models~", wordTrig = true }, { t("\\models") }),
  s({ trig = "\\mprulepar~", wordTrig = true }, { t("\\mprulepar") }),
  s({ trig = "\\mprule~", wordTrig = true }, { t("\\mprule") }),
  s({ trig = "\\mtruesat~", wordTrig = true }, { t("\\mtruesat{"), i(1), t("}") }),
  s({ trig = "\\mwnp~", wordTrig = true }, { t("\\mwnp") }),
  s({ trig = "\\mwnv~", wordTrig = true }, { t("\\mwnv") }),
  s({ trig = "\\mwrp~", wordTrig = true }, { t("\\mwrp") }),
  s({ trig = "\\mwrv~", wordTrig = true }, { t("\\mwrv") }),
  s({ trig = "\\natent~", wordTrig = true }, { t("\\natent") }),
  s({ trig = "\\naxc~", wordTrig = true }, { t("\\naxc") }),
  s({ trig = "\\naxpar~", wordTrig = true }, { t("\\naxpar") }),
  s({ trig = "\\nax~", wordTrig = true }, { t("\\nax") }),
  s({ trig = "\\neced~", wordTrig = true }, { t("\\neced") }),
  s({ trig = "\\necessitates~", wordTrig = true }, { t("\\necessitates") }),
  s({ trig = "\\nec~", wordTrig = true }, { t("\\nec") }),
  s({ trig = "\\negedrule~", wordTrig = true }, { t("\\negedrule") }),
  s({ trig = "\\negidrule~", wordTrig = true }, { t("\\negidrule{"), i(1), t("}") }),
  s({ trig = "\\negiprule~", wordTrig = true }, { t("\\negiprule{"), i(1), t("}") }),
  s({ trig = "\\negipstarrule~", wordTrig = true }, { t("\\negipstarrule{"), i(1), t("}") }),
  s({ trig = "\\nmodels~", wordTrig = true }, { t("\\nmodels") }),
  s({ trig = "\\nnatent~", wordTrig = true }, { t("\\nnatent") }),
  s({ trig = "\\nproves~", wordTrig = true }, { t("\\nproves") }),
  s({ trig = "\\nrulepar~", wordTrig = true }, { t("\\nrulepar") }),
  s({ trig = "\\nrule~", wordTrig = true }, { t("\\nrule") }),
  s({ trig = "\\ntrues~", wordTrig = true }, { t("\\ntrues") }),
  s({ trig = "\\obligatory~", wordTrig = true }, { t("\\obligatory") }),
  s({ trig = "\\onlyif~", wordTrig = true }, { t("\\onlyif") }),
  s({ trig = "\\optional~", wordTrig = true }, { t("\\optional") }),
  s({ trig = "\\oputi~", wordTrig = true }, { t("\\oputi{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\oput~", wordTrig = true }, { t("\\oput{"), i(1), t("}") }),
  s({ trig = "\\oset~", wordTrig = true }, { t("\\oset{"), i(1), t("}") }),
  s({ trig = "\\ought~", wordTrig = true }, { t("\\ought") }),
  s({ trig = "\\parent~", wordTrig = true }, { t("\\parent{"), i(1), t("}") }),
  s({ trig = "\\pax~", wordTrig = true }, { t("\\pax") }),
  s({ trig = "\\permissible~", wordTrig = true }, { t("\\permissible") }),
  s({ trig = "\\plrulepar~", wordTrig = true }, { t("\\plrulepar") }),
  s({ trig = "\\plrule~", wordTrig = true }, { t("\\plrule") }),
  s({ trig = "\\poax~", wordTrig = true }, { t("\\poax") }),
  s({ trig = "\\pone~", wordTrig = true }, { t("\\pone") }),
  s({ trig = "\\porulepar~", wordTrig = true }, { t("\\porulepar") }),
  s({ trig = "\\porule~", wordTrig = true }, { t("\\porule") }),
  s({ trig = "\\posax~", wordTrig = true }, { t("\\posax") }),
  s({ trig = "\\posrulepar~", wordTrig = true }, { t("\\posrulepar") }),
  s({ trig = "\\posrule~", wordTrig = true }, { t("\\posrule") }),
  s({ trig = "\\possed~", wordTrig = true }, { t("\\possed") }),
  s({ trig = "\\poss~", wordTrig = true }, { t("\\poss") }),
  s({ trig = "\\power~", wordTrig = true }, { t("\\power{"), i(1), t("}") }),
  s({ trig = "\\pp~", wordTrig = true }, { t("\\pp{"), i(1), t("}") }),
  s({ trig = "\\precedes~", wordTrig = true }, { t("\\precedes") }),
  s({ trig = "\\proofsetl~", wordTrig = true }, { t("\\proofsetl{"), i(1), t("}") }),
  s({ trig = "\\proofset~", wordTrig = true }, { t("\\proofset{"), i(1), t("}") }),
  s({ trig = "\\props~", wordTrig = true }, { t("\\props") }),
  s({ trig = "\\provesc~", wordTrig = true }, { t("\\provesc") }),
  s({ trig = "\\provesio~", wordTrig = true }, { t("\\provesio") }),
  s({ trig = "\\provesm~", wordTrig = true }, { t("\\provesm") }),
  s({ trig = "\\provesrel~", wordTrig = true }, { t("\\provesrel{"), i(1), t("}") }),
  s({ trig = "\\provestf~", wordTrig = true }, { t("\\provestf") }),
  s({ trig = "\\proves~", wordTrig = true }, { t("\\proves") }),
  s({ trig = "\\psax~", wordTrig = true }, { t("\\psax") }),
  s({ trig = "\\pthree~", wordTrig = true }, { t("\\pthree") }),
  s({ trig = "\\ptwo~", wordTrig = true }, { t("\\ptwo") }),
  s({ trig = "\\pzero~", wordTrig = true }, { t("\\pzero") }),
  s({ trig = "\\p~", wordTrig = true }, { t("\\p{"), i(1), t("}") }),
  s({ trig = "\\qed~", wordTrig = true }, { t("\\qed") }),
  s({ trig = "\\question~", wordTrig = true }, { t({ "\\begin{question}", "\t" }), i(1), t({ "", "\\end{question}" }) }),
  s({ trig = "\\relrulepar~", wordTrig = true }, { t("\\relrulepar") }),
  s({ trig = "\\relrule~", wordTrig = true }, { t("\\relrule") }),
  s({ trig = "\\reposspar~", wordTrig = true }, { t("\\reposspar") }),
  s({ trig = "\\reposs~", wordTrig = true }, { t("\\reposs") }),
  s({ trig = "\\reprulepar~", wordTrig = true }, { t("\\reprulepar") }),
  s({ trig = "\\reprule~", wordTrig = true }, { t("\\reprule") }),
  s({ trig = "\\rerrulepar~", wordTrig = true }, { t("\\rerrulepar") }),
  s({ trig = "\\rerrule~", wordTrig = true }, { t("\\rerrule") }),
  s({ trig = "\\rerulepar~", wordTrig = true }, { t("\\rerulepar") }),
  s({ trig = "\\rerule~", wordTrig = true }, { t("\\rerule") }),
  s({ trig = "\\rmposspar~", wordTrig = true }, { t("\\rmposspar") }),
  s({ trig = "\\rmposs~", wordTrig = true }, { t("\\rmposs") }),
  s({ trig = "\\romanlist~", wordTrig = true }, { t({ "\\begin{romanlist}", "\t\\item " }), i(1), t({ "", "\\end{romanlist}" }) }),
  s({ trig = "\\rposspar~", wordTrig = true }, { t("\\rposspar") }),
  s({ trig = "\\rposs~", wordTrig = true }, { t("\\rposs") }),
  s({ trig = "\\samevas~", wordTrig = true }, { t("\\samevas{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\seq~", wordTrig = true }, { t("\\seq") }),
  s({ trig = "\\setfmla~", wordTrig = true }, { t("\\setfmla") }),
  s({ trig = "\\setset~", wordTrig = true }, { t("\\setset") }),
  s({ trig = "\\set~", wordTrig = true }, { t("\\set{"), i(1), t("}") }),
  s({ trig = "\\sphere~", wordTrig = true }, { t("\\sphere") }),
  s({ trig = "\\stitought~", wordTrig = true }, { t("\\stitought") }),
  s({ trig = "\\stitval~", wordTrig = true }, { t("\\stitval") }),
  s({ trig = "\\stit~", wordTrig = true }, { t("\\stit") }),
  s({ trig = "\\st~", wordTrig = true }, { t("\\st") }),
  s({ trig = "\\subought~", wordTrig = true }, { t("\\subought") }),
  s({ trig = "\\subrulepar~", wordTrig = true }, { t("\\subrulepar") }),
  s({ trig = "\\subrule~", wordTrig = true }, { t("\\subrule") }),
  s({ trig = "\\suchthat~", wordTrig = true }, { t("\\suchthat") }),
  s({ trig = "\\tautrulepar~", wordTrig = true }, { t("\\tautrulepar") }),
  s({ trig = "\\tautrule~", wordTrig = true }, { t("\\tautrule") }),
  s({ trig = "\\taxc~", wordTrig = true }, { t("\\taxc") }),
  s({ trig = "\\taxpar~", wordTrig = true }, { t("\\taxpar") }),
  s({ trig = "\\thempfootnote~", wordTrig = true }, { t("\\thempfootnote") }),
  s({ trig = "\\then~", wordTrig = true }, { t("\\then") }),
  s({ trig = "\\theory~", wordTrig = true }, { t("\\theory{"), i(1), t("}") }),
  s({ trig = "\\tightwedge~", wordTrig = true }, { t("\\tightwedge") }),
  s({ trig = "\\topg~", wordTrig = true }, { t("\\topg") }),
  s({ trig = "\\topt~", wordTrig = true }, { t("\\topt") }),
  s({ trig = "\\to~", wordTrig = true }, { t("\\to") }),
  s({ trig = "\\tree~", wordTrig = true }, { t("\\tree") }),
  s({ trig = "\\triggers~", wordTrig = true }, { t("\\triggers") }),
  s({ trig = "\\trues~", wordTrig = true }, { t("\\trues") }),
  s({ trig = "\\true~", wordTrig = true }, { t("\\true") }),
  s({ trig = "\\truthsetmm~", wordTrig = true }, { t("\\truthsetmm{"), i(1), t("}") }),
  s({ trig = "\\truthsetmsub~", wordTrig = true }, { t("\\truthsetmsub{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\truthsetm~", wordTrig = true }, { t("\\truthsetm{"), i(1), t("}") }),
  s({ trig = "\\truthset~", wordTrig = true }, { t("\\truthset{"), i(1), t("}") }),
  s({ trig = "\\tseq~", wordTrig = true }, { t("\\tseq") }),
  s({ trig = "\\uaxc~", wordTrig = true }, { t("\\uaxc") }),
  s({ trig = "\\uaxpar~", wordTrig = true }, { t("\\uaxpar") }),
  s({ trig = "\\uax~", wordTrig = true }, { t("\\uax") }),
  s({ trig = "\\union~", wordTrig = true }, { t("\\union") }),
  s({ trig = "\\unneced~", wordTrig = true }, { t("\\unneced") }),
  s({ trig = "\\unpossed~", wordTrig = true }, { t("\\unpossed") }),
  s({ trig = "\\val~", wordTrig = true }, { t("\\val{"), i(1), t("}") }),
  s({ trig = "\\versal~", wordTrig = true }, { t("\\versal{"), i(1), t("}") }),
  s({ trig = "\\vw~", wordTrig = true }, { t("\\vw{"), i(1), t("}{"), i(2), t("}") }),
  s({ trig = "\\was~", wordTrig = true }, { t("\\was") }),
  s({ trig = "\\waxc~", wordTrig = true }, { t("\\waxc") }),
  s({ trig = "\\wax~", wordTrig = true }, { t("\\wax") }),
  s({ trig = "\\wedgeset~", wordTrig = true }, { t("\\wedgeset") }),
  s({ trig = "\\willbe~", wordTrig = true }, { t("\\willbe") }),
  s({ trig = "\\woax~", wordTrig = true }, { t("\\woax") }),
  s({ trig = "\\wocax~", wordTrig = true }, { t("\\wocax") }),
}

return snippets
