#!/usr/bin/env python3
"""Regenerate latex/french-logic/AUDIT.md, the member inventory, from the package files.

Usage: inventory.py --hub PATH --modes modes.tsv [--usage usage.tsv] --out AUDIT.md

Units are the files the hub loads, in the hub's order, plus the quarry last.  The
mode column comes from the mode table; the two use columns from an optional census
of the consumers (the private harness keeps one as usage.tsv: name, then counts per
document group), and print as "-" without it.
"""
import argparse, csv, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_fixture_lib import strip_comments

def members(path):
    src = strip_comments(open(path, encoding='utf-8').read())
    out, seen = [], set()
    pat = re.compile(r'\\(?:(?:re)?newcommand|providecommand)\s*\*?\s*\{\\([A-Za-z@]+)\}\s*(?:\[(\d+)\])?\s*(?:\[([^\]]*)\])?'
                     r'|\\DeclareMathSymbol\{\\([A-Za-z]+)\}'
                     r'|\\(?:re)?newenvironment\s*\*?\s*\{([A-Za-z]+)\}'
                     r'|\\newtheorem\s*\*?\s*\{([A-Za-z]+)\}'
                     r'|\\NewDocumentCommand\s*\\([A-Za-z]+)'
                     r'|\\DeclareCiteCommand\{\\([A-Za-z]+)\}')
    # Headings come from the raw file's comments.  A %%% line is always a heading
    # (the old section markers); a %% line is the unit's own prose, never one; a
    # single-% line is a heading only when it opens a run of comment lines (the
    # later lines of a run continue it as prose), is short, and is not a sentence.
    # A trailing parenthetical is dropped from an over-long candidate, so
    # "Applied Modal Operators (to make these bold ...)" keeps its heading.
    heading = None
    raw = open(path, encoding='utf-8').read().split('\n')
    prev_comment = False
    for line in raw:
        s = line.strip()
        is_comment = s.startswith('%')
        is_rule = is_comment and not s.strip('%').strip()  # a bare %%%% line separates runs
        if is_comment and not is_rule:
            body = s.strip('%').strip()
            strong = s.startswith('%%%')
            if len(body) > 60 and body.endswith(')') and ' (' in body:
                body = body[:body.rfind(' (')].strip()
            ok = bool(re.match(r'^[A-Za-z]', body)) and len(body) <= 60 and not body.endswith('.')
            if ok and (strong or (not s.startswith('%%') and not prev_comment)):
                heading = body
            if strong:
                prev_comment = False  # a %%% heading opens a new run: a % line under it is a sub-heading
                continue
        prev_comment = is_comment and not is_rule
        if is_comment: continue
        code = re.split(r'(?<!\\)%', line, maxsplit=1)[0]
        for m in pat.finditer(code):
            if m.group(1): name, args, opt = '\\' + m.group(1), int(m.group(2) or 0), m.group(3) is not None
            elif m.group(4): name, args, opt = '\\' + m.group(4), 0, False
            elif m.group(5): name, args, opt = 'env:' + m.group(5), 0, False
            elif m.group(6): name, args, opt = 'env:' + m.group(6), 0, False
            elif m.group(7): name, args, opt = '\\' + m.group(7), 0, False
            else: name, args, opt = '\\' + m.group(8), 0, False
            if name in seen or '@' in name: continue
            seen.add(name); out.append((name, args, opt, heading))
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--hub', required=True); ap.add_argument('--modes', required=True)
    ap.add_argument('--usage'); ap.add_argument('--out', required=True); ap.add_argument('--date', default='today')
    a = ap.parse_args()
    pkgdir = os.path.dirname(os.path.abspath(a.hub))
    hub = open(a.hub, encoding='utf-8').read()
    units = re.findall(r'\\RequirePackage\{french-logic-([a-z-]+)\}', hub) + ['quarry']
    modes = {r['name']: r for r in csv.DictReader(open(a.modes), delimiter='\t')}
    usage = {}
    if a.usage:
        for r in csv.DictReader(open(a.usage), delimiter='\t'):
            other = sum(int(r[k]) for k in ('diss-beamer', 'teach', 'opusc', 'other') if k in r)
            usage[r['name']] = (int(r.get('diss', 0)), other)
    def mode(n):
        m = modes.get(n)
        if not m: return '?'
        if n.startswith('env:'): return 'T' if m['text'] == 'ok' else '✗'
        key = (m['text'], m['math'])
        return {('ok', 'ok'): 'TM', ('ERR', 'ok'): 'M', ('ok', 'ERR'): 'T', ('ERR', 'ERR'): '✗', ('ok', '-'): 'T (in tree)', ('ERR', '-'): '✗'}.get(key, '?')
    lines = [f"""# AUDIT.md — french-logic member inventory

Inventory contract for the `french-logic` package: every member, by unit file,
with its argument count, the modes it survives, its use in the live consumers,
and known trouble. Generated by `tests/french-logic/inventory.py` — do not edit
by hand; regenerate after any change to the package. Units are the files the
hub loads, in the hub's order; the quarry, which the hub never loads, is last.

Columns: **args** — mandatory arguments, `[opt]` if the first is optional;
**mode** — `TM` works in text and math, `M` math only, `T` text only,
`T (in tree)` meaningful only inside a `gentzen` tree, `✗` fails in both;
**diss** — uses in the live dissertation and its article wrappers;
**other** — uses in the beamer decks, teaching, opuscula, and the other
documents that load the stowed package. A `0 0` member is vocabulary, not a
deletion candidate (README, principle 1).
"""]
    total = 0
    for u in units:
        path = os.path.join(pkgdir, f'french-logic-{u}.sty')
        if not os.path.exists(path): continue
        ms = members(path); total += len(ms)
        lines.append(f'\n## `french-logic-{u}.sty` — {len(ms)} members\n')
        cur = object()  # not None: a first group with no heading still gets its header row
        for name, args, opt, heading in ms:
            if heading != cur:
                cur = heading
                lines.append(f'\n**{heading or "(unheaded)"}**\n')
                lines.append('| member | args | mode | diss | other | notes |\n|---|---|---|---|---|---|')
            astr = (f"{args}{'[opt]' if opt else ''}" if args else '')
            d, o = usage.get(name, ('-', '-'))
            m = modes.get(name); notes = ''
            if m and m.get('warning'): notes = 'warns: ' + m['warning'][:40]
            if m and m['text'] == 'ERR' and (m['math'] == 'ERR'): notes = 'fails in both modes: ' + (m['math_error'] or m['text_error'])[:50]
            lines.append(f'| `{name}` | {astr} | {mode(name)} | {d} | {o} | {notes} |')
    lines.append(f'\n\n{total} members in the loaded units.\n')
    open(a.out, 'w', encoding='utf-8').write('\n'.join(lines))
    print(f'AUDIT: {total} members across {len(units)} unit files')

if __name__ == '__main__':
    main()
