-- BibTeX / biblatex entry templates, hand-kept: the 32 entry types of LaTeX Workshop's data,
-- converted once in 2025-11 (latex-workshop.lua, retired 2026-09-13 at stage 3 of the LaTeX
-- completion campaign) and moved here without the trailing ~ their triggers carried.  The
-- loader registers this file as the pseudo-filetype hand-bibtex for bib and bibtex buffers.
-- Edit freely; nothing regenerates it.
local ls = require("luasnip")
local s, t, i = ls.snippet, ls.text_node, ls.insert_node

return {
  package = "hand-bibtex",
  includes = {},
  lists = {},
  snippets = {
    s({ trig = "@article~", wordTrig = true }, {
      t("@article{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  annotator = {" }),
      i(3, "annotator"),
      t({ "},", "  commentator = {" }),
      i(4, "commentator"),
      t({ "},", "  doi = {" }),
      i(5, "doi"),
      t({ "},", "  editor = {" }),
      i(6, "editor"),
      t({ "},", "  eid = {" }),
      i(7, "eid"),
      t({ "},", "  eprint = {" }),
      i(8, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(9, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(10, "eprinttype"),
      t({ "},", "  issn = {" }),
      i(11, "issn"),
      t({ "},", "  issue = {" }),
      i(12, "issue"),
      t({ "},", "  issuesubtitle = {" }),
      i(13, "issuesubtitle"),
      t({ "},", "  issuetitle = {" }),
      i(14, "issuetitle"),
      t({ "},", "  journalsubtitle = {" }),
      i(15, "journalsubtitle"),
      t({ "},", "  language = {" }),
      i(16, "language"),
      t({ "},", "  month = {" }),
      i(17, "month"),
      t({ "},", "  note = {" }),
      i(18, "note"),
      t({ "},", "  number = {" }),
      i(19, "number"),
      t({ "},", "  origlanguage = {" }),
      i(20, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(21, "pages"),
      t({ "},", "  pubstate = {" }),
      i(22, "pubstate"),
      t({ "},", "  series = {" }),
      i(23, "series"),
      t({ "},", "  subtitle = {" }),
      i(24, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(25, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(26, "translator"),
      t({ "},", "  url = {" }),
      i(27, "url"),
      t({ "},", "  urldate = {" }),
      i(28, "urldate"),
      t({ "},", "  version = {" }),
      i(29, "version"),
      t({ "},", "  volume = {" }),
      i(30, "volume"),
      t({ "}", "}" }),
    }),
    s({ trig = "@bookinbook~", wordTrig = true }, {
      t("@bookinbook{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  bookauthor = {" }),
      i(5, "bookauthor"),
      t({ "},", "  booksubtitle = {" }),
      i(6, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(7, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(8, "chapter"),
      t({ "},", "  commentator = {" }),
      i(9, "commentator"),
      t({ "},", "  doi = {" }),
      i(10, "doi"),
      t({ "},", "  edition = {" }),
      i(11, "edition"),
      t({ "},", "  editor = {" }),
      i(12, "editor"),
      t({ "},", "  editora = {" }),
      i(13, "editora"),
      t({ "},", "  editorb = {" }),
      i(14, "editorb"),
      t({ "},", "  editorc = {" }),
      i(15, "editorc"),
      t({ "},", "  eid = {" }),
      i(16, "eid"),
      t({ "},", "  eprint = {" }),
      i(17, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(18, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(19, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(20, "foreword"),
      t({ "},", "  introduction = {" }),
      i(21, "introduction"),
      t({ "},", "  isbn = {" }),
      i(22, "isbn"),
      t({ "},", "  language = {" }),
      i(23, "language"),
      t({ "},", "  location = {" }),
      i(24, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(25, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(26, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(27, "maintitleaddon"),
      t({ "},", "  note = {" }),
      i(28, "note"),
      t({ "},", "  number = {" }),
      i(29, "number"),
      t({ "},", "  origlanguage = {" }),
      i(30, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(31, "pages"),
      t({ "},", "  part = {" }),
      i(32, "part"),
      t({ "},", "  publisher = {" }),
      i(33, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(34, "pubstate"),
      t({ "},", "  series = {" }),
      i(35, "series"),
      t({ "},", "  subtitle = {" }),
      i(36, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(37, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(38, "translator"),
      t({ "},", "  url = {" }),
      i(39, "url"),
      t({ "},", "  urldate = {" }),
      i(40, "urldate"),
      t({ "},", "  volume = {" }),
      i(41, "volume"),
      t({ "},", "  volumes = {" }),
      i(42, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@booklet~", wordTrig = true }, {
      t("@booklet{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  adress = {" }),
      i(3, "adress"),
      t({ "},", "  chapter = {" }),
      i(4, "chapter"),
      t({ "},", "  doi = {" }),
      i(5, "doi"),
      t({ "},", "  eprint = {" }),
      i(6, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(7, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(8, "eprinttype"),
      t({ "},", "  howpublished = {" }),
      i(9, "howpublished"),
      t({ "},", "  language = {" }),
      i(10, "language"),
      t({ "},", "  location = {" }),
      i(11, "location"),
      t({ "},", "  month = {" }),
      i(12, "month"),
      t({ "},", "  note = {" }),
      i(13, "note"),
      t({ "},", "  pages = {" }),
      i(14, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(15, "pagetotal"),
      t({ "},", "  pubstate = {" }),
      i(16, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(17, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(18, "titleaddon"),
      t({ "},", "  type = {" }),
      i(19, "type"),
      t({ "},", "  url = {" }),
      i(20, "url"),
      t({ "},", "  urldate = {" }),
      i(21, "urldate"),
      t({ "}", "}" }),
    }),
    s({ trig = "@book~", wordTrig = true }, {
      t("@book{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  chapter = {" }),
      i(5, "chapter"),
      t({ "},", "  commentator = {" }),
      i(6, "commentator"),
      t({ "},", "  doi = {" }),
      i(7, "doi"),
      t({ "},", "  edition = {" }),
      i(8, "edition"),
      t({ "},", "  editor = {" }),
      i(9, "editor"),
      t({ "},", "  eprint = {" }),
      i(10, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(11, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(12, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(13, "foreword"),
      t({ "},", "  introduction = {" }),
      i(14, "introduction"),
      t({ "},", "  isbn = {" }),
      i(15, "isbn"),
      t({ "},", "  language = {" }),
      i(16, "language"),
      t({ "},", "  location = {" }),
      i(17, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(18, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(19, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(20, "maintitleaddon"),
      t({ "},", "  month = {" }),
      i(21, "month"),
      t({ "},", "  note = {" }),
      i(22, "note"),
      t({ "},", "  number = {" }),
      i(23, "number"),
      t({ "},", "  origlanguage = {" }),
      i(24, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(25, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(26, "pagetotal"),
      t({ "},", "  part = {" }),
      i(27, "part"),
      t({ "},", "  publisher = {" }),
      i(28, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(29, "pubstate"),
      t({ "},", "  series = {" }),
      i(30, "series"),
      t({ "},", "  subtitle = {" }),
      i(31, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(32, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(33, "translator"),
      t({ "},", "  url = {" }),
      i(34, "url"),
      t({ "},", "  urldate = {" }),
      i(35, "urldate"),
      t({ "},", "  volume = {" }),
      i(36, "volume"),
      t({ "},", "  volumes = {" }),
      i(37, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@collection~", wordTrig = true }, {
      t("@collection{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  chapter = {" }),
      i(5, "chapter"),
      t({ "},", "  commentator = {" }),
      i(6, "commentator"),
      t({ "},", "  doi = {" }),
      i(7, "doi"),
      t({ "},", "  edition = {" }),
      i(8, "edition"),
      t({ "},", "  editora = {" }),
      i(9, "editora"),
      t({ "},", "  editorb = {" }),
      i(10, "editorb"),
      t({ "},", "  editorc = {" }),
      i(11, "editorc"),
      t({ "},", "  eid = {" }),
      i(12, "eid"),
      t({ "},", "  eprint = {" }),
      i(13, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(14, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(15, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(16, "foreword"),
      t({ "},", "  introduction = {" }),
      i(17, "introduction"),
      t({ "},", "  isbn = {" }),
      i(18, "isbn"),
      t({ "},", "  language = {" }),
      i(19, "language"),
      t({ "},", "  location = {" }),
      i(20, "location"),
      t({ "},", "  maintitle = {" }),
      i(21, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(22, "maintitleaddon"),
      t({ "},", "  note = {" }),
      i(23, "note"),
      t({ "},", "  number = {" }),
      i(24, "number"),
      t({ "},", "  origlanguage = {" }),
      i(25, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(26, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(27, "pagetotal"),
      t({ "},", "  part = {" }),
      i(28, "part"),
      t({ "},", "  publisher = {" }),
      i(29, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(30, "pubstate"),
      t({ "},", "  series = {" }),
      i(31, "series"),
      t({ "},", "  subtitle = {" }),
      i(32, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(33, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(34, "translator"),
      t({ "},", "  url = {" }),
      i(35, "url"),
      t({ "},", "  urldate = {" }),
      i(36, "urldate"),
      t({ "},", "  volume = {" }),
      i(37, "volume"),
      t({ "},", "  volumes = {" }),
      i(38, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@conference~", wordTrig = true }, {
      t("@conference{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  address = {" }),
      i(3, "address"),
      t({ "},", "  booksubtitle = {" }),
      i(4, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(5, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(6, "chapter"),
      t({ "},", "  doi = {" }),
      i(7, "doi"),
      t({ "},", "  editor = {" }),
      i(8, "editor"),
      t({ "},", "  eprint = {" }),
      i(9, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(10, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(11, "eprinttype"),
      t({ "},", "  eventdate = {" }),
      i(12, "eventdate"),
      t({ "},", "  eventtitle = {" }),
      i(13, "eventtitle"),
      t({ "},", "  eventtitleaddon = {" }),
      i(14, "eventtitleaddon"),
      t({ "},", "  isbn = {" }),
      i(15, "isbn"),
      t({ "},", "  language = {" }),
      i(16, "language"),
      t({ "},", "  location = {" }),
      i(17, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(18, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(19, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(20, "maintitleaddon"),
      t({ "},", "  month = {" }),
      i(21, "month"),
      t({ "},", "  note = {" }),
      i(22, "note"),
      t({ "},", "  note. = {" }),
      i(23, "note."),
      t({ "},", "  number = {" }),
      i(24, "number"),
      t({ "},", "  organization = {" }),
      i(25, "organization"),
      t({ "},", "  pages = {" }),
      i(26, "pages"),
      t({ "},", "  part = {" }),
      i(27, "part"),
      t({ "},", "  publisher = {" }),
      i(28, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(29, "pubstate"),
      t({ "},", "  series = {" }),
      i(30, "series"),
      t({ "},", "  subtitle = {" }),
      i(31, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(32, "titleaddon"),
      t({ "},", "  url = {" }),
      i(33, "url"),
      t({ "},", "  urldate = {" }),
      i(34, "urldate"),
      t({ "},", "  venue = {" }),
      i(35, "venue"),
      t({ "},", "  volume = {" }),
      i(36, "volume"),
      t({ "},", "  volumes = {" }),
      i(37, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@dataset~", wordTrig = true }, {
      t("@dataset{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  doi = {" }),
      i(3, "doi"),
      t({ "},", "  edition = {" }),
      i(4, "edition"),
      t({ "},", "  eprint = {" }),
      i(5, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(6, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(7, "eprinttype"),
      t({ "},", "  language = {" }),
      i(8, "language"),
      t({ "},", "  location = {" }),
      i(9, "location"),
      t({ "},", "  note = {" }),
      i(10, "note"),
      t({ "},", "  number = {" }),
      i(11, "number"),
      t({ "},", "  organization = {" }),
      i(12, "organization"),
      t({ "},", "  publisher = {" }),
      i(13, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(14, "pubstate"),
      t({ "},", "  series = {" }),
      i(15, "series"),
      t({ "},", "  subtitle = {" }),
      i(16, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(17, "titleaddon"),
      t({ "},", "  type = {" }),
      i(18, "type"),
      t({ "},", "  url = {" }),
      i(19, "url"),
      t({ "},", "  urldate = {" }),
      i(20, "urldate"),
      t({ "},", "  version = {" }),
      i(21, "version"),
      t({ "}", "}" }),
    }),
    s({ trig = "@inbook~", wordTrig = true }, {
      t("@inbook{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  bookauthor = {" }),
      i(5, "bookauthor"),
      t({ "},", "  booksubtitle = {" }),
      i(6, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(7, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(8, "chapter"),
      t({ "},", "  commentator = {" }),
      i(9, "commentator"),
      t({ "},", "  doi = {" }),
      i(10, "doi"),
      t({ "},", "  edition = {" }),
      i(11, "edition"),
      t({ "},", "  editor = {" }),
      i(12, "editor"),
      t({ "},", "  eprint = {" }),
      i(13, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(14, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(15, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(16, "foreword"),
      t({ "},", "  introduction = {" }),
      i(17, "introduction"),
      t({ "},", "  isbn = {" }),
      i(18, "isbn"),
      t({ "},", "  language = {" }),
      i(19, "language"),
      t({ "},", "  location = {" }),
      i(20, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(21, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(22, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(23, "maintitleaddon"),
      t({ "},", "  month = {" }),
      i(24, "month"),
      t({ "},", "  note = {" }),
      i(25, "note"),
      t({ "},", "  number = {" }),
      i(26, "number"),
      t({ "},", "  origlanguage = {" }),
      i(27, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(28, "pages"),
      t({ "},", "  part = {" }),
      i(29, "part"),
      t({ "},", "  publisher = {" }),
      i(30, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(31, "pubstate"),
      t({ "},", "  series = {" }),
      i(32, "series"),
      t({ "},", "  subtitle = {" }),
      i(33, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(34, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(35, "translator"),
      t({ "},", "  type = {" }),
      i(36, "type"),
      t({ "},", "  url = {" }),
      i(37, "url"),
      t({ "},", "  urldate = {" }),
      i(38, "urldate"),
      t({ "},", "  volume = {" }),
      i(39, "volume"),
      t({ "},", "  volumes = {" }),
      i(40, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@incollection~", wordTrig = true }, {
      t("@incollection{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  address = {" }),
      i(3, "address"),
      t({ "},", "  afterword = {" }),
      i(4, "afterword"),
      t({ "},", "  annotator = {" }),
      i(5, "annotator"),
      t({ "},", "  booksubtitle = {" }),
      i(6, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(7, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(8, "chapter"),
      t({ "},", "  commentator = {" }),
      i(9, "commentator"),
      t({ "},", "  doi = {" }),
      i(10, "doi"),
      t({ "},", "  edition = {" }),
      i(11, "edition"),
      t({ "},", "  editor = {" }),
      i(12, "editor"),
      t({ "},", "  eprint = {" }),
      i(13, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(14, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(15, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(16, "foreword"),
      t({ "},", "  introduction = {" }),
      i(17, "introduction"),
      t({ "},", "  isbn = {" }),
      i(18, "isbn"),
      t({ "},", "  language = {" }),
      i(19, "language"),
      t({ "},", "  location = {" }),
      i(20, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(21, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(22, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(23, "maintitleaddon"),
      t({ "},", "  month = {" }),
      i(24, "month"),
      t({ "},", "  note = {" }),
      i(25, "note"),
      t({ "},", "  number = {" }),
      i(26, "number"),
      t({ "},", "  origlanguage = {" }),
      i(27, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(28, "pages"),
      t({ "},", "  part = {" }),
      i(29, "part"),
      t({ "},", "  publisher = {" }),
      i(30, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(31, "pubstate"),
      t({ "},", "  series = {" }),
      i(32, "series"),
      t({ "},", "  subtitle = {" }),
      i(33, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(34, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(35, "translator"),
      t({ "},", "  type = {" }),
      i(36, "type"),
      t({ "},", "  url = {" }),
      i(37, "url"),
      t({ "},", "  urldate = {" }),
      i(38, "urldate"),
      t({ "},", "  volume = {" }),
      i(39, "volume"),
      t({ "},", "  volumes = {" }),
      i(40, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@inproceedings~", wordTrig = true }, {
      t("@inproceedings{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  address = {" }),
      i(3, "address"),
      t({ "},", "  booksubtitle = {" }),
      i(4, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(5, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(6, "chapter"),
      t({ "},", "  doi = {" }),
      i(7, "doi"),
      t({ "},", "  editor = {" }),
      i(8, "editor"),
      t({ "},", "  eprint = {" }),
      i(9, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(10, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(11, "eprinttype"),
      t({ "},", "  eventdate = {" }),
      i(12, "eventdate"),
      t({ "},", "  eventtitle = {" }),
      i(13, "eventtitle"),
      t({ "},", "  eventtitleaddon = {" }),
      i(14, "eventtitleaddon"),
      t({ "},", "  isbn = {" }),
      i(15, "isbn"),
      t({ "},", "  language = {" }),
      i(16, "language"),
      t({ "},", "  location = {" }),
      i(17, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(18, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(19, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(20, "maintitleaddon"),
      t({ "},", "  month = {" }),
      i(21, "month"),
      t({ "},", "  note = {" }),
      i(22, "note"),
      t({ "},", "  number = {" }),
      i(23, "number"),
      t({ "},", "  organization = {" }),
      i(24, "organization"),
      t({ "},", "  pages = {" }),
      i(25, "pages"),
      t({ "},", "  part = {" }),
      i(26, "part"),
      t({ "},", "  publisher = {" }),
      i(27, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(28, "pubstate"),
      t({ "},", "  series = {" }),
      i(29, "series"),
      t({ "},", "  subtitle = {" }),
      i(30, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(31, "titleaddon"),
      t({ "},", "  url = {" }),
      i(32, "url"),
      t({ "},", "  urldate = {" }),
      i(33, "urldate"),
      t({ "},", "  venue = {" }),
      i(34, "venue"),
      t({ "},", "  volume = {" }),
      i(35, "volume"),
      t({ "},", "  volumes = {" }),
      i(36, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@inreference~", wordTrig = true }, {
      t("@inreference{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  booksubtitle = {" }),
      i(5, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(6, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(7, "chapter"),
      t({ "},", "  commentator = {" }),
      i(8, "commentator"),
      t({ "},", "  doi = {" }),
      i(9, "doi"),
      t({ "},", "  edition = {" }),
      i(10, "edition"),
      t({ "},", "  editor = {" }),
      i(11, "editor"),
      t({ "},", "  editora = {" }),
      i(12, "editora"),
      t({ "},", "  editorb = {" }),
      i(13, "editorb"),
      t({ "},", "  editorc = {" }),
      i(14, "editorc"),
      t({ "},", "  eid = {" }),
      i(15, "eid"),
      t({ "},", "  eprint = {" }),
      i(16, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(17, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(18, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(19, "foreword"),
      t({ "},", "  introduction = {" }),
      i(20, "introduction"),
      t({ "},", "  isbn = {" }),
      i(21, "isbn"),
      t({ "},", "  language = {" }),
      i(22, "language"),
      t({ "},", "  location = {" }),
      i(23, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(24, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(25, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(26, "maintitleaddon"),
      t({ "},", "  note = {" }),
      i(27, "note"),
      t({ "},", "  number = {" }),
      i(28, "number"),
      t({ "},", "  origlanguage = {" }),
      i(29, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(30, "pages"),
      t({ "},", "  part = {" }),
      i(31, "part"),
      t({ "},", "  publisher = {" }),
      i(32, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(33, "pubstate"),
      t({ "},", "  series = {" }),
      i(34, "series"),
      t({ "},", "  subtitle = {" }),
      i(35, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(36, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(37, "translator"),
      t({ "},", "  url = {" }),
      i(38, "url"),
      t({ "},", "  urldate = {" }),
      i(39, "urldate"),
      t({ "},", "  volume = {" }),
      i(40, "volume"),
      t({ "},", "  volumes = {" }),
      i(41, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@manual~", wordTrig = true }, {
      t("@manual{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  address = {" }),
      i(3, "address"),
      t({ "},", "  chapter = {" }),
      i(4, "chapter"),
      t({ "},", "  doi = {" }),
      i(5, "doi"),
      t({ "},", "  edition = {" }),
      i(6, "edition"),
      t({ "},", "  eprint = {" }),
      i(7, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(8, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(9, "eprinttype"),
      t({ "},", "  isbn = {" }),
      i(10, "isbn"),
      t({ "},", "  language = {" }),
      i(11, "language"),
      t({ "},", "  location = {" }),
      i(12, "location"),
      t({ "},", "  month = {" }),
      i(13, "month"),
      t({ "},", "  note = {" }),
      i(14, "note"),
      t({ "},", "  number = {" }),
      i(15, "number"),
      t({ "},", "  organization = {" }),
      i(16, "organization"),
      t({ "},", "  pages = {" }),
      i(17, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(18, "pagetotal"),
      t({ "},", "  publisher = {" }),
      i(19, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(20, "pubstate"),
      t({ "},", "  series = {" }),
      i(21, "series"),
      t({ "},", "  subtitle = {" }),
      i(22, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(23, "titleaddon"),
      t({ "},", "  type = {" }),
      i(24, "type"),
      t({ "},", "  url = {" }),
      i(25, "url"),
      t({ "},", "  urldate = {" }),
      i(26, "urldate"),
      t({ "},", "  version = {" }),
      i(27, "version"),
      t({ "},", "  year = {" }),
      i(28, "year"),
      t({ "}", "}" }),
    }),
    s({ trig = "@mastersthesis~", wordTrig = true }, {
      t("@mastersthesis{"),
      i(1, "key"),
      t({ ",", "  address = {" }),
      i(2, "address"),
      t({ "},", "  month = {" }),
      i(3, "month"),
      t({ "},", "  note = {" }),
      i(4, "note"),
      t({ "},", "  type = {" }),
      i(5, "type"),
      t({ "}", "}" }),
    }),
    s({ trig = "@misc~", wordTrig = true }, {
      t("@misc{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  doi = {" }),
      i(3, "doi"),
      t({ "},", "  eprint = {" }),
      i(4, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(5, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(6, "eprinttype"),
      t({ "},", "  howpublished = {" }),
      i(7, "howpublished"),
      t({ "},", "  language = {" }),
      i(8, "language"),
      t({ "},", "  location = {" }),
      i(9, "location"),
      t({ "},", "  month = {" }),
      i(10, "month"),
      t({ "},", "  note = {" }),
      i(11, "note"),
      t({ "},", "  organization = {" }),
      i(12, "organization"),
      t({ "},", "  pubstate = {" }),
      i(13, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(14, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(15, "titleaddon"),
      t({ "},", "  type = {" }),
      i(16, "type"),
      t({ "},", "  url = {" }),
      i(17, "url"),
      t({ "},", "  urldate = {" }),
      i(18, "urldate"),
      t({ "},", "  version = {" }),
      i(19, "version"),
      t({ "},", "  year = {" }),
      i(20, "year"),
      t({ "}", "}" }),
    }),
    s({ trig = "@mvbook~", wordTrig = true }, {
      t("@mvbook{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  booksubtitle = {" }),
      i(5, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(6, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(7, "chapter"),
      t({ "},", "  commentator = {" }),
      i(8, "commentator"),
      t({ "},", "  doi = {" }),
      i(9, "doi"),
      t({ "},", "  edition = {" }),
      i(10, "edition"),
      t({ "},", "  editor = {" }),
      i(11, "editor"),
      t({ "},", "  editora = {" }),
      i(12, "editora"),
      t({ "},", "  editorb = {" }),
      i(13, "editorb"),
      t({ "},", "  editorc = {" }),
      i(14, "editorc"),
      t({ "},", "  eid = {" }),
      i(15, "eid"),
      t({ "},", "  eprint = {" }),
      i(16, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(17, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(18, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(19, "foreword"),
      t({ "},", "  introduction = {" }),
      i(20, "introduction"),
      t({ "},", "  isbn = {" }),
      i(21, "isbn"),
      t({ "},", "  language = {" }),
      i(22, "language"),
      t({ "},", "  location = {" }),
      i(23, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(24, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(25, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(26, "maintitleaddon"),
      t({ "},", "  note = {" }),
      i(27, "note"),
      t({ "},", "  number = {" }),
      i(28, "number"),
      t({ "},", "  origlanguage = {" }),
      i(29, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(30, "pages"),
      t({ "},", "  part = {" }),
      i(31, "part"),
      t({ "},", "  publisher = {" }),
      i(32, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(33, "pubstate"),
      t({ "},", "  series = {" }),
      i(34, "series"),
      t({ "},", "  subtitle = {" }),
      i(35, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(36, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(37, "translator"),
      t({ "},", "  url = {" }),
      i(38, "url"),
      t({ "},", "  urldate = {" }),
      i(39, "urldate"),
      t({ "},", "  volume = {" }),
      i(40, "volume"),
      t({ "},", "  volumes = {" }),
      i(41, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@mvcollection~", wordTrig = true }, {
      t("@mvcollection{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  commentator = {" }),
      i(5, "commentator"),
      t({ "},", "  doi = {" }),
      i(6, "doi"),
      t({ "},", "  edition = {" }),
      i(7, "edition"),
      t({ "},", "  editora = {" }),
      i(8, "editora"),
      t({ "},", "  editorb = {" }),
      i(9, "editorb"),
      t({ "},", "  editorc = {" }),
      i(10, "editorc"),
      t({ "},", "  eprint = {" }),
      i(11, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(12, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(13, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(14, "foreword"),
      t({ "},", "  introduction = {" }),
      i(15, "introduction"),
      t({ "},", "  isbn = {" }),
      i(16, "isbn"),
      t({ "},", "  language = {" }),
      i(17, "language"),
      t({ "},", "  location = {" }),
      i(18, "location"),
      t({ "},", "  note = {" }),
      i(19, "note"),
      t({ "},", "  number = {" }),
      i(20, "number"),
      t({ "},", "  origlanguage = {" }),
      i(21, "origlanguage"),
      t({ "},", "  pagetotal = {" }),
      i(22, "pagetotal"),
      t({ "},", "  publisher = {" }),
      i(23, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(24, "pubstate"),
      t({ "},", "  series = {" }),
      i(25, "series"),
      t({ "},", "  subtitle = {" }),
      i(26, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(27, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(28, "translator"),
      t({ "},", "  url = {" }),
      i(29, "url"),
      t({ "},", "  urldate = {" }),
      i(30, "urldate"),
      t({ "},", "  volumes = {" }),
      i(31, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@mvproceedings~", wordTrig = true }, {
      t("@mvproceedings{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  doi = {" }),
      i(3, "doi"),
      t({ "},", "  editor = {" }),
      i(4, "editor"),
      t({ "},", "  eprint = {" }),
      i(5, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(6, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(7, "eprinttype"),
      t({ "},", "  eventdate = {" }),
      i(8, "eventdate"),
      t({ "},", "  eventtitle = {" }),
      i(9, "eventtitle"),
      t({ "},", "  eventtitleaddon = {" }),
      i(10, "eventtitleaddon"),
      t({ "},", "  isbn = {" }),
      i(11, "isbn"),
      t({ "},", "  language = {" }),
      i(12, "language"),
      t({ "},", "  location = {" }),
      i(13, "location"),
      t({ "},", "  month = {" }),
      i(14, "month"),
      t({ "},", "  note = {" }),
      i(15, "note"),
      t({ "},", "  number = {" }),
      i(16, "number"),
      t({ "},", "  organization = {" }),
      i(17, "organization"),
      t({ "},", "  pagetotal = {" }),
      i(18, "pagetotal"),
      t({ "},", "  publisher = {" }),
      i(19, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(20, "pubstate"),
      t({ "},", "  series = {" }),
      i(21, "series"),
      t({ "},", "  subtitle = {" }),
      i(22, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(23, "titleaddon"),
      t({ "},", "  url = {" }),
      i(24, "url"),
      t({ "},", "  urldate = {" }),
      i(25, "urldate"),
      t({ "},", "  venue = {" }),
      i(26, "venue"),
      t({ "},", "  volumes = {" }),
      i(27, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@mvreference~", wordTrig = true }, {
      t("@mvreference{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  commentator = {" }),
      i(5, "commentator"),
      t({ "},", "  doi = {" }),
      i(6, "doi"),
      t({ "},", "  edition = {" }),
      i(7, "edition"),
      t({ "},", "  editora = {" }),
      i(8, "editora"),
      t({ "},", "  editorb = {" }),
      i(9, "editorb"),
      t({ "},", "  editorc = {" }),
      i(10, "editorc"),
      t({ "},", "  eprint = {" }),
      i(11, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(12, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(13, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(14, "foreword"),
      t({ "},", "  introduction = {" }),
      i(15, "introduction"),
      t({ "},", "  isbn = {" }),
      i(16, "isbn"),
      t({ "},", "  language = {" }),
      i(17, "language"),
      t({ "},", "  location = {" }),
      i(18, "location"),
      t({ "},", "  note = {" }),
      i(19, "note"),
      t({ "},", "  number = {" }),
      i(20, "number"),
      t({ "},", "  origlanguage = {" }),
      i(21, "origlanguage"),
      t({ "},", "  pagetotal = {" }),
      i(22, "pagetotal"),
      t({ "},", "  publisher = {" }),
      i(23, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(24, "pubstate"),
      t({ "},", "  series = {" }),
      i(25, "series"),
      t({ "},", "  subtitle = {" }),
      i(26, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(27, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(28, "translator"),
      t({ "},", "  url = {" }),
      i(29, "url"),
      t({ "},", "  urldate = {" }),
      i(30, "urldate"),
      t({ "},", "  volumes = {" }),
      i(31, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@online~", wordTrig = true }, {
      t("@online{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  eprintclass = {" }),
      i(3, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(4, "eprinttype"),
      t({ "},", "  language = {" }),
      i(5, "language"),
      t({ "},", "  month = {" }),
      i(6, "month"),
      t({ "},", "  note = {" }),
      i(7, "note"),
      t({ "},", "  organization = {" }),
      i(8, "organization"),
      t({ "},", "  pubstate = {" }),
      i(9, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(10, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(11, "titleaddon"),
      t({ "},", "  urldate = {" }),
      i(12, "urldate"),
      t({ "},", "  version = {" }),
      i(13, "version"),
      t({ "}", "}" }),
    }),
    s({ trig = "@patent~", wordTrig = true }, {
      t("@patent{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  doi = {" }),
      i(3, "doi"),
      t({ "},", "  eprint = {" }),
      i(4, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(5, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(6, "eprinttype"),
      t({ "},", "  holder = {" }),
      i(7, "holder"),
      t({ "},", "  location = {" }),
      i(8, "location"),
      t({ "},", "  month = {" }),
      i(9, "month"),
      t({ "},", "  note = {" }),
      i(10, "note"),
      t({ "},", "  pubstate = {" }),
      i(11, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(12, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(13, "titleaddon"),
      t({ "},", "  type = {" }),
      i(14, "type"),
      t({ "},", "  url = {" }),
      i(15, "url"),
      t({ "},", "  urldate = {" }),
      i(16, "urldate"),
      t({ "},", "  version = {" }),
      i(17, "version"),
      t({ "}", "}" }),
    }),
    s({ trig = "@periodical~", wordTrig = true }, {
      t("@periodical{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  doi = {" }),
      i(3, "doi"),
      t({ "},", "  editora = {" }),
      i(4, "editora"),
      t({ "},", "  editorb = {" }),
      i(5, "editorb"),
      t({ "},", "  editorc = {" }),
      i(6, "editorc"),
      t({ "},", "  eprint = {" }),
      i(7, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(8, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(9, "eprinttype"),
      t({ "},", "  issn = {" }),
      i(10, "issn"),
      t({ "},", "  issue = {" }),
      i(11, "issue"),
      t({ "},", "  issuesubtitle = {" }),
      i(12, "issuesubtitle"),
      t({ "},", "  issuetitle = {" }),
      i(13, "issuetitle"),
      t({ "},", "  issuetitleaddon = {" }),
      i(14, "issuetitleaddon"),
      t({ "},", "  language = {" }),
      i(15, "language"),
      t({ "},", "  month = {" }),
      i(16, "month"),
      t({ "},", "  note = {" }),
      i(17, "note"),
      t({ "},", "  number = {" }),
      i(18, "number"),
      t({ "},", "  pubstate = {" }),
      i(19, "pubstate"),
      t({ "},", "  series = {" }),
      i(20, "series"),
      t({ "},", "  subtitle = {" }),
      i(21, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(22, "titleaddon"),
      t({ "},", "  url = {" }),
      i(23, "url"),
      t({ "},", "  urldate = {" }),
      i(24, "urldate"),
      t({ "},", "  volume = {" }),
      i(25, "volume"),
      t({ "}", "}" }),
    }),
    s({ trig = "@phdthesis~", wordTrig = true }, {
      t("@phdthesis{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  address = {" }),
      i(3, "address"),
      t({ "},", "  chapter = {" }),
      i(4, "chapter"),
      t({ "},", "  doi = {" }),
      i(5, "doi"),
      t({ "},", "  eprint = {" }),
      i(6, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(7, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(8, "eprinttype"),
      t({ "},", "  isbn = {" }),
      i(9, "isbn"),
      t({ "},", "  language = {" }),
      i(10, "language"),
      t({ "},", "  location = {" }),
      i(11, "location"),
      t({ "},", "  month = {" }),
      i(12, "month"),
      t({ "},", "  note = {" }),
      i(13, "note"),
      t({ "},", "  pages = {" }),
      i(14, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(15, "pagetotal"),
      t({ "},", "  pubstate = {" }),
      i(16, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(17, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(18, "titleaddon"),
      t({ "},", "  type = {" }),
      i(19, "type"),
      t({ "},", "  url = {" }),
      i(20, "url"),
      t({ "},", "  urldate = {" }),
      i(21, "urldate"),
      t({ "}", "}" }),
    }),
    s({ trig = "@proceedings~", wordTrig = true }, {
      t("@proceedings{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  address = {" }),
      i(3, "address"),
      t({ "},", "  chapter = {" }),
      i(4, "chapter"),
      t({ "},", "  doi = {" }),
      i(5, "doi"),
      t({ "},", "  editor = {" }),
      i(6, "editor"),
      t({ "},", "  eprint = {" }),
      i(7, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(8, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(9, "eprinttype"),
      t({ "},", "  eventdate = {" }),
      i(10, "eventdate"),
      t({ "},", "  eventtitle = {" }),
      i(11, "eventtitle"),
      t({ "},", "  eventtitleaddon = {" }),
      i(12, "eventtitleaddon"),
      t({ "},", "  isbn = {" }),
      i(13, "isbn"),
      t({ "},", "  language = {" }),
      i(14, "language"),
      t({ "},", "  location = {" }),
      i(15, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(16, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(17, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(18, "maintitleaddon"),
      t({ "},", "  month = {" }),
      i(19, "month"),
      t({ "},", "  note = {" }),
      i(20, "note"),
      t({ "},", "  number = {" }),
      i(21, "number"),
      t({ "},", "  organization = {" }),
      i(22, "organization"),
      t({ "},", "  pages = {" }),
      i(23, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(24, "pagetotal"),
      t({ "},", "  part = {" }),
      i(25, "part"),
      t({ "},", "  publisher = {" }),
      i(26, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(27, "pubstate"),
      t({ "},", "  series = {" }),
      i(28, "series"),
      t({ "},", "  subtitle = {" }),
      i(29, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(30, "titleaddon"),
      t({ "},", "  url = {" }),
      i(31, "url"),
      t({ "},", "  urldate = {" }),
      i(32, "urldate"),
      t({ "},", "  venue = {" }),
      i(33, "venue"),
      t({ "},", "  volume = {" }),
      i(34, "volume"),
      t({ "},", "  volumes = {" }),
      i(35, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@reference~", wordTrig = true }, {
      t("@reference{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  chapter = {" }),
      i(5, "chapter"),
      t({ "},", "  commentator = {" }),
      i(6, "commentator"),
      t({ "},", "  doi = {" }),
      i(7, "doi"),
      t({ "},", "  edition = {" }),
      i(8, "edition"),
      t({ "},", "  editora = {" }),
      i(9, "editora"),
      t({ "},", "  editorb = {" }),
      i(10, "editorb"),
      t({ "},", "  editorc = {" }),
      i(11, "editorc"),
      t({ "},", "  eid = {" }),
      i(12, "eid"),
      t({ "},", "  eprint = {" }),
      i(13, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(14, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(15, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(16, "foreword"),
      t({ "},", "  introduction = {" }),
      i(17, "introduction"),
      t({ "},", "  isbn = {" }),
      i(18, "isbn"),
      t({ "},", "  language = {" }),
      i(19, "language"),
      t({ "},", "  location = {" }),
      i(20, "location"),
      t({ "},", "  maintitle = {" }),
      i(21, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(22, "maintitleaddon"),
      t({ "},", "  note = {" }),
      i(23, "note"),
      t({ "},", "  number = {" }),
      i(24, "number"),
      t({ "},", "  origlanguage = {" }),
      i(25, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(26, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(27, "pagetotal"),
      t({ "},", "  part = {" }),
      i(28, "part"),
      t({ "},", "  publisher = {" }),
      i(29, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(30, "pubstate"),
      t({ "},", "  series = {" }),
      i(31, "series"),
      t({ "},", "  subtitle = {" }),
      i(32, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(33, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(34, "translator"),
      t({ "},", "  url = {" }),
      i(35, "url"),
      t({ "},", "  urldate = {" }),
      i(36, "urldate"),
      t({ "},", "  volume = {" }),
      i(37, "volume"),
      t({ "},", "  volumes = {" }),
      i(38, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@report~", wordTrig = true }, {
      t("@report{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  chapter = {" }),
      i(3, "chapter"),
      t({ "},", "  doi = {" }),
      i(4, "doi"),
      t({ "},", "  eid = {" }),
      i(5, "eid"),
      t({ "},", "  eprint = {" }),
      i(6, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(7, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(8, "eprinttype"),
      t({ "},", "  isrn = {" }),
      i(9, "isrn"),
      t({ "},", "  language = {" }),
      i(10, "language"),
      t({ "},", "  location = {" }),
      i(11, "location"),
      t({ "},", "  month = {" }),
      i(12, "month"),
      t({ "},", "  note = {" }),
      i(13, "note"),
      t({ "},", "  number = {" }),
      i(14, "number"),
      t({ "},", "  pages = {" }),
      i(15, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(16, "pagetotal"),
      t({ "},", "  pubstate = {" }),
      i(17, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(18, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(19, "titleaddon"),
      t({ "},", "  url = {" }),
      i(20, "url"),
      t({ "},", "  urldate = {" }),
      i(21, "urldate"),
      t({ "},", "  version = {" }),
      i(22, "version"),
      t({ "}", "}" }),
    }),
    s({ trig = "@software~", wordTrig = true }, {
      t("@software{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  doi = {" }),
      i(3, "doi"),
      t({ "},", "  eprint = {" }),
      i(4, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(5, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(6, "eprinttype"),
      t({ "},", "  howpublished = {" }),
      i(7, "howpublished"),
      t({ "},", "  language = {" }),
      i(8, "language"),
      t({ "},", "  location = {" }),
      i(9, "location"),
      t({ "},", "  month = {" }),
      i(10, "month"),
      t({ "},", "  note = {" }),
      i(11, "note"),
      t({ "},", "  organization = {" }),
      i(12, "organization"),
      t({ "},", "  pubstate = {" }),
      i(13, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(14, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(15, "titleaddon"),
      t({ "},", "  type = {" }),
      i(16, "type"),
      t({ "},", "  url = {" }),
      i(17, "url"),
      t({ "},", "  urldate = {" }),
      i(18, "urldate"),
      t({ "},", "  version = {" }),
      i(19, "version"),
      t({ "}", "}" }),
    }),
    s({ trig = "@suppbook~", wordTrig = true }, {
      t("@suppbook{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  bookauthor = {" }),
      i(5, "bookauthor"),
      t({ "},", "  booksubtitle = {" }),
      i(6, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(7, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(8, "chapter"),
      t({ "},", "  commentator = {" }),
      i(9, "commentator"),
      t({ "},", "  doi = {" }),
      i(10, "doi"),
      t({ "},", "  edition = {" }),
      i(11, "edition"),
      t({ "},", "  editor = {" }),
      i(12, "editor"),
      t({ "},", "  editora = {" }),
      i(13, "editora"),
      t({ "},", "  editorb = {" }),
      i(14, "editorb"),
      t({ "},", "  editorc = {" }),
      i(15, "editorc"),
      t({ "},", "  eid = {" }),
      i(16, "eid"),
      t({ "},", "  eprint = {" }),
      i(17, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(18, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(19, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(20, "foreword"),
      t({ "},", "  introduction = {" }),
      i(21, "introduction"),
      t({ "},", "  isbn = {" }),
      i(22, "isbn"),
      t({ "},", "  language = {" }),
      i(23, "language"),
      t({ "},", "  location = {" }),
      i(24, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(25, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(26, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(27, "maintitleaddon"),
      t({ "},", "  note = {" }),
      i(28, "note"),
      t({ "},", "  number = {" }),
      i(29, "number"),
      t({ "},", "  origlanguage = {" }),
      i(30, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(31, "pages"),
      t({ "},", "  part = {" }),
      i(32, "part"),
      t({ "},", "  publisher = {" }),
      i(33, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(34, "pubstate"),
      t({ "},", "  series = {" }),
      i(35, "series"),
      t({ "},", "  subtitle = {" }),
      i(36, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(37, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(38, "translator"),
      t({ "},", "  url = {" }),
      i(39, "url"),
      t({ "},", "  urldate = {" }),
      i(40, "urldate"),
      t({ "},", "  volume = {" }),
      i(41, "volume"),
      t({ "},", "  volumes = {" }),
      i(42, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@suppcollection~", wordTrig = true }, {
      t("@suppcollection{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  afterword = {" }),
      i(3, "afterword"),
      t({ "},", "  annotator = {" }),
      i(4, "annotator"),
      t({ "},", "  booksubtitle = {" }),
      i(5, "booksubtitle"),
      t({ "},", "  booktitleaddon = {" }),
      i(6, "booktitleaddon"),
      t({ "},", "  chapter = {" }),
      i(7, "chapter"),
      t({ "},", "  commentator = {" }),
      i(8, "commentator"),
      t({ "},", "  doi = {" }),
      i(9, "doi"),
      t({ "},", "  edition = {" }),
      i(10, "edition"),
      t({ "},", "  editor = {" }),
      i(11, "editor"),
      t({ "},", "  editora = {" }),
      i(12, "editora"),
      t({ "},", "  editorb = {" }),
      i(13, "editorb"),
      t({ "},", "  editorc = {" }),
      i(14, "editorc"),
      t({ "},", "  eid = {" }),
      i(15, "eid"),
      t({ "},", "  eprint = {" }),
      i(16, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(17, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(18, "eprinttype"),
      t({ "},", "  foreword = {" }),
      i(19, "foreword"),
      t({ "},", "  introduction = {" }),
      i(20, "introduction"),
      t({ "},", "  isbn = {" }),
      i(21, "isbn"),
      t({ "},", "  language = {" }),
      i(22, "language"),
      t({ "},", "  location = {" }),
      i(23, "location"),
      t({ "},", "  mainsubtitle = {" }),
      i(24, "mainsubtitle"),
      t({ "},", "  maintitle = {" }),
      i(25, "maintitle"),
      t({ "},", "  maintitleaddon = {" }),
      i(26, "maintitleaddon"),
      t({ "},", "  note = {" }),
      i(27, "note"),
      t({ "},", "  number = {" }),
      i(28, "number"),
      t({ "},", "  origlanguage = {" }),
      i(29, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(30, "pages"),
      t({ "},", "  part = {" }),
      i(31, "part"),
      t({ "},", "  publisher = {" }),
      i(32, "publisher"),
      t({ "},", "  pubstate = {" }),
      i(33, "pubstate"),
      t({ "},", "  series = {" }),
      i(34, "series"),
      t({ "},", "  subtitle = {" }),
      i(35, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(36, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(37, "translator"),
      t({ "},", "  url = {" }),
      i(38, "url"),
      t({ "},", "  urldate = {" }),
      i(39, "urldate"),
      t({ "},", "  volume = {" }),
      i(40, "volume"),
      t({ "},", "  volumes = {" }),
      i(41, "volumes"),
      t({ "}", "}" }),
    }),
    s({ trig = "@suppperiodical~", wordTrig = true }, {
      t("@suppperiodical{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  annotator = {" }),
      i(3, "annotator"),
      t({ "},", "  commentator = {" }),
      i(4, "commentator"),
      t({ "},", "  doi = {" }),
      i(5, "doi"),
      t({ "},", "  editor = {" }),
      i(6, "editor"),
      t({ "},", "  editora = {" }),
      i(7, "editora"),
      t({ "},", "  editorb = {" }),
      i(8, "editorb"),
      t({ "},", "  editorc = {" }),
      i(9, "editorc"),
      t({ "},", "  eid = {" }),
      i(10, "eid"),
      t({ "},", "  eprint = {" }),
      i(11, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(12, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(13, "eprinttype"),
      t({ "},", "  issn = {" }),
      i(14, "issn"),
      t({ "},", "  issue = {" }),
      i(15, "issue"),
      t({ "},", "  issuesubtitle = {" }),
      i(16, "issuesubtitle"),
      t({ "},", "  issuetitle = {" }),
      i(17, "issuetitle"),
      t({ "},", "  issuetitleaddon = {" }),
      i(18, "issuetitleaddon"),
      t({ "},", "  journalsubtitle = {" }),
      i(19, "journalsubtitle"),
      t({ "},", "  journaltitleaddon = {" }),
      i(20, "journaltitleaddon"),
      t({ "},", "  language = {" }),
      i(21, "language"),
      t({ "},", "  month = {" }),
      i(22, "month"),
      t({ "},", "  note = {" }),
      i(23, "note"),
      t({ "},", "  number = {" }),
      i(24, "number"),
      t({ "},", "  origlanguage = {" }),
      i(25, "origlanguage"),
      t({ "},", "  pages = {" }),
      i(26, "pages"),
      t({ "},", "  pubstate = {" }),
      i(27, "pubstate"),
      t({ "},", "  series = {" }),
      i(28, "series"),
      t({ "},", "  subtitle = {" }),
      i(29, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(30, "titleaddon"),
      t({ "},", "  translator = {" }),
      i(31, "translator"),
      t({ "},", "  url = {" }),
      i(32, "url"),
      t({ "},", "  urldate = {" }),
      i(33, "urldate"),
      t({ "},", "  version = {" }),
      i(34, "version"),
      t({ "},", "  volume = {" }),
      i(35, "volume"),
      t({ "}", "}" }),
    }),
    s({ trig = "@techreport~", wordTrig = true }, {
      t("@techreport{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  address = {" }),
      i(3, "address"),
      t({ "},", "  chapter = {" }),
      i(4, "chapter"),
      t({ "},", "  doi = {" }),
      i(5, "doi"),
      t({ "},", "  eprint = {" }),
      i(6, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(7, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(8, "eprinttype"),
      t({ "},", "  isrn = {" }),
      i(9, "isrn"),
      t({ "},", "  language = {" }),
      i(10, "language"),
      t({ "},", "  location = {" }),
      i(11, "location"),
      t({ "},", "  month = {" }),
      i(12, "month"),
      t({ "},", "  note = {" }),
      i(13, "note"),
      t({ "},", "  number = {" }),
      i(14, "number"),
      t({ "},", "  pages = {" }),
      i(15, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(16, "pagetotal"),
      t({ "},", "  pubstate = {" }),
      i(17, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(18, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(19, "titleaddon"),
      t({ "},", "  type = {" }),
      i(20, "type"),
      t({ "},", "  url = {" }),
      i(21, "url"),
      t({ "},", "  urldate = {" }),
      i(22, "urldate"),
      t({ "},", "  version = {" }),
      i(23, "version"),
      t({ "}", "}" }),
    }),
    s({ trig = "@thesis~", wordTrig = true }, {
      t("@thesis{"),
      i(1, "key"),
      t({ ",", "  addendum = {" }),
      i(2, "addendum"),
      t({ "},", "  chapter = {" }),
      i(3, "chapter"),
      t({ "},", "  doi = {" }),
      i(4, "doi"),
      t({ "},", "  eid = {" }),
      i(5, "eid"),
      t({ "},", "  eprint = {" }),
      i(6, "eprint"),
      t({ "},", "  eprintclass = {" }),
      i(7, "eprintclass"),
      t({ "},", "  eprinttype = {" }),
      i(8, "eprinttype"),
      t({ "},", "  isbn = {" }),
      i(9, "isbn"),
      t({ "},", "  language = {" }),
      i(10, "language"),
      t({ "},", "  location = {" }),
      i(11, "location"),
      t({ "},", "  month = {" }),
      i(12, "month"),
      t({ "},", "  note = {" }),
      i(13, "note"),
      t({ "},", "  pages = {" }),
      i(14, "pages"),
      t({ "},", "  pagetotal = {" }),
      i(15, "pagetotal"),
      t({ "},", "  pubstate = {" }),
      i(16, "pubstate"),
      t({ "},", "  subtitle = {" }),
      i(17, "subtitle"),
      t({ "},", "  titleaddon = {" }),
      i(18, "titleaddon"),
      t({ "},", "  url = {" }),
      i(19, "url"),
      t({ "},", "  urldate = {" }),
      i(20, "urldate"),
      t({ "}", "}" }),
    }),
    s({ trig = "@unpublished~", wordTrig = true }, {
      t("@unpublished{"),
      i(1, "key"),
      t({ ",", "  month = {" }),
      i(2, "month"),
      t({ "},", "  year = {" }),
      i(3, "year"),
      t({ "}", "}" }),
    }),
  },
}
